           document.addEventListener("DOMContentLoaded", function() {
               // Array of daily texts
               const shaelynMbaso1 = [
   //"Day Zero",
   // January
   "God is love; and he that dwelleth in love dwelleth in God, and God in him. 1 John 4:16.",
   "And God saw everything that he had made, and, behold, it was very good. And the evening and the morning were the sixth day. Genesis 1:31.",
   "Thou wast perfect in thy ways from the day that thou wast created, till iniquity was found in thee. Ezekiel 28:15.",
   "He was a murderer from the beginning, and abode not in the truth, because there is no truth in him. John 8:44.",
   "Thine heart was lifted up because of thy beauty, thou hast corrupted thy wisdom by reason of thy brightness. Ezekiel 28:17.",
   "How art thou fallen from heaven, O Lucifer, son of the morning! how art thou cut down to the ground, which didst weaken the nations! Isaiah 14:12.",
   "Sometimes there is a way that seems to be right, but in the end it is the way to death. Proverbs 16:25, NRSV.",
   "Wherefore by their fruits ye shall know them. Matthew 7:20.",
   "Thou shalt worship the Lord thy God, and him only shalt thou serve. Matthew 4:10.",
   "Thou hast defiled thy sanctuaries by the multitude of thine iniquities. Ezekiel 28:18.",
   "Thou hast sinned: therefore I will cast thee as profane out of the mountain of God: and I will destroy thee, O covering cherub, from the midst of the stones of fire. Ezekiel 28:16.",
   "Thus the heavens and the earth were finished, and all the host of them. And on the seventh day God ended his work which he had made; and he rested on the seventh day from all his work which he had made. Genesis 2:1, 2.",
   "I made the earth, and created humankind upon it; it was my hands that stretched out the heavens, and I commanded all their host. Isaiah 45:12, NRSV.",
   "But of the tree of the knowledge of good and evil, thou shalt not eat of it. Genesis 2:17.",
   "Yea, hath God said, Ye shall not eat of every tree of the garden? Genesis 3:1.",
   "God doth know that in the day ye eat thereof, then your eyes shall be opened, and ye shall be as gods, knowing good and evil. Genesis 3:5.",
   "And when the woman saw that the tree was ... pleasant to the eyes, and a tree to be desired to make one wise, she took of the fruit thereof, and did eat, and gave also unto her husband with her; and he did eat. Genesis 3:6.",
   "As by one man’s disobedience many were made sinners, so by the obedience of one shall many be made righteous. Romans 5:19.",
   "And Adam and his wife hid themselves from the presence of the Lord God amongst the trees of the garden. Genesis 3:8.",
   "And the Lord God said unto the woman, What is this that thou hast done? And the woman said, The serpent beguiled me, and I did eat. Genesis 3:13.",
   "Thy desire shall be to thy husband, and he shall rule over thee. And unto Adam he said . . Cursed is the ground for thy sake; in sorrow shalt thou eat of it all the days of thy life. Genesis 3:16, 17.",
   "And I will put enmity between thee and the woman. Genesis 3:15.",
   "And I will put enmity between ... thy seed and her seed; it shall bruise thy head, and thou shalt bruise his heel. Genesis 3:15.",
   "Forasmuch as ye know that ye were not redeemed with corruptible things ... but with the precious blood of Christ, as of a lamb without blemish and without spot. 1 Peter 1:18, 19.",
   "Are they not all ministering spirits, sent forth to minister for them who shall be heirs of salvation? Hebrews 1:14.",
   "So if anyone is in Christ, there is a new creation: everything old has passed away; see, everything has become new! 2 Corinthians 5:17, NRSV.",
   "And the Lord God said, Behold, the man is become as one of us, to know good and evil. Genesis 3:22.",
   "When the fullness of time had come, God sent his Son ... to redeem those who were under the law, so that we might receive adoption as children. Galatians 4:4, 5, NRSV.",
   "And the Lord had respect unto Abel and to his offering: but unto Cain and to his offering he had not respect. Genesis 4:4, 5.",
   "Why art thou wroth? and why is thy countenance fallen? If thou doest well, shalt thou not be accepted? and if thou doest not well, sin lieth at the door. Genesis 4:6, 7.",
   "And Cain was very wroth, and his countenance fell. Genesis 4:5.",
   
   // February
   "God ... hath appointed me another seed instead of Abel, whom Cain slew.... Adam ... begat a son in his own likeness, after his image; and called his name Seth. Genesis 4:25-5:3.",
   "To Seth also a son was born, and he named him Enosh. At that time people began to invoke the name of the Lord. Genesis 4:26, NRSV.",
   "When they knew God, they glorified him not as God, neither were thankful; but became vain in their imaginations, and their foolish heart was darkened. Romans 1:21.",
   "Can two walk together, except they be agreed? Amos 3:3.",
   "For the one who sanctifies and those who are sanctified all have one Father. For this reason Jesus is not ashamed to call them brothers and sisters. Hebrews 2:11, NRSV.",
   "Open thou mine eyes, that I may behold wondrous things out of thy law. Psalm 119:18.",
   "Whereby are given unto us exceeding great and precious promises: that by these ye might be partakers of the divine nature, having escaped the corruption that is in the world through lust. 2 Peter 1:4.",
   "Let your light shine before others, so that they may see your good works and give glory to your Father in heaven. Matthew 5:16, NRSV.",
   "Keep yourselves in the love of God, looking for the mercy of our Lord Jesus Christ unto eternal life. Jude 21.",
   "Thou hast a few names even in Sardis which have not defiled their garments; and they shall walk with me in white: for they are worthy. Revelation 3:4.",
   "And Enoch also, the seventh from Adam, prophesied of these, saying, Behold, the Lord cometh with ten thousands of his saints, to execute judgment upon all. Jude 14.",
   "Remembering without ceasing your work of faith, and labour of love, and patience of hope in our Lord Jesus Christ, in the sight of God and our Father. 1 Thessalonians 1:3.",
   "I in them, and thou in me, that they may be made perfect in one; and that the world may know that thou hast sent me, and hast loved them, as thou hast loved me. John 17:23.",
   "The Lord saw that the wickedness of humankind was great in the earth, and that every inclination of the thoughts of their hearts was only evil continually. Genesis 6:5, NRSV.",
   "For ye were sometimes darkness, but now are ye light in the Lord: walk as children of light. Ephesians 5:8.",
   "Work out your own salvation with fear and trembling. For it is God which worketh in you both to will and to do of his good pleasure. Philippians 2:12, 13.",
   "If ye then, being evil, know how to give good gifts unto your children: how much more shall your heavenly Father give the Holy Spirit to them that ask him? Luke 11:13.",
   "And the Lord said unto Noah, Come thou and all thy house into the ark; for thee have I seen righteous before me in this generation. Genesis 7:1.",
   "And God said unto Noah, The end of all flesh is come before me; for the earth is filled with violence through them; and, behold, I will destroy them with the earth. Genesis 6:13.",
   "And Noah did according unto all that the Lord commanded him. Genesis 7:5.",
   "Hearken unto me, my people; and give ear unto me, O my nation: for a law shall proceed from me, and I will make my judgment to rest for a light of the people. Isaiah 51:4.",
   "But those who look into the perfect law, the law of liberty, and persevere, being not hearers who forget but doers who act—they will be blessed in their doing. James 1:25, NRSV.",
   "Thou believest that there is one God; thou doest well: the devils also believe, and tremble. James 2:19.",
   "The same day were all the fountains of the great deep broken up, and the windows of heaven were opened. Genesis 7:11.",
   "Wherefore come out from among them, and be ye separate, saith the Lord, and touch not the unclean thing; and I will receive you. 2 Corinthians 6:17.",
   "Jesus Christ the same yesterday, and today, and for ever. Hebrews 13:8.",
   "The light of the body is the eye: if therefore thine eye be single, thy whole body shall be full of light. Matthew 6:22.",
   "These are they which came out of great tribulation, and have washed their robes, and made them white in the blood of the Lamb. Revelation 7:14.",
   "Ho, every one that thirsteth, come ye to the waters, and he that hath no money; come ye, buy, and eat. Isaiah 55:1.",
   
   // March
   "The Lord knoweth the days of the upright: and their inheritance shall be for ever.... For such as be blessed of him shall inherit the earth; and they that be cursed of him shall be cut off. Psalm 37:18-22.",
   "Cursed be Canaan; a servant of servants shall he be unto his brethren. Genesis 9:25.",
   "Let us build us a city and a tower, whose top may reach unto heaven; and let us make us a name, lest we be scattered abroad. Genesis 11:4.",
   "The Lord bringeth the counsel of the heathen to nought: he maketh the devices of the people of none effect. The counsel of the Lord standeth for ever, the thoughts of his heart to all generations. Psalm 33:10, 11.",
   "I will make of thee a great nation, and I will bless thee, and make thy name great; and thou shalt be a blessing. Genesis 12:2.",
   "If thou wilt take the left hand, then I will go to the right; or if thou depart to the right hand, then I will go to the left. Genesis 13:9.",
   "Then Lot chose him all the plain of Jordan; and Lot journeyed east: and they separated themselves the one from the other. Genesis 13:11.",
   "And Lot lifted up his eyes, and beheld all the plain of Jordan, that it was well watered every where. Genesis 13:10.",
   "And Abraham drew near, and said, Wilt thou also destroy the righteous with the wicked? Genesis 18:23.",
   "And there came two angels to Sodom at even: and Lot sat in the gate of Sodom: and Lot seeing them rose up to meet them; and he bowed himself with his face toward the ground. Genesis 19:1.",
   "Whoever says, ‘I have come to know him,’ but does not obey his commandments, is a liar, and in such a person the truth does not exist. 1 John 2:4, NRSV.",
   "For this is the love of God, that we keep his commandments: and his commandments are not grievous. 1 John 5:3.",
   "To day if ye will hear his voice, harden not your hearts. Hebrews 3:15.",
   "If the mighty works, which have been done in thee, had been done in Sodom, it would have remained until this day. Matthew 11:23.",
   "I know him, that he will command his children and his household after him, and they shall keep the way of the Lord, to do justice and judgment. Genesis 18:19.",
   "And Abraham ... took bread, and a bottle of water, and gave it unto Hagar, putting it on her shoulder, and the child, and sent her away. Genesis 21:14.",
   "Take now thy son, thine only son Isaac, whom thou lovest, and get thee into the land of Moriah; and offer him there for a burnt offering upon one of the mountains which I will tell thee of. Genesis 22:2.",
   "One people shall be stronger than the other people; and the elder shall serve the younger. Genesis 25:23.",
   "And Esau said to Jacob, Feed me, I pray thee, with that same red pottage; for I am faint: ... And Jacob said, Sell me this day thy birthright.... And he sold his birthright unto Jacob. Genesis 25:30-34.",
   "And Jacob awaked out of his sleep, and he said, Surely the Lord is in this place; and I knew it not. Genesis 28:16.",
   "Whoever enters by me will be saved, and will come in and go out and find pasture. John 10:9, NRSV.",
   "And he dreamed, and behold a ladder set up on the earth, and the top of it reached to heaven ... And, behold, the Lord stood above it, and said ... the land whereon thou liest, to thee will I give it, and to thy seed. Genesis 28:12, 13.",
   "And he said, Let me go, for the day breaketh. And he said, I will not let thee go, except thou bless me. Genesis 32:26.",
   "Though an host should encamp against me, my heart shall not fear: though war should rise against me, in this will I be confident. Psalm 27:3.",
   "Now Israel loved Joseph more than all his children, because he was the son of his old age: and he made him a coat of many colours. Genesis 37:3.",
   "And Judah said unto his brethren, What profit is it if we slay our brother, and conceal his blood? Come, and let us sell him to the Ishmeelites, and let not our hand be upon him; for he is our brother. Genesis 37:26, 27.",
   "The sceptre shall not depart from Judah, nor a lawgiver from between his feet, until Shiloh come; and unto him shall the gathering of the people be. Genesis 49:10.",
   "And his master saw that the Lord was with him.... And Joseph found grace in his sight, and he served him: and he made him overseer over his house, and all that he had he put into his hand. Genesis 39:3, 4.",
   "The Lord blessed the Egyptian’s house for Joseph’s sake.... Joseph was a goodly person, and well favoured. Genesis 39:5, 6.",
   "His master’s wife cast her eyes upon Joseph; and she said, Lie with me. But he refused, and said unto his master’s wife ... :how then can I do this great wickedness, and sin against God? Genesis 39:7-9.",
   "And Joseph’s master took him, and put him into the prison.... But the Lord was with Joseph, and shewed him mercy, and gave him favour in the sight of the keeper of the prison. Genesis 39:20, 21.",
   
   // April
   "By faith Moses, when he had come to years, refused to be called the son of Pharaoh’s daughter; choosing rather to suffer affliction with the people of God, than to enjoy the pleasures of sin for a season. Hebrews 11:24, 25.",
   "Moses fled from the face of Pharaoh, and dwelt in the land of Midian. Exodus 2:15.",
   "By faith he [Moses] forsook Egypt, not fearing the wrath of the king: for he endured, as seeing him who is invisible. Hebrews 11:27.",
   "He smote the Egyptians, and delivered our houses. Exodus 12:27.",
   "When your children shall say unto you, What mean ye by this service? That ye shall say, It is the sacrifice of the Lord’s passover, who passed over the houses of the children of Israel in Egypt. Exodus 12:26, 27.",
   "And the Lord hardened the heart of Pharaoh king of Egypt, and he pursued after the children of Israel. Exodus 14:8.",
   "Because there were no graves in Egypt, hast thou taken us away to die in the wilderness? wherefore hast thou dealt thus with us? Exodus 14:11.",
   "And the Lord caused the sea to go back by a strong east wind all that night, and made the sea dry land, and the waters were divided. And the children of Israel went into the midst of the sea. Exodus 14:21, 22.",
   "And the Lord overthrew the Egyptians in the midst of the sea. Exodus 14:27.",
   "And Israel saw the great work which the Lord did upon the Egyptians: and the people feared the Lord, and believed the Lord, and his servant Moses. Exodus 14:31.",
   "In all their affliction he was afflicted, and the angel of his presence saved them: in his love and in his pity he redeemed them; and he bare them, and carried them all the days of old. But they rebelled, and vexed his holy Spirit. Isaiah 63:9.",
   "And it shall come to pass, that on the sixth day they shall prepare that which they bring in; and it shall be twice as much as they gather daily. Exodus 16:5.",
   "See! The Lord has given you the sabbath, therefore on the sixth day he gives you food for two days; each of you stay where you are; do not leave your place on the seventh day. So the people rested on the seventh day. Exodus 16:29, 30, NRSV.",
   "Would to God we had died by the hand of the Lord in the land of Egypt, when we sat by the flesh pots, and when we did eat bread to the full; for ye have brought us forth ... to kill this whole assembly with hunger. Exodus 16:3.",
   "Behold, I will stand before thee there upon the rock in Horeb; and thou shalt smite the rock, and there shall come water out of it, that the people may drink. Exodus 17:6.",
   "And the Lord said unto Moses, Go unto the people, and sanctify them today and tomorrow, and let them wash their clothes. Exodus 19:10.",
   "If ye will obey my voice indeed, and keep my covenant, then ye shall be a peculiar treasure unto me above all people: for all the earth is mine: And ye shall be unto me a kingdom of priests, and a holy nation. Exodus 19:5, 6.",
   "The people gathered themselves together unto Aaron, and said unto him, Up, make us gods, which shall go before us; for as for this Moses, ... we wot not what is become of him. Exodus 32:1.",
   "If thou wilt forgive their sin—and if not, blot me, I pray thee, out of thy book which thou hast written. Exodus 32:32.",
   "And he said, I beseech thee, shew me thy glory. Exodus 33:18.",
   "And they said, Hath the Lord indeed spoken only by Moses? hath he not spoken also by us? And the Lord heard it. Numbers 12:2.",
   "We be not able to go up against the people; for they are stronger than we. Numbers 13:31.",
   "We came unto the land whither thou sentest us, and surely it floweth with milk and honey; and this is the fruit of it. Numbers 13:27.",
   "Now if thou shalt kill all this people as one man, then the nations ... will speak, saying, Because the Lord was not able to bring this people into the land ... therefore he hath slain them in the wilderness. Numbers 14:15, 16.",
   "And Caleb stilled the people before Moses, and said, Let us go up at once, and possess it; for we are well able to overcome it. Numbers 13:30.",
   "Surely they shall not see the land which I sware unto their fathers. Numbers 14:23.",
   "My servant Caleb, because he had another spirit with him, and hath followed me fully, him will I bring into the land whereinto he went; and his seed shall possess it. Numbers 14:24.",
   "Ye take too much upon you, seeing all the congregation are holy. Numbers 16:3.",
   "With his rod he smote the rock twice: and the water came out abundantly.... And the Lord spake unto Moses and Aaron, Because ye believed me not, ye shall not bring this congregation into the land. Numbers 20:10-12.",
   "And the Lord said unto Moses, Make thee a fiery serpent, and set it upon a pole: and it shall come to pass, that every one that is bitten, when he looketh upon it, shall live. Numbers 21:8.",
   
   // May
   "Thou shalt see the land before thee; but thou shalt not go thither unto the land which I give the children of Israel. Deuteronomy 32:52.",
   "So Moses the servant of the Lord died there in the land of Moab, according to the word of the Lord. Deuteronomy 34:5.",
   "Yet Michael the archangel, when contending with the devil he disputed about the body of Moses, durst not bring against him a railing accusation, but said, The Lord rebuke thee. Jude 9.",
   "Blessed is anyone who endures temptation. Such a one has stood the test and will receive the crown of life that the Lord has promised to those who love him. James 1:12, NRSV.",
   "And the priests that bare the ark of the covenant of the Lord stood firm on dry ground in the midst of Jordan, and all the Israelites passed over on dry ground, until all the people were passed clean over Jordan. Joshua 3:17.",
   "And Joshua went unto him, and said unto him, Art thou for us, or for our adversaries? And he said, Nay; but as captain of the host of the Lord am I now come. Joshua 5:13, 14.",
   "And it came to pass, when ... the people shouted with a great shout, that the wall fell down flat, so that the people went up into the city ... and they took the city. Joshua 6:20.",
   "I press toward the mark for the prize of the high calling of God in Christ Jesus. Philippians 3:14.",
   "In the world ye shall have tribulation: but be of good cheer; I have overcome the world. John 16:33.",
   "There is an accursed thing in the midst of thee, O Israel: thou canst not stand before thine enemies, until ye take away the accursed thing from among you. Joshua 7:13.",
   "And it shall be, that he that is taken with the accursed thing shall be burnt with fire, he and all that he hath: because he hath transgressed the covenant of the Lord, and because he hath wrought folly in Israel. Joshua 7:15.",
   "Ye have seen all that the Lord your God hath done unto all these nations because of you; for the Lord your God is he that hath fought for you. Joshua 23:3.",
   "Choose you this day whom ye will serve; ... but as for me and my house, we will serve the Lord. Joshua 24:15.",
   "And the Lord said unto Samuel, Hearken unto the voice of the people in all that they say unto thee: for they have not rejected thee, but they have rejected me, that I should not reign over them. 1 Samuel 8:7.",
   "Nevertheless the people refused to obey the voice of Samuel; and they said, Nay; but we will have a king over us. 1 Samuel 8:19.",
   "Hath the Lord as great delight in burnt offerings and sacrifices, as in obeying the voice of the Lord? Behold, to obey is better than sacrifice, and to hearken than the fat of rams. 1 Samuel 15:22.",
   "And she said unto her servants, Go on before me; behold, I come after you. But she told not her husband Nabal. 1 Samuel 25:19.",
   "A soft answer turneth away wrath: but grievous words stir up anger. Proverbs 15:1.",
   "How long wilt thou mourn for Saul, seeing I have rejected him from reigning over Israel? fill thine horn with oil, and go, I will send thee to Jesse the Beth-lehemite: for I have provided me a king among his sons. 1 Samuel 16:1.",
   "And David’s anger was greatly kindled against the man; and he said to Nathan, As the Lord liveth, the man that hath done this thing shall surely die. 2 Samuel 12:5.",
   "And David said unto all his servants that were with him at Jerusalem, Arise, and let us flee; for we shall not else escape from Absalom. 2 Samuel 15:14.",
   "I dwell in the high and holy place, and also with those who are contrite and humble in spirit, to revive the spirit of the humble, and to revive the heart of the contrite. Isaiah 57:15, NRSV.",
   "Happy are those whose transgression is forgiven, whose sin is covered. Happy are those to whom the Lord imputes no iniquity, and in whose spirit there is no deceit. Psalm 32:1, 2, NRSV.",
   "Unto thee will I cry, O Lord my rock; be not silent to me: lest, if thou be silent to me, I become like them that go down into the pit. Psalm 28:1.",
   "Then David said to Gad, ‘I am in great distress: let us fall into the hand of the Lord, for his mercy is great; but let me not fall into human hands.’ 2 Samuel 24:14, NRSV.",
   "I will remember the works of the Lord: surely I will remember thy wonders of old. I will meditate also of all thy work, and talk of thy doings. Psalm 77:11, 12.",
   "Thus Solomon finished the house of the Lord ... and all that came into Solomon’s heart to make in the house of the Lord, and in his own house, he prosperously effected. 2 Chronicles 7:11.",
   "The king [David] said unto Nathan the prophet, See now, I dwell in an house of cedar, but the ark of God dwelleth within curtains. 2 Samuel 7:2.",
   "Keep and seek for all the commandments of the Lord your God: that ye may possess this good land, and leave it for an inheritance for your children after you for ever. 1 Chronicles 28:8.",
   "If any of you is lacking in wisdom, ask God, who gives to all generously and ungrudgingly, and it will be given you. James 1:5, NRSV.",
   "And the Lord magnified Solomon exceedingly in the sight of all Israel, and bestowed upon him such royal majesty as had not been on any king before him in Israel. 1 Chronicles 29:25.",
   
   // June
   "Then I looked on all the works that my hands had wrought, and on the labour that I had laboured to do: and, behold, all was vanity and vexation of spirit, and there was no profit under the sun. Ecclesiastes 2:11.",
   "Those to whom God gives wealth, possessions, and honor, so that they lack nothing of all that they desire, yet God does not enable them to enjoy these things, but a stranger enjoys them. Ecclesiastes 6:2, NRSV.",
   "Jeroboam stood by the altar to burn incense.... The altar also was rent, and the ashes poured out from the altar, according to the sign which the man of God had given by the word of the Lord. 1 Kings 13:1-5.",
   "Ahab said unto him, Art thou he that troubleth Israel? And he answered, I have not troubled Israel; but thou, and thy father’s house, in that ye have forsaken the commandments of the Lord. 1 Kings 18:17, 18.",
   "Then Jezebel sent a messenger unto Elijah, saying, So let the gods do to me, and more also, if I make not thy life as the life of one of them by tomorrow about this time. 1 Kings 19:2.",
   "And he requested for himself that he might die; and said, It is enough; now, O Lord, take away my life; for I am not better than my fathers. 1 Kings 19:4.",
   "Yet I have left me seven thousand in Israel, all the knees which have not bowed unto Baal. 1 Kings 19:18.",
   "Elisha the son of Shaphat of Abelmeholah shalt thou anoint to be prophet in thy room. 1 Kings 19:16.",
   "So he ... found Elisha the son of Shaphat, who was plowing with twelve yoke of oxen before him ... and Elijah passed by him, and cast his mantle upon him. 1 Kings 19:19.",
   "Here is Elisha the son of Shaphat, which poured water on the hands of Elijah. 2 Kings 3:11.",
   "Whoever is faithful in a very little is faithful also in much. Luke 16:10, NRSV.",
   "And his servants came near, and spake unto him, and said, My father, if the prophet had bid thee do some great thing, wouldest thou not have done it? how much rather then, when he saith to thee, Wash, and be clean? 2 Kings 5:13.",
   "But Gehazi, the servant of Elisha the man of God, said ... I will run after him, and take somewhat of him. 2 Kings 5:20.",
   "Arise, go to Nineveh, that great city, and cry against it; for their wickedness is come up before me. Jonah 1:2.",
   "But Daniel purposed in his heart that he would not defile himself with the portion of the king’s meat, nor with the wine which he drank: therefore he requested of the prince of the eunuchs that he might not defile himself. Daniel 1:8.",
   "Prove thy servants, I beseech thee, ten days; and let them give us pulse to eat, and water to drink ... and as thou seest, deal with thy servants. Daniel 1:12, 13.",
   "As for these four children, God gave them knowledge and skill in all learning and wisdom: and Daniel had understanding in all visions and dreams. Daniel 1:17.",
   "Then was the secret revealed unto Daniel in a night vision. Then Daniel blessed the God of heaven. Daniel 2:19.",
   "Our God whom we serve is able to deliver us from the burning fiery furnace, and he will deliver us out of thine hand, O king. But if not, ... we will not serve thy gods, nor worship the golden image which thou hast set up. Daniel 3:17, 18.",
   "And the princes, governors, and captains, and the king’s counsellors, being gathered together, saw these men, upon whose bodies the fire had no power, nor was an hair of their head singed. Daniel 3:27.",
   "They shall drive thee from men, and thy dwelling shall be with the beasts of the field, ... and seven times shall pass over thee, till thou know that the most High ruleth in the kingdom of men. Daniel 4:22-25.",
   "Now I Nebuchadnezzar praise and extol and honour the King of heaven, all whose works are truth, and his ways judgment: and those that walk in pride he is able to abase. Daniel 4:37.",
   "The former governors that had been before me were chargeable unto the people, and had taken of them bread and wine, beside forty shekels of silver; yea, even their servants bare rule over the people. Nehemiah 5:15.",
   "Let now thine ear be attentive to the prayer of thy servant, and to the prayer of thy servants, who desire to fear thy name: and prosper, I pray thee, thy servant this day, and grant him mercy in the sight of this man. Nehemiah 1:11.",
   "And I said unto the king, If it please the king, and if thy servant have found favour in thy sight, that thou wouldest send me unto Judah, unto the city of my fathers’ sepulchres, that I may build it. Nehemiah 2:5.",
   "Let letters be given me to the governors beyond the river, that they may convey me over till I come into Judah; and a letter unto Asaph ... that he may give me timber ... for the wall of the city. Nehemiah 2:7, 8.",
   "Ezra had prepared his heart to seek the law of the Lord, and to do it, and to teach in Israel statutes and judgments. Ezra 7:10.",
   "And the Lord said unto Satan, The Lord rebuke thee, O Satan; even the Lord that hath chosen Jerusalem rebuke thee: is not this a brand plucked out of the fire? Zechariah 3:2.",
   "Then they that feared the Lord spake often one to another: and the Lord hearkened, and heard it, and a book of remembrance was written before him for them that feared the Lord, and that thought upon his name. Malachi 3:16.",
   "Now all these things happened unto them for ensamples: and they are written for our admonition, upon whom the ends of the world are come. 1 Corinthians 10:11.",

   // July
   "And Jesus being full of the Holy Ghost returned from Jordan, and was led by the Spirit into the wilderness. Luke 4:1.",
   "When a strong man armed keepeth his palace, his goods are in peace. Luke 11:21.",
   "But unto the Son he saith, Thy throne, O God, is for ever and ever: a sceptre of righteousness is the sceptre of thy kingdom. Hebrews 1:8.",
   "If thou be the Son of God, command that these stones be made bread. Matthew 4:3.",
   "It is written, ‘One does not live by bread alone, but by every word that comes from the mouth of God.’ Matthew 4:4, NRSV.",
   "If thou be the Son of God, cast thyself down: for it is written, He shall give his angels charge concerning thee: and in their hands they shall bear thee up, lest at any time thou dash thy foot against a stone. Matthew 4:6.",
   "Then the devil leaveth him, and, behold, angels came and ministered unto him. Matthew 4:11.",
   "For he shall give his angels charge over thee, to keep thee in all thy ways. They shall bear thee up in their hands, lest thou dash thy foot against a stone. Psalm 91:11, 12.",
   "His divine power hath given unto us all things that pertain unto life and godliness, through the knowledge of him that hath called us to glory and virtue. 2 Peter 1:3.",
   "Blessed is every one that feareth the Lord; that walketh in his ways. For thou shalt eat the labour of thine hands: happy shalt thou be, and it shall be well with thee. Psalm 128:1, 2.",
   "That the trial of your faith, being much more precious than of gold that perisheth, though it be tried with fire, might be found unto praise and honour and glory at the appearing of Jesus Christ. 1 Peter 1:7.",
   "The salvation of the righteous is of the Lord: he is their strength in the time of trouble. And the Lord shall help them, and deliver them: he shall deliver them from the wicked, and save them, because they trust in him. Psalm 37:39, 40.",
   "But to all who received him, who believed in his name, he gave power to become children of God. John 1:12, NRSV.",
   "If thou be the Son of God, command this stone that it may be made bread.... If thou be the Son of God, cast thyself down from hence. Luke 4:3-9.",
   "Strive to enter in at the strait gate: for many, I say unto you, will seek to enter in, and shall not be able. Luke 13:24.",
   "To the one who conquers I will give a place with me on my throne, just as I myself conquered and sat down with my Father on his throne. Revelation 3:21, NRSV.",
   "While we look not at the things which are seen, but at the things which are not seen: for the things which are seen are temporal; but the things which are not seen are eternal. 2 Corinthians 4:18.",
   "Give diligence to make your calling and election sure: for if ye do these things, ye shall never fall. 2 Peter 1:10.",
   "Can the Ethiopian change his skin, or the leopard his spots? then may ye also do good, that are accustomed to do evil. Jeremiah 13:23.",
   "Abide in me, and I in you. As the branch cannot bear fruit of itself, except it abide in the vine; no more can ye, except ye abide in me. John 15:4.",
   "Beloved, we are God’s children now; what we will be has not yet been revealed. What we do know is this: when he is revealed, we will be like him, for we will see him as he is. 1 John 3:2, NRSV.",
   "And they that be wise shall shine as the brightness of the firmament; and they that turn many to righteousness as the stars for ever and ever. Daniel 12:3.",
   "This is my beloved Son, in whom I am well pleased. Matthew 3:17.",
   "All scripture is inspired by God and is useful for teaching, for reproof, for correction, and for training in righteousness, so that everyone who belongs to God may be proficient, equipped for every good work. 2 Timothy 3:16, 17, NRSV.",
   "Let him take hold of my strength, that he may make peace with me; and he shall make peace with me. Isaiah 27:5.",
   "To everyone who conquers, I will give permission to eat from the tree of life that is in the paradise of God. Revelation 2:7, NRSV.",
   "Thanks be to God, which giveth us the victory through our Lord Jesus Christ. 1 Corinthians 15:57.",
   "He was in the world, and the world was made by him, and the world knew him not. John 1:10.",
   "He humbled you ... in order to make you understand that one does not live by bread alone, but by every word that comes from the mouth of the Lord. Deuteronomy 8:3, NRSV.",
   "Thou shalt fear the Lord thy God, and serve him. Deuteronomy 6:13.",
   "The name of the Lord is a strong tower: the righteous runneth into it, and is safe. Proverbs 18:10.",
   
   // August
   "For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them. Ephesians 2:10.",
   "For by grace are ye saved through faith; ... it is the gift of God. Ephesians 2:8.",
   "And the child grew, and waxed strong in spirit, filled with wisdom: and the grace of God was upon him. Luke 2:40.",
   "Wist ye not that I must be about my Father’s business? Luke 2:49.",
   "And Jesus increased in wisdom and stature, and in favour with God and man. Luke 2:52.",
   "All these things spake Jesus unto the multitude in parables. Matthew 13:34.",
   "And he said unto them, Full well ye reject the commandment of God, that ye may keep your own tradition. Mark 7:9.",
   "I will write upon him the name of my God, and the name of the city of my God, which is new Jerusalem, which cometh down out of heaven from my God: and I will write upon him my new name. Revelation 3:12.",
   "For neither did his brethren believe in him. John 7:5.",
   "The steward called the bridegroom and said to him, ‘Everyone serves the good wine first, and then the inferior wine after the guests have become drunk. But you have kept the good wine until now.’ John 2:10, NRSV.",
   "This beginning of miracles did Jesus in Cana of Galilee, and manifested forth his glory; and his disciples believed on him. John 2:11.",
   "There cometh a woman of Samaria to draw water: Jesus saith unto her, Give me to drink. John 4:7.",
   "Is not this the carpenter, the son of Mary, the brother of James, and Joses, and of Juda, and Simon? and are not his sisters here with us? And they were offended at him. Mark 6:3.",
   "Jesus answered and said unto him, Verily, verily, I say unto thee, Except a man be born again, he cannot see the kingdom of God. John 3:3.",
   "Then came the officers to the chief priests and Pharisees; and they said unto them, Why have ye not brought him? The officers answered, Never man spake like this man. John 7:45, 46.",
   "Sanctify them through thy truth: thy word is truth. John 17:17.",
   "The kingdom of heaven may be compared to someone who sowed good seed in his field; but while everybody was asleep, an enemy came and sowed weeds among the wheat, and then went away. Matthew 13:24, 25, NRSV.",
   "And, behold, they brought to him a man sick of the palsy, lying on a bed: and Jesus seeing their faith said unto the sick of the palsy; Son, be of good cheer; thy sins be forgiven thee. Matthew 9:2.",
   "Then goeth he, and taketh with himself seven other spirits more wicked than himself, and they enter in and dwell there. Matthew 12:45.",
   "But Jesus turned him about, and when he saw her, he said, Daughter, be of good comfort; thy faith hath made thee whole. Matthew 9:22.",
   "And seeing the multitudes, he went up into a mountain: and when he was set, his disciples came unto him. Matthew 5:1.",
   "There came unto him a centurion, beseeching him, and saying, Lord, my servant lieth at home sick of the palsy, grievously tormented. And Jesus saith unto him, I will come and heal him. Matthew 8:5-7.",
   "But straightway Jesus spake unto them, saying, Be of good cheer; it is I; be not afraid. Matthew 14:27.",
   "And he said, Verily I say unto you, No prophet is accepted in his own country. Luke 4:24.",
   "The Lord is my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him. Psalm 28:7.",
   "But the Pharisees said, He casteth out devils through the prince of the devils. Matthew 9:34.",
   "For as in Adam all die, even so in Christ shall all be made alive. 1 Corinthians 15:22.",
   "For ye are all the children of God by faith in Christ Jesus. Galatians 3:26.",
   "If they have persecuted me, they will also persecute you. John 15:20.",
   "Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls. Matthew 11:29.",
   "And this is life eternal, that they might know thee the only true God, and Jesus Christ, whom thou hast sent. John 17:3.",
   
   // September
   "Jesus said, Take ye away the stone. Martha, the sister of him that was dead, saith unto him, Lord ... he hath been dead four days. John 11:39.",
   "Now when Jesus was in Bethany, in the house of Simon the leper, there came unto him a woman having an alabaster box of very precious ointment, and poured it on his head, as he sat at meat. Matthew 26:6, 7.",
   "Ye shall find an ass tied, and a colt with her: loose them, and bring them unto me. And if any man say aught unto you, ye shall say, The Lord hath need of them. Matthew 21:2, 3.",
   "He came unto his own, and his own received him not. John 1:11.",
   "And Jesus went into the temple of God, and cast out all them that sold and bought in the temple, and overthrew the tables of the moneychangers, and the seats of them that sold doves. Matthew 21:12.",
   "And when he saw a fig tree in the way, he came to it, and found nothing thereon, but leaves only, and said unto it, Let no fruit grow on thee henceforward for ever. And presently the fig tree withered away. Matthew 21:19.",
   "Every branch in me that beareth not fruit he taketh away: and every branch that beareth fruit, he purgeth it, that it may bring forth more fruit. John 15:2.",
   "Behold, what manner of love the Father hath bestowed upon us, that we should be called the sons of God: therefore the world knoweth us not, because it knew him not. 1 John 3:1.",
   "Hereafter I will not talk much with you: for the prince of this world cometh, and hath nothing in me. John 14:30.",
   "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid. John 14:27.",
   "Then came the day of unleavened bread, when the passover must be killed. And he sent Peter and John, saying, Go and prepare us the passover, that we may eat. Luke 22:7, 8.",
   "And there was also a strife among them, which of them should be accounted the greatest. Luke 22:24.",
   "Then cometh he to Simon Peter: and Peter saith unto him, Lord, dost thou wash my feet? John 13:6.",
   "Verily, verily, I say unto you, that one of you shall betray me. John 13:21.",
   "Have not I chosen you twelve, and one of you is a devil? He spake of Judas Iscariot the son of Simon: for he it was that should betray him. John 6:70, 71.",
   "And they came to a place which was named Gethsemane: and he saith to his disciples, Sit ye here, while I shall pray. Mark 14:32.",
   "And being in an agony he prayed more earnestly: and his sweat was as it were great drops of blood falling down to the ground. Luke 22:44.",
   "Rise up, let us go; lo, he that betrayeth me is at hand. Mark 14:42.",
   "Consider that it is expedient for us, that one man should die for the people, and that the whole nation perish not. John 11:50.",
   "Knowest thou not that I have power to crucify thee, and have power to release thee? Jesus answered, Thou couldest have no power at all against me, except it were given thee from above. John 19:10, 11.",
   "And Herod with his men of war set him at nought, and mocked him, and arrayed him in a gorgeous robe, and sent him again to Pilate. Luke 23:11.",
   "And from henceforth Pilate sought to release him: but the Jews cried out, saying, If thou let this man go, thou art not Caesar’s friend: whosoever maketh himself a king speaketh against Caesar. John 19:12.",
   "Pilate said unto them, Whom will ye that I release unto you? Barabbas, or Jesus which is called Christ? Matthew 27:17.",
   "But ye have a custom, that I should release unto you one at the passover: will ye therefore that I release unto you the King of the Jews? John 18:39.",
   "Wherefore let him that thinketh he standeth take heed lest he fall. 1 Corinthians 10:12.",
   "And when they were come to the place, which is called Calvary, there they crucified him, and the malefactors, one on the right hand, and the other on the left. Luke 23:33.",
   "Reproach hath broken my heart; and I am full of heaviness: and I looked for some to take pity, but there was none; and for comforters, but I found none. Psalm 69:20.",
   "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed. Isaiah 53:5.",
   "If the world hate you, ye know that it hated me before it hated you.... because ye are not of the world, but I have chosen you out of the world, therefore the world hateth you. John 15:18, 19.",

   // October
   "And, behold, the veil of the temple was rent in twain from the top to the bottom; and the earth did quake, and the rocks rent. Matthew 27:51.",
   "He went to Pilate, and begged the body of Jesus.... And when Joseph had taken the body, he wrapped it in a clean linen cloth, and laid it in his own new tomb, which he had hewn out in the rock. Matthew 27:58-60.",
   "And, behold, there was a great earthquake: for the angel of the Lord descended from heaven, and came and rolled back the stone from the door, and sat upon it. Matthew 28:2.",
   "He is not here, but is risen: remember how he spake unto you when he was yet in Galilee, saying, The Son of man must be delivered into the hands of sinful men, and be crucified, and the third day rise again. Luke 24:6, 7.",
   "And for fear of him the keepers did shake, and became as dead men. Matthew 28:4.",
   "And the graves were opened; and many bodies of the saints which slept arose, and came out of the graves after his resurrection, and went into the holy city, and appeared unto many. Matthew 27:52, 53.",
   "To him that overcometh will I grant to sit with me in my throne, even as I also overcame, and am set down with my Father in his throne. Revelation 3:21.",
   "Lift up your heads, O ye gates; and be ye lift up, ye everlasting doors; and the King of glory shall come in. Psalm 24:7.",
   "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life. John 3:16.",
   "It is finished. John 19:30.",
   "Give me understanding, and I shall keep thy law; yea, I shall observe it with my whole heart. Psalm 119:34.",
   "Who his own self bear our sins in his own body on the tree, that we, being dead to sins, should live unto righteousness: by whose stripes ye were healed. 1 Peter 2:24.",
   "Lift up your heads, O ye gates; even lift them up, ye everlasting doors; and the King of glory shall come in. Psalm 24:9.",
   "And, behold, I send the promise of my Father upon you: but tarry ye in the city of Jerusalem, until ye be endued with power from on high. Luke 24:49.",
   "Two of them went that same day to a village called Emmaus, which was from Jerusalem about threescore furlongs. And they talked together of all these things which had happened. Luke 24:13, 14.",
   "And beginning at Moses and all the prophets, he expounded unto them in all the scriptures the things concerning himself. Luke 24:27.",
   "And it came to pass, as he sat at meat with them, he took bread, and blessed it, and brake, and gave to them. And their eyes were opened, and they knew him; and he vanished out of their sight. Luke 24:30, 31.",
   "And they told what things were done in the way, and how he was known of them in breaking of bread. And as they thus spake, Jesus himself stood in the midst of them, and saith unto them, Peace be unto you. Luke 24:35, 36.",
   "Then opened he their understanding, that they might understand the scriptures. Luke 24:45.",
   "But when the Comforter is come, whom I will send unto you from the Father, even the Spirit of truth, which proceedeth from the Father, he shall testify of me. John 15:26.",
   "But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me both in Jerusalem, and in all Judaea, and in Samaria, and unto the uttermost part of the earth. Acts 1:8.",
   "I will pour out of my Spirit upon all flesh: and your sons and your daughters shall prophesy, and your young men shall see visions, and your old men shall dream dreams. Acts 2:17.",
   "The Sadducees, came upon them, being grieved that they taught the people, and preached through Jesus the resurrection from the dead. And they laid hands on them, and put them in hold unto the next day. Acts 4:1-3.",
   "But Peter and the apostles answered, ‘We must obey God rather than any human authority.’ Acts 5:29, NRSV.",
   "But if it be of God, ye cannot overthrow it; lest haply ye be found even to fight against God. Acts 5:39.",
   "Be patient therefore, brethren, unto the coming of the Lord. Behold, the husbandman waiteth for the precious fruit of the earth, and hath long patience for it, until he receive the early and latter rain. James 5:7.",
   "Then they cried out with a loud voice, and stopped their ears, and ran upon him with one accord, and cast him out of the city, and stoned him. Acts 7:57, 58.",
   "A man of Ethiopia, an eunuch of great authority, ... was returning, and sitting in his chariot read Esaias the prophet. Then the Spirit said unto Philip, Go near, and join thyself to this chariot. Acts 8:27-29.",
   "And he fell to the earth, and heard a voice saying unto him, Saul, Saul, why persecutest thou me? And he said, Who art thou, Lord? And the Lord said, I am Jesus whom thou persecutest. Acts 9:4, 5.",
   "Let no man despise thy youth; but be thou an example of the believers, in word, in conversation, in charity, in spirit, in faith, in purity. 1 Timothy 4:12.",
   "The Revelation of Jesus Christ, which God gave unto him, to shew unto his servants things which must shortly come to pass; and he sent and signified it by his angel unto his servant John. Revelation 1:1.",
   
   // November
   "The devil shall cast some of you into prison, that ye may be tried; and ye shall have tribulation ten days: be thou faithful unto death, and I will give thee a crown of life. Revelation 2:10.",
   "Blessed is he that readeth, and they that hear the words of this prophecy, and keep those things which are written therein: for the time is at hand. Revelation 1:3.",
   "I John, who also am your brother, and companion in tribulation, and in the kingdom and patience of Jesus Christ, was in the isle that is called Patmos, for the word of God, and for the testimony of Jesus Christ. Revelation 1:9.",
   "Behold, the Lion of the tribe of Juda.... And in the midst of the elders stood a Lamb as it had been slain. Revelation 5:5, 6.",
   "There will be signs.... People will faint from fear and foreboding of what is coming upon the world. Luke 21:25, 26, NRSV.",
   "Strait is the gate, and narrow is the way, which leadeth unto life, and few there be that find it. Matthew 7:14.",
   "And this is the judgment, that the light has come into the world, and people loved darkness rather than light. John 3:19, NRSV.",
   "And others had trial of cruel mockings and scourgings, yea, moreover of bonds and imprisonment. Hebrews 11:36.",
   "I have a few things against thee, because thou sufferest that woman Jezebel, which calleth herself a prophetess, to teach and to seduce my servants to commit fornication, and to eat things sacrificed unto idols. Revelation 2:20.",
   "Then shall the kingdom of heaven be likened unto ten virgins, which took their lamps, and went forth to meet the bridegroom. And five of them were wise, and five were foolish. Matthew 25:1, 2.",
   "Yea, and all that will live godly in Christ Jesus shall suffer persecution. 2 Timothy 3:12.",
   "Write the things which thou hast seen, and the things which are, and the things which shall be hereafter. Revelation 1:19.",
   "Keep back thy servant also from presumptuous sins; let them not have dominion over me: then shall I be upright, and I shall be innocent from the great transgression. Psalm 19:13.",
   "He shall cover thee with his feathers, and under his wings shalt thou trust: his truth shall be thy shield and buckler. Psalm 91:4.",
   "I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the Lord, which made heaven and earth. Psalm 121:1, 2.",
   "But there is a God in heaven that revealeth king Nebuchadnezzar what shall be in the latter days. Daniel 2:28.",
   "Ye are all the children of light, and the children of the day: we are not of the night, nor of darkness. 1 Thessalonians 5:5.",
   "Ye ought to be quiet, and to do nothing rashly. Acts 19:36.",
   "Only by pride cometh contention: but with the well advised is wisdom. Proverbs 13:10.",
   "Anyone who resolves to do the will of God will know whether the teaching is from God or whether I am speaking on my own. John 7:17, NRSV.",
   "Search the scriptures; for in them ye think ye have eternal life: and they are they which testify of me. John 5:39.",
   "For we wrestle not against flesh and blood, but against principalities, against powers, against the rulers of the darkness of this world. Ephesians 6:12.",
   "Now I am come to make thee understand what shall befall thy people in the latter days: for yet the vision is for many days. Daniel 10:14.",
   "But thou, O Daniel, shut up the words, and seal the book, even to the time of the end: many shall run to and fro, and knowledge shall be increased. Daniel 12:4.",
   "Who shall separate us from the love of Christ? shall tribulation, or distress, or persecution, or famine, or nakedness, or peril, or sword? Romans 8:35.",
   "We are troubled on every side, yet not distressed; we are perplexed, but not in despair; persecuted, but not forsaken; cast down, but not destroyed. 2 Corinthians 4:8, 9.",
   "And I saw another angel fly in the midst of heaven, ... saying with a loud voice, Fear God, and give glory to him; for the hour of his judgment is come. Revelation 14:6, 7.",
   "And they that shall be of thee shall build the old waste places: thou shalt raise up the foundations of many generations; and thou shalt be called, The repairer of the breach, The restorer of paths to dwell in. Isaiah 58:12.",
   "And he set his right foot upon the sea, and his left foot on the earth. Revelation 10:2.",
   "And I took the little book out of the angel’s hand, and ate it up; and it was in my mouth sweet as honey: and as soon as I had eaten it, my belly was bitter. And he said unto me, Thou must prophesy again. Revelation 10:10, 11.",
   
   // December
   "Study to shew thyself approved unto God, a workman that needeth not to be ashamed, rightly dividing the word of truth. 2 Timothy 2:15.",
   "But about that day and hour no one knows, neither the angels of heaven, nor the Son, but only the Father. Matthew 24:36, NRSV.",
   "And the angel which I saw stand upon the sea and upon the earth lifted up his hand to heaven, and sware by him that liveth for ever and ever, ... that there should be time no longer. Revelation 10:5, 6.",
   "Who gave himself for us, that he might redeem us from all iniquity, and purify unto himself a peculiar people, ... These things speak, and exhort, and rebuke with all authority. Let no man despise thee. Titus 2:14, 15.",
   "Watch therefore: for ye know not what hour your Lord doth come.... Therefore be ye also ready: for in such an hour as ye think not the Son of man cometh. Matthew 24:42-44.",
   "The watchman said, The morning cometh, and also the night: if ye will inquire, inquire ye: return, come. Isaiah 21:12.",
   "And before him shall be gathered all nations: and he shall separate them one from another, as a shepherd divideth his sheep from the goats: and he shall set the sheep on his right hand, but the goats on the left. Matthew 25:32, 33.",
   "And they shall be mine, saith the Lord of hosts, in that day when I make up my jewels; and I will spare them, as a man spareth his own son that serveth him. Malachi 3:17.",
   "Cry aloud, spare not, lift up thy voice like a trumpet, and shew my people their transgression, and the house of Jacob their sins. Isaiah 58:1.",
   "A new heart also will I give you, and a new spirit will I put within you: and I will take away the stony heart out of your flesh, and I will give you an heart of flesh. Ezekiel 36:26.",
   "Ye are the light of the world. A city that is set on an hill cannot be hid. Matthew 5:14.",
   "The disciples came unto him privately, saying, Tell us, when shall these things be? And what shall be the sign of thy coming, and of the end of the world? Matthew 24:3.",
   "For I reckon that the sufferings of this present time are not worthy to be compared with the glory which shall be revealed in us. Romans 8:18.",
   "I am the Lord your God; walk in my statutes, and keep my judgments, and do them; and hallow my sabbaths; and they shall be a sign between me and you, that ye may know that I am the Lord your God. Ezekiel 20:19, 20.",
   "Finally, my brethren, be strong in the Lord, and in the power of his might. Ephesians 6:10.",
   "Not unto themselves, but unto us they did minister the things, which are now reported unto you by them that have preached the gospel unto you with the Holy Ghost sent down from heaven. 1 Peter 1:12.",
   "He that shall endure unto the end, the same shall be saved. And this gospel of the kingdom shall be preached in all the world ... and then shall the end come. Matthew 24:13, 14.",
   "Many shall be purified, and made white, and tried; but the wicked shall do wickedly: and none of the wicked shall understand; but the wise shall understand. Daniel 12:10.",
   "Come unto me, all ye that labour and are heavy laden, and I will give you rest. Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls. Matthew 11:28, 29.",
   "For we are labourers together with God: ye are God’s husbandry, ye are God’s building. 1 Corinthians 3:9.",
   "In vain do they worship me, teaching human precepts as doctrines. Matthew 15:9, NRSV.",
   "We have not followed cunningly devised fables, when we made known unto you the power and coming of our Lord Jesus Christ. 2 Peter 1:16.",
   "Not everyone who says to me, ‘Lord, Lord,’ will enter the kingdom of heaven, but only the one who does the will of my Father in heaven. Matthew 7:21, NRSV.",
   "For our gospel came not unto you in word only, but also in power, and in the Holy Ghost, and in much assurance. 1 Thessalonians 1:5.",
   "And the letters were sent by posts into all the king’s provinces, to destroy, to kill, and to cause to perish, all Jews, both young and old, little children and women, in one day. Esther 3:13.",
   "No prophecy of scripture is a matter of one’s own interpretation, because no prophecy ever came by human will, but men and women moved by the Holy Spirit spoke from God. 2 Peter 1:20, 21, NRSV.",
   "The way of the just is uprightness: thou, most upright, dost weigh the path of the just. Isaiah 26:7.",
   "For it became him, for whom are all things, and by whom are all things, ... to make the captain of their salvation perfect through sufferings. Hebrews 2:10.",
   "And they brought up an evil report of the land which they had searched unto the children of Israel, saying, The land, through which we have gone to search it, is a land that eateth up the inhabitants thereof. Numbers 13:32.",
   "But the Comforter, which is the Holy Ghost, whom the Father will send in my name, he shall teach you all things, and bring all things to your remembrance, whatsoever I have said unto you. John 14:26.",
   "And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away. Revelation 21:4.",
   


   // Add more texts for each day
               ];
   
               // Get today's date
               const today = new Date();
               const dayOfYear = today.getDate() + today.getMonth() * 30;
   
               // Choose the daily text based on the day of the year
               const selectedText = shaelynMbaso1[dayOfYear % shaelynMbaso1.length];
   
               // Display the daily text on the webpage
               const dailyTextElement = document.getElementById("shaelynMbaso1");
               dailyTextElement.textContent = selectedText;
   
               // Display the current date
               const currentDateElement = document.getElementById("currentDate");
               const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
               currentDateElement.textContent = today.toLocaleDateString('en-US', options);
           });
