const bibleVerses4 = {
    // Numbers 1 (King James Version)
    "Numbers 1:1": "And the LORD spake unto Moses in the wilderness of Sinai, in the tabernacle of the congregation, on the first day of the second month, in the second year after they were come out of the land of Egypt, saying,",
    "Numbers 1:2": "Take ye the sum of all the congregation of the children of Israel, after their families, by the house of their fathers, with the number of their names, every male by their poles;",
    "Numbers 1:3": "From twenty years old and upward, all that are able to go forth to war in Israel: thou and Aaron shall number them by their armies.",
    "Numbers 1:4": "And with you there shall be a man of every tribe; every one head of the house of his fathers.",
    "Numbers 1:5": "And these are the names of the men that shall stand with you: of the tribe of Reuben; Elizur the son of Shedeur.",
    "Numbers 1:6": "Of Simeon; Shelumiel the son of Zurishaddai.",
    "Numbers 1:7": "Of Judah; Nahshon the son of Amminadab.",
    "Numbers 1:8": "Of Issachar; Nethaneel the son of Zuar.",
    "Numbers 1:9": "Of Zebulun; Eliab the son of Helon.",
    "Numbers 1:10": "Of the children of Joseph; of Ephraim; Elishama the son of Ammihud: of Manasseh; Gamaliel the son of Pedahzur.",
    "Numbers 1:11": "Of Benjamin; Abidan the son of Gideoni.",
    "Numbers 1:12": "Of Dan; Ahiezer the son of Ammishaddai.",
    "Numbers 1:13": "Of Asher; Pagiel the son of Ocran.",
    "Numbers 1:14": "Of Gad; Eliasaph the son of Deuel.",
    "Numbers 1:15": "Of Naphtali; Ahira the son of Enan.",
    "Numbers 1:16": "These were the renowned of the congregation, princes of the tribes of their fathers, heads of the thousands of Israel.",
    "Numbers 1:17": "And Moses and Aaron took these men which are expressed by their names.",
    "Numbers 1:18": "And they assembled all the congregation together on the first day of the second month, and they declared their pedigrees after their families, by the house of their fathers, according to the number of the names, from twenty years old and upward, by their poles.",
    "Numbers 1:19": "As the LORD commanded Moses, so he numbered them in the wilderness of Sinai.",
    "Numbers 1:20": "And the children of Reuben, Israel’s eldest son, by their generations, after their families, by the house of their fathers, according to the number of the names, by their poles, every male from twenty years old and upward, all that were able to go forth to war;",
    "Numbers 1:21": "Those that were numbered of them, even of the tribe of Reuben, were forty and six thousand and five hundred.",
    "Numbers 1:22": "Of the children of Simeon, by their generations, after their families, by the house of their fathers, those that were numbered of them, according to the number of the names, from twenty years old and upward, all that were able to go forth to war;",
    "Numbers 1:23": "Those that were numbered of them, even of the tribe of Simeon, were fifty and nine thousand and three hundred.",
    "Numbers 1:24": "Of the children of Gad, by their generations, after their families, by the house of their fathers, those that were numbered of them, according to the number of the names, from twenty years old and upward, all that were able to go forth to war;",
    "Numbers 1:25": "Those that were numbered of them, even of the tribe of Gad, were forty and five thousand and six hundred and fifty.",
    "Numbers 1:26": "Of the children of Judah, by their generations, after their families, by the house of their fathers, those that were numbered of them, according to the number of the names, from twenty years old and upward, all that were able to go forth to war;",
    "Numbers 1:27": "Those that were numbered of them, even of the tribe of Judah, were threescore and fourteen thousand and six hundred.",
    "Numbers 1:28": "Of the children of Issachar, by their generations, after their families, by the house of their fathers, those that were numbered of them, according to the number of the names, from twenty years old and upward, all that were able to go forth to war;",
    "Numbers 1:29": "Those that were numbered of them, even of the tribe of Issachar, were fifty and four thousand and four hundred.",
    "Numbers 1:30": "Of the children of Zebulun, by their generations, after their families, by the house of their fathers, those that were numbered of them, according to the number of the names, from twenty years old and upward, all that were able to go forth to war;",
    "Numbers 1:31": "Those that were numbered of them, even of the tribe of Zebulun, were fifty and seven thousand and four hundred.",
    "Numbers 1:32": "Of the children of Joseph, namely, of the children of Ephraim, by their generations, after their families, by the house of their fathers, those that were numbered of them, according to the number of the names, from twenty years old and upward, all that were able to go forth to war;",
    "Numbers 1:33": "Those that were numbered of them, even of the tribe of Ephraim, were forty thousand and five hundred.",
    "Numbers 1:34": "Of the children of Manasseh, by their generations, after their families, by the house of their fathers, those that were numbered of them, according to the number of the names, from twenty years old and upward, all that were able to go forth to war;",
    "Numbers 1:35": "Those that were numbered of them, even of the tribe of Manasseh, were thirty and two thousand and two hundred.",
    "Numbers 1:36": "Of the children of Benjamin, by their generations, after their families, by the house of their fathers, those that were numbered of them, according to the number of the names, from twenty years old and upward, all that were able to go forth to war;",
    "Numbers 1:37": "Those that were numbered of them, even of the tribe of Benjamin, were thirty and five thousand and four hundred.",
    "Numbers 1:38": "Of the children of Dan, by their generations, after their families, by the house of their fathers, those that were numbered of them, according to the number of the names, from twenty years old and upward, all that were able to go forth to war;",
    "Numbers 1:39": "Those that were numbered of them, even of the tribe of Dan, were threescore and two thousand and seven hundred.",
    "Numbers 1:40": "Of the children of Asher, by their generations, after their families, by the house of their fathers, those that were numbered of them, according to the number of the names, from twenty years old and upward, all that were able to go forth to war;",
    "Numbers 1:41": "Those that were numbered of them, even of the tribe of Asher, were forty and one thousand and five hundred.",
    "Numbers 1:42": "Of the children of Naphtali, by their generations, after their families, by the house of their fathers, those that were numbered of them, according to the number of the names, from twenty years old and upward, all that were able to go forth to war;",
    "Numbers 1:43": "Those that were numbered of them, even of the tribe of Naphtali, were fifty and three thousand and four hundred.",
    "Numbers 1:44": "These are those that were numbered, which Moses and Aaron numbered, and the princes of Israel, being twelve men: they were each one for the house of his fathers.",
    "Numbers 1:45": "So were all those that were numbered of the children of Israel, by the house of their fathers, from twenty years old and upward, all that were able to go forth to war in Israel;",
    "Numbers 1:46": "Even all they that were numbered were six hundred thousand and three thousand and five hundred and fifty.",
    "Numbers 1:47": "But the Levites after the tribe of their fathers were not numbered among them.",
    "Numbers 1:48": "For the LORD had spoken unto Moses, saying,",
    "Numbers 1:49": "Only thou shalt not number the tribe of Levi, neither take the sum of them among the children of Israel:",
    "Numbers 1:50": "But thou shalt appoint the Levites over the tabernacle of testimony, and over all the vessels thereof, and over all things that belong to it: they shall bear the tabernacle, and all the vessels thereof; and they shall minister unto it, and shall encamp round about the tabernacle.",
    "Numbers 1:51": "And when the tabernacle setteth forward, the Levites shall take it down: and when the tabernacle is to be pitched, the Levites shall set it up: and the stranger that cometh nigh shall be put to death.",
    "Numbers 1:52": "And the children of Israel shall pitch their tents, every man by his own camp, and every man by his own standard, throughout their hosts.",
    "Numbers 1:53": "But the Levites shall pitch round about the tabernacle of testimony, that there be no wrath upon the congregation of the children of Israel: and the Levites shall keep the charge of the tabernacle of testimony.",
    "Numbers 1:54": "And the children of Israel did according to all that the LORD commanded Moses, so did they.",
    
    // Numbers 2 (King James Version)
    "Numbers 2:1": "And the LORD spake unto Moses and unto Aaron, saying,",
    "Numbers 2:2": "Every man of the children of Israel shall pitch by his own standard, with the ensign of their father's house: far off about the tabernacle of the congregation shall they pitch.",
    "Numbers 2:3": "And on the east side toward the rising of the sun shall they of the standard of the camp of Judah pitch throughout their armies: and Nahshon the son of Amminadab shall be captain of the children of Judah.",
    "Numbers 2:4": "And his host, and those that were numbered of them, were threescore and fourteen thousand and six hundred.",
    "Numbers 2:5": "And those that do pitch next unto him shall be the tribe of Issachar: and Nethanel the son of Zuar shall be captain of the children of Issachar.",
    "Numbers 2:6": "And his host, and those that were numbered thereof, were fifty and four thousand and four hundred.",
    "Numbers 2:7": "Then the tribe of Zebulun: and Eliab the son of Helon shall be captain of the children of Zebulun.",
    "Numbers 2:8": "And his host, and those that were numbered thereof, were fifty and seven thousand and four hundred.",
    "Numbers 2:9": "All that were numbered in the camp of Judah were an hundred thousand and fourscore thousand and six thousand and four hundred, throughout their armies. These shall first set forth.",
    "Numbers 2:10": "On the south side shall be the standard of the camp of Reuben according to their armies: and the captain of the children of Reuben shall be Eliezer the son of Shedeur.",
    "Numbers 2:11": "And his host, and those that were numbered thereof, were forty and six thousand and five hundred.",
    "Numbers 2:12": "And those which pitch by him shall be the tribe of Simeon: and the captain of the children of Simeon shall be Shelumiel the son of Zurishaddai.",
    "Numbers 2:13": "And his host, and those that were numbered of them, were fifty and nine thousand and three hundred.",
    "Numbers 2:14": "Then the tribe of Gad: and the captain of the sons of Gad shall be Eliasaph the son of Reuel.",
    "Numbers 2:15": "And his host, and those that were numbered of them, were forty and five thousand and six hundred and fifty.",
    "Numbers 2:16": "All that were numbered in the camp of Reuben were an hundred thousand and fifty and one thousand and four hundred and fifty, throughout their armies. And they shall set forth in the second rank.",
    "Numbers 2:17": "Then the tabernacle of the congregation shall set forward with the camp of the Levites in the midst of the camp: as they encamp, so shall they set forward, every man in his place by their standards.",
    "Numbers 2:18": "On the west side shall be the standard of the camp of Ephraim according to their armies: and the captain of the sons of Ephraim shall be Elishama the son of Ammihud.",
    "Numbers 2:19": "And his host, and those that were numbered of them, were forty thousand and five hundred.",
    "Numbers 2:20": "And by him shall be the tribe of Manasseh: and the captain of the children of Manasseh shall be Gamaliel the son of Pedahzur.",
    "Numbers 2:21": "And his host, and those that were numbered of them, were thirty and two thousand and two hundred.",
    "Numbers 2:22": "Then the tribe of Benjamin: and the captain of the sons of Benjamin shall be Abidan the son of Gideoni.",
    "Numbers 2:23": "And his host, and those that were numbered of them, were thirty and five thousand and four hundred.",
    "Numbers 2:24": "All that were numbered of the camp of Ephraim were an hundred thousand and eight thousand and an hundred, throughout their armies. And they shall go forward in the third rank.",
    "Numbers 2:25": "The standard of the camp of Dan shall be on the north side by their armies: and the captain of the children of Dan shall be Ahiezer the son of Ammishaddai.",
    "Numbers 2:26": "And his host, and those that were numbered of them, were threescore and two thousand and seven hundred.",
    "Numbers 2:27": "And those that encamp by him shall be the tribe of Asher: and the captain of the children of Asher shall be Pagiel the son of Ocran.",
    "Numbers 2:28": "And his host, and those that were numbered of them, were forty and one thousand and five hundred.",
    "Numbers 2:29": "Then the tribe of Naphtali: and the captain of the children of Naphtali shall be Ahira the son of Enan.",
    "Numbers 2:30": "And his host, and those that were numbered of them, were fifty and three thousand and four hundred.",
    "Numbers 2:31": "All they that were numbered of the camp of Dan were an hundred thousand and fifty and seven thousand and six hundred. They shall go hindmost with their standards.",
    "Numbers 2:32": "These are those which were numbered of the children of Israel by the house of their fathers: all those that were numbered of the camps throughout their hosts were six hundred thousand and three thousand and five hundred and fifty.",
    "Numbers 2:33": "But the Levites were not numbered among the children of Israel; as the LORD commanded Moses.",
    "Numbers 2:34": "And the children of Israel did according to all that the LORD commanded Moses: so they pitched by their standards, and so they set forward, every one after their families, according to the house of their fathers.",
    
};