const bibleVerses6 = {
    // Joshua 1 (King James Version)
    "Joshua 1:1": "Now after the death of Moses the servant of the LORD it came to pass, that the LORD spake unto Joshua the son of Nun, Moses' minister, saying,",
    "Joshua 1:2": "Moses my servant is dead; now therefore arise, go over this Jordan, thou, and all this people, unto the land which I do give to them, even to the children of Israel.",
    "Joshua 1:3": "Every place that the sole of your foot shall tread upon, that have I given unto you, as I said unto Moses.",
    "Joshua 1:4": "From the wilderness and this Lebanon even unto the great river, the river Euphrates, all the land of the Hittites, and unto the great sea toward the going down of the sun, shall be your coast.",
    "Joshua 1:5": "There shall not any man be able to stand before thee all the days of thy life: as I was with Moses, so I will be with thee: I will not fail thee, nor forsake thee.",
    "Joshua 1:6": "Be strong and of a good courage: for unto this people shalt thou divide for an inheritance the land, which I sware unto their fathers to give them.",
    "Joshua 1:7": "Only be thou strong and very courageous, that thou mayest observe to do according to all the law, which Moses my servant commanded thee: turn not from it to the right hand or to the left, that thou mayest prosper whithersoever thou goest.",
    "Joshua 1:8": "This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night, that thou mayest observe to do according to all that is written therein: for then thou shalt make thy way prosperous, and then thou shalt have good success.",
    "Joshua 1:9": "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.",
    "Joshua 1:10": "Then Joshua commanded the officers of the people, saying,",
    "Joshua 1:11": "Pass through the host, and command the people, saying, Prepare you victuals; for within three days ye shall pass over this Jordan, to go in to possess the land, which the LORD your God giveth you to possess it.",
    "Joshua 1:12": "And to the Reubenites, and to the Gadites, and to half the tribe of Manasseh, spake Joshua, saying,",
    "Joshua 1:13": "Remember the word which Moses the servant of the LORD commanded you, saying, The LORD your God hath given you rest, and hath given you this land.",
    "Joshua 1:14": "Your wives, your little ones, and your cattle, shall remain in the land which Moses gave you on this side Jordan; but ye shall pass before your brethren armed, all the mighty men of valour, and help them;",
    "Joshua 1:15": "Until the LORD have given your brethren rest, as he hath given you, and they also have possessed the land which the LORD your God giveth them: then ye shall return unto the land of your possession, and enjoy it, which Moses the LORD's servant gave you on this side Jordan toward the sunrising.",
    "Joshua 1:16": "And they answered Joshua, saying, All that thou commandest us we will do, and whithersoever thou sendest us, we will go.",
    "Joshua 1:17": "According as we hearkened unto Moses in all things, so will we hearken unto thee: only the LORD thy God be with thee, as he was with Moses.",
    "Joshua 1:18": "Whosoever he be that doth rebel against thy commandment, and will not hearken unto thy words in all that thou commandest him, he shall be put to death: only be strong and of a good courage.",
    
    // Joshua 2 (King James Version)
    "Joshua 2:1": "And Joshua the son of Nun sent out of Shittim two men to spy secretly, saying, Go view the land, even Jericho. And they went, and came into an harlot's house, named Rahab, and lodged there.",
    "Joshua 2:2": "And it was told the king of Jericho, saying, Behold, there came men in hither to night of the children of Israel to search out the country.",
    "Joshua 2:3": "And the king of Jericho sent unto Rahab, saying, Bring forth the men that are come to thee, which are entered into thine house: for they be come to search out all the country.",
    "Joshua 2:4": "And the woman took the two men, and hid them, and said thus, There came men unto me, but I wist not whence they were:",
    "Joshua 2:5": "And it came to pass about the time of shutting of the gate, when it was dark, that the men went out: whither the men went I wot not: pursue after them quickly; for ye shall overtake them.",
    "Joshua 2:6": "But she had brought them up to the roof of the house, and hid them with the stalks of flax, which she had laid in order upon the roof.",
    "Joshua 2:7": "And the men pursued after them the way to Jordan unto the fords: and as soon as they which pursued after them were gone out, they shut the gate.",
    "Joshua 2:8": "And before they were laid down, she came up unto them upon the roof;",
    "Joshua 2:9": "And she said unto the men, I know that the LORD hath given you the land, and that your terror is fallen upon us, and that all the inhabitants of the land faint because of you.",
    "Joshua 2:10": "For we have heard how the LORD dried up the water of the Red sea for you, when ye came out of Egypt; and what ye did unto the two kings of the Amorites, that were on the other side Jordan, Sihon and Og, whom ye utterly destroyed.",
    "Joshua 2:11": "And as soon as we had heard these things, our hearts did melt, neither did there remain any more courage in any man, because of you: for the LORD your God, he is God in heaven above, and in earth beneath.",
    "Joshua 2:12": "Now therefore, I pray you, swear unto me by the LORD, since I have shewed you kindness, that ye will also shew kindness unto my father's house, and give me a true token:",
    "Joshua 2:13": "And that ye will save alive my father, and my mother, and my brethren, and my sisters, and all that they have, and deliver our lives from death.",
    "Joshua 2:14": "And the men answered her, Our life for yours, if ye utter not this our business. And it shall be, when the LORD hath given us the land, that we will deal kindly and truly with thee.",
    "Joshua 2:15": "Then she let them down by a cord through the window: for her house was upon the town wall, and she dwelt upon the wall.",
    "Joshua 2:16": "And she said unto them, Get you to the mountain, lest the pursuers meet you; and hide yourselves there three days, until the pursuers be returned: and afterward may ye go your way.",
    "Joshua 2:17": "And the men said unto her, We will be blameless of this thine oath which thou hast made us swear.",
    "Joshua 2:18": "Behold, when we come into the land, thou shalt bind this line of scarlet thread in the window which thou didst let us down by: and thou shalt bring thy father, and thy mother, and thy brethren, and all thy father's household, home unto thee.",
    "Joshua 2:19": "And it shall be, that whosoever shall go out of the doors of thy house into the street, his blood shall be upon his head, and we will be guiltless: and whosoever shall be with thee in the house, his blood shall be on our head, if any hand be upon him.",
    "Joshua 2:20": "And if thou utter this our business, then we will be quit of thine oath which thou hast made us to swear.",
    "Joshua 2:21": "And she said, According unto your words, so be it. And she sent them away, and they departed: and she bound the scarlet line in the window.",
    "Joshua 2:22": "And they went, and came unto the mountain, and abode there three days, until the pursuers were returned: and the pursuers sought them throughout all the way, but found them not.",
    "Joshua 2:23": "So the two men returned, and descended from the mountain, and passed over, and came to Joshua the son of Nun, and told him all things that befell them:",
    "Joshua 2:24": "And they said unto Joshua, Truly the LORD hath delivered into our hands all the land; for even all the inhabitants of the country do faint because of us.",
    
    // Joshua 3 (King James Version)
    "Joshua 3:1": "And Joshua rose early in the morning; and they removed from Shittim, and came to Jordan, he and all the children of Israel, and lodged there before they passed over.",
    "Joshua 3:2": "And it came to pass after three days, that the officers went through the host;",
    "Joshua 3:3": "And they commanded the people, saying, When ye see the ark of the covenant of the LORD your God, and the priests the Levites bearing it, then ye shall remove from your place, and go after it.",
    "Joshua 3:4": "Yet there shall be a space between you and it, about two thousand cubits by measure: come not near unto it, that ye may know the way by which ye must go: for ye have not passed this way heretofore.",
    "Joshua 3:5": "And Joshua said unto the people, Sanctify yourselves: for to morrow the LORD will do wonders among you.",
    "Joshua 3:6": "And Joshua spake unto the priests, saying, Take up the ark of the covenant, and pass over before the people. And they took up the ark of the covenant, and went before the people.",
    "Joshua 3:7": "And the LORD said unto Joshua, This day will I begin to magnify thee in the sight of all Israel, that they may know that, as I was with Moses, so I will be with thee.",
    "Joshua 3:8": "And thou shalt command the priests that bear the ark of the covenant, saying, When ye are come to the brink of the water of Jordan, ye shall stand still in Jordan.",
    "Joshua 3:9": "And Joshua said unto the children of Israel, Come hither, and hear the words of the LORD your God.",
    "Joshua 3:10": "And Joshua said, Hereby ye shall know that the living God is among you, and that he will without fail drive out from before you the Canaanites, and the Hittites, and the Hivites, and the Perizzites, and the Girgashites, and the Amorites, and the Jebusites.",
    "Joshua 3:11": "Behold, the ark of the covenant of the LORD of all the earth passeth over before you into Jordan.",
    "Joshua 3:12": "Now therefore take you twelve men out of the tribes of Israel, out of every tribe a man.",
    "Joshua 3:13": "And it shall come to pass, as soon as the soles of the feet of the priests that bear the ark of the LORD, the Lord of all the earth, shall rest in the waters of Jordan, that the waters of Jordan shall be cut off from the waters that come down from above; and they shall stand upon an heap.",
    "Joshua 3:14": "And it came to pass, when the people removed from their tents, to pass over Jordan, and the priests bearing the ark of the covenant before the people;",
    "Joshua 3:15": "And as they that bare the ark were come unto Jordan, and the feet of the priests that bare the ark were dipped in the brim of the water, (for Jordan overfloweth all his banks all the time of harvest,)",
    "Joshua 3:16": "That the waters which came down from above stood and rose up upon an heap very far from the city Adam, that is beside Zaretan: and those that came down toward the sea of the plain, even the salt sea, failed, and were cut off: and the people passed over right against Jericho.",
    "Joshua 3:17": "And the priests that bare the ark of the covenant of the LORD stood firm on dry ground in the midst of Jordan, and all the Israelites passed over on dry ground, until all the people were passed clean over Jordan.",
    
    // Joshua 4 (King James Version)
    "Joshua 4:1": "And it came to pass, when all the people were clean passed over Jordan, that the LORD spake unto Joshua, saying,",
    "Joshua 4:2": "Take you twelve men out of the people, out of every tribe a man,",
    "Joshua 4:3": "And command ye them, saying, Take you hence out of the Jordan a stone upon your shoulder, according unto the number of the tribes of the children of Israel:",
    "Joshua 4:4": "That this may be a sign among you, that when your children ask their fathers in time to come, saying, What mean ye by these stones?",
    "Joshua 4:5": "Then ye shall answer them, That the waters of Jordan were cut off before the ark of the covenant of the LORD; when it passed over Jordan, the waters of Jordan were cut off: and these stones shall be for a memorial unto the children of Israel for ever.",
    "Joshua 4:6": "And the children of Israel did so as Joshua commanded, and took up twelve stones out of the midst of Jordan, as the LORD spake unto Joshua, according to the number of the tribes of the children of Israel, and carried them over with them unto the place where they lodged, and laid them down there.",
    "Joshua 4:7": "And Joshua set up twelve stones in the midst of Jordan, in the place where the feet of the priests which bare the ark of the covenant stood: and they are there unto this day.",
    "Joshua 4:8": "For the priests which bare the ark stood in the midst of Jordan, until every thing was finished that the LORD commanded Joshua to speak unto the people, according to all that Moses commanded Joshua: and the people hasted and passed over.",
    "Joshua 4:9": "And it came to pass, when the people were clean passed over, that the ark of the LORD passed over, and the priests, in the presence of the people.",
    "Joshua 4:10": "And the children of Reuben and the children of Gad and half the tribe of Manasseh passed over armed before the children of Israel, as Moses spake unto them:",
    "Joshua 4:11": "About forty thousand prepared for war passed over before the LORD unto battle, to the plains of Jericho.",
    "Joshua 4:12": "On that day the LORD magnified Joshua in the sight of all Israel; and they feared him, as they feared Moses, all the days of his life.",
    "Joshua 4:13": "And the LORD spake unto Joshua, saying,",
    "Joshua 4:14": "Command the priests that bear the ark of the covenant, that they come up out of Jordan.",
    "Joshua 4:15": "Joshua therefore commanded the priests, saying, Come ye up out of Jordan.",
    "Joshua 4:16": "And it came to pass, when the priests that bare the ark of the covenant of the LORD were come up out of the midst of Jordan, and the soles of the priests' feet were lifted up unto the dry land, that the waters of Jordan returned unto their place, and flowed over all his banks, as they did before.",
    "Joshua 4:17": "And the people came up out of Jordan on the tenth day of the first month, and encamped in Gilgal, in the east border of Jericho.",
    "Joshua 4:18": "And those twelve stones, which they took out of Jordan, did Joshua pitch in Gilgal.",
    "Joshua 4:19": "And he spake unto the children of Israel, saying, When your children shall ask their fathers in time to come, saying, What mean these stones?",
    "Joshua 4:20": "Then ye shall let your children know, saying, Israel came over this Jordan on dry land.",
    "Joshua 4:21": "For the LORD your God dried up the waters of Jordan from before you, until ye were passed over, as the LORD your God did to the Red sea, which he dried up from before us, until we were gone over:",
    "Joshua 4:22": "That all the people of the earth might know the hand of the LORD, that it is mighty: that ye might fear the LORD your God for ever.",
    
    // Joshua 5 (King James Version)
    "Joshua 5:1": "And it came to pass, when all the kings of the Amorites, which were on the side of Jordan westward, and all the kings of the Canaanites, which were by the sea, heard that the LORD had dried up the waters of Jordan from before the children of Israel, until we were passed over, that their heart melted, neither was there spirit in them any more, because of the children of Israel.",
    "Joshua 5:2": "At that time the LORD said unto Joshua, Make thee sharp knives, and circumcise again the children of Israel the second time.",
    "Joshua 5:3": "And Joshua made him sharp knives, and circumcised the children of Israel at the hill of the foreskins.",
    "Joshua 5:4": "And this is the cause why Joshua did circumcise: All the people that came out of Egypt, that were males, even all the men of war, died in the wilderness by the way, after they came out of Egypt.",
    "Joshua 5:5": "Now all the people that came out were circumcised: but all the people that were born in the wilderness by the way as they came forth out of Egypt, them they had not circumcised.",
    "Joshua 5:6": "For the children of Israel walked forty years in the wilderness, till all the people that were men of war, which came out of Egypt, were consumed, because they obeyed not the voice of the LORD: unto whom the LORD sware that he would not shew them the land, which the LORD sware unto their fathers that he would give us, a land that floweth with milk and honey.",
    "Joshua 5:7": "And their children, whom he raised up in their stead, them Joshua circumcised: for they were uncircumcised, because they had not circumcised them by the way.",
    "Joshua 5:8": "And it came to pass, when they had done circumcising all the people, that they abode in their places in the camp, till they were whole.",
    "Joshua 5:9": "And the LORD said unto Joshua, This day have I rolled away the reproach of Egypt from off you. Wherefore the name of the place is called Gilgal unto this day.",
    "Joshua 5:10": "And the children of Israel encamped in Gilgal, and kept the passover on the fourteenth day of the month at even in the plains of Jericho.",
    "Joshua 5:11": "And they did eat of the old corn of the land on the morrow after the passover, unleavened cakes, and parched corn in the selfsame day.",
    "Joshua 5:12": "And the manna ceased on the morrow after they had eaten of the old corn of the land; neither had the children of Israel manna any more; but they did eat of the fruit of the land of Canaan that year.",
    "Joshua 5:13": "And it came to pass, when Joshua was by Jericho, that he lifted up his eyes and looked, and, behold, there stood a man over against him with his sword drawn in his hand: and Joshua went unto him, and said unto him, Art thou for us, or for our adversaries?",
    "Joshua 5:14": "And he said, Nay; but as captain of the host of the LORD am I now come. And Joshua fell on his face to the earth, and did worship, and said unto him, What saith my lord unto his servant?",
    "Joshua 5:15": "And the captain of the LORD'S host said unto Joshua, Loose thy shoe from off thy foot; for the place whereon thou standest is holy. And Joshua did so.",
    
    // Joshua 6 (King James Version)
    "Joshua 6:1": "Now Jericho was straitly shut up because of the children of Israel: none went out, and none came in.",
    "Joshua 6:2": "And the LORD said unto Joshua, See, I have given into thine hand Jericho, and the king thereof, and the mighty men of valour.",
    "Joshua 6:3": "And ye shall compass the city, all ye men of war, and go round about the city once. Thus shalt thou do six days.",
    "Joshua 6:4": "And seven priests shall bear before the ark seven trumpets of rams' horns: and the seventh day ye shall compass the city seven times, and the priests shall blow with the trumpets.",
    "Joshua 6:5": "And it shall come to pass, that when they make a long blast with the rams' horn, and when ye hear the sound of the trumpet, all the people shall shout with a great shout; and the wall of the city shall fall down flat, and the people shall ascend up every man straight before him.",
    "Joshua 6:6": "And Joshua the son of Nun called the priests, and said unto them, Take up the ark of the covenant, and let seven priests bear seven trumpets of rams' horns before the ark of the LORD.",
    "Joshua 6:7": "And he said unto the people, Pass on, and compass the city, and let him that is armed pass on before the ark of the LORD.",
    "Joshua 6:8": "And it came to pass, when Joshua had spoken unto the people, that the seven priests bearing the seven trumpets of rams' horns passed on before the LORD, and blew with the trumpets: and the ark of the covenant of the LORD followed them.",
    "Joshua 6:9": "And the armed men went before the priests that blew with the trumpets, and the rereward came after the ark, the priests going on, and blowing with the trumpets.",
    "Joshua 6:10": "And Joshua had commanded the people, saying, Ye shall not shout, nor make any noise with your voice, neither shall any word proceed out of your mouth, until the day I bid you shout; then shall ye shout.",
    "Joshua 6:11": "So the ark of the LORD compassed the city, going about it once: and they came into the camp, and lodged in the camp.",
    "Joshua 6:12": "And Joshua rose early in the morning, and the priests took up the ark of the LORD.",
    "Joshua 6:13": "And seven priests bearing seven trumpets of rams' horns before the ark of the LORD went on continually, and blew with the trumpets: and the armed men went before them; but the rereward came after the ark of the LORD, the priests going on, and blowing with the trumpets.",
    "Joshua 6:14": "And the second day they compassed the city once, and returned into the camp: so they did six days.",
    "Joshua 6:15": "And it came to pass on the seventh day, that they rose early about the dawning of the day, and compassed the city after the same manner seven times: only on that day they compassed the city seven times.",
    "Joshua 6:16": "And it came to pass at the seventh time, when the priests blew with the trumpets, Joshua said unto the people, Shout; for the LORD hath given you the city.",
    "Joshua 6:17": "And the city shall be accursed, even it, and all that are therein, to the LORD: only Rahab the harlot shall live, she and all that are with her in the house, because she hid the messengers that we sent.",
    "Joshua 6:18": "And ye, in any wise keep yourselves from the accursed thing, lest ye make yourselves accursed, when ye take of the accursed thing, and make the camp of Israel a curse, and trouble it.",
    "Joshua 6:19": "But all the silver, and gold, and vessels of brass and iron, are consecrated unto the LORD: they shall come into the treasury of the LORD.",
    "Joshua 6:20": "So the people shouted when the priests blew with the trumpets: and it came to pass, when the people heard the sound of the trumpet, and the people shouted with a great shout, that the wall fell down flat, so that the people went up into the city, every man straight before him, and they took the city.",
    "Joshua 6:21": "And they utterly destroyed all that was in the city, both man and woman, young and old, and ox, and sheep, and ass, with the edge of the sword.",
    "Joshua 6:22": "But Joshua had said unto the two men that had spied out the country, Go into the harlot's house, and bring out thence the woman, and all that she hath, as ye sware unto her.",
    "Joshua 6:23": "And the young men that were spies went in, and brought out Rahab, and her father, and her mother, and her brethren, and all that she had; and they brought out all her kindred, and left them without the camp of Israel.",
    "Joshua 6:24": "And they burnt the city with fire, and all that was therein: only the silver, and the gold, and the vessels of brass and of iron, they put into the treasury of the house of the LORD.",
    "Joshua 6:25": "And Joshua saved Rahab the harlot alive, and her father's household, and all that she had; and she dwelleth in Israel even unto this day; because she hid the messengers, which Joshua sent to spy out Jericho.",
    "Joshua 6:26": "And Joshua adjured them at that time, saying, Cursed be the man before the LORD, that riseth up and buildeth this city Jericho: he shall lay the foundation thereof in his firstborn, and in his youngest son shall he set up the gates of it.",
    "Joshua 6:27": "So the LORD was with Joshua; and his fame was noised throughout all the country.",
    
    // Joshua 7 (King James Version)
    "Joshua 7:1": "But the children of Israel committed a trespass in the accursed thing: for Achan, the son of Carmi, the son of Zabdi, the son of Zerah, of the tribe of Judah, took of the accursed thing: and the anger of the LORD was kindled against the children of Israel.",
    "Joshua 7:2": "And Joshua sent men from Jericho to Ai, which is beside Beth-aven, on the east side of Bethel, and spake unto them, saying, Go up and view the country. And the men went up and viewed Ai.",
    "Joshua 7:3": "And they returned to Joshua, and said unto him, Let not all the people go up; but let about two or three thousand men go up and smite Ai; and make not all the people to labor thither; for they are but few.",
    "Joshua 7:4": "So there went up thither of the people about three thousand men: and they fled before the men of Ai.",
    "Joshua 7:5": "And the men of Ai smote of them about thirty and six men: for they chased them from before the gate even unto Shebarim, and smote them in the going down: wherefore the hearts of the people melted, and became as water.",
    "Joshua 7:6": "And Joshua rent his clothes, and fell to the earth upon his face before the ark of the LORD until the eventide, he and the elders of Israel, and put dust upon their heads.",
    "Joshua 7:7": "And Joshua said, Alas, O Lord GOD, wherefore hast thou at all brought this people over Jordan, to deliver us into the hand of the Amorites, to destroy us? would to God we had been content, and dwelt on the other side Jordan!",
    "Joshua 7:8": "O Lord, what shall I say, when Israel turneth their backs before their enemies!",
    "Joshua 7:9": "For the Canaanites and all the inhabitants of the land shall hear of it, and shall environ us round, and cut off our name from the earth: and what wilt thou do unto thy great name?",
    "Joshua 7:10": "And the LORD said unto Joshua, Get thee up; wherefore liest thou upon thy face?",
    "Joshua 7:11": "Israel hath sinned, and they have also transgressed my covenant which I commanded them: for they have even taken of the accursed thing, and have also stolen, and dissembled also, and they have put it even among their own stuff.",
    "Joshua 7:12": "Therefore the children of Israel could not stand before their enemies, but turned their backs before their enemies, because they were accursed: neither will I be with you any more, except ye destroy the accursed from among you.",
    "Joshua 7:13": "Up, sanctify the people, and say, Sanctify yourselves against to morrow: for thus saith the LORD God of Israel, There is an accursed thing in the midst of thee, O Israel: thou canst not stand before thine enemies, until ye take away the accursed thing from among you.",
    "Joshua 7:14": "In the morning therefore ye shall be brought according to your tribes: and it shall be, that the tribe which the LORD taketh shall come according to the families thereof; and the family which the LORD shall take shall come by households; and the household which the LORD shall take shall come man by man.",
    "Joshua 7:15": "And it shall be, that he that is taken with the accursed thing shall be burnt with fire, he and all that he hath; because he hath transgressed the covenant of the LORD, and because he hath wrought folly in Israel.",
    "Joshua 7:16": "So Joshua rose up early in the morning, and brought Israel by their tribes; and the tribe of Judah was taken.",
    "Joshua 7:17": "And he brought the family of Judah; and he took the family of the Zarhites: and he brought the family of the Zarhites man by man; and Zabdi was taken.",
    "Joshua 7:18": "And he brought his household man by man; and Achan, the son of Carmi, the son of Zabdi, the son of Zerah, of the tribe of Judah, was taken.",
    "Joshua 7:19": "And Joshua said unto Achan, My son, give, I pray thee, glory to the LORD God of Israel, and make confession unto him; and tell me now what thou hast done; hide it not from me.",
    "Joshua 7:20": "And Achan answered Joshua, and said, Indeed I have sinned against the LORD God of Israel, and thus and thus have I done:",
    "Joshua 7:21": "When I saw among the spoils a goodly Babylonish garment, and two hundred shekels of silver, and a wedge of gold of fifty shekels weight, then I coveted them, and took them; and, behold, they are hid in the earth in the midst of my tent, and the silver under it.",
    "Joshua 7:22": "So Joshua sent messengers, and they ran unto the tent; and, behold, it was hid in his tent, and the silver under it.",
    "Joshua 7:23": "And they took them out of the midst of the tent, and brought them unto Joshua, and unto all the children of Israel, and laid them out before the LORD.",
    "Joshua 7:24": "And Joshua, and all Israel with him, took Achan the son of Zerah, and the silver, and the garment, and the wedge of gold, and his sons, and his daughters, and his oxen, and his asses, and his sheep, and his tent, and all that he had: and they brought them unto the valley of Achor.",
    "Joshua 7:25": "And Joshua said, Why hast thou troubled us? the LORD shall trouble thee this day. And all Israel stoned him with stones, and burned them with fire, after they had stoned them with stones.",
    "Joshua 7:26": "And they raised over him a great heap of stones unto this day. So the LORD turned from the fierceness of his anger. Wherefore the name of that place was called, The valley of Achor, unto this day.",
    
    // Joshua 8 (King James Version)
    "Joshua 8:1": "And the LORD said unto Joshua, Fear not, neither be thou dismayed: take all the people of war with thee, and arise, go up to Ai: see, I have given into thy hand the king of Ai, and his people, and his city, and his land.",
    "Joshua 8:2": "And thou shalt do to Ai and her king as thou didst unto Jericho and her king: only the spoil thereof, and the cattle thereof, shall ye take for a prey unto yourselves: lay thee an ambush for the city behind it.",
    "Joshua 8:3": "So Joshua arose, and all the people of war, to go up against Ai: and Joshua chose out thirty thousand mighty men of valour, and sent them away by night.",
    "Joshua 8:4": "And he commanded them, saying, Behold, ye shall lie in wait against the city, even behind the city: go not very far from the city, but be ye all ready:",
    "Joshua 8:5": "And I, and all the people that are with me, will approach unto the city: and it shall come to pass, when they come out against us, as at the first, that we will flee before them.",
    "Joshua 8:6": "For they will come out after us, till we have drawn them from the city; for they will say, The men of Israel flee before us, as at the first: therefore we will flee before them.",
    "Joshua 8:7": "Then ye shall rise up from the ambush, and seize upon the city: for the LORD your God will deliver it into your hand.",
    "Joshua 8:8": "And it shall be, when ye have taken the city, that ye shall set the city on fire: according to the commandment of the LORD shall ye do. See, I have commanded you.",
    "Joshua 8:9": "Joshua therefore sent them forth: and they went to lie in ambush, and abode between Bethel and Ai, on the west side of Ai: but Joshua lodged that night among the people.",
    "Joshua 8:10": "And Joshua rose up early in the morning, and numbered the people, and went up, he and the elders of Israel, before the people to Ai.",
    "Joshua 8:11": "And all the people, even the people of war that were with him, went up, and drew nigh, and came before the city, and pitched on the north side of Ai: now there was a valley between them and Ai.",
    "Joshua 8:12": "And he took about five thousand men, and set them to lie in ambush between Bethel and Ai, on the west side of the city.",
    "Joshua 8:13": "And when they had set the people, even all the host that was on the north of the city, and their liers in wait on the west of the city, Joshua went that night into the midst of the valley.",
    "Joshua 8:14": "And it came to pass, when the king of Ai saw it, that they hasted and rose up early, and the men of the city went out against Israel to battle, he and all his people, at a time appointed, before the plain; but he wist not that there were liers in ambush against him behind the city.",
    "Joshua 8:15": "And Joshua and all Israel made as if they were beaten before them, and fled by the way of the wilderness.",
    "Joshua 8:16": "And all the people that were in Ai were called together to pursue after them: and they pursued after Joshua, and were drawn away from the city.",
    "Joshua 8:17": "And there was not a man left in Ai or Bethel, that went not out after Israel: and they left the city open, and pursued after Israel.",
    "Joshua 8:18": "And the LORD said unto Joshua, Stretch out the spear that is in thy hand toward Ai; for I will give it into thine hand. And Joshua stretched out the spear that he had in his hand toward the city.",
    "Joshua 8:19": "And the ambushers arose quickly out of their place, and they ran as soon as he had stretched out his hand: and they entered into the city, and took it, and hasted and set the city on fire.",
    "Joshua 8:20": "And when the men of Ai looked behind them, they saw, and, behold, the smoke of the city ascended up to heaven, and they had no power to flee this way or that way: and the people that fled to the wilderness turned back upon the pursuers.",
    "Joshua 8:21": "And when Joshua and all Israel saw that the ambush had taken the city, and that the smoke of the city ascended, then they turned again, and slew the men of Ai.",
    "Joshua 8:22": "And the other issued out of the city against them; so they were in the midst of Israel, some on this side, and some on that side: and they smote them, so that they let none of them remain or escape.",
    "Joshua 8:23": "And the king of Ai they took alive, and brought him to Joshua.",
    "Joshua 8:24": "And it came to pass, when Israel had made an end of slaying all the inhabitants of Ai in the field, in the wilderness wherein they chased them, and when they were all fallen on the edge of the sword, until they were consumed, that all the Israelites returned unto Ai, and smote it with the edge of the sword.",
    "Joshua 8:25": "And so it was, that all that fell that day, both of men and women, were twelve thousand, even all the men of Ai.",
    "Joshua 8:26": "For Joshua drew not his hand back, wherewith he stretched out the spear, until he had utterly destroyed all the inhabitants of Ai.",
    "Joshua 8:27": "Only the cattle and the spoil of that city Israel took for a prey unto themselves, according unto the word of the LORD which he commanded Joshua.",
    "Joshua 8:28": "And Joshua burnt Ai, and made it an heap for ever, even a desolation unto this day.",
    "Joshua 8:29": "And the king of Ai he hanged on a tree until eventide: and as soon as the sun was down, Joshua commanded that they should take his carcass down from the tree, and cast it at the entering of the gate of the city, and raise thereon a great heap of stones, that remaineth unto this day.",
    "Joshua 8:30": "Then Joshua built an altar unto the LORD God of Israel in mount Ebal,",
    "Joshua 8:31": "As Moses the servant of the LORD commanded the children of Israel, as it is written in the book of the law of Moses, an altar of whole stones, over which no man hath lift up any iron: and they offered thereon burnt offerings unto the LORD, and sacrificed peace offerings.",
    "Joshua 8:32": "And he wrote there upon the stones a copy of the law of Moses, which he wrote in the presence of the children of Israel.",
    "Joshua 8:33": "And all Israel, and their elders, and officers, and their judges, stood on this side the ark and on that side before the priests the Levites, which bare the ark of the covenant of the LORD, as well the stranger, as he that was born among them; half of them over against mount Gerizim, and half of them over against mount Ebal; as Moses the servant of the LORD had commanded before, that they should bless the people of Israel.",
    "Joshua 8:34": "And afterward he read all the words of the law, the blessings and cursings, according to all that is written in the book of the law.",
    "Joshua 8:35": "There was not a word of all that Moses commanded, which Joshua read not before all the congregation of Israel, with the women, and the little ones, and the strangers that were conversant among them.",
    
    // Joshua 9 (King James Version)
    "Joshua 9:1": "And it came to pass, when all the kings which were on this side Jordan, in the hills and in the valleys, and in all the coasts of the great sea over against Lebanon, the Hittite, and the Amorite, the Canaanite, the Perizzite, the Hivite, and the Jebusite, heard thereof;",
    "Joshua 9:2": "That they gathered themselves together, to fight with Joshua and with Israel, with one accord.",
    "Joshua 9:3": "And when the inhabitants of Gibeon heard what Joshua had done unto Jericho and to Ai,",
    "Joshua 9:4": "They did work wilily, and went and made as if they had been ambassadors, and took old sacks upon their asses, and wine bottles, old and rent, and bound up;",
    "Joshua 9:5": "And old shoes and clouted upon their feet, and old garments upon them; and all the bread of their provision was dry and mouldy.",
    "Joshua 9:6": "And they went to Joshua unto the camp at Gilgal, and said unto him, and to the men of Israel, We be come from a far country: now therefore make ye a league with us.",
    "Joshua 9:7": "And the men of Israel said unto the Hivites, Peradventure ye dwell among us; and how shall we make a league with you?",
    "Joshua 9:8": "And they said unto Joshua, We are thy servants. And Joshua said unto them, Who are ye? and from whence come ye?",
    "Joshua 9:9": "And they said unto him, From a very far country thy servants are come because of the name of the LORD thy God: for we have heard the fame of him, and all that he did in Egypt,",
    "Joshua 9:10": "And all that he did to the two kings of the Amorites, that were beyond Jordan, to Sihon king of Heshbon, and to Og king of Bashan, which was at Ashtaroth.",
    "Joshua 9:11": "Wherefore our elders and all the inhabitants of our country spake to us, saying, Take victuals with you for the journey, and go to meet them, and say unto them, We are your servants: therefore now make ye a league with us.",
    "Joshua 9:12": "This our bread we took hot for our provision out of our houses on the day we came forth to go unto you; but now, behold, it is dry, and it is mouldy:",
    "Joshua 9:13": "And these bottles of wine, which we filled, were new; and, behold, they be rent: and these our garments and our shoes are become old by reason of the very long journey.",
    "Joshua 9:14": "And the men took of their victuals, and asked not counsel at the mouth of the LORD.",
    "Joshua 9:15": "And Joshua made peace with them, and made a league with them, to let them live: and the princes of the congregation swear unto them.",
    "Joshua 9:16": "And it came to pass at the end of three days after they had made a league with them, that they heard that they were their neighbours, and that they dwelt among them.",
    "Joshua 9:17": "And the children of Israel journeyed, and came unto their cities on the third day. Now their cities were Gibeon, and Chephirah, and Beeroth, and Kirjath-jearim.",
    "Joshua 9:18": "And the children of Israel smote them not, because the princes of the congregation had sworn unto them by the LORD God of Israel. And all the congregation murmured against the princes.",
    "Joshua 9:19": "But all the princes said unto all the congregation, We have sworn unto them by the LORD God of Israel: now therefore we may not touch them.",
    "Joshua 9:20": "This we will do to them; we will even let them live, lest wrath be upon us, because of the oath which we sware unto them.",
    "Joshua 9:21": "And the princes said unto them, Let them live; but let them be hewers of wood and drawers of water unto all the congregation; as the princes had promised them.",
    "Joshua 9:22": "And Joshua called for them, and he spake unto them, saying, Wherefore have ye beguiled us, saying, We are very far from you; when ye dwell among us?",
    "Joshua 9:23": "Now therefore ye are cursed, and there shall none of you be freed from being bondmen, and hewers of wood and drawers of water for the house of my God.",
    "Joshua 9:24": "And they answered Joshua, and said, Because it was certainly told thy servants, how that the LORD thy God commanded his servant Moses to give you all the land, and to destroy all the inhabitants of the land from before you, therefore we were sore afraid of our lives because of you, and have done this thing.",
    "Joshua 9:25": "And now, behold, we are in thine hand: as it seemeth good and right unto thee to do unto us, do.",
    "Joshua 9:26": "And so did he unto them, and delivered them out of the hand of the children of Israel, that they slew them not.",
    "Joshua 9:27": "And Joshua made them that day hewers of wood and drawers of water for the congregation and for the altar of the LORD, even unto this day, in the place which he should choose.",
    
    // Joshua 10 (King James Version)
    "Joshua 10:1": "Now it came to pass, when Adoni-zedek king of Jerusalem had heard how Joshua had taken Ai, and had utterly destroyed it; as he had done to Jericho and her king, so he had done to Ai and her king; and how the inhabitants of Gibeon had made peace with Israel, and were among them;",
    "Joshua 10:2": "That they feared greatly, because Gibeon was a great city, as one of the royal cities, and because it was greater than Ai, and all the men thereof were mighty.",
    "Joshua 10:3": "Wherefore Adoni-zedek king of Jerusalem sent unto Hoham king of Hebron, and unto Piram king of Jarmuth, and unto Japhia king of Lachish, and unto Debir king of Eglon, saying,",
    "Joshua 10:4": "Come up unto me, and help me, that we may smite Gibeon: for it hath made peace with Joshua and with the children of Israel.",
    "Joshua 10:5": "Therefore the five kings of the Amorites, the king of Jerusalem, the king of Hebron, the king of Jarmuth, the king of Lachish, the king of Eglon, gathered themselves together, and went up, they and all their hosts, and encamped before Gibeon, and made war against it.",
    "Joshua 10:6": "And the men of Gibeon sent unto Joshua to the camp to Gilgal, saying, Slack not thy hand from thy servants; come up to us quickly, and save us, and help us: for all the kings of the Amorites that dwell in the mountains are gathered together against us.",
    "Joshua 10:7": "So Joshua ascended from Gilgal, he, and all the people of war with him, and all the mighty men of valour.",
    "Joshua 10:8": "And the LORD said unto Joshua, Fear them not: for I have delivered them into thine hand; there shall not a man of them stand before thee.",
    "Joshua 10:9": "Joshua therefore came unto them suddenly, and went up from Gilgal all night.",
    "Joshua 10:10": "And the LORD discomfited them before Israel, and slew them with a great slaughter at Gibeon, and chased them along the way that goeth up to Beth-horon, and smote them to Azekah, and unto Makkedah.",
    "Joshua 10:11": "And it came to pass, as they fled from before Israel, and were in the going down to Beth-horon, that the LORD cast down great stones from heaven upon them unto Azekah, and they died: they were more which died with hailstones than they whom the children of Israel slew with the sword.",
    "Joshua 10:12": "Then spake Joshua to the LORD in the day when the LORD delivered up the Amorites before the children of Israel, and he said in the sight of Israel, Sun, stand thou still upon Gibeon; and thou, Moon, in the valley of Ajalon.",
    "Joshua 10:13": "And the sun stood still, and the moon stayed, until the people had avenged themselves upon their enemies. Is not this written in the book of Jasher? So the sun stood still in the midst of heaven, and hasted not to go down about a whole day.",
    "Joshua 10:14": "And there was no day like that before it or after it, that the LORD hearkened unto the voice of a man: for the LORD fought for Israel.",
    "Joshua 10:15": "And Joshua returned, and all Israel with him, unto the camp to Gilgal.",
    "Joshua 10:16": "But these five kings fled, and hid themselves in a cave at Makkedah.",
    "Joshua 10:17": "And it was told Joshua, saying, The five kings are found hid in a cave at Makkedah.",
    "Joshua 10:18": "And Joshua said, Roll great stones upon the mouth of the cave, and set men by it for to keep them:",
    "Joshua 10:19": "And stay ye not, but pursue after your enemies, and smite the hindmost of them; suffer them not to enter into their cities: for the LORD your God hath delivered them into your hand.",
    "Joshua 10:20": "And it came to pass, when Joshua and the children of Israel had made an end of slaying them with a very great slaughter, till they were consumed, that the rest which remained of them entered into fenced cities.",
    "Joshua 10:21": "And all the people returned to the camp to Joshua at Makkedah in peace: none moved his tongue against any of the children of Israel.",
    "Joshua 10:22": "Then said Joshua, Open the mouth of the cave, and bring out those five kings unto me out of the cave.",
    "Joshua 10:23": "And they did so, and brought forth those five kings unto him out of the cave, the king of Jerusalem, the king of Hebron, the king of Jarmuth, the king of Lachish, and the king of Eglon.",
    "Joshua 10:24": "And it came to pass, when they brought out those kings unto Joshua, that Joshua called for all the men of Israel, and said unto the captains of the men of war which went with him, Come near, put your feet upon the necks of these kings. And they came near, and put their feet upon the necks of them.",
    "Joshua 10:25": "And Joshua said unto them, Fear not, nor be dismayed, be strong and of good courage: for thus shall the LORD do to all your enemies against whom ye fight.",
    "Joshua 10:26": "And afterward Joshua smote them, and slew them, and hanged them on five trees: and they were hanging upon the trees until the evening.",
    "Joshua 10:27": "And it came to pass at the time of the going down of the sun, that Joshua commanded, and they took them down off the trees, and cast them into the cave wherein they had been hid, and laid great stones in the cave's mouth, which remain until this very day.",
    "Joshua 10:28": "And that day Joshua took Makkedah, and smote it with the edge of the sword, and the king thereof he utterly destroyed, them, and all the souls that were therein; he let none remain: and he did to the king of Makkedah as he did unto the king of Jericho.",
    "Joshua 10:29": "Then Joshua passed from Makkedah, and all Israel with him, unto Libnah, and fought against Libnah:",
    "Joshua 10:30": "And the LORD delivered it also, and the king thereof, into the hand of Israel; and he smote it with the edge of the sword, and all the souls that were therein; he let none remain in it; but did unto the king thereof as he did unto the king of Jericho.",
    "Joshua 10:31": "And Joshua passed from Libnah, and all Israel with him, unto Lachish, and encamped against it, and fought against it:",
    "Joshua 10:32": "And the LORD delivered Lachish into the hand of Israel, which took it on the second day, and smote it with the edge of the sword, and all the souls that were therein, according to all that he had done to Libnah.",
    "Joshua 10:33": "Then Horam king of Gezer came up to help Lachish; and Joshua smote him and his people, until he had left him none remaining.",
    "Joshua 10:34": "And from Lachish Joshua passed unto Eglon, and all Israel with him; and they encamped against it, and fought against it:",
    "Joshua 10:35": "And they took it on that day, and smote it with the edge of the sword, and all the souls that were therein he utterly destroyed that day, according to all that he had done to Lachish.",
    "Joshua 10:36": "And Joshua went up from Eglon, and all Israel with him, unto Hebron; and they fought against it:",
    "Joshua 10:37": "And they took it, and smote it with the edge of the sword, and the king thereof, and all the cities thereof, and all the souls that were therein; he left none remaining, according to all that he had done to Eglon; but destroyed it utterly, and all the souls that were therein.",
    "Joshua 10:38": "And Joshua returned, and all Israel with him, to Debir; and fought against it:",
    "Joshua 10:39": "And he took it, and the king thereof, and all the cities thereof; and they smote them with the edge of the sword, and utterly destroyed all the souls that were therein; he left none remaining: as he had done to Hebron, so he did to Debir, and to the king thereof; as he had done also to Libnah, and to her king.",
    "Joshua 10:40": "So Joshua smote all the country of the hills, and of the south, and of the vale, and of the springs, and all their kings: he left none remaining, but utterly destroyed all that breathed, as the LORD God of Israel commanded.",
    "Joshua 10:41": "And Joshua smote them from Kadeshbarnea even unto Gaza, and all the country of Goshen, even unto Gibeon.",
    "Joshua 10:42": "And all these kings and their land did Joshua take at one time, because the LORD God of Israel fought for Israel.",
    "Joshua 10:43": "And Joshua returned, and all Israel with him, unto the camp to Gilgal.",
    
    // Joshua 11 (King James Version)
    "Joshua 11:1": "And it came to pass, when Jabin king of Hazor had heard those things, that he sent to Jobab king of Madon, and to the king of Shimron, and to the king of Achshaph,",
    "Joshua 11:2": "And to the kings that were on the north of the mountains, and of the plains south of Chinneroth, and in the valley, and in the borders of Dor on the west,",
    "Joshua 11:3": "And to the Canaanite on the east and on the west, and to the Amorite, and the Hittite, and the Perizzite, and the Jebusite in the mountains, and to the Hivite under Hermon in the land of Mizpeh.",
    "Joshua 11:4": "And they went out, they and all their hosts with them, much people, even as the sand that is upon the sea shore in multitude, with horses and chariots very many.",
    "Joshua 11:5": "And when all these kings were met together, they came and pitched together at the waters of Merom, to fight against Israel.",
    "Joshua 11:6": "And the LORD said unto Joshua, Be not afraid because of them: for to morrow about this time will I deliver them up all slain before Israel: thou shalt hough their horses, and burn their chariots with fire.",
    "Joshua 11:7": "So Joshua came, and all the people of war with him, against them by the waters of Merom suddenly; and they fell upon them.",
    "Joshua 11:8": "And the LORD delivered them into the hand of Israel, who smote them, and chased them unto great Zidon, and unto Misrephothmaim, and unto the valley of Mizpeh eastward; and they smote them, until they left them none remaining.",
    "Joshua 11:9": "And Joshua did unto them as the LORD bade him: he houghed their horses, and burnt their chariots with fire.",
    "Joshua 11:10": "And Joshua at that time turned back, and took Hazor, and smote the king thereof with the sword: for Hazor beforetime was the head of all those kingdoms.",
    "Joshua 11:11": "And they smote all the souls that were therein with the edge of the sword, utterly destroying them: there was not any left to breathe: and he burnt Hazor with fire.",
    "Joshua 11:12": "And all the cities of those kings, and all the kings of them, did Joshua take, and smote them with the edge of the sword, and he utterly destroyed them, as Moses the servant of the LORD commanded.",
    "Joshua 11:13": "But as for the cities that stood still in their strength, Israel burned none of them, save Hazor only; that did Joshua burn.",
    "Joshua 11:14": "And all the spoil of these cities, and the cattle, the children of Israel took for a prey unto themselves; but every man they smote with the edge of the sword, until they had destroyed them, neither left they any to breathe.",
    "Joshua 11:15": "As the LORD commanded Moses his servant, so did Moses command Joshua, and so did Joshua; he left nothing undone of all that the LORD commanded Moses.",
    "Joshua 11:16": "So Joshua took all that land, the hills, and all the south country, and all the land of Goshen, and the valley, and the plain, and the mountain of Israel, and the valley of the same;",
    "Joshua 11:17": "Even from the mount Halak, that goeth up to Seir, even unto Baalgad in the valley of Lebanon under mount Hermon: and all their kings he took, and smote them, and slew them.",
    "Joshua 11:18": "Joshua made war a long time with all those kings.",
    "Joshua 11:19": "There was not a city that made peace with the children of Israel, save the Hivites the inhabitants of Gibeon: all other they took in battle.",
    "Joshua 11:20": "For it was of the LORD to harden their hearts, that they should come against Israel in battle, that he might destroy them utterly, and that they might have no favour, but that he might destroy them, as the LORD commanded Moses.",
    "Joshua 11:21": "And at that time came Joshua, and cut off the Anakims from the mountains, from Hebron, from Debir, from Anab, and from all the mountains of Judah, and from all the mountains of Israel: Joshua destroyed them utterly with their cities.",
    "Joshua 11:22": "There was none of the Anakims left in the land of the children of Israel: only in Gaza, in Gath, and in Ashdod, there remained.",
    "Joshua 11:23": "So Joshua took the whole land, according to all that the LORD said unto Moses; and Joshua gave it for an inheritance unto Israel according to their divisions by their tribes. And the land rested from war.",
    
    // Joshua 12 (King James Version)
    "Joshua 12:1": "Now these are the kings of the land, which the children of Israel smote, and possessed their land on the other side Jordan toward the rising of the sun, from the river Arnon unto mount Hermon, and all the plain on the east:",
    "Joshua 12:2": "Sihon king of the Amorites, who dwelt in Heshbon, and ruled from Aroer, which is upon the bank of the river Arnon, and from the middle of the river, and from half Gilead, even unto the river Jabbok, which is the border of the children of Ammon;",
    "Joshua 12:3": "And from the plain to the sea of Chinneroth on the east, and unto the sea of the plain, even the salt sea on the east, the way to Bethjeshimoth; and from the south, under Ashdothpisgah:",
    "Joshua 12:4": "And the coast of Og king of Bashan, which was of the remnant of the giants, that dwelt at Ashtaroth and at Edrei,",
    "Joshua 12:5": "And reigned in mount Hermon, and in Salcah, and in all Bashan, unto the border of the Geshurites and the Maachathites, and half Gilead, the border of Sihon king of Heshbon.",
    "Joshua 12:6": "Them did Moses the servant of the LORD and the children of Israel smite: and Moses the servant of the LORD gave it for a possession unto the Reubenites, and the Gadites, and the half tribe of Manasseh.",
    "Joshua 12:7": "And these are the kings of the country which Joshua and the children of Israel smote on this side Jordan on the west, from Baalgad in the valley of Lebanon even unto the mount Halak, that goeth up to Seir; which Joshua gave unto the tribes of Israel for a possession according to their divisions;",
    "Joshua 12:8": "In the mountains, and in the valleys, and in the plains, and in the springs, and in the wilderness, and in the south country; the Hittites, the Amorites, and the Canaanites, the Perizzites, the Hivites, and the Jebusites:",
    "Joshua 12:9": "The king of Jericho, one; the king of Ai, which is beside Bethel, one;",
    "Joshua 12:10": "The king of Jerusalem, one; the king of Hebron, one;",
    "Joshua 12:11": "The king of Jarmuth, one; the king of Lachish, one;",
    "Joshua 12:12": "The king of Eglon, one; the king of Gezer, one;",
    "Joshua 12:13": "The king of Debir, one; the king of Geder, one;",
    "Joshua 12:14": "The king of Hormah, one; the king of Arad, one;",
    "Joshua 12:15": "The king of Libnah, one; the king of Adullam, one;",
    "Joshua 12:16": "The king of Makkedah, one; the king of Bethel, one;",
    "Joshua 12:17": "The king of Tappuah, one; the king of Hepher, one;",
    "Joshua 12:18": "The king of Aphek, one; the king of Lasharon, one;",
    "Joshua 12:19": "The king of Madon, one; the king of Hazor, one;",
    "Joshua 12:20": "The king of Shimronmeron, one; the king of Achshaph, one;",
    "Joshua 12:21": "The king of Taanach, one; the king of Megiddo, one;",
    "Joshua 12:22": "The king of Kedesh, one; the king of Jokneam of Carmel, one;",
    "Joshua 12:23": "The king of Dor in the coast of Dor, one; the king of the nations of Gilgal, one;",
    "Joshua 12:24": "The king of Tirzah, one: all the kings thirty and one.",
    
    // Joshua 13 (King James Version)
    "Joshua 13:1": "Now Joshua was old and stricken in years; and the LORD said unto him, Thou art old and stricken in years, and there remaineth yet very much land to be possessed.",
    "Joshua 13:2": "This is the land that yet remaineth: all the borders of the Philistines, and all Geshuri,",
    "Joshua 13:3": "From Sihor, which is before Egypt, even unto the borders of Ekron northward, which is counted to the Canaanite: five lords of the Philistines; the Gazathites, and the Ashdothites, the Eshkalonites, the Gittites, and the Ekronites; also the Avites:",
    "Joshua 13:4": "From the south, all the land of the Canaanites, and Mearah that is beside the Sidonians, unto Aphek, to the borders of the Amorites:",
    "Joshua 13:5": "And the land of the Giblites, and all Lebanon, toward the sunrising, from Baal-gad under mount Hermon unto the entering into Hamath.",
    "Joshua 13:6": "All the inhabitants of the hill country from Lebanon unto Misrephoth-maim, and all the Sidonians, them will I drive out from before the children of Israel: only divide thou it by lot unto the Israelites for an inheritance, as I have commanded thee.",
    "Joshua 13:7": "Now therefore divide this land for an inheritance unto the nine tribes, and the half tribe of Manasseh,",
    "Joshua 13:8": "With whom the Reubenites and the Gadites have received their inheritance, which Moses gave them, beyond Jordan eastward, even as Moses the servant of the LORD gave them;",
    "Joshua 13:9": "From Aroer, that is upon the bank of the river Arnon, and the city that is in the midst of the river, and all the plain of Medeba unto Dibon;",
    "Joshua 13:10": "And all the cities of Sihon king of the Amorites, which reigned in Heshbon, unto the border of the children of Ammon;",
    "Joshua 13:11": "And Gilead, and the border of the Geshurites and Maachathites, and all mount Hermon, and all Bashan unto Salcah;",
    "Joshua 13:12": "All the kingdom of Og in Bashan, which reigned in Ashtaroth and in Edrei, who remained of the remnant of the giants: for these did Moses smite, and cast them out.",
    "Joshua 13:13": "Nevertheless the children of Israel expelled not the Geshurites, nor the Maachathites: but the Geshurites and the Maachathites dwell among the Israelites until this day.",
    "Joshua 13:14": "Only unto the tribe of Levi he gave none inheritance; the sacrifices of the LORD God of Israel made by fire are their inheritance, as he said unto them.",
    "Joshua 13:15": "And Moses gave unto the tribe of the children of Reuben inheritance according to their families.",
    "Joshua 13:16": "And their coast was from Aroer, that is on the bank of the river Arnon, and the city that is in the midst of the river, and all the plain by Medeba;",
    "Joshua 13:17": "Heshbon, and all her cities that are in the plain; Dibon, and Bamoth-baal, and Beth-baalmeon,",
    "Joshua 13:18": "And Jahaza, and Kedemoth, and Mephaath,",
    "Joshua 13:19": "And Kirjathaim, and Sibmah, and Zareth-shahar in the mount of the valley,",
    "Joshua 13:20": "And Beth-peor, and Ashdoth-pisgah, and Beth-jeshimoth,",
    "Joshua 13:21": "And all the cities of the plain, and all the kingdom of Sihon king of the Amorites, which reigned in Heshbon, whom Moses smote with the princes of Midian, Evi, and Rekem, and Zur, and Hur, and Reba, which were dukes of Sihon, dwelling in the country.",
    "Joshua 13:22": "Balaam also the son of Beor, the soothsayer, did the children of Israel slay with the sword among them that were slain by them.",
    "Joshua 13:23": "And the border of the children of Reuben was Jordan, and the border thereof. This was the inheritance of the children of Reuben after their families, the cities and the villages thereof.",
    "Joshua 13:24": "And Moses gave inheritance unto the tribe of Gad, even unto the children of Gad according to their families.",
    "Joshua 13:25": "And their coast was Jazer, and all the cities of Gilead, and half the land of the children of Ammon, unto Aroer that is before Rabbah;",
    "Joshua 13:26": "And from Heshbon unto Ramath-mizpeh, and Betonim; and from Mahanaim unto the border of Debir;",
    "Joshua 13:27": "And in the valley, Beth-aram, and Beth-nimrah, and Succoth, and Zaphon, the rest of the kingdom of Sihon king of Heshbon, Jordan and his border, even unto the edge of the sea of Chinnereth on the other side Jordan eastward.",
    "Joshua 13:28": "This is the inheritance of the children of Gad after their families, the cities, and their villages.",
    "Joshua 13:29": "And Moses gave inheritance unto the half tribe of Manasseh: and this was the possession of the half tribe of the children of Manasseh by their families.",
    "Joshua 13:30": "And their coast was from Mahanaim, all Bashan, all the kingdom of Og king of Bashan, and all the towns of Jair, which are in Bashan, threescore cities:",
    "Joshua 13:31": "And half Gilead, and Ashtaroth, and Edrei, cities of the kingdom of Og in Bashan, were pertaining unto the children of Machir the son of Manasseh, even to the one half of the children of Machir by their families.",
    "Joshua 13:32": "These are the countries which Moses did distribute for inheritance in the plains of Moab, on the other side Jordan, by Jericho, eastward.",
    "Joshua 13:33": "But unto the tribe of Levi Moses gave not any inheritance: the LORD God of Israel was their inheritance, as he said unto them.",
    
    // Joshua 14 (King James Version)
    "Joshua 14:1": "And these are the countries which the children of Israel inherited in the land of Canaan, which Eleazar the priest, and Joshua the son of Nun, and the heads of the fathers of the tribes of the children of Israel, distributed for inheritance to them.",
    "Joshua 14:2": "By lot was their inheritance, as the LORD commanded by the hand of Moses, for the nine tribes, and for the half tribe.",
    "Joshua 14:3": "For Moses had given the inheritance of two tribes and an half tribe on the other side Jordan: but unto the Levites he gave none inheritance among them.",
    "Joshua 14:4": "For the children of Joseph were two tribes, Manasseh and Ephraim: therefore they gave no part unto the Levites in the land, save cities to dwell in, with their suburbs for their cattle and for their substance.",
    "Joshua 14:5": "As the LORD commanded Moses, so the children of Israel did, and they divided the land.",
    "Joshua 14:6": "Then the children of Judah came unto Joshua in Gilgal: and Caleb the son of Jephunneh the Kenezite said unto him, Thou knowest the thing that the LORD said unto Moses the man of God concerning me and thee in Kadesh-barnea.",
    "Joshua 14:7": "Forty years old was I when Moses the servant of the LORD sent me from Kadesh-barnea to espy out the land; and I brought him word again as it was in mine heart.",
    "Joshua 14:8": "Nevertheless my brethren that went up with me made the heart of the people melt: but I wholly followed the LORD my God.",
    "Joshua 14:9": "And Moses sware on that day, saying, Surely the land whereon thy feet have trodden shall be thine inheritance, and thy children's for ever, because thou hast wholly followed the LORD my God.",
    "Joshua 14:10": "And now, behold, the LORD hath kept me alive, as he said, these forty and five years, even since the LORD spake this word unto Moses, while the children of Israel wandered in the wilderness: and now, lo, I am this day fourscore and five years old.",
    "Joshua 14:11": "As yet I am as strong this day as I was in the day that Moses sent me: as my strength was then, even so is my strength now, for war, both to go out, and to come in.",
    "Joshua 14:12": "Now therefore give me this mountain, whereof the LORD spake in that day; for thou heardest in that day how the Anakims were there, and that the cities were great and fenced: if so be the LORD will be with me, then I shall be able to drive them out, as the LORD said.",
    "Joshua 14:13": "And Joshua blessed him, and gave unto Caleb the son of Jephunneh Hebron for an inheritance.",
    "Joshua 14:14": "Hebron therefore became the inheritance of Caleb the son of Jephunneh the Kenezite unto this day, because that he wholly followed the LORD God of Israel.",
    "Joshua 14:15": "And the name of Hebron before was Kirjath-arba; which Arba was a great man among the Anakims. And the land had rest from war.",
    
    // Joshua 15 (King James Version)
    "Joshua 15:1": "This then was the lot of the tribe of the children of Judah by their families; even to the border of Edom the wilderness of Zin southward was the uttermost part of the south coast.",
    "Joshua 15:2": "And their south border was from the shore of the salt sea, from the bay that looketh southward:",
    "Joshua 15:3": "And it went out to the south side to Maaleh-acrabbim, and passed along to Zin, and ascended up on the south side unto Kadesh-barnea, and passed along to Hezron, and went up to Adar, and fetched a compass to Karkaa:",
    "Joshua 15:4": "From thence it passed toward Azmon, and went out unto the river of Egypt; and the goings out of that coast were at the sea: this shall be your south coast.",
    "Joshua 15:5": "And the east border was the salt sea, even unto the end of Jordan. And their border in the north quarter was from the bay of the sea at the uttermost part of Jordan:",
    "Joshua 15:6": "And the border went up to Beth-hogla, and passed along by the north of Beth-arabah; and the border went up to the stone of Bohan the son of Reuben:",
    "Joshua 15:7": "And the border went up toward Debir from the valley of Achor, and so northward, looking toward Gilgal, that is before the going up to Adummim, which is on the south side of the river: and the border passed toward the waters of En-shemesh, and the goings out thereof were at En-rogel:",
    "Joshua 15:8": "And the border went up by the valley of the son of Hinnom unto the south side of the Jebusite; the same is Jerusalem: and the border went up to the top of the mountain that lieth before the valley of Hinnom westward, which is at the end of the valley of the giants northward:",
    "Joshua 15:9": "And the border was drawn from the top of the hill unto the fountain of the water of Nephtoah, and went out to the cities of mount Ephron; and the border was drawn to Baalah, which is Kirjath-jearim:",
    "Joshua 15:10": "And the border compassed from Baalah westward unto mount Seir, and passed along unto the side of mount Jearim, which is Chesalon, on the north side, and went down to Beth-shemesh, and passed on to Timnah:",
    "Joshua 15:11": "And the border went out unto the side of Ekron northward: and the border was drawn to Shicron, and passed along to mount Baalah, and went out unto Jabneel; and the goings out of the border were at the sea.",
    "Joshua 15:12": "And the west border was to the great sea, and the coast thereof. This is the coast of the children of Judah round about according to their families.",
    "Joshua 15:13": "And unto Caleb the son of Jephunneh he gave a part among the children of Judah, according to the commandment of the LORD to Joshua, even the city of Arba the father of Anak, which city is Hebron.",
    "Joshua 15:14": "And Caleb drove thence the three sons of Anak, Sheshai, and Ahiman, and Talmai, the children of Anak.",
    "Joshua 15:15": "And he went up thence to the inhabitants of Debir: and the name of Debir before was Kirjath-sepher.",
    "Joshua 15:16": "And Caleb said, He that smiteth Kirjath-sepher, and taketh it, to him will I give Achsah my daughter to wife.",
    "Joshua 15:17": "And Othniel the son of Kenaz, the brother of Caleb, took it: and he gave him Achsah his daughter to wife.",
    "Joshua 15:18": "And it came to pass, as she came unto him, that she moved him to ask of her father a field: and she lighted off her ass; and Caleb said unto her, What wouldest thou?",
    "Joshua 15:19": "Who answered, Give me a blessing; for thou hast given me a south land; give me also springs of water. And he gave her the upper springs, and the nether springs.",
    "Joshua 15:20": "This is the inheritance of the tribe of the children of Judah according to their families.",
    "Joshua 15:21": "And the uttermost cities of the tribe of the children of Judah toward the coast of Edom southward were Kabzeel, and Eder, and Jagur,",
    "Joshua 15:22": "And Kinah, and Dimonah, and Adadah,",
    "Joshua 15:23": "And Kedesh, and Hazor, and Ithnan,",
    "Joshua 15:24": "Ziph, and Telem, and Bealoth,",
    "Joshua 15:25": "And Hazor, Hadattah, and Kerioth, and Hezron, which is Hazor,",
    "Joshua 15:26": "Amam, and Shema, and Moladah,",
    "Joshua 15:27": "And Hazargaddah, and Heshmon, and Beth-palet,",
    "Joshua 15:28": "And Hazar-shual, and Beersheba, and Bizjothjah,",
    "Joshua 15:29": "Baalah, and Iim, and Azem,",
    "Joshua 15:30": "And Eltolad, and Chesil, and Hormah,",
    "Joshua 15:31": "And Ziklag, and Madmannah, and Sansannah,",
    "Joshua 15:32": "And Lebaoth, and Shilhim, and Ain, and Rimmon: all the cities are twenty and nine, with their villages:",
    "Joshua 15:33": "And in the valley, Eshtaol, and Zoreah, and Ashnah,",
    "Joshua 15:34": "And Zanoah, and En-gannim, Tappuah, and Enam,",
    "Joshua 15:35": "Jarmuth, and Adullam, Socoh, and Azekah,",
    "Joshua 15:36": "And Sharaim, and Adithaim, and Gederah, and Gederothaim; fourteen cities with their villages:",
    "Joshua 15:37": "Zenan, and Hadashah, and Migdal-gad,",
    "Joshua 15:38": "And Dilean, and Mizpeh, and Joktheel,",
    "Joshua 15:39": "Lachish, and Bozkath, and Eglon,",
    "Joshua 15:40": "And Cabbon, and Lahmam, and Kithlish,",
    "Joshua 15:41": "And Gederoth, Beth-dagon, and Naamah, and Makkedah; sixteen cities with their villages:",
    "Joshua 15:42": "Libnah, and Ether, and Ashan,",
    "Joshua 15:43": "And Jiphtah, and Ashnah, and Nezib,",
    "Joshua 15:44": "And Keilah, and Achzib, and Mareshah; nine cities with their villages:",
    "Joshua 15:45": "Ekron, with her towns and her villages:",
    "Joshua 15:46": "From Ekron even unto the sea, all that lay near Ashdod, with their villages:",
    "Joshua 15:47": "Ashdod with her towns and her villages, Gaza with her towns and her villages, unto the river of Egypt, and the great sea, and the border thereof:",
    "Joshua 15:48": "And in the mountains, Shamir, and Jattir, and Socoh,",
    "Joshua 15:49": "And Dannah, and Kirjath-sannah, which is Debir,",
    "Joshua 15:50": "And Anab, and Eshtemoh, and Anim,",
    "Joshua 15:51": "And Goshen, and Holon, and Giloh; eleven cities with their villages:",
    "Joshua 15:52": "Arab, and Dumah, and Eshean,",
    "Joshua 15:53": "And Janum, and Beth-tappuah, and Aphekah,",
    "Joshua 15:54": "And Humtah, and Kirjath-arba, which is Hebron, and Zior; nine cities with their villages:",
    "Joshua 15:55": "Maon, Carmel, and Ziph, and Juttah,",
    "Joshua 15:56": "And Jezreel, and Jokdeam, and Zanoah,",
    "Joshua 15:57": "Cain, Gibeah, and Timnah; ten cities with their villages:",
    "Joshua 15:58": "Halhul, Beth-zur, and Gedor,",
    "Joshua 15:59": "And Maarath, and Beth-anoth, and Eltekon; six cities with their villages:",
    "Joshua 15:60": "Kirjath-baal, which is Kirjath-jearim, and Rabbah; two cities with their villages.",
    "Joshua 15:61": "In the wilderness, Beth-arabah, Middin, and Secacah,",
    "Joshua 15:62": "And Nibshan, and the city of Salt, and En-gedi; six cities with their villages.",
    "Joshua 15:63": "As for the Jebusites the inhabitants of Jerusalem, the children of Judah could not drive them out: but the Jebusites dwell with the children of Judah at Jerusalem unto this day.",
    
    // Joshua 16 (King James Version)
    "Joshua 16:1": "And the lot of the children of Joseph fell from Jordan by Jericho, unto the water of Jericho on the east, to the wilderness that goeth up from Jericho throughout mount Bethel,",
    "Joshua 16:2": "And goeth out from Bethel to Luz, and passeth along unto the borders of Archi to Ataroth,",
    "Joshua 16:3": "And goeth down westward to the coast of Japhleti, unto the coast of Bethhoron the nether, and to Gezer: and the goings out thereof are at the sea.",
    "Joshua 16:4": "So the children of Joseph, Manasseh and Ephraim, took their inheritance.",
    "Joshua 16:5": "And the border of the children of Ephraim according to their families was thus: even the border of their inheritance on the east side was Atarothaddar, unto Bethhoron the upper;",
    "Joshua 16:6": "And the border went out toward the sea to Michmethah on the north side; and the border went about eastward unto Taanathshiloh, and passed by it on the east to Janohah;",
    "Joshua 16:7": "And it went down from Janohah to Ataroth, and to Naarath, and came to Jericho, and went out at Jordan.",
    "Joshua 16:8": "The border went out from Tappuah westward unto the river Kanah; and the goings out thereof were at the sea. This is the inheritance of the tribe of the children of Ephraim by their families.",
    "Joshua 16:9": "And the separate cities for the children of Ephraim were among the inheritance of the children of Manasseh, all the cities with their villages.",
    "Joshua 16:10": "And they drave not out the Canaanites that dwelt in Gezer: but the Canaanites dwell among the Ephraimites unto this day, and serve under tribute.",
    
    // Joshua 17 (King James Version)
    "Joshua 17:1": "There was also a lot for the tribe of Manasseh; for he was the firstborn of Joseph; to wit, for Machir the firstborn of Manasseh, the father of Gilead: because he was a man of war, therefore he had Gilead and Bashan.",
    "Joshua 17:2": "There was also a lot for the rest of the children of Manasseh by their families; for the children of Abiezer, and for the children of Helek, and for the children of Asriel, and for the children of Shechem, and for the children of Hepher, and for the children of Shemida: these were the male children of Manasseh the son of Joseph by their families.",
    "Joshua 17:3": "But Zelophehad, the son of Hepher, the son of Gilead, the son of Machir, the son of Manasseh, had no sons, but daughters: and these are the names of his daughters, Mahlah, and Noah, Hoglah, Milcah, and Tirzah.",
    "Joshua 17:4": "And they came near before Eleazar the priest, and before Joshua the son of Nun, and before the princes, saying, The LORD commanded Moses to give us an inheritance among our brethren. Therefore according to the commandment of the LORD he gave them an inheritance among the brethren of their father.",
    "Joshua 17:5": "And there fell ten portions to Manasseh, beside the land of Gilead and Bashan, which were on the other side Jordan;",
    "Joshua 17:6": "Because the daughters of Manasseh had an inheritance among his sons: and the rest of Manasseh's sons had the land of Gilead.",
    "Joshua 17:7": "And the coast of Manasseh was from Asher to Michmethah, that lieth before Shechem; and the border went along on the right hand unto the inhabitants of Entappuah.",
    "Joshua 17:8": "Now Manasseh had the land of Tappuah: but Tappuah on the border of Manasseh belonged to the children of Ephraim;",
    "Joshua 17:9": "And the coast descended unto the river Kanah, southward of the river: these cities of Ephraim are among the cities of Manasseh: the coast of Manasseh also was on the north side of the river, and the outgoings of it were at the sea:",
    "Joshua 17:10": "Southward it was Ephraim's, and northward it was Manasseh's, and the sea is his border; and they met together in Asher on the north, and in Issachar on the east.",
    "Joshua 17:11": "And Manasseh had in Issachar and in Asher Bethshean and her towns, and Ibleam and her towns, and the inhabitants of Dor and her towns, and the inhabitants of Endor and her towns, and the inhabitants of Taanach and her towns, and the inhabitants of Megiddo and her towns, even three countries.",
    "Joshua 17:12": "Yet the children of Manasseh could not drive out the inhabitants of those cities; but the Canaanites would dwell in that land.",
    "Joshua 17:13": "Yet it came to pass, when the children of Israel were waxen strong, that they put the Canaanites to tribute; but did not utterly drive them out.",
    "Joshua 17:14": "And the children of Joseph spake unto Joshua, saying, Why hast thou given me but one lot and one portion to inherit, seeing I am a great people, forasmuch as the LORD hath blessed me hitherto?",
    "Joshua 17:15": "And Joshua answered them, If thou be a great people, then get thee up to the wood country, and cut down for thyself there in the land of the Perizzites and of the giants, if mount Ephraim be too narrow for thee.",
    "Joshua 17:16": "And the children of Joseph said, The hill is not enough for us: and all the Canaanites that dwell in the land of the valley have chariots of iron, both they who are of Bethshean and her towns, and they who are of the valley of Jezreel.",
    "Joshua 17:17": "And Joshua spake unto the house of Joseph, even to Ephraim and to Manasseh, saying, Thou art a great people, and hast great power: thou shalt not have one lot only:",
    "Joshua 17:18": "But the mountain shall be thine; for it is a wood, and thou shalt cut it down: and the outgoings of it shall be thine: for thou shalt drive out the Canaanites, though they have iron chariots, and though they be strong.",
    
};