const bibleVerses19 = {
    // Psalm 1 (King James Version)
    "Psalm 1:1": "Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners, nor sitteth in the seat of the scornful.",
    "Psalm 1:2": "But his delight is in the law of the LORD; and in his law doth he meditate day and night.",
    "Psalm 1:3": "And he shall be like a tree planted by the rivers of water, that bringeth forth his fruit in his season; his leaf also shall not wither; and whatsoever he doeth shall prosper.",
    "Psalm 1:4": "The ungodly are not so: but are like the chaff which the wind driveth away.",
    "Psalm 1:5": "Therefore the ungodly shall not stand in the judgment, nor sinners in the congregation of the righteous.",
    "Psalm 1:6": "For the LORD knoweth the way of the righteous: but the way of the ungodly shall perish.",
    
    // Psalm 2 (King James Version)
    "Psalm 2:1": "Why do the heathen rage, and the people imagine a vain thing?",
    "Psalm 2:2": "The kings of the earth set themselves, and the rulers take counsel together, against the LORD, and against his anointed, saying,",
    "Psalm 2:3": "Let us break their bands asunder, and cast away their cords from us.",
    "Psalm 2:4": "He that sitteth in the heavens shall laugh: the LORD shall have them in derision.",
    "Psalm 2:5": "Then shall he speak unto them in his wrath, and vex them in his sore displeasure.",
    "Psalm 2:6": "Yet have I set my king upon my holy hill of Zion.",
    "Psalm 2:7": "I will declare the decree: the LORD hath said unto me, Thou art my Son; this day have I begotten thee.",
    "Psalm 2:8": "Ask of me, and I shall give thee the heathen for thine inheritance, and the uttermost parts of the earth for thy possession.",
    "Psalm 2:9": "Thou shalt break them with a rod of iron; thou shalt dash them in pieces like a potter's vessel.",
    "Psalm 2:10": "Be wise now therefore, O ye kings: be instructed, ye judges of the earth.",
    "Psalm 2:11": "Serve the LORD with fear, and rejoice with trembling.",
    "Psalm 2:12": "Kiss the Son, lest he be angry, and ye perish from the way, when his wrath is kindled but a little. Blessed are all they that put their trust in him.",
    
    // Psalm 3 (King James Version)
    "Psalm 3:1": "LORD, how are they increased that trouble me! many are they that rise up against me.",
    "Psalm 3:2": "Many there be which say of my soul, There is no help for him in God. Selah.",
    "Psalm 3:3": "But thou, O LORD, art a shield for me; my glory, and the lifter up of mine head.",
    "Psalm 3:4": "I cried unto the LORD with my voice, and he heard me out of his holy hill. Selah.",
    "Psalm 3:5": "I laid me down and slept; I awaked; for the LORD sustained me.",
    "Psalm 3:6": "I will not be afraid of ten thousands of people, that have set themselves against me round about.",
    "Psalm 3:7": "Arise, O LORD; save me, O my God: for thou hast smitten all mine enemies upon the cheek bone; thou hast broken the teeth of the ungodly.",
    "Psalm 3:8": "Salvation belongeth unto the LORD: thy blessing is upon thy people. Selah.",
    
    // Psalm 4 (King James Version)
    "Psalm 4:1": "Hear me when I call, O God of my righteousness: thou hast enlarged me when I was in distress; have mercy upon me, and hear my prayer.",
    "Psalm 4:2": "O ye sons of men, how long will ye turn my glory into shame? how long will ye love vanity, and seek after leasing? Selah.",
    "Psalm 4:3": "But know that the LORD hath set apart him that is godly for himself: the LORD will hear when I call unto him.",
    "Psalm 4:4": "Stand in awe, and sin not: commune with your own heart upon your bed, and be still. Selah.",
    "Psalm 4:5": "Offer the sacrifices of righteousness, and put your trust in the LORD.",
    "Psalm 4:6": "There be many that say, Who will shew us any good? LORD, lift thou up the light of thy countenance upon us.",
    "Psalm 4:7": "Thou hast put gladness in my heart, more than in the time that their corn and their wine increased.",
    "Psalm 4:8": "I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety.",
    
    // Psalm 5 (King James Version)
    "Psalm 5:1": "Give ear to my words, O LORD, consider my meditation.",
    "Psalm 5:2": "Hearken unto the voice of my cry, my King, and my God: for unto thee will I pray.",
    "Psalm 5:3": "My voice shalt thou hear in the morning, O LORD; in the morning will I direct my prayer unto thee, and will look up.",
    "Psalm 5:4": "For thou art not a God that hath pleasure in wickedness: neither shall evil dwell with thee.",
    "Psalm 5:5": "The foolish shall not stand in thy sight: thou hatest all workers of iniquity.",
    "Psalm 5:6": "Thou shalt destroy them that speak leasing: the LORD will abhor the bloody and deceitful man.",
    "Psalm 5:7": "But as for me, I will come into thy house in the multitude of thy mercy: and in thy fear will I worship toward thy holy temple.",
    "Psalm 5:8": "Lead me, O LORD, in thy righteousness because of mine enemies; make thy way straight before my face.",
    "Psalm 5:9": "For there is no faithfulness in their mouth; their inward part is very wickedness; their throat is an open sepulchre; they flatter with their tongue.",
    "Psalm 5:10": "Destroy thou them, O God; let them fall by their own counsels; cast them out in the multitude of their transgressions; for they have rebelled against thee.",
    "Psalm 5:11": "But let all those that put their trust in thee rejoice: let them ever shout for joy, because thou defendest them: let them also that love thy name be joyful in thee.",
    "Psalm 5:12": "For thou, LORD, wilt bless the righteous; with favour wilt thou compass him as with a shield.",
    
    // Psalm 6 (King James Version)
    "Psalm 6:1": "O LORD, rebuke me not in thine anger, neither chasten me in thy hot displeasure.",
    "Psalm 6:2": "Have mercy upon me, O LORD; for I am weak: O LORD, heal me; for my bones are vexed.",
    "Psalm 6:3": "My soul is also sore vexed: but thou, O LORD, how long?",
    "Psalm 6:4": "Return, O LORD, deliver my soul: O save me for thy mercies' sake.",
    "Psalm 6:5": "For in death there is no remembrance of thee: in the grave who shall give thee thanks?",
    "Psalm 6:6": "I am weary with my groaning; all the night make I my bed to swim; I water my couch with my tears.",
    "Psalm 6:7": "Mine eye is consumed because of grief; it waxeth old because of all mine enemies.",
    "Psalm 6:8": "Depart from me, all ye workers of iniquity; for the LORD hath heard the voice of my weeping.",
    "Psalm 6:9": "The LORD hath heard my supplication; the LORD will receive my prayer.",
    "Psalm 6:10": "Let all mine enemies be ashamed and sore vexed: let them return and be ashamed suddenly.",
    
    // Psalm 7 (King James Version)
    "Psalm 7:1": "O LORD my God, in thee do I put my trust: save me from all them that persecute me, and deliver me:",
    "Psalm 7:2": "Lest he tear my soul like a lion, rending it in pieces, while there is none to deliver.",
    "Psalm 7:3": "O LORD my God, if I have done this; if there be iniquity in my hands;",
    "Psalm 7:4": "If I have rewarded evil unto him that was at peace with me; (yea, I have delivered him that without cause is mine enemy:)",
    "Psalm 7:5": "Let the enemy persecute my soul, and take it; yea, let him tread down my life upon the earth, and lay mine honour in the dust. Selah.",
    "Psalm 7:6": "Arise, O LORD, in thine anger, lift up thyself because of the rage of mine enemies: and awake for me to the judgment that thou hast commanded.",
    "Psalm 7:7": "So shall the congregation of the people compass thee about: for their sakes therefore return thou on high.",
    "Psalm 7:8": "The LORD shall judge the people: judge me, O LORD, according to my righteousness, and according to mine integrity that is in me.",
    "Psalm 7:9": "O let the wickedness of the wicked come to an end; but establish the just: for the righteous God trieth the hearts and reins.",
    "Psalm 7:10": "My defence is of God, which saveth the upright in heart.",
    "Psalm 7:11": "God judgeth the righteous, and God is angry with the wicked every day.",
    "Psalm 7:12": "If he turn not, he will whet his sword; he hath bent his bow, and made it ready.",
    "Psalm 7:13": "He hath also prepared for him the instruments of death; he ordaineth his arrows against the persecutors.",
    "Psalm 7:14": "Behold, he travaileth with iniquity, and hath conceived mischief, and brought forth falsehood.",
    "Psalm 7:15": "He made a pit, and digged it, and is fallen into the ditch which he made.",
    "Psalm 7:16": "His mischief shall return upon his own head, and his violent dealing shall come down upon his own pate.",
    "Psalm 7:17": "I will praise the LORD according to his righteousness: and will sing praise to the name of the LORD most high.",
    
    // Psalm 8 (King James Version)
    "Psalm 8:1": "O LORD our Lord, how excellent is thy name in all the earth! who hast set thy glory above the heavens.",
    "Psalm 8:2": "Out of the mouth of babes and sucklings hast thou ordained strength because of thine enemies, that thou mightest still the enemy and the avenger.",
    "Psalm 8:3": "When I consider thy heavens, the work of thy fingers, the moon and the stars, which thou hast ordained;",
    "Psalm 8:4": "What is man, that thou art mindful of him? and the son of man, that thou visitest him?",
    "Psalm 8:5": "For thou hast made him a little lower than the angels, and hast crowned him with glory and honour.",
    "Psalm 8:6": "Thou madest him to have dominion over the works of thy hands; thou hast put all things under his feet:",
    "Psalm 8:7": "All sheep and oxen, yea, and the beasts of the field;",
    "Psalm 8:8": "The fowl of the air, and the fish of the sea, and whatsoever passeth through the paths of the seas.",
    "Psalm 8:9": "O LORD our Lord, how excellent is thy name in all the earth!",
    
    // Psalm 9 (King James Version)
    "Psalm 9:1": "I will praise thee, O LORD, with my whole heart; I will shew forth all thy marvellous works.",
    "Psalm 9:2": "I will be glad and rejoice in thee: I will sing praise to thy name, O thou most High.",
    "Psalm 9:3": "When mine enemies are turned back, they shall fall and perish at thy presence.",
    "Psalm 9:4": "For thou hast maintained my right and my cause; thou satest in the throne judging right.",
    "Psalm 9:5": "Thou hast rebuked the heathen, thou hast destroyed the wicked, thou hast put out their name for ever and ever.",
    "Psalm 9:6": "O thou enemy, destructions are come to a perpetual end: and thou hast destroyed cities; their memorial is perished with them.",
    "Psalm 9:7": "But the LORD shall endure for ever: he hath prepared his throne for judgment.",
    "Psalm 9:8": "And he shall judge the world in righteousness, he shall minister judgment to the people in uprightness.",
    "Psalm 9:9": "The LORD also will be a refuge for the oppressed, a refuge in times of trouble.",
    "Psalm 9:10": "And they that know thy name will put their trust in thee: for thou, LORD, hast not forsaken them that seek thee.",
    "Psalm 9:11": "Sing praises to the LORD, which dwelleth in Zion: declare among the people his doings.",
    "Psalm 9:12": "When he maketh inquisition for blood, he remembereth them: he forgetteth not the cry of the humble.",
    "Psalm 9:13": "Have mercy upon me, O LORD; consider my trouble which I suffer of them that hate me, thou that liftest me up from the gates of death:",
    "Psalm 9:14": "That I may shew forth all thy praise in the gates of the daughter of Zion: I will rejoice in thy salvation.",
    "Psalm 9:15": "The heathen are sunk down in the pit that they made: in the net which they hid is their own foot taken.",
    "Psalm 9:16": "The LORD is known by the judgment which he executeth: the wicked is snared in the work of his own hands. Higgaion. Selah.",
    "Psalm 9:17": "The wicked shall be turned into hell, and all the nations that forget God.",
    "Psalm 9:18": "For the needy shall not alway be forgotten: the expectation of the poor shall not perish for ever.",
    "Psalm 9:19": "Arise, O LORD; let not man prevail: let the heathen be judged in thy sight.",
    "Psalm 9:20": "Put them in fear, O LORD: that the nations may know themselves to be but men. Selah.",
    
    // Psalm 10 (King James Version)
    "Psalm 10:1": "Why standest thou afar off, O LORD? why hidest thou thyself in times of trouble?",
    "Psalm 10:2": "The wicked in his pride doth persecute the poor: let them be taken in the devices that they have imagined.",
    "Psalm 10:3": "For the wicked boasteth of his heart's desire, and blesseth the covetous, whom the LORD abhorreth.",
    "Psalm 10:4": "The wicked, through the pride of his countenance, will not seek after God: God is not in all his thoughts.",
    "Psalm 10:5": "His ways are always grievous; thy judgments are far above out of his sight: as for all his enemies, he puffeth at them.",
    "Psalm 10:6": "He hath said in his heart, I shall not be moved: for I shall never be in adversity.",
    "Psalm 10:7": "His mouth is full of cursing and deceit and fraud: under his tongue is mischief and vanity.",
    "Psalm 10:8": "He sitteth in the lurking places of the villages: in the secret places doth he murder the innocent: his eyes are privily set against the poor.",
    "Psalm 10:9": "He lieth in wait secretly as a lion in his den: he lieth in wait to catch the poor: he doth catch the poor, when he draweth him into his net.",
    "Psalm 10:10": "He croucheth, and humbleth himself, that the poor may fall by his strong ones.",
    "Psalm 10:11": "He hath said in his heart, God hath forgotten: he hideth his face; he will never see it.",
    "Psalm 10:12": "Arise, O LORD; O God, lift up thine hand: forget not the humble.",
    "Psalm 10:13": "Wherefore doth the wicked contemn God? he hath said in his heart, Thou wilt not require it.",
    "Psalm 10:14": "Thou hast seen it; for thou beholdest mischief and spite, to requite it with thy hand: the poor committeth himself unto thee; thou art the helper of the fatherless.",
    "Psalm 10:15": "Break thou the arm of the wicked and the evil man: seek out his wickedness till thou find none.",
    "Psalm 10:16": "The LORD is King for ever and ever: the heathen are perished out of his land.",
    "Psalm 10:17": "LORD, thou hast heard the desire of the humble: thou wilt prepare their heart, thou wilt cause thine ear to hear:",
    "Psalm 10:18": "To judge the fatherless and the oppressed, that the man of the earth may no more oppress.",
    
    // Psalm 11 (King James Version)
    "Psalm 11:1": "In the LORD put I my trust: how say ye to my soul, Flee as a bird to your mountain?",
    "Psalm 11:2": "For, lo, the wicked bend their bow, they make ready their arrow upon the string, that they may privily shoot at the upright in heart.",
    "Psalm 11:3": "If the foundations be destroyed, what can the righteous do?",
    "Psalm 11:4": "The LORD is in his holy temple, the LORD's throne is in heaven: his eyes behold, his eyelids try, the children of men.",
    "Psalm 11:5": "The LORD trieth the righteous: but the wicked and him that loveth violence his soul hateth.",
    "Psalm 11:6": "Upon the wicked he shall rain snares, fire and brimstone, and an horrible tempest: this shall be the portion of their cup.",
    "Psalm 11:7": "For the righteous LORD loveth righteousness; his countenance doth behold the upright.",
    
    // Psalm 12 (King James Version)
    "Psalm 12:1": "Help, LORD; for the godly man ceaseth; for the faithful fail from among the children of men.",
    "Psalm 12:2": "They speak vanity every one with his neighbour: with flattering lips and with a double heart do they speak.",
    "Psalm 12:3": "The LORD shall cut off all flattering lips, and the tongue that speaketh proud things:",
    "Psalm 12:4": "Who have said, With our tongue will we prevail; our lips are our own: who is lord over us?",
    "Psalm 12:5": "For the oppression of the poor, for the sighing of the needy, now will I arise, saith the LORD; I will set him in safety from him that puffeth at him.",
    "Psalm 12:6": "The words of the LORD are pure words: as silver tried in a furnace of earth, purified seven times.",
    "Psalm 12:7": "Thou shalt keep them, O LORD, thou shalt preserve them from this generation for ever.",
    "Psalm 12:8": "The wicked walk on every side, when the vilest men are exalted.",
    
    // Psalm 13 (King James Version)
    "Psalm 13:1": "How long wilt thou forget me, O LORD? for ever? how long wilt thou hide thy face from me?",
    "Psalm 13:2": "How long shall I take counsel in my soul, having sorrow in my heart daily? how long shall mine enemy be exalted over me?",
    "Psalm 13:3": "Consider and hear me, O LORD my God: lighten mine eyes, lest I sleep the sleep of death;",
    "Psalm 13:4": "Lest mine enemy say, I have prevailed against him; and those that trouble me rejoice when I am moved.",
    "Psalm 13:5": "But I have trusted in thy mercy; my heart shall rejoice in thy salvation.",
    "Psalm 13:6": "I will sing unto the LORD, because he hath dealt bountifully with me.",
    
    // Psalm 14 (King James Version)
    "Psalm 14:1": "The fool hath said in his heart, There is no God. They are corrupt, they have done abominable works, there is none that doeth good.",
    "Psalm 14:2": "The LORD looked down from heaven upon the children of men, to see if there were any that did understand, and seek God.",
    "Psalm 14:3": "They are all gone aside, they are all together become filthy: there is none that doeth good, no, not one.",
    "Psalm 14:4": "Have all the workers of iniquity no knowledge? who eat up my people as they eat bread, and call not upon the LORD.",
    "Psalm 14:5": "There were they in great fear: for God is in the generation of the righteous.",
    "Psalm 14:6": "Ye have shamed the counsel of the poor, because the LORD is his refuge.",
    "Psalm 14:7": "Oh that the salvation of Israel were come out of Zion! when the LORD bringeth back the captivity of his people, Jacob shall rejoice, and Israel shall be glad.",
    
    // Psalm 15 (King James Version)
    "Psalm 15:1": "LORD, who shall abide in thy tabernacle? who shall dwell in thy holy hill?",
    "Psalm 15:2": "He that walketh uprightly, and worketh righteousness, and speaketh the truth in his heart.",
    "Psalm 15:3": "He that backbiteth not with his tongue, nor doeth evil to his neighbour, nor taketh up a reproach against his neighbour.",
    "Psalm 15:4": "In whose eyes a vile person is contemned; but he honoureth them that fear the LORD. He that sweareth to his own hurt, and changeth not.",
    "Psalm 15:5": "He that putteth not out his money to usury, nor taketh reward against the innocent. He that doeth these things shall never be moved.",
    
    // Psalm 16 (King James Version)
    "Psalm 16:1": "Preserve me, O God: for in thee do I put my trust.",
    "Psalm 16:2": "O my soul, thou hast said unto the LORD, Thou art my Lord: my goodness extendeth not to thee;",
    "Psalm 16:3": "But to the saints that are in the earth, and to the excellent, in whom is all my delight.",
    "Psalm 16:4": "Their sorrows shall be multiplied that hasten after another god: their drink offerings of blood will I not offer, nor take up their names into my lips.",
    "Psalm 16:5": "The LORD is the portion of mine inheritance and of my cup: thou maintainest my lot.",
    "Psalm 16:6": "The lines are fallen unto me in pleasant places; yea, I have a goodly heritage.",
    "Psalm 16:7": "I will bless the LORD, who hath given me counsel: my reins also instruct me in the night seasons.",
    "Psalm 16:8": "I have set the LORD always before me: because he is at my right hand, I shall not be moved.",
    "Psalm 16:9": "Therefore my heart is glad, and my glory rejoiceth: my flesh also shall rest in hope.",
    "Psalm 16:10": "For thou wilt not leave my soul in hell; neither wilt thou suffer thine Holy One to see corruption.",
    "Psalm 16:11": "Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore.",
    
    // Psalm 17 (King James Version)
    "Psalm 17:1": "Hear the right, O LORD, attend unto my cry, give ear unto my prayer, that goeth not out of feigned lips.",
    "Psalm 17:2": "Let my sentence come forth from thy presence; let thine eyes behold the things that are equal.",
    "Psalm 17:3": "Thou hast proved mine heart; thou hast visited me in the night; thou hast tried me, and shalt find nothing: I am purposed that my mouth shall not transgress.",
    "Psalm 17:4": "Concerning the works of men, by the word of thy lips I have kept me from the paths of the destroyer.",
    "Psalm 17:5": "Hold up my goings in thy paths, that my footsteps slip not.",
    "Psalm 17:6": "I have called upon thee, for thou wilt hear me, O God: incline thine ear unto me, and hear my speech.",
    "Psalm 17:7": "Shew thy marvellous lovingkindness, O thou that savest by thy right hand them which put their trust in thee from those that rise up against them.",
    "Psalm 17:8": "Keep me as the apple of the eye; hide me under the shadow of thy wings,",
    "Psalm 17:9": "From the wicked that oppress me, from my deadly enemies, who compass me about.",
    "Psalm 17:10": "They are inclosed in their own fat: with their mouth they speak proudly.",
    "Psalm 17:11": "They have now compassed us in our steps: they have set their eyes bowing down to the earth;",
    "Psalm 17:12": "Like as a lion that is greedy of his prey, and as it were a young lion lurking in secret places.",
    "Psalm 17:13": "Arise, O LORD, disappoint him, cast him down: deliver my soul from the wicked, which is thy sword:",
    "Psalm 17:14": "From men which are thy hand, O LORD, from men of the world, which have their portion in this life, and whose belly thou fillest with thy hid treasure: they are full of children, and leave the rest of their substance to their babes.",
    "Psalm 17:15": "As for me, I will behold thy face in righteousness: I shall be satisfied, when I awake, with thy likeness.",
    
    // Psalm 18 (King James Version)
    "Psalm 18:1": "I will love thee, O LORD, my strength.",
    "Psalm 18:2": "The LORD is my rock, and my fortress, and my deliverer; my God, my strength, in whom I will trust; my buckler, and the horn of my salvation, and my high tower.",
    "Psalm 18:3": "I will call upon the LORD, who is worthy to be praised: so shall I be saved from mine enemies.",
    "Psalm 18:4": "The sorrows of death compassed me, and the floods of ungodly men made me afraid.",
    "Psalm 18:5": "The sorrows of hell compassed me about: the snares of death prevented me.",
    "Psalm 18:6": "In my distress I called upon the LORD, and cried unto my God: he heard my voice out of his temple, and my cry came before him, even into his ears.",
    "Psalm 18:7": "Then the earth shook and trembled; the foundations also of the hills moved and were shaken, because he was wroth.",
    "Psalm 18:8": "There went up a smoke out of his nostrils, and fire out of his mouth devoured: coals were kindled by it.",
    "Psalm 18:9": "He bowed the heavens also, and came down: and darkness was under his feet.",
    "Psalm 18:10": "And he rode upon a cherub, and did fly: yea, he did fly upon the wings of the wind.",
    "Psalm 18:11": "He made darkness his secret place; his pavilion round about him were dark waters and thick clouds of the skies.",
    "Psalm 18:12": "At the brightness that was before him his thick clouds passed, hail stones and coals of fire.",
    "Psalm 18:13": "The LORD also thundered in the heavens, and the Highest gave his voice; hail stones and coals of fire.",
    "Psalm 18:14": "Yea, he sent out his arrows, and scattered them; and he shot out lightnings, and discomfited them.",
    "Psalm 18:15": "Then the channels of waters were seen, and the foundations of the world were discovered at thy rebuke, O LORD, at the blast of the breath of thy nostrils.",
    "Psalm 18:16": "He sent from above, he took me, he drew me out of many waters.",
    "Psalm 18:17": "He delivered me from my strong enemy, and from them which hated me: for they were too strong for me.",
    "Psalm 18:18": "They prevented me in the day of my calamity: but the LORD was my stay.",
    "Psalm 18:19": "He brought me forth also into a large place; he delivered me, because he delighted in me.",
    "Psalm 18:20": "The LORD rewarded me according to my righteousness; according to the cleanness of my hands hath he recompensed me.",
    "Psalm 18:21": "For I have kept the ways of the LORD, and have not wickedly departed from my God.",
    "Psalm 18:22": "For all his judgments were before me, and I did not put away his statutes from me.",
    "Psalm 18:23": "I was also upright before him, and I kept myself from mine iniquity.",
    "Psalm 18:24": "Therefore hath the LORD recompensed me according to my righteousness, according to the cleanness of my hands in his eyesight.",
    "Psalm 18:25": "With the merciful thou wilt shew thyself merciful; with an upright man thou wilt shew thyself upright;",
    "Psalm 18:26": "With the pure thou wilt shew thyself pure; and with the froward thou wilt shew thyself froward.",
    "Psalm 18:27": "For thou wilt save the afflicted people; but wilt bring down high looks.",
    "Psalm 18:28": "For thou wilt light my candle: the LORD my God will enlighten my darkness.",
    "Psalm 18:29": "For by thee I have run through a troop; and by my God have I leaped over a wall.",
    "Psalm 18:30": "As for God, his way is perfect: the word of the LORD is tried: he is a buckler to all those that trust in him.",
    "Psalm 18:31": "For who is God save the LORD? or who is a rock save our God?",
    "Psalm 18:32": "It is God that girdeth me with strength, and maketh my way perfect.",
    "Psalm 18:33": "He maketh my feet like hinds' feet, and setteth me upon my high places.",
    "Psalm 18:34": "He teacheth my hands to war, so that a bow of steel is broken by mine arms.",
    "Psalm 18:35": "Thou hast also given me the shield of thy salvation: and thy right hand hath holden me up, and thy gentleness hath made me great.",
    "Psalm 18:36": "Thou hast enlarged my steps under me, that my feet did not slip.",
    "Psalm 18:37": "I have pursued mine enemies, and overtaken them: neither did I turn again till they were consumed.",
    "Psalm 18:38": "I have wounded them that they were not able to rise: they are fallen under my feet.",
    "Psalm 18:39": "For thou hast girded me with strength unto the battle: thou hast subdued under me those that rose up against me.",
    "Psalm 18:40": "Thou hast also given me the necks of mine enemies; that I might destroy them that hate me.",
    "Psalm 18:41": "They cried, but there was none to save them: even unto the LORD, but he answered them not.",
    "Psalm 18:42": "Then did I beat them small as the dust before the wind: I did cast them out as the dirt in the streets.",
    "Psalm 18:43": "Thou hast delivered me from the strivings of the people; and thou hast made me the head of the heathen: a people whom I have not known shall serve me.",
    "Psalm 18:44": "As soon as they hear of me, they shall obey me: the strangers shall submit themselves unto me.",
    "Psalm 18:45": "The strangers shall fade away, and be afraid out of their close places.",
    "Psalm 18:46": "The LORD liveth; and blessed be my rock; and let the God of my salvation be exalted.",
    "Psalm 18:47": "It is God that avengeth me, and subdueth the people under me.",
    "Psalm 18:48": "He delivereth me from mine enemies: yea, thou liftest me up above those that rise up against me: thou hast delivered me from the violent man.",
    "Psalm 18:49": "Therefore will I give thanks unto thee, O LORD, among the heathen, and sing praises unto thy name.",
    "Psalm 18:50": "Great deliverance giveth he to his king; and sheweth mercy to his anointed, to David, and to his seed for evermore.",
    
    // Psalm 19 (King James Version)
    "Psalm 19:1": "The heavens declare the glory of God; and the firmament sheweth his handywork.",
    "Psalm 19:2": "Day unto day uttereth speech, and night unto night sheweth knowledge.",
    "Psalm 19:3": "There is no speech nor language, where their voice is not heard.",
    "Psalm 19:4": "Their line is gone out through all the earth, and their words to the end of the world. In them hath he set a tabernacle for the sun,",
    "Psalm 19:5": "Which is as a bridegroom coming out of his chamber, and rejoiceth as a strong man to run a race.",
    "Psalm 19:6": "His going forth is from the end of the heaven, and his circuit unto the ends of it: and there is nothing hid from the heat thereof.",
    "Psalm 19:7": "The law of the LORD is perfect, converting the soul: the testimony of the LORD is sure, making wise the simple.",
    "Psalm 19:8": "The statutes of the LORD are right, rejoicing the heart: the commandment of the LORD is pure, enlightening the eyes.",
    "Psalm 19:9": "The fear of the LORD is clean, enduring for ever: the judgments of the LORD are true and righteous altogether.",
    "Psalm 19:10": "More to be desired are they than gold, yea, than much fine gold: sweeter also than honey and the honeycomb.",
    "Psalm 19:11": "Moreover by them is thy servant warned: and in keeping of them there is great reward.",
    "Psalm 19:12": "Who can understand his errors? cleanse thou me from secret faults.",
    "Psalm 19:13": "Keep back thy servant also from presumptuous sins; let them not have dominion over me: then shall I be upright, and I shall be innocent from the great transgression.",
    "Psalm 19:14": "Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O LORD, my strength, and my redeemer.",
    
    // Psalm 20 (King James Version)
    "Psalm 20:1": "The LORD hear thee in the day of trouble; the name of the God of Jacob defend thee;",
    "Psalm 20:2": "Send thee help from the sanctuary, and strengthen thee out of Zion;",
    "Psalm 20:3": "Remember all thy offerings, and accept thy burnt sacrifice; Selah.",
    "Psalm 20:4": "Grant thee according to thine own heart, and fulfil all thy counsel.",
    "Psalm 20:5": "We will rejoice in thy salvation, and in the name of our God we will set up our banners: the LORD fulfil all thy petitions.",
    "Psalm 20:6": "Now know I that the LORD saveth his anointed; he will hear him from his holy heaven with the saving strength of his right hand.",
    "Psalm 20:7": "Some trust in chariots, and some in horses: but we will remember the name of the LORD our God.",
    "Psalm 20:8": "They are brought down and fallen: but we are risen, and stand upright.",
    "Psalm 20:9": "Save, LORD: let the king hear us when we call.",
    
    // Psalm 21 (King James Version)
    "Psalm 21:1": "The king shall joy in thy strength, O LORD; and in thy salvation how greatly shall he rejoice!",
    "Psalm 21:2": "Thou hast given him his heart's desire, and hast not withholden the request of his lips. Selah.",
    "Psalm 21:3": "For thou preventest him with the blessings of goodness: thou settest a crown of pure gold on his head.",
    "Psalm 21:4": "He asked life of thee, and thou gavest it him, even length of days for ever and ever.",
    "Psalm 21:5": "His glory is great in thy salvation: honour and majesty hast thou laid upon him.",
    "Psalm 21:6": "For thou hast made him most blessed for ever: thou hast made him exceeding glad with thy countenance.",
    "Psalm 21:7": "For the king trusteth in the LORD, and through the mercy of the most High he shall not be moved.",
    "Psalm 21:8": "Thine hand shall find out all thine enemies: thy right hand shall find out those that hate thee.",
    "Psalm 21:9": "Thou shalt make them as a fiery oven in the time of thine anger: the LORD shall swallow them up in his wrath, and the fire shall devour them.",
    "Psalm 21:10": "Their fruit shalt thou destroy from the earth, and their seed from among the children of men.",
    "Psalm 21:11": "For they intended evil against thee: they imagined a mischievous device, which they are not able to perform.",
    "Psalm 21:12": "Therefore shalt thou make them turn their back, when thou shalt make ready thine arrows upon thy strings against the face of them.",
    "Psalm 21:13": "Be thou exalted, LORD, in thine own strength: so will we sing and praise thy power.",
    
    // Psalm 22 (King James Version)
    "Psalm 22:1": "My God, my God, why hast thou forsaken me? why art thou so far from helping me, and from the words of my roaring?",
    "Psalm 22:2": "O my God, I cry in the daytime, but thou hearest not; and in the night season, and am not silent.",
    "Psalm 22:3": "But thou art holy, O thou that inhabitest the praises of Israel.",
    "Psalm 22:4": "Our fathers trusted in thee: they trusted, and thou didst deliver them.",
    "Psalm 22:5": "They cried unto thee, and were delivered: they trusted in thee, and were not confounded.",
    "Psalm 22:6": "But I am a worm, and no man; a reproach of men, and despised of the people.",
    "Psalm 22:7": "All they that see me laugh me to scorn: they shoot out the lip, they shake the head, saying,",
    "Psalm 22:8": "He trusted on the LORD that he would deliver him: let him deliver him, seeing he delighted in him.",
    "Psalm 22:9": "But thou art he that took me out of the womb: thou didst make me hope when I was upon my mother's breasts.",
    "Psalm 22:10": "I was cast upon thee from the womb: thou art my God from my mother's belly.",
    "Psalm 22:11": "Be not far from me; for trouble is near; for there is none to help.",
    "Psalm 22:12": "Many bulls have compassed me: strong bulls of Bashan have beset me round.",
    "Psalm 22:13": "They gaped upon me with their mouths, as a ravening and a roaring lion.",
    "Psalm 22:14": "I am poured out like water, and all my bones are out of joint: my heart is like wax; it is melted in the midst of my bowels.",
    "Psalm 22:15": "My strength is dried up like a potsherd; and my tongue cleaveth to my jaws; and thou hast brought me into the dust of death.",
    "Psalm 22:16": "For dogs have compassed me: the assembly of the wicked have enclosed me: they pierced my hands and my feet.",
    "Psalm 22:17": "I may tell all my bones: they look and stare upon me.",
    "Psalm 22:18": "They part my garments among them, and cast lots upon my vesture.",
    "Psalm 22:19": "But be not thou far from me, O LORD: O my strength, haste thee to help me.",
    "Psalm 22:20": "Deliver my soul from the sword; my darling from the power of the dog.",
    "Psalm 22:21": "Save me from the lion's mouth: for thou hast heard me from the horns of the unicorns.",
    "Psalm 22:22": "I will declare thy name unto my brethren: in the midst of the congregation will I praise thee.",
    "Psalm 22:23": "Ye that fear the LORD, praise him; all ye the seed of Jacob, glorify him; and fear him, all ye the seed of Israel.",
    "Psalm 22:24": "For he hath not despised nor abhorred the affliction of the afflicted; neither hath he hid his face from him; but when he cried unto him, he heard.",
    "Psalm 22:25": "My praise shall be of thee in the great congregation: I will pay my vows before them that fear him.",
    "Psalm 22:26": "The meek shall eat and be satisfied: they shall praise the LORD that seek him: your heart shall live for ever.",
    "Psalm 22:27": "All the ends of the world shall remember and turn unto the LORD: and all the kindreds of the nations shall worship before thee.",
    "Psalm 22:28": "For the kingdom is the LORD's: and he is the governor among the nations.",
    "Psalm 22:29": "All they that be fat upon earth shall eat and worship: all they that go down to the dust shall bow before him: and none can keep alive his own soul.",
    "Psalm 22:30": "A seed shall serve him; it shall be accounted to the Lord for a generation.",
    "Psalm 22:31": "They shall come, and shall declare his righteousness unto a people that shall be born, that he hath done this.",
    
    // Psalm 23 (King James Version)
    "Psalm 23:1": "The LORD is my shepherd; I shall not want.",
    "Psalm 23:2": "He maketh me to lie down in green pastures: he leadeth me beside the still waters.",
    "Psalm 23:3": "He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake.",
    "Psalm 23:4": "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.",
    "Psalm 23:5": "Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over.",
    "Psalm 23:6": "Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the LORD for ever.",
    
    // Psalm 24 (King James Version)
    "Psalm 24:1": "The earth is the LORD's, and the fullness thereof; the world, and they that dwell therein.",
    "Psalm 24:2": "For he hath founded it upon the seas, and established it upon the floods.",
    "Psalm 24:3": "Who shall ascend into the hill of the LORD? or who shall stand in his holy place?",
    "Psalm 24:4": "He that hath clean hands, and a pure heart; who hath not lifted up his soul unto vanity, nor sworn deceitfully.",
    "Psalm 24:5": "He shall receive the blessing from the LORD, and righteousness from the God of his salvation.",
    "Psalm 24:6": "This is the generation of them that seek him, that seek thy face, O Jacob. Selah.",
    "Psalm 24:7": "Lift up your heads, O ye gates; and be ye lifted up, ye everlasting doors; and the King of glory shall come in.",
    "Psalm 24:8": "Who is this King of glory? The LORD strong and mighty, the LORD mighty in battle.",
    "Psalm 24:9": "Lift up your heads, O ye gates; even lift them up, ye everlasting doors; and the King of glory shall come in.",
    "Psalm 24:10": "Who is this King of glory? The LORD of hosts, he is the King of glory. Selah.",
    
    // Psalm 25 (King James Version)
    "Psalm 25:1": "Unto thee, O LORD, do I lift up my soul.",
    "Psalm 25:2": "O my God, I trust in thee: let me not be ashamed, let not mine enemies triumph over me.",
    "Psalm 25:3": "Yea, let none that wait on thee be ashamed: let them be ashamed which transgress without cause.",
    "Psalm 25:4": "Shew me thy ways, O LORD; teach me thy paths.",
    "Psalm 25:5": "Lead me in thy truth, and teach me: for thou art the God of my salvation; on thee do I wait all the day.",
    "Psalm 25:6": "Remember, O LORD, thy tender mercies and thy lovingkindnesses; for they have been ever of old.",
    "Psalm 25:7": "Remember not the sins of my youth, nor my transgressions: according to thy mercy remember thou me for thy goodness' sake, O LORD.",
    "Psalm 25:8": "Good and upright is the LORD: therefore will he teach sinners in the way.",
    "Psalm 25:9": "The meek will he guide in judgment: and the meek will he teach his way.",
    "Psalm 25:10": "All the paths of the LORD are mercy and truth unto such as keep his covenant and his testimonies.",
    "Psalm 25:11": "For thy name's sake, O LORD, pardon mine iniquity; for it is great.",
    "Psalm 25:12": "What man is he that feareth the LORD? him shall he teach in the way that he shall choose.",
    "Psalm 25:13": "His soul shall dwell at ease; and his seed shall inherit the earth.",
    "Psalm 25:14": "The secret of the LORD is with them that fear him; and he will shew them his covenant.",
    "Psalm 25:15": "Mine eyes are ever toward the LORD; for he shall pluck my feet out of the net.",
    "Psalm 25:16": "Turn thee unto me, and have mercy upon me; for I am desolate and afflicted.",
    "Psalm 25:17": "The troubles of my heart are enlarged: O bring thou me out of my distresses.",
    "Psalm 25:18": "Look upon mine affliction and my pain; and forgive all my sins.",
    "Psalm 25:19": "Consider mine enemies; for they are many; and they hate me with cruel hatred.",
    "Psalm 25:20": "O keep my soul, and deliver me: let me not be ashamed; for I put my trust in thee.",
    "Psalm 25:21": "Let integrity and uprightness preserve me; for I wait on thee.",
    "Psalm 25:22": "Redeem Israel, O God, out of all his troubles.",
    
    // Psalm 26 (King James Version)
    "Psalm 26:1": "Judge me, O LORD; for I have walked in mine integrity: I have trusted also in the LORD; therefore I shall not slide.",
    "Psalm 26:2": "Examine me, O LORD, and prove me; try my reins and my heart.",
    "Psalm 26:3": "For thy lovingkindness is before mine eyes: and I have walked in thy truth.",
    "Psalm 26:4": "I have not sat with vain persons, neither will I go in with dissemblers.",
    "Psalm 26:5": "I have hated the congregation of evil doers; and will not sit with the wicked.",
    "Psalm 26:6": "I will wash mine hands in innocency: so will I compass thine altar, O LORD:",
    "Psalm 26:7": "That I may publish with the voice of thanksgiving, and tell of all thy wondrous works.",
    "Psalm 26:8": "LORD, I have loved the habitation of thy house, and the place where thine honour dwelleth.",
    "Psalm 26:9": "Gather not my soul with sinners, nor my life with bloody men:",
    "Psalm 26:10": "In whose hands is mischief, and their right hand is full of bribes.",
    "Psalm 26:11": "But as for me, I will walk in mine integrity: redeem me, and be merciful unto me.",
    "Psalm 26:12": "My foot standeth in an even place: in the congregations will I bless the LORD.",
    
    // Psalm 27 (King James Version)
    "Psalm 27:1": "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?",
    "Psalm 27:2": "When the wicked, even mine enemies and my foes, came upon me to eat up my flesh, they stumbled and fell.",
    "Psalm 27:3": "Though an host should encamp against me, my heart shall not fear: though war should rise against me, in this will I be confident.",
    "Psalm 27:4": "One thing have I desired of the LORD, that will I seek after; that I may dwell in the house of the LORD all the days of my life, to behold the beauty of the LORD, and to inquire in his temple.",
    "Psalm 27:5": "For in the time of trouble he shall hide me in his pavilion: in the secret of his tabernacle shall he hide me; he shall set me up upon a rock.",
    "Psalm 27:6": "And now shall mine head be lifted up above mine enemies round about me: therefore will I offer in his tabernacle sacrifices of joy; I will sing, yea, I will sing praises unto the LORD.",
    "Psalm 27:7": "Hear, O LORD, when I cry with my voice: have mercy also upon me, and answer me.",
    "Psalm 27:8": "When thou saidst, Seek ye my face; my heart said unto thee, Thy face, LORD, will I seek.",
    "Psalm 27:9": "Hide not thy face far from me; put not thy servant away in anger: thou hast been my help; leave me not, neither forsake me, O God of my salvation.",
    "Psalm 27:10": "When my father and my mother forsake me, then the LORD will take me up.",
    "Psalm 27:11": "Teach me thy way, O LORD, and lead me in a plain path, because of mine enemies.",
    "Psalm 27:12": "Deliver me not over unto the will of mine enemies: for false witnesses are risen up against me, and such as breathe out cruelty.",
    "Psalm 27:13": "I had fainted, unless I had believed to see the goodness of the LORD in the land of the living.",
    "Psalm 27:14": "Wait on the LORD: be of good courage, and he shall strengthen thine heart: wait, I say, on the LORD.",
    
    // Psalm 28 (King James Version)
    "Psalm 28:1": "Unto thee will I cry, O LORD my rock; be not silent to me: lest, if thou be silent to me, I become like them that go down into the pit.",
    "Psalm 28:2": "Hear the voice of my supplications, when I cry unto thee, when I lift up my hands toward thy holy oracle.",
    "Psalm 28:3": "Draw me not away with the wicked, and with the workers of iniquity, which speak peace to their neighbors, but mischief is in their hearts.",
    "Psalm 28:4": "Give them according to their deeds, and according to the wickedness of their endeavors: give them after the work of their hands; render to them their desert.",
    "Psalm 28:5": "Because they regard not the works of the LORD, nor the operation of his hands, he shall destroy them, and not build them up.",
    "Psalm 28:6": "Blessed be the LORD, because he hath heard the voice of my supplications.",
    "Psalm 28:7": "The LORD is my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him.",
    "Psalm 28:8": "The LORD is their strength, and he is the saving strength of his anointed.",
    "Psalm 28:9": "Save thy people, and bless thine inheritance: feed them also, and lift them up for ever.",
    
    // Psalm 29 (King James Version)
    "Psalm 29:1": "Give unto the LORD, O ye mighty, give unto the LORD glory and strength.",
    "Psalm 29:2": "Give unto the LORD the glory due unto his name; worship the LORD in the beauty of holiness.",
    "Psalm 29:3": "The voice of the LORD is upon the waters: the God of glory thundereth: the LORD is upon many waters.",
    "Psalm 29:4": "The voice of the LORD is powerful; the voice of the LORD is full of majesty.",
    "Psalm 29:5": "The voice of the LORD breaketh the cedars; yea, the LORD breaketh the cedars of Lebanon.",
    "Psalm 29:6": "He maketh them also to skip like a calf; Lebanon and Sirion like a young unicorn.",
    "Psalm 29:7": "The voice of the LORD divideth the flames of fire.",
    "Psalm 29:8": "The voice of the LORD shaketh the wilderness; the LORD shaketh the wilderness of Kadesh.",
    "Psalm 29:9": "The voice of the LORD maketh the hinds to calve, and discovereth the forests: and in his temple doth every one speak of his glory.",
    "Psalm 29:10": "The LORD sitteth upon the flood; yea, the LORD sitteth King for ever.",
    "Psalm 29:11": "The LORD will give strength unto his people; the LORD will bless his people with peace.",
    
    // Psalm 30 (King James Version)
    "Psalm 30:1": "I will extol thee, O LORD; for thou hast lifted me up, and hast not made my foes to rejoice over me.",
    "Psalm 30:2": "O LORD my God, I cried unto thee, and thou hast healed me.",
    "Psalm 30:3": "O LORD, thou hast brought up my soul from the grave: thou hast kept me alive, that I should not go down to the pit.",
    "Psalm 30:4": "Sing unto the LORD, O ye saints of his, and give thanks at the remembrance of his holiness.",
    "Psalm 30:5": "For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning.",
    "Psalm 30:6": "And in my prosperity I said, I shall never be moved.",
    "Psalm 30:7": "LORD, by thy favour thou hast made my mountain to stand strong: thou didst hide thy face, and I was troubled.",
    "Psalm 30:8": "I cried to thee, O LORD; and unto the LORD I made supplication.",
    "Psalm 30:9": "What profit is there in my blood, when I go down to the pit? shall the dust praise thee? shall it declare thy truth?",
    "Psalm 30:10": "Hear, O LORD, and have mercy upon me: LORD, be thou my helper.",
    "Psalm 30:11": "Thou hast turned for me my mourning into dancing: thou hast put off my sackcloth, and girded me with gladness;",
    "Psalm 30:12": "To the end that my glory may sing praise to thee, and not be silent. O LORD my God, I will give thanks unto thee for ever.",
    
    // Psalm 31 (King James Version)
    "Psalm 31:1": "In thee, O LORD, do I put my trust; let me never be ashamed: deliver me in thy righteousness.",
    "Psalm 31:2": "Bow down thine ear to me; deliver me speedily: be thou my strong rock, for an house of defence to save me.",
    "Psalm 31:3": "For thou art my rock and my fortress; therefore for thy name's sake lead me, and guide me.",
    "Psalm 31:4": "Pull me out of the net that they have laid privily for me: for thou art my strength.",
    "Psalm 31:5": "Into thine hand I commit my spirit: thou hast redeemed me, O LORD God of truth.",
    "Psalm 31:6": "I have hated them that regard lying vanities: but I trust in the LORD.",
    "Psalm 31:7": "I will be glad and rejoice in thy mercy: for thou hast considered my trouble; thou hast known my soul in adversities;",
    "Psalm 31:8": "And hast not shut me up into the hand of the enemy: thou hast set my feet in a large room.",
    "Psalm 31:9": "Have mercy upon me, O LORD, for I am in trouble: mine eye is consumed with grief, yea, my soul and my belly.",
    "Psalm 31:10": "For my life is spent with grief, and my years with sighing: my strength faileth because of mine iniquity, and my bones are consumed.",
    "Psalm 31:11": "I was a reproach among all mine enemies, but especially among my neighbours, and a fear to mine acquaintance: they that did see me without fled from me.",
    "Psalm 31:12": "I am forgotten as a dead man out of mind: I am like a broken vessel.",
    "Psalm 31:13": "For I have heard the slander of many: fear was on every side: while they took counsel together against me, they devised to take away my life.",
    "Psalm 31:14": "But I trusted in thee, O LORD: I said, Thou art my God.",
    "Psalm 31:15": "My times are in thy hand: deliver me from the hand of mine enemies, and from them that persecute me.",
    "Psalm 31:16": "Make thy face to shine upon thy servant: save me for thy mercies' sake.",
    "Psalm 31:17": "Let me not be ashamed, O LORD; for I have called upon thee: let the wicked be ashamed, and let them be silent in the grave.",
    "Psalm 31:18": "Let the lying lips be put to silence; which speak grievous things proudly and contemptuously against the righteous.",
    "Psalm 31:19": "Oh how great is thy goodness, which thou hast laid up for them that fear thee; which thou hast wrought for them that trust in thee before the sons of men!",
    "Psalm 31:20": "Thou shalt hide them in the secret of thy presence from the pride of man: thou shalt keep them secretly in a pavilion from the strife of tongues.",
    "Psalm 31:21": "Blessed be the LORD: for he hath shewed me his marvellous kindness in a strong city.",
    "Psalm 31:22": "For I said in my haste, I am cut off from before thine eyes: nevertheless thou heardest the voice of my supplications when I cried unto thee.",
    "Psalm 31:23": "O love the LORD, all ye his saints: for the LORD preserveth the faithful, and plentifully rewardeth the proud doer.",
    "Psalm 31:24": "Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD.",
    
    // Psalm 32 (King James Version)
    "Psalm 32:1": "Blessed is he whose transgression is forgiven, whose sin is covered.",
    "Psalm 32:2": "Blessed is the man unto whom the LORD imputeth not iniquity, and in whose spirit there is no guile.",
    "Psalm 32:3": "When I kept silence, my bones waxed old through my roaring all the day long.",
    "Psalm 32:4": "For day and night thy hand was heavy upon me: my moisture is turned into the drought of summer. Selah.",
    "Psalm 32:5": "I acknowledged my sin unto thee, and mine iniquity have I not hid. I said, I will confess my transgressions unto the LORD; and thou forgavest the iniquity of my sin. Selah.",
    "Psalm 32:6": "For this shall every one that is godly pray unto thee in a time when thou mayest be found: surely in the floods of great waters they shall not come nigh unto him.",
    "Psalm 32:7": "Thou art my hiding place; thou shalt preserve me from trouble; thou shalt compass me about with songs of deliverance. Selah.",
    "Psalm 32:8": "I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye.",
    "Psalm 32:9": "Be ye not as the horse, or as the mule, which have no understanding: whose mouth must be held in with bit and bridle, lest they come near unto thee.",
    "Psalm 32:10": "Many sorrows shall be to the wicked: but he that trusteth in the LORD, mercy shall compass him about.",
    "Psalm 32:11": "Be glad in the LORD, and rejoice, ye righteous: and shout for joy, all ye that are upright in heart.",
    
    // Psalm 33 (King James Version)
    "Psalm 33:1": "Rejoice in the LORD, O ye righteous: for praise is comely for the upright.",
    "Psalm 33:2": "Praise the LORD with harp: sing unto him with the psaltery and an instrument of ten strings.",
    "Psalm 33:3": "Sing unto him a new song; play skilfully with a loud noise.",
    "Psalm 33:4": "For the word of the LORD is right; and all his works are done in truth.",
    "Psalm 33:5": "He loveth righteousness and judgment: the earth is full of the goodness of the LORD.",
    "Psalm 33:6": "By the word of the LORD were the heavens made; and all the host of them by the breath of his mouth.",
    "Psalm 33:7": "He gathereth the waters of the sea together as an heap: he layeth up the depth in storehouses.",
    "Psalm 33:8": "Let all the earth fear the LORD: let all the inhabitants of the world stand in awe of him.",
    "Psalm 33:9": "For he spake, and it was done; he commanded, and it stood fast.",
    "Psalm 33:10": "The LORD bringeth the counsel of the heathen to nought: he maketh the devices of the people of none effect.",
    "Psalm 33:11": "The counsel of the LORD standeth for ever, the thoughts of his heart to all generations.",
    "Psalm 33:12": "Blessed is the nation whose God is the LORD; and the people whom he hath chosen for his own inheritance.",
    "Psalm 33:13": "The LORD looketh from heaven; he beholdeth all the sons of men.",
    "Psalm 33:14": "From the place of his habitation he looketh upon all the inhabitants of the earth.",
    "Psalm 33:15": "He fashioneth their hearts alike; he considereth all their works.",
    "Psalm 33:16": "There is no king saved by the multitude of an host: a mighty man is not delivered by much strength.",
    "Psalm 33:17": "An horse is a vain thing for safety: neither shall he deliver any by his great strength.",
    "Psalm 33:18": "Behold, the eye of the LORD is upon them that fear him, upon them that hope in his mercy;",
    "Psalm 33:19": "To deliver their soul from death, and to keep them alive in famine.",
    "Psalm 33:20": "Our soul waiteth for the LORD: he is our help and our shield.",
    "Psalm 33:21": "For our heart shall rejoice in him, because we have trusted in his holy name.",
    "Psalm 33:22": "Let thy mercy, O LORD, be upon us, according as we hope in thee.",
    
    // Psalm 34 (King James Version)
    "Psalm 34:1": "I will bless the LORD at all times: his praise shall continually be in my mouth.",
    "Psalm 34:2": "My soul shall make her boast in the LORD: the humble shall hear thereof, and be glad.",
    "Psalm 34:3": "O magnify the LORD with me, and let us exalt his name together.",
    "Psalm 34:4": "I sought the LORD, and he heard me, and delivered me from all my fears.",
    "Psalm 34:5": "They looked unto him, and were lightened: and their faces were not ashamed.",
    "Psalm 34:6": "This poor man cried, and the LORD heard him, and saved him out of all his troubles.",
    "Psalm 34:7": "The angel of the LORD encampeth round about them that fear him, and delivereth them.",
    "Psalm 34:8": "O taste and see that the LORD is good: blessed is the man that trusteth in him.",
    "Psalm 34:9": "O fear the LORD, ye his saints: for there is no want to them that fear him.",
    "Psalm 34:10": "The young lions do lack, and suffer hunger: but they that seek the LORD shall not want any good thing.",
    "Psalm 34:11": "Come, ye children, hearken unto me: I will teach you the fear of the LORD.",
    "Psalm 34:12": "What man is he that desireth life, and loveth many days, that he may see good?",
    "Psalm 34:13": "Keep thy tongue from evil, and thy lips from speaking guile.",
    "Psalm 34:14": "Depart from evil, and do good; seek peace, and pursue it.",
    "Psalm 34:15": "The eyes of the LORD are upon the righteous, and his ears are open unto their cry.",
    "Psalm 34:16": "The face of the LORD is against them that do evil, to cut off the remembrance of them from the earth.",
    "Psalm 34:17": "The righteous cry, and the LORD heareth, and delivereth them out of all their troubles.",
    "Psalm 34:18": "The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.",
    "Psalm 34:19": "Many are the afflictions of the righteous: but the LORD delivereth him out of them all.",
    "Psalm 34:20": "He keepeth all his bones: not one of them is broken.",
    "Psalm 34:21": "Evil shall slay the wicked: and they that hate the righteous shall be desolate.",
    "Psalm 34:22": "The LORD redeemeth the soul of his servants: and none of them that trust in him shall be desolate.",
    
    // Psalm 35 (King James Version)
    "Psalm 35:1": "Plead my cause, O LORD, with them that strive with me: fight against them that fight against me.",
    "Psalm 35:2": "Take hold of shield and buckler, and stand up for mine help.",
    "Psalm 35:3": "Draw out also the spear, and stop the way against them that persecute me: say unto my soul, I am thy salvation.",
    "Psalm 35:4": "Let them be confounded and put to shame that seek after my soul: let them be turned back and brought to confusion that devise my hurt.",
    "Psalm 35:5": "Let them be as chaff before the wind: and let the angel of the LORD chase them.",
    "Psalm 35:6": "Let their way be dark and slippery: and let the angel of the LORD persecute them.",
    "Psalm 35:7": "For without cause have they hid for me their net in a pit, which without cause they have digged for my soul.",
    "Psalm 35:8": "Let destruction come upon him at unawares; and let his net that he hath hid catch himself: into that very destruction let him fall.",
    "Psalm 35:9": "And my soul shall be joyful in the LORD: it shall rejoice in his salvation.",
    "Psalm 35:10": "All my bones shall say, LORD, who is like unto thee, which deliverest the poor from him that is too strong for him, yea, the poor and the needy from him that spoileth him?",
    "Psalm 35:11": "False witnesses did rise up; they laid to my charge things that I knew not.",
    "Psalm 35:12": "They rewarded me evil for good to the spoiling of my soul.",
    "Psalm 35:13": "But as for me, when they were sick, my clothing was sackcloth: I humbled my soul with fasting; and my prayer returned into mine own bosom.",
    "Psalm 35:14": "I behaved myself as though he had been my friend or brother: I bowed down heavily, as one that mourneth for his mother.",
    "Psalm 35:15": "But in mine adversity they rejoiced, and gathered themselves together: yea, the abjects gathered themselves together against me, and I knew it not; they did tear me, and ceased not:",
    "Psalm 35:16": "With hypocritical mockers in feasts, they gnashed upon me with their teeth.",
    "Psalm 35:17": "Lord, how long wilt thou look on? rescue my soul from their destructions, my darling from the lions.",
    "Psalm 35:18": "I will give thee thanks in the great congregation: I will praise thee among much people.",
    "Psalm 35:19": "Let not them that are mine enemies wrongfully rejoice over me: neither let them wink with the eye that hate me without a cause.",
    "Psalm 35:20": "For they speak not peace: but they devise deceitful matters against them that are quiet in the land.",
    "Psalm 35:21": "Yea, they opened their mouth wide against me, and said, Aha, Aha, our eye hath seen it.",
    "Psalm 35:22": "This thou hast seen, O LORD: keep not silence: O LORD, be not far from me.",
    "Psalm 35:23": "Stir up thyself, and awake to my judgment, even unto my cause, my God and my Lord.",
    "Psalm 35:24": "Judge me, O LORD my God, according to thy righteousness; and let them not rejoice over me.",
    "Psalm 35:25": "Let them not say in their hearts, Ah, so would we have it: let them not say, We have swallowed him up.",
    "Psalm 35:26": "Let them be ashamed and brought to confusion together that rejoice at mine hurt: let them be clothed with shame and dishonour that magnify themselves against me.",
    "Psalm 35:27": "Let them shout for joy, and be glad, that favour my righteous cause: yea, let them say continually, Let the LORD be magnified, which hath pleasure in the prosperity of his servant.",
    "Psalm 35:28": "And my tongue shall speak of thy righteousness and of thy praise all the day long.",
    
    // Psalm 36 (King James Version)
    "Psalm 36:1": "The transgression of the wicked saith within my heart, that there is no fear of God before his eyes.",
    "Psalm 36:2": "For he flattereth himself in his own eyes, until his iniquity be found to be hateful.",
    "Psalm 36:3": "The words of his mouth are iniquity and deceit: he hath left off to be wise, and to do good.",
    "Psalm 36:4": "He deviseth mischief upon his bed; he setteth himself in a way that is not good; he abhorreth not evil.",
    "Psalm 36:5": "Thy mercy, O LORD, is in the heavens; and thy faithfulness reacheth unto the clouds.",
    "Psalm 36:6": "Thy righteousness is like the great mountains; thy judgments are a great deep: O LORD, thou preservest man and beast.",
    "Psalm 36:7": "How excellent is thy lovingkindness, O God! therefore the children of men put their trust under the shadow of thy wings.",
    "Psalm 36:8": "They shall be abundantly satisfied with the fatness of thy house; and thou shalt make them drink of the river of thy pleasures.",
    "Psalm 36:9": "For with thee is the fountain of life: in thy light shall we see light.",
    "Psalm 36:10": "O continue thy lovingkindness unto them that know thee; and thy righteousness to the upright in heart.",
    "Psalm 36:11": "Let not the foot of pride come against me, and let not the hand of the wicked remove me.",
    "Psalm 36:12": "There are the workers of iniquity fallen: they are cast down, and shall not be able to rise.",
    
    // Psalm 37 (King James Version)
    "Psalm 37:1": "Fret not thyself because of evildoers, neither be thou envious against the workers of iniquity.",
    "Psalm 37:2": "For they shall soon be cut down like the grass, and wither as the green herb.",
    "Psalm 37:3": "Trust in the LORD, and do good; so shalt thou dwell in the land, and verily thou shalt be fed.",
    "Psalm 37:4": "Delight thyself also in the LORD; and he shall give thee the desires of thine heart.",
    "Psalm 37:5": "Commit thy way unto the LORD; trust also in him; and he shall bring it to pass.",
    "Psalm 37:6": "And he shall bring forth thy righteousness as the light, and thy judgment as the noonday.",
    "Psalm 37:7": "Rest in the LORD, and wait patiently for him: fret not thyself because of him who prospereth in his way, because of the man who bringeth wicked devices to pass.",
    "Psalm 37:8": "Cease from anger, and forsake wrath: fret not thyself in any wise to do evil.",
    "Psalm 37:9": "For evildoers shall be cut off: but those that wait upon the LORD, they shall inherit the earth.",
    "Psalm 37:10": "For yet a little while, and the wicked shall not be: yea, thou shalt diligently consider his place, and it shall not be.",
    "Psalm 37:11": "But the meek shall inherit the earth; and shall delight themselves in the abundance of peace.",
    "Psalm 37:12": "The wicked plotteth against the just, and gnasheth upon him with his teeth.",
    "Psalm 37:13": "The Lord shall laugh at him: for he seeth that his day is coming.",
    "Psalm 37:14": "The wicked have drawn out the sword, and have bent their bow, to cast down the poor and needy, and to slay such as be of upright conversation.",
    "Psalm 37:15": "Their sword shall enter into their own heart, and their bows shall be broken.",
    "Psalm 37:16": "A little that a righteous man hath is better than the riches of many wicked.",
    "Psalm 37:17": "For the arms of the wicked shall be broken: but the LORD upholdeth the righteous.",
    "Psalm 37:18": "The LORD knoweth the days of the upright: and their inheritance shall be for ever.",
    "Psalm 37:19": "They shall not be ashamed in the evil time: and in the days of famine they shall be satisfied.",
    "Psalm 37:20": "But the wicked shall perish, and the enemies of the LORD shall be as the fat of lambs: they shall consume; into smoke shall they consume away.",
    "Psalm 37:21": "The wicked borroweth, and payeth not again: but the righteous sheweth mercy, and giveth.",
    "Psalm 37:22": "For such as be blessed of him shall inherit the earth; and they that be cursed of him shall be cut off.",
    "Psalm 37:23": "The steps of a good man are ordered by the LORD: and he delighteth in his way.",
    "Psalm 37:24": "Though he fall, he shall not be utterly cast down: for the LORD upholdeth him with his hand.",
    "Psalm 37:25": "I have been young, and now am old; yet have I not seen the righteous forsaken, nor his seed begging bread.",
    "Psalm 37:26": "He is ever merciful, and lendeth; and his seed is blessed.",
    "Psalm 37:27": "Depart from evil, and do good; and dwell for evermore.",
    "Psalm 37:28": "For the LORD loveth judgment, and forsaketh not his saints; they are preserved for ever: but the seed of the wicked shall be cut off.",
    "Psalm 37:29": "The righteous shall inherit the land, and dwell therein for ever.",
    "Psalm 37:30": "The mouth of the righteous speaketh wisdom, and his tongue talketh of judgment.",
    "Psalm 37:31": "The law of his God is in his heart; none of his steps shall slide.",
    "Psalm 37:32": "The wicked watcheth the righteous, and seeketh to slay him.",
    "Psalm 37:33": "The LORD will not leave him in his hand, nor condemn him when he is judged.",
    "Psalm 37:34": "Wait on the LORD, and keep his way, and he shall exalt thee to inherit the land: when the wicked are cut off, thou shalt see it.",
    "Psalm 37:35": "I have seen the wicked in great power, and spreading himself like a green bay tree.",
    "Psalm 37:36": "Yet he passed away, and, lo, he was not: yea, I sought him, but he could not be found.",
    "Psalm 37:37": "Mark the perfect man, and behold the upright: for the end of that man is peace.",
    "Psalm 37:38": "But the transgressors shall be destroyed together: the end of the wicked shall be cut off.",
    "Psalm 37:39": "But the salvation of the righteous is of the LORD: he is their strength in the time of trouble.",
    "Psalm 37:40": "And the LORD shall help them, and deliver them: he shall deliver them from the wicked, and save them, because they trust in him.",
    
    // Psalm 38 (King James Version)
    "Psalm 38:1": "O LORD, rebuke me not in thy wrath: neither chasten me in thy hot displeasure.",
    "Psalm 38:2": "For thine arrows stick fast in me, and thy hand presseth me sore.",
    "Psalm 38:3": "There is no soundness in my flesh because of thine anger; neither is there any rest in my bones because of my sin.",
    "Psalm 38:4": "For mine iniquities are gone over my head: as a heavy burden they are too heavy for me.",
    "Psalm 38:5": "My wounds stink and are corrupt because of my foolishness.",
    "Psalm 38:6": "I am troubled; I am bowed down greatly; I go mourning all the day long.",
    "Psalm 38:7": "For my loins are filled with a loathsome disease: and there is no soundness in my flesh.",
    "Psalm 38:8": "I am feeble and sore broken: I have roared by reason of the disquietness of my heart.",
    "Psalm 38:9": "Lord, all my desire is before thee; and my groaning is not hid from thee.",
    "Psalm 38:10": "My heart panteth, my strength faileth me: as for the light of mine eyes, it also is gone from me.",
    "Psalm 38:11": "My lovers and my friends stand aloof from my sore; and my kinsmen stand afar off.",
    "Psalm 38:12": "They also that seek after my life lay snares for me: and they that seek my hurt speak mischievous things, and imagine deceits all the day long.",
    "Psalm 38:13": "But I, as a deaf man, heard not; and I was as a dumb man that openeth not his mouth.",
    "Psalm 38:14": "Thus I was as a man that heareth not, and in whose mouth are no reproofs.",
    "Psalm 38:15": "For in thee, O LORD, do I hope: thou wilt hear, O Lord my God.",
    "Psalm 38:16": "For I said, Hear me, lest otherwise they should rejoice over me: when my foot slippeth, they magnify themselves against me.",
    "Psalm 38:17": "For I am ready to halt, and my sorrow is continually before me.",
    "Psalm 38:18": "For I will declare mine iniquity; I will be sorry for my sin.",
    "Psalm 38:19": "But mine enemies are lively, and they are strong: and they that hate me wrongfully are multiplied.",
    "Psalm 38:20": "They also that render evil for good are mine adversaries; because I follow the thing that good is.",
    "Psalm 38:21": "Forsake me not, O LORD: O my God, be not far from me.",
    "Psalm 38:22": "Make haste to help me, O Lord my salvation.",
    
    // Psalm 39 (King James Version)
    "Psalm 39:1": "I said, I will take heed to my ways, that I sin not with my tongue: I will keep my mouth with a bridle, while the wicked is before me.",
    "Psalm 39:2": "I was dumb with silence, I held my peace, even from good; and my sorrow was stirred.",
    "Psalm 39:3": "My heart was hot within me, while I was musing the fire burned: then spake I with my tongue,",
    "Psalm 39:4": "LORD, make me to know mine end, and the measure of my days, what it is; that I may know how frail I am.",
    "Psalm 39:5": "Behold, thou hast made my days as an handbreadth; and mine age is as nothing before thee: verily every man at his best state is altogether vanity. Selah.",
    "Psalm 39:6": "Surely every man walketh in a vain shew: surely they are disquieted in vain: he heapeth up riches, and knoweth not who shall gather them.",
    "Psalm 39:7": "And now, Lord, what wait I for? my hope is in thee.",
    "Psalm 39:8": "Deliver me from all my transgressions: make me not the reproach of the foolish.",
    "Psalm 39:9": "I was dumb, I opened not my mouth; because thou didst it.",
    "Psalm 39:10": "Remove thy stroke away from me: I am consumed by the blow of thine hand.",
    "Psalm 39:11": "When thou with rebukes dost correct man for iniquity, thou makest his beauty to consume away like a moth: surely every man is vanity. Selah.",
    "Psalm 39:12": "Hear my prayer, O LORD, and give ear unto my cry; hold not thy peace at my tears: for I am a stranger with thee, and a sojourner, as all my fathers were.",
    "Psalm 39:13": "O spare me, that I may recover strength, before I go hence, and be no more.",
    
    // Psalm 40 (King James Version)
    "Psalm 40:1": "I waited patiently for the LORD; and he inclined unto me, and heard my cry.",
    "Psalm 40:2": "He brought me up also out of an horrible pit, out of the miry clay, and set my feet upon a rock, and established my goings.",
    "Psalm 40:3": "And he hath put a new song in my mouth, even praise unto our God: many shall see it, and fear, and shall trust in the LORD.",
    "Psalm 40:4": "Blessed is that man that maketh the LORD his trust, and respecteth not the proud, nor such as turn aside to lies.",
    "Psalm 40:5": "Many, O LORD my God, are thy wonderful works which thou hast done, and thy thoughts which are to us-ward: they cannot be reckoned up in order unto thee: if I would declare and speak of them, they are more than can be numbered.",
    "Psalm 40:6": "Sacrifice and offering thou didst not desire; mine ears hast thou opened: burnt offering and sin offering hast thou not required.",
    "Psalm 40:7": "Then said I, Lo, I come: in the volume of the book it is written of me,",
    "Psalm 40:8": "I delight to do thy will, O my God: yea, thy law is within my heart.",
    "Psalm 40:9": "I have preached righteousness in the great congregation: lo, I have not refrained my lips, O LORD, thou knowest.",
    "Psalm 40:10": "I have not hid thy righteousness within my heart; I have declared thy faithfulness and thy salvation: I have not concealed thy lovingkindness and thy truth from the great congregation.",
    "Psalm 40:11": "Withhold not thou thy tender mercies from me, O LORD: let thy lovingkindness and thy truth continually preserve me.",
    "Psalm 40:12": "For innumerable evils have compassed me about: mine iniquities have taken hold upon me, so that I am not able to look up; they are more than the hairs of mine head: therefore my heart faileth me.",
    "Psalm 40:13": "Be pleased, O LORD, to deliver me: O LORD, make haste to help me.",
    "Psalm 40:14": "Let them be ashamed and confounded together that seek after my soul to destroy it; let them be driven backward and put to shame that wish me evil.",
    "Psalm 40:15": "Let them be desolate for a reward of their shame that say unto me, Aha, aha.",
    "Psalm 40:16": "Let all those that seek thee rejoice and be glad in thee: let such as love thy salvation say continually, The LORD be magnified.",
    "Psalm 40:17": "But I am poor and needy; yet the LORD thinketh upon me: thou art my help and my deliverer; make no tarrying, O my God.",
    
    
    
    
    
    
    
    // Psalm 140 (King James Version)
    "Psalm 140:1": "Deliver me, O LORD, from the evil man: preserve me from the violent man;",
    "Psalm 140:2": "Which imagine mischiefs in their heart; continually are they gathered together for war.",
    "Psalm 140:3": "They have sharpened their tongues like a serpent; adders' poison is under their lips. Selah.",
    "Psalm 140:4": "Keep me, O LORD, from the hands of the wicked; preserve me from the violent man; who have purposed to overthrow my goings.",
    "Psalm 140:5": "The proud have hid a snare for me, and cords; they have spread a net by the wayside; they have set gins for me. Selah.",
    "Psalm 140:6": "I said unto the LORD, Thou art my God: hear the voice of my supplications, O LORD.",
    "Psalm 140:7": "O GOD the Lord, the strength of my salvation, thou hast covered my head in the day of battle.",
    "Psalm 140:8": "Grant not, O LORD, the desires of the wicked: further not his wicked device; lest they exalt themselves. Selah.",
    "Psalm 140:9": "As for the head of those that compass me about, let the mischief of their own lips cover them.",
    "Psalm 140:10": "Let burning coals fall upon them: let them be cast into the fire; into deep pits, that they rise not up again.",
    "Psalm 140:11": "Let not an evil speaker be established in the earth: evil shall hunt the violent man to overthrow him.",
    "Psalm 140:12": "I know that the LORD will maintain the cause of the afflicted, and the right of the poor.",
    "Psalm 140:13": "Surely the righteous shall give thanks unto thy name: the upright shall dwell in thy presence.",
    
    // Psalm 141 (King James Version)
    "Psalm 141:1": "LORD, I cry unto thee: make haste unto me; give ear unto my voice, when I cry unto thee.",
    "Psalm 141:2": "Let my prayer be set forth before thee as incense; and the lifting up of my hands as the evening sacrifice.",
    "Psalm 141:3": "Set a watch, O LORD, before my mouth; keep the door of my lips.",
    "Psalm 141:4": "Incline not my heart to any evil thing, to practise wicked works with men that work iniquity: and let me not eat of their dainties.",
    "Psalm 141:5": "Let the righteous smite me; it shall be a kindness: and let him reprove me; it shall be an excellent oil, which shall not break my head: for yet my prayer also shall be in their calamities.",
    "Psalm 141:6": "When their judges are overthrown in stony places, they shall hear my words; for they are sweet.",
    "Psalm 141:7": "Our bones are scattered at the grave's mouth, as when one cutteth and cleaveth wood upon the earth.",
    "Psalm 141:8": "But mine eyes are unto thee, O GOD the Lord: in thee is my trust; leave not my soul destitute.",
    "Psalm 141:9": "Keep me from the snares which they have laid for me, and the gins of the workers of iniquity.",
    "Psalm 141:10": "Let the wicked fall into their own nets, whilst that I withal escape.",
    
    // Psalm 142 (King James Version)
    "Psalm 142:1": "I cried unto the LORD with my voice; with my voice unto the LORD did I make my supplication.",
    "Psalm 142:2": "I poured out my complaint before him; I shewed before him my trouble.",
    "Psalm 142:3": "When my spirit was overwhelmed within me, then thou knewest my path. In the way wherein I walked have they privily laid a snare for me.",
    "Psalm 142:4": "I looked on my right hand, and beheld, but there was no man that would know me: refuge failed me; no man cared for my soul.",
    "Psalm 142:5": "I cried unto thee, O LORD: I said, Thou art my refuge and my portion in the land of the living.",
    "Psalm 142:6": "Attend unto my cry; for I am brought very low: deliver me from my persecutors; for they are stronger than I.",
    "Psalm 142:7": "Bring my soul out of prison, that I may praise thy name: the righteous shall compass me about; for thou shalt deal bountifully with me.",
    
    // Psalm 143 (King James Version)
    "Psalm 143:1": "Hear my prayer, O LORD, give ear to my supplications: in thy faithfulness answer me, and in thy righteousness.",
    "Psalm 143:2": "And enter not into judgment with thy servant: for in thy sight shall no man living be justified.",
    "Psalm 143:3": "For the enemy hath persecuted my soul; he hath smitten my life down to the ground; he hath made me to dwell in darkness, as those that have been long dead.",
    "Psalm 143:4": "Therefore is my spirit overwhelmed within me; my heart within me is desolate.",
    "Psalm 143:5": "I remember the days of old; I meditate on all thy works; I muse on the work of thy hands.",
    "Psalm 143:6": "I stretch forth my hands unto thee: my soul thirsteth after thee, as a thirsty land. Selah.",
    "Psalm 143:7": "Hear me speedily, O LORD: my spirit faileth: hide not thy face from me, lest I be like unto them that go down into the pit.",
    "Psalm 143:8": "Cause me to hear thy lovingkindness in the morning; for in thee do I trust: cause me to know the way wherein I should walk; for I lift up my soul unto thee.",
    "Psalm 143:9": "Deliver me, O LORD, from mine enemies: I flee unto thee to hide me.",
    "Psalm 143:10": "Teach me to do thy will; for thou art my God: thy spirit is good; lead me into the land of uprightness.",
    "Psalm 143:11": "Quicken me, O LORD, for thy name's sake: for thy righteousness' sake bring my soul out of trouble.",
    "Psalm 143:12": "And of thy mercy cut off mine enemies, and destroy all them that afflict my soul: for I am thy servant.",
    
    
};