const bibleVerses23 = {
    // Isaiah 1 (King James Version)
    "Isaiah 1:1": "The vision of Isaiah the son of Amoz, which he saw concerning Judah and Jerusalem in the days of Uzziah, Jotham, Ahaz, and Hezekiah, kings of Judah.",
    "Isaiah 1:2": "Hear, O heavens, and give ear, O earth: for the LORD hath spoken, I have nourished and brought up children, and they have rebelled against me.",
    "Isaiah 1:3": "The ox knoweth his owner, and the ass his master's crib: but Israel doth not know, my people doth not consider.",
    "Isaiah 1:4": "Ah sinful nation, a people laden with iniquity, a seed of evildoers, children that are corrupters: they have forsaken the LORD, they have provoked the Holy One of Israel unto anger, they are gone away backward.",
    "Isaiah 1:5": "Why should ye be stricken any more? ye will revolt more and more: the whole head is sick, and the whole heart faint.",
    "Isaiah 1:6": "From the sole of the foot even unto the head there is no soundness in it; but wounds, and bruises, and putrifying sores: they have not been closed, neither bound up, neither mollified with ointment.",
    "Isaiah 1:7": "Your country is desolate, your cities are burned with fire: your land, strangers devour it in your presence, and it is desolate, as overthrown by strangers.",
    "Isaiah 1:8": "And the daughter of Zion is left as a cottage in a vineyard, as a lodge in a garden of cucumbers, as a besieged city.",
    "Isaiah 1:9": "Except the LORD of hosts had left unto us a very small remnant, we should have been as Sodom, and we should have been like unto Gomorrah.",
    "Isaiah 1:10": "Hear the word of the LORD, ye rulers of Sodom; give ear unto the law of our God, ye people of Gomorrah.",
    "Isaiah 1:11": "To what purpose is the multitude of your sacrifices unto me? saith the LORD: I am full of the burnt offerings of rams, and the fat of fed beasts; and I delight not in the blood of bullocks, or of lambs, or of he goats.",
    "Isaiah 1:12": "When ye come to appear before me, who hath required this at your hand, to tread my courts?",
    "Isaiah 1:13": "Bring no more vain oblations; incense is an abomination unto me; the new moons and sabbaths, the calling of assemblies, I cannot away with; it is iniquity, even the solemn meeting.",
    "Isaiah 1:14": "Your new moons and your appointed feasts my soul hateth: they are a trouble unto me; I am weary to bear them.",
    "Isaiah 1:15": "And when ye spread forth your hands, I will hide mine eyes from you: yea, when ye make many prayers, I will not hear: your hands are full of blood.",
    "Isaiah 1:16": "Wash you, make you clean; put away the evil of your doings from before mine eyes; cease to do evil;",
    "Isaiah 1:17": "Learn to do well; seek judgment, relieve the oppressed, judge the fatherless, plead for the widow.",
    "Isaiah 1:18": "Come now, and let us reason together, saith the LORD: though your sins be as scarlet, they shall be as white as snow; though they be red like crimson, they shall be as wool.",
    "Isaiah 1:19": "If ye be willing and obedient, ye shall eat the good of the land:",
    "Isaiah 1:20": "But if ye refuse and rebel, ye shall be devoured with the sword: for the mouth of the LORD hath spoken it.",
    "Isaiah 1:21": "How is the faithful city become an harlot! it was full of judgment; righteousness lodged in it; but now murderers.",
    "Isaiah 1:22": "Thy silver is become dross, thy wine mixed with water:",
    "Isaiah 1:23": "Thy princes are rebellious, and companions of thieves: every one loveth gifts, and followeth after rewards: they judge not the fatherless, neither doth the cause of the widow come unto them.",
    "Isaiah 1:24": "Therefore saith the Lord, the LORD of hosts, the mighty One of Israel, Ah, I will ease me of mine adversaries, and avenge me of mine enemies:",
    "Isaiah 1:25": "And I will turn my hand upon thee, and purely purge away thy dross, and take away all thy tin:",
    "Isaiah 1:26": "And I will restore thy judges as at the first, and thy counsellors as at the beginning: afterward thou shalt be called, The city of righteousness, the faithful city.",
    "Isaiah 1:27": "Zion shall be redeemed with judgment, and her converts with righteousness.",
    "Isaiah 1:28": "And the destruction of the transgressors and of the sinners shall be together, and they that forsake the LORD shall be consumed.",
    "Isaiah 1:29": "For they shall be ashamed of the oaks which ye have desired, and ye shall be confounded for the gardens that ye have chosen.",
    "Isaiah 1:30": "For ye shall be as an oak whose leaf fadeth, and as a garden that hath no water.",
    "Isaiah 1:31": "And the strong shall be as tow, and the maker of it as a spark, and they shall both burn together, and none shall quench them.",
    
    
    
    
    // Isaiah 50 (King James Version)
    "Isaiah 50:1": "Thus saith the LORD, Where is the bill of your mother's divorcement, whom I have put away? or which of my creditors is it to whom I have sold you? Behold, for your iniquities have ye sold yourselves, and for your transgressions is your mother put away.",
    "Isaiah 50:2": "Wherefore, when I came, was there no man? when I called, was there none to answer? Is my hand shortened at all, that it cannot redeem? or have I no power to deliver? behold, at my rebuke I dry up the sea, I make the rivers a wilderness: their fish stinketh, because there is no water, and dieth for thirst.",
    "Isaiah 50:3": "I clothe the heavens with blackness, and I make sackcloth their covering.",
    "Isaiah 50:4": "The Lord GOD hath given me the tongue of the learned, that I should know how to speak a word in season to him that is weary: he wakeneth morning by morning, he wakeneth mine ear to hear as the learned.",
    "Isaiah 50:5": "The Lord GOD hath opened mine ear, and I was not rebellious, neither turned away back.",
    "Isaiah 50:6": "I gave my back to the smiters, and my cheeks to them that plucked off the hair: I hid not my face from shame and spitting.",
    "Isaiah 50:7": "For the Lord GOD will help me; therefore shall I not be confounded: therefore have I set my face like a flint, and I know that I shall not be ashamed.",
    "Isaiah 50:8": "He is near that justifieth me; who will contend with me? let us stand together: who is mine adversary? let him come near to me.",
    "Isaiah 50:9": "Behold, the Lord GOD will help me; who is he that shall condemn me? lo, they all shall wax old as a garment; the moth shall eat them up.",
    "Isaiah 50:10": "Who is among you that feareth the LORD, that obeyeth the voice of his servant, that walketh in darkness, and hath no light? let him trust in the name of the LORD, and stay upon his God.",
    "Isaiah 50:11": "Behold, all ye that kindle a fire, that compass yourselves about with sparks: walk in the light of your fire, and in the sparks that ye have kindled. This shall ye have of mine hand; ye shall lie down in sorrow.",
    
    // Isaiah 51 (King James Version)
    "Isaiah 51:1": "Hearken to me, ye that follow after righteousness, ye that seek the LORD: look unto the rock whence ye are hewn, and to the hole of the pit whence ye are digged.",
    "Isaiah 51:2": "Look unto Abraham your father, and unto Sarah that bare you: for I called him alone, and blessed him, and increased him.",
    "Isaiah 51:3": "For the LORD shall comfort Zion: he will comfort all her waste places; and he will make her wilderness like Eden, and her desert like the garden of the LORD; joy and gladness shall be found therein, thanksgiving, and the voice of melody.",
    "Isaiah 51:4": "Hearken unto me, my people; and give ear unto me, O my nation: for a law shall proceed from me, and I will make my judgment to rest for a light of the people.",
    "Isaiah 51:5": "My righteousness is near; my salvation is gone forth, and mine arms shall judge the people; the isles shall wait upon me, and on mine arm shall they trust.",
    "Isaiah 51:6": "Lift up your eyes to the heavens, and look upon the earth beneath: for the heavens shall vanish away like smoke, and the earth shall wax old like a garment, and they that dwell therein shall die in like manner: but my salvation shall be for ever, and my righteousness shall not be abolished.",
    "Isaiah 51:7": "Hearken unto me, ye that know righteousness, the people in whose heart is my law; fear ye not the reproach of men, neither be ye afraid of their revilings.",
    "Isaiah 51:8": "For the moth shall eat them up like a garment, and the worm shall eat them like wool: but my righteousness shall be for ever, and my salvation from generation to generation.",
    "Isaiah 51:9": "Awake, awake, put on strength, O arm of the LORD; awake, as in the ancient days, in the generations of old. Art thou not it that hath cut Rahab, and wounded the dragon?",
    "Isaiah 51:10": "Art thou not it which hath dried the sea, the waters of the great deep; that hath made the depths of the sea a way for the ransomed to pass over?",
    "Isaiah 51:11": "Therefore the redeemed of the LORD shall return, and come with singing unto Zion; and everlasting joy shall be upon their head: they shall obtain gladness and joy; and sorrow and mourning shall flee away.",
    "Isaiah 51:12": "I, even I, am he that comforteth you: who art thou, that thou shouldest be afraid of a man that shall die, and of the son of man which shall be made as grass;",
    "Isaiah 51:13": "And forgettest the LORD thy maker, that hath stretched forth the heavens, and laid the foundations of the earth; and hast feared continually every day because of the fury of the oppressor, as if he were ready to destroy? and where is the fury of the oppressor?",
    "Isaiah 51:14": "The captive exile hasteneth that he may be loosed, and that he should not die in the pit, nor that his bread should fail.",
    "Isaiah 51:15": "But I am the LORD thy God, that divided the sea, whose waves roared: The LORD of hosts is his name.",
    "Isaiah 51:16": "And I have put my words in thy mouth, and I have covered thee in the shadow of mine hand, that I may plant the heavens, and lay the foundations of the earth, and say unto Zion, Thou art my people.",
    "Isaiah 51:17": "Awake, awake, stand up, O Jerusalem, which hast drunk at the hand of the LORD the cup of his fury; thou hast drunken the dregs of the cup of trembling, and wrung them out.",
    "Isaiah 51:18": "There is none to guide her among all the sons whom she hath brought forth; neither is there any that taketh her by the hand of all the sons that she hath brought up.",
    "Isaiah 51:19": "These two things are come unto thee; who shall be sorry for thee? desolation, and destruction, and the famine, and the sword: by whom shall I comfort thee?",
    "Isaiah 51:20": "Thy sons have fainted, they lie at the head of all the streets, as a wild bull in a net: they are full of the fury of the LORD, the rebuke of thy God.",
    "Isaiah 51:21": "Therefore hear now this, thou afflicted, and drunken, but not with wine:",
    "Isaiah 51:22": "Thus saith thy Lord the LORD, and thy God that pleadeth the cause of his people, Behold, I have taken out of thine hand the cup of trembling, even the dregs of the cup of my fury; thou shalt no more drink it again:",
    "Isaiah 51:23": "But I will put it into the hand of them that afflict thee; which have said to thy soul, Bow down, that we may go over: and thou hast laid thy body as the ground, and as the street, to them that went over.",
    
    // Isaiah 52 (King James Version)
    "Isaiah 52:1": "Awake, awake; put on thy strength, O Zion; put on thy beautiful garments, O Jerusalem, the holy city: for henceforth there shall no more come into thee the uncircumcised and the unclean.",
    "Isaiah 52:2": "Shake thyself from the dust; arise, and sit down, O Jerusalem: loose thyself from the bands of thy neck, O captive daughter of Zion.",
    "Isaiah 52:3": "For thus saith the LORD, Ye have sold yourselves for nought; and ye shall be redeemed without money.",
    "Isaiah 52:4": "For thus saith the Lord GOD, My people went down aforetime into Egypt to sojourn there; and the Assyrian oppressed them without cause.",
    "Isaiah 52:5": "Now therefore, what have I here, saith the LORD, that my people is taken away for nought? they that rule over them make them to howl, saith the LORD; and my name continually every day is blasphemed.",
    "Isaiah 52:6": "Therefore my people shall know my name: therefore they shall know in that day that I am he that doth speak: behold, it is I.",
    "Isaiah 52:7": "How beautiful upon the mountains are the feet of him that bringeth good tidings, that publisheth peace; that bringeth good tidings of good, that publisheth salvation; that saith unto Zion, Thy God reigneth!",
    "Isaiah 52:8": "Thy watchmen shall lift up the voice; with the voice together shall they sing: for they shall see eye to eye, when the LORD shall bring again Zion.",
    "Isaiah 52:9": "Break forth into joy, sing together, ye waste places of Jerusalem: for the LORD hath comforted his people, he hath redeemed Jerusalem.",
    "Isaiah 52:10": "The LORD hath made bare his holy arm in the eyes of all the nations; and all the ends of the earth shall see the salvation of our God.",
    "Isaiah 52:11": "Depart ye, depart ye, go ye out from thence, touch no unclean thing; go ye out of the midst of her; be ye clean, that bear the vessels of the LORD.",
    "Isaiah 52:12": "For ye shall not go out with haste, nor go by flight: for the LORD will go before you; and the God of Israel will be your rereward.",
    "Isaiah 52:13": "Behold, my servant shall deal prudently, he shall be exalted and extolled, and be very high.",
    "Isaiah 52:14": "As many were astonied at thee; his visage was so marred more than any man, and his form more than the sons of men:",
    "Isaiah 52:15": "So shall he sprinkle many nations; the kings shall shut their mouths at him: for that which had not been told them shall they see; and that which they had not heard shall they consider.",
    
    // Isaiah 53 (King James Version)
    "Isaiah 53:1": "Who hath believed our report? and to whom is the arm of the LORD revealed?",
    "Isaiah 53:2": "For he shall grow up before him as a tender plant, and as a root out of a dry ground: he hath no form nor comeliness; and when we shall see him, there is no beauty that we should desire him.",
    "Isaiah 53:3": "He is despised and rejected of men; a man of sorrows, and acquainted with grief: and we hid as it were our faces from him; he was despised, and we esteemed him not.",
    "Isaiah 53:4": "Surely he hath borne our griefs, and carried our sorrows: yet we did esteem him stricken, smitten of God, and afflicted.",
    "Isaiah 53:5": "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.",
    "Isaiah 53:6": "All we like sheep have gone astray; we have turned every one to his own way; and the LORD hath laid on him the iniquity of us all.",
    "Isaiah 53:7": "He was oppressed, and he was afflicted, yet he opened not his mouth: he is brought as a lamb to the slaughter, and as a sheep before her shearers is dumb, so he openeth not his mouth.",
    "Isaiah 53:8": "He was taken from prison and from judgment: and who shall declare his generation? for he was cut off out of the land of the living: for the transgression of my people was he stricken.",
    "Isaiah 53:9": "And he made his grave with the wicked, and with the rich in his death; because he had done no violence, neither was any deceit in his mouth.",
    "Isaiah 53:10": "Yet it pleased the LORD to bruise him; he hath put him to grief: when thou shalt make his soul an offering for sin, he shall see his seed, he shall prolong his days, and the pleasure of the LORD shall prosper in his hand.",
    "Isaiah 53:11": "He shall see of the travail of his soul, and shall be satisfied: by his knowledge shall my righteous servant justify many; for he shall bear their iniquities.",
    "Isaiah 53:12": "Therefore will I divide him a portion with the great, and he shall divide the spoil with the strong; because he hath poured out his soul unto death: and he was numbered with the transgressors; and he bare the sin of many, and made intercession for the transgressors.",
    
    // Isaiah 54 (King James Version)
    "Isaiah 54:1": "Sing, O barren, thou that didst not bear; break forth into singing, and cry aloud, thou that didst not travail with child: for more are the children of the desolate than the children of the married wife, saith the LORD.",
    "Isaiah 54:2": "Enlarge the place of thy tent, and let them stretch forth the curtains of thine habitations: spare not, lengthen thy cords, and strengthen thy stakes;",
    "Isaiah 54:3": "For thou shalt break forth on the right hand and on the left; and thy seed shall inherit the Gentiles, and make the desolate cities to be inhabited.",
    "Isaiah 54:4": "Fear not; for thou shalt not be ashamed: neither be thou confounded; for thou shalt not be put to shame: for thou shalt forget the shame of thy youth, and shalt not remember the reproach of thy widowhood any more.",
    "Isaiah 54:5": "For thy Maker is thine husband; the LORD of hosts is his name; and thy Redeemer the Holy One of Israel; The God of the whole earth shall he be called.",
    "Isaiah 54:6": "For the LORD hath called thee as a woman forsaken and grieved in spirit, and a wife of youth, when thou wast refused, saith thy God.",
    "Isaiah 54:7": "For a small moment have I forsaken thee; but with great mercies will I gather thee.",
    "Isaiah 54:8": "In a little wrath I hid my face from thee for a moment; but with everlasting kindness will I have mercy on thee, saith the LORD thy Redeemer.",
    "Isaiah 54:9": "For this is as the waters of Noah unto me: for as I have sworn that the waters of Noah should no more go over the earth; so have I sworn that I would not be wroth with thee, nor rebuke thee.",
    "Isaiah 54:10": "For the mountains shall depart, and the hills be removed; but my kindness shall not depart from thee, neither shall the covenant of my peace be removed, saith the LORD that hath mercy on thee.",
    "Isaiah 54:11": "O thou afflicted, tossed with tempest, and not comforted, behold, I will lay thy stones with fair colours, and lay thy foundations with sapphires.",
    "Isaiah 54:12": "And I will make thy windows of agates, and thy gates of carbuncles, and all thy borders of pleasant stones.",
    "Isaiah 54:13": "And all thy children shall be taught of the LORD; and great shall be the peace of thy children.",
    "Isaiah 54:14": "In righteousness shalt thou be established: thou shalt be far from oppression; for thou shalt not fear: and from terror; for it shall not come near thee.",
    "Isaiah 54:15": "Behold, they shall surely gather together, but not by me: whosoever shall gather together against thee shall fall for thy sake.",
    "Isaiah 54:16": "Behold, I have created the smith that bloweth the coals in the fire, and that bringeth forth an instrument for his work; and I have created the waster to destroy.",
    "Isaiah 54:17": "No weapon that is formed against thee shall prosper; and every tongue that shall rise against thee in judgment thou shalt condemn. This is the heritage of the servants of the LORD, and their righteousness is of me, saith the LORD.",
    
    // Isaiah 55 (King James Version)
    "Isaiah 55:1": "Ho, every one that thirsteth, come ye to the waters, and he that hath no money; come ye, buy, and eat; yea, come, buy wine and milk without money and without price.",
    "Isaiah 55:2": "Wherefore do ye spend money for that which is not bread? and your labour for that which satisfieth not? hearken diligently unto me, and eat ye that which is good, and let your soul delight itself in fatness.",
    "Isaiah 55:3": "Incline your ear, and come unto me: hear, and your soul shall live; and I will make an everlasting covenant with you, even the sure mercies of David.",
    "Isaiah 55:4": "Behold, I have given him for a witness to the people, a leader and commander to the people.",
    "Isaiah 55:5": "Behold, thou shalt call a nation that thou knowest not, and nations that knew not thee shall run unto thee because of the LORD thy God, and for the Holy One of Israel; for he hath glorified thee.",
    "Isaiah 55:6": "Seek ye the LORD while he may be found, call ye upon him while he is near:",
    "Isaiah 55:7": "Let the wicked forsake his way, and the unrighteous man his thoughts: and let him return unto the LORD, and he will have mercy upon him; and to our God, for he will abundantly pardon.",
    "Isaiah 55:8": "For my thoughts are not your thoughts, neither are your ways my ways, saith the LORD.",
    "Isaiah 55:9": "For as the heavens are higher than the earth, so are my ways higher than your ways, and my thoughts than your thoughts.",
    "Isaiah 55:10": "For as the rain cometh down, and the snow from heaven, and returneth not thither, but watereth the earth, and maketh it bring forth and bud, that it may give seed to the sower, and bread to the eater:",
    "Isaiah 55:11": "So shall my word be that goeth forth out of my mouth: it shall not return unto me void, but it shall accomplish that which I please, and it shall prosper in the thing whereto I sent it.",
    "Isaiah 55:12": "For ye shall go out with joy, and be led forth with peace: the mountains and the hills shall break forth before you into singing, and all the trees of the field shall clap their hands.",
    "Isaiah 55:13": "Instead of the thorn shall come up the fir tree, and instead of the brier shall come up the myrtle tree: and it shall be to the LORD for a name, for an everlasting sign that shall not be cut off.",
    
};