const bibleVerses24 = {
    // Jeremiah 1 (King James Version)
    "Jeremiah 1:1": "The words of Jeremiah the son of Hilkiah, of the priests that were in Anathoth in the land of Benjamin:",
    "Jeremiah 1:2": "To whom the word of the LORD came in the days of Josiah the son of Amon king of Judah, in the thirteenth year of his reign.",
    "Jeremiah 1:3": "And it came also in the days of Jehoiakim the son of Josiah king of Judah, unto the end of the eleventh year of Zedekiah the son of Josiah king of Judah, unto the carrying away of Jerusalem captive in the fifth month.",
    "Jeremiah 1:4": "Then the word of the LORD came unto me, saying,",
    "Jeremiah 1:5": "Before I formed thee in the belly I knew thee; and before thou camest forth out of the womb I sanctified thee, and I ordained thee a prophet unto the nations.",
    "Jeremiah 1:6": "Then said I, Ah, Lord GOD! behold, I cannot speak: for I am a child.",
    "Jeremiah 1:7": "But the LORD said unto me, Say not, I am a child: for thou shalt go to all that I shall send thee, and whatsoever I command thee thou shalt speak.",
    "Jeremiah 1:8": "Be not afraid of their faces: for I am with thee to deliver thee, saith the LORD.",
    "Jeremiah 1:9": "Then the LORD put forth his hand, and touched my mouth. And the LORD said unto me, Behold, I have put my words in thy mouth.",
    "Jeremiah 1:10": "See, I have this day set thee over the nations and over the kingdoms, to root out, and to pull down, and to destroy, and to throw down, to build, and to plant.",
    "Jeremiah 1:11": "Moreover the word of the LORD came unto me, saying, Jeremiah, what seest thou? And I said, I see a rod of an almond tree.",
    "Jeremiah 1:12": "Then said the LORD unto me, Thou hast well seen: for I will hasten my word to perform it.",
    "Jeremiah 1:13": "And the word of the LORD came unto me the second time, saying, What seest thou? And I said, I see a seething pot; and the face thereof is toward the north.",
    "Jeremiah 1:14": "Then the LORD said unto me, Out of the north an evil shall break forth upon all the inhabitants of the land.",
    "Jeremiah 1:15": "For, lo, I will call all the families of the kingdoms of the north, saith the LORD; and they shall come, and they shall set every one his throne at the entering of the gates of Jerusalem, and against all the walls thereof round about, and against all the cities of Judah.",
    "Jeremiah 1:16": "And I will utter my judgments against them touching all their wickedness, who have forsaken me, and have burned incense unto other gods, and worshipped the works of their own hands.",
    "Jeremiah 1:17": "Thou therefore gird up thy loins, and arise, and speak unto them all that I command thee: be not dismayed at their faces, lest I confound thee before them.",
    "Jeremiah 1:18": "For, behold, I have made thee this day a defenced city, and an iron pillar, and brasen walls against the whole land, against the kings of Judah, against the princes thereof, against the priests thereof, and against the people of the land.",
    "Jeremiah 1:19": "And they shall fight against thee; but they shall not prevail against thee; for I am with thee, saith the LORD, to deliver thee.",
    
    // Jeremiah 2 (King James Version)
    "Jeremiah 2:1": "Moreover the word of the LORD came to me, saying,",
    "Jeremiah 2:2": "Go and cry in the ears of Jerusalem, saying, Thus saith the LORD; I remember thee, the kindness of thy youth, the love of thine espousals, when thou wentest after me in the wilderness, in a land that was not sown.",
    "Jeremiah 2:3": "Israel was holiness unto the LORD, and the firstfruits of his increase: all that devour him shall offend; evil shall come upon them, saith the LORD.",
    "Jeremiah 2:4": "Hear ye the word of the LORD, O house of Jacob, and all the families of the house of Israel:",
    "Jeremiah 2:5": "Thus saith the LORD, What iniquity have your fathers found in me, that they are gone far from me, and have walked after vanity, and are become vain?",
    "Jeremiah 2:6": "Neither said they, Where is the LORD that brought us up out of the land of Egypt, that led us through the wilderness, through a land of deserts and of pits, through a land of drought, and of the shadow of death, through a land that no man passed through, and where no man dwelt?",
    "Jeremiah 2:7": "And I brought you into a plentiful country, to eat the fruit thereof and the goodness thereof; but when ye entered, ye defiled my land, and made mine heritage an abomination.",
    "Jeremiah 2:8": "The priests said not, Where is the LORD? and they that handle the law knew me not: the pastors also transgressed against me, and the prophets prophesied by Baal, and walked after things that do not profit.",
    "Jeremiah 2:9": "Wherefore I will yet plead with you, saith the LORD, and with your children's children will I plead.",
    "Jeremiah 2:10": "For pass over the isles of Chittim, and see; and send unto Kedar, and consider diligently, and see if there be such a thing.",
    "Jeremiah 2:11": "Hath a nation changed their gods, which are yet no gods? but my people have changed their glory for that which doth not profit.",
    "Jeremiah 2:12": "Be astonished, O ye heavens, at this, and be horribly afraid, be ye very desolate, saith the LORD.",
    "Jeremiah 2:13": "For my people have committed two evils; they have forsaken me the fountain of living waters, and hewed them out cisterns, broken cisterns, that can hold no water.",
    "Jeremiah 2:14": "Is Israel a servant? is he a homeborn slave? why is he spoiled?",
    "Jeremiah 2:15": "The young lions roared upon him, and yelled, and they made his land waste: his cities are burned without inhabitant.",
    "Jeremiah 2:16": "Also the children of Noph and Tahapanes have broken the crown of thy head.",
    "Jeremiah 2:17": "Hast thou not procured this unto thyself, in that thou hast forsaken the LORD thy God, when he led thee by the way?",
    "Jeremiah 2:18": "And now what hast thou to do in the way of Egypt, to drink the waters of Sihor? or what hast thou to do in the way of Assyria, to drink the waters of the river?",
    "Jeremiah 2:19": "Thine own wickedness shall correct thee, and thy backslidings shall reprove thee: know therefore and see that it is an evil thing and bitter, that thou hast forsaken the LORD thy God, and that my fear is not in thee, saith the LORD God of hosts.",
    "Jeremiah 2:20": "For of old time I have broken thy yoke, and burst thy bands; and thou saidst, I will not transgress; when upon every high hill and under every green tree thou wanderest, playing the harlot.",
    "Jeremiah 2:21": "Yet I had planted thee a noble vine, wholly a right seed: how then art thou turned into the degenerate plant of a strange vine unto me?",
    "Jeremiah 2:22": "For though thou wash thee with lye, and take thee much soap, yet thine iniquity is marked before me, saith the LORD God.",
    "Jeremiah 2:23": "How canst thou say, I am not polluted, I have not gone after Baalim? see thy way in the valley, know what thou hast done: thou art a swift dromedary traversing her ways;",
    "Jeremiah 2:24": "A wild ass used to the wilderness, that snuffeth up the wind at her pleasure; in her occasion who can turn her away? all they that seek her will not weary themselves; in her month they shall find her.",
    "Jeremiah 2:25": "Withhold thy foot from being unshod, and thy throat from thirst: but thou saidst, There is no hope: no; for I have loved strangers, and after them will I go.",
    "Jeremiah 2:26": "As the thief is ashamed when he is found, so is the house of Israel ashamed; they, their kings, their princes, and their priests, and their prophets,",
    "Jeremiah 2:27": "Saying to a stock, Thou art my father; and to a stone, Thou hast brought me forth: for they have turned their back unto me, and not their face: but in the time of their trouble they will say, Arise, and save us.",
    "Jeremiah 2:28": "But where are thy gods that thou hast made thee? let them arise, if they can save thee in the time of thy trouble: for according to the number of thy cities are thy gods, O Judah.",
    "Jeremiah 2:29": "Wherefore will ye plead with me? ye all have transgressed against me, saith the LORD.",
    "Jeremiah 2:30": "In vain have I smitten your children; they received no correction: your own sword hath devoured your prophets, like a destroying lion.",
    "Jeremiah 2:31": "O generation, see ye the word of the LORD. Have I been a wilderness unto Israel? a land of darkness? wherefore say my people, We are lords; we will come no more unto thee?",
    "Jeremiah 2:32": "Can a maid forget her ornaments, or a bride her attire? yet my people have forgotten me days without number.",
    "Jeremiah 2:33": "Why trimmest thou thy way to seek love? therefore hast thou also taught the wicked ones thy ways.",
    "Jeremiah 2:34": "Also in thy skirts is found the blood of the souls of the poor innocents: I have not found it by secret search, but upon all these.",
    "Jeremiah 2:35": "Yet thou sayest, Because I am innocent, surely his anger shall turn from me. Behold, I will plead with thee, because thou sayest, I have not sinned.",
    "Jeremiah 2:36": "Why gaddest thou about so much to change thy way? thou also shalt be ashamed of Egypt, as thou wast ashamed of Assyria.",
    "Jeremiah 2:37": "Yea, thou shalt go forth from him, and thine hands upon thine head: for the LORD hath rejected thy confidences, and thou shalt not prosper in them.",
    
    // Jeremiah 3 (King James Version)
    "Jeremiah 3:1": "They say, If a man put away his wife, and she go from him, and become another man's, shall he return unto her again? shall not that land be greatly polluted? but thou hast played the harlot with many lovers; yet return again to me, saith the LORD.",
    "Jeremiah 3:2": "Lift up thine eyes unto the high places, and see where thou hast not been lien with. In the ways hast thou sat for them, as the Arabian in the wilderness; and thou hast polluted the land with thy whoredoms and with thy wickedness.",
    "Jeremiah 3:3": "Therefore the showers have been withholden, and there hath been no latter rain; and thou hadst a whore's forehead, thou refusedst to be ashamed.",
    "Jeremiah 3:4": "Wilt thou not from this time cry unto me, My father, thou art the guide of my youth?",
    "Jeremiah 3:5": "Will he reserve his anger for ever? will he keep it to the end? Behold, thou hast spoken and done evil things as thou couldest.",
    "Jeremiah 3:6": "The LORD said also unto me in the days of Josiah the king, Hast thou seen that which backsliding Israel hath done? she is gone up upon every high mountain and under every green tree, and there hath played the harlot.",
    "Jeremiah 3:7": "And I said after she had done all these things, Turn thou unto me. But she returned not. And her treacherous sister Judah saw it.",
    "Jeremiah 3:8": "And I saw, when for all the causes whereby backsliding Israel committed adultery I had put her away, and given her a bill of divorce; yet her treacherous sister Judah feared not, but went and played the harlot also.",
    "Jeremiah 3:9": "And it came to pass through the lightness of her whoredom, that she defiled the land, and committed adultery with stones and with stocks.",
    "Jeremiah 3:10": "And yet for all this her treacherous sister Judah hath not turned unto me with her whole heart, but feignedly, saith the LORD.",
    "Jeremiah 3:11": "And the LORD said unto me, The backsliding Israel hath justified herself more than treacherous Judah.",
    "Jeremiah 3:12": "Go and proclaim these words toward the north, and say, Return, thou backsliding Israel, saith the LORD; and I will not cause mine anger to fall upon you: for I am merciful, saith the LORD, and I will not keep anger for ever.",
    "Jeremiah 3:13": "Only acknowledge thine iniquity, that thou hast transgressed against the LORD thy God, and hast scattered thy ways to the strangers under every green tree, and ye have not obeyed my voice, saith the LORD.",
    "Jeremiah 3:14": "Turn, O backsliding children, saith the LORD; for I am married unto you: and I will take you one of a city, and two of a family, and I will bring you to Zion:",
    "Jeremiah 3:15": "And I will give you pastors according to mine heart, which shall feed you with knowledge and understanding.",
    "Jeremiah 3:16": "And it shall come to pass, when ye be multiplied and increased in the land, in those days, saith the LORD, they shall say no more, The ark of the covenant of the LORD: neither shall it come to mind: neither shall they remember it; neither shall they visit it; neither shall that be done any more.",
    "Jeremiah 3:17": "At that time they shall call Jerusalem the throne of the LORD; and all the nations shall be gathered unto it, to the name of the LORD, to Jerusalem: neither shall they walk any more after the imagination of their evil heart.",
    "Jeremiah 3:18": "In those days the house of Judah shall walk with the house of Israel, and they shall come together out of the land of the north to the land that I have given for an inheritance unto your fathers.",
    "Jeremiah 3:19": "But I said, How shall I put thee among the children, and give thee a pleasant land, a goodly heritage of the hosts of nations? and I said, Thou shalt call me, My father; and shalt not turn away from me.",
    "Jeremiah 3:20": "Surely as a wife treacherously departeth from her husband, so have ye dealt treacherously with me, O house of Israel, saith the LORD.",
    "Jeremiah 3:21": "A voice was heard upon the high places, weeping and supplications of the children of Israel: for they have perverted their way, and they have forgotten the LORD their God.",
    "Jeremiah 3:22": "Return, ye backsliding children, and I will heal your backslidings. Behold, we come unto thee; for thou art the LORD our God.",
    "Jeremiah 3:23": "Truly in vain is salvation hoped for from the hills, and from the multitude of mountains: truly in the LORD our God is the salvation of Israel.",
    "Jeremiah 3:24": "For shame hath devoured the labour of our fathers from our youth; their flocks and their herds, their sons and their daughters.",
    "Jeremiah 3:25": "We lie down in our shame, and our confusion covereth us: for we have sinned against the LORD our God, we and our fathers, from our youth even unto this day, and have not obeyed the voice of the LORD our God.",
    
    
};