const bibleVerses24 = {
    // Jeremiah 1 (King James Version)
    "Jeremiah 1:1": "The words of Jeremiah the son of Hilkiah, of the priests that were in Anathoth in the land of Benjamin:",
    "Jeremiah 1:2": "To whom the word of the LORD came in the days of Josiah the son of Amon king of Judah, in the thirteenth year of his reign.",
    "Jeremiah 1:3": "And it came also in the days of Jehoiakim the son of Josiah king of Judah, unto the end of the eleventh year of Zedekiah the son of Josiah king of Judah, unto the carrying away of Jerusalem captive in the fifth month.",
    "Jeremiah 1:4": "Then the word of the LORD came unto me, saying,",
    "Jeremiah 1:5": "Before I formed thee in the belly I knew thee; and before thou camest forth out of the womb I sanctified thee, and I ordained thee a prophet unto the nations.",
    "Jeremiah 1:6": "Then said I, Ah, Lord GOD! behold, I cannot speak: for I am a child.",
    "Jeremiah 1:7": "But the LORD said unto me, Say not, I am a child: for thou shalt go to all that I shall send thee, and whatsoever I command thee thou shalt speak.",
    "Jeremiah 1:8": "Be not afraid of their faces: for I am with thee to deliver thee, saith the LORD.",
    "Jeremiah 1:9": "Then the LORD put forth his hand, and touched my mouth. And the LORD said unto me, Behold, I have put my words in thy mouth.",
    "Jeremiah 1:10": "See, I have this day set thee over the nations and over the kingdoms, to root out, and to pull down, and to destroy, and to throw down, to build, and to plant.",
    "Jeremiah 1:11": "Moreover the word of the LORD came unto me, saying, Jeremiah, what seest thou? And I said, I see a rod of an almond tree.",
    "Jeremiah 1:12": "Then said the LORD unto me, Thou hast well seen: for I will hasten my word to perform it.",
    "Jeremiah 1:13": "And the word of the LORD came unto me the second time, saying, What seest thou? And I said, I see a seething pot; and the face thereof is toward the north.",
    "Jeremiah 1:14": "Then the LORD said unto me, Out of the north an evil shall break forth upon all the inhabitants of the land.",
    "Jeremiah 1:15": "For, lo, I will call all the families of the kingdoms of the north, saith the LORD; and they shall come, and they shall set every one his throne at the entering of the gates of Jerusalem, and against all the walls thereof round about, and against all the cities of Judah.",
    "Jeremiah 1:16": "And I will utter my judgments against them touching all their wickedness, who have forsaken me, and have burned incense unto other gods, and worshipped the works of their own hands.",
    "Jeremiah 1:17": "Thou therefore gird up thy loins, and arise, and speak unto them all that I command thee: be not dismayed at their faces, lest I confound thee before them.",
    "Jeremiah 1:18": "For, behold, I have made thee this day a defenced city, and an iron pillar, and brasen walls against the whole land, against the kings of Judah, against the princes thereof, against the priests thereof, and against the people of the land.",
    "Jeremiah 1:19": "And they shall fight against thee; but they shall not prevail against thee; for I am with thee, saith the LORD, to deliver thee.",
    
    // Jeremiah 2 (King James Version)
    "Jeremiah 2:1": "Moreover the word of the LORD came to me, saying,",
    "Jeremiah 2:2": "Go and cry in the ears of Jerusalem, saying, Thus saith the LORD; I remember thee, the kindness of thy youth, the love of thine espousals, when thou wentest after me in the wilderness, in a land that was not sown.",
    "Jeremiah 2:3": "Israel was holiness unto the LORD, and the firstfruits of his increase: all that devour him shall offend; evil shall come upon them, saith the LORD.",
    "Jeremiah 2:4": "Hear ye the word of the LORD, O house of Jacob, and all the families of the house of Israel:",
    "Jeremiah 2:5": "Thus saith the LORD, What iniquity have your fathers found in me, that they are gone far from me, and have walked after vanity, and are become vain?",
    "Jeremiah 2:6": "Neither said they, Where is the LORD that brought us up out of the land of Egypt, that led us through the wilderness, through a land of deserts and of pits, through a land of drought, and of the shadow of death, through a land that no man passed through, and where no man dwelt?",
    "Jeremiah 2:7": "And I brought you into a plentiful country, to eat the fruit thereof and the goodness thereof; but when ye entered, ye defiled my land, and made mine heritage an abomination.",
    "Jeremiah 2:8": "The priests said not, Where is the LORD? and they that handle the law knew me not: the pastors also transgressed against me, and the prophets prophesied by Baal, and walked after things that do not profit.",
    "Jeremiah 2:9": "Wherefore I will yet plead with you, saith the LORD, and with your children's children will I plead.",
    "Jeremiah 2:10": "For pass over the isles of Chittim, and see; and send unto Kedar, and consider diligently, and see if there be such a thing.",
    "Jeremiah 2:11": "Hath a nation changed their gods, which are yet no gods? but my people have changed their glory for that which doth not profit.",
    "Jeremiah 2:12": "Be astonished, O ye heavens, at this, and be horribly afraid, be ye very desolate, saith the LORD.",
    "Jeremiah 2:13": "For my people have committed two evils; they have forsaken me the fountain of living waters, and hewed them out cisterns, broken cisterns, that can hold no water.",
    "Jeremiah 2:14": "Is Israel a servant? is he a homeborn slave? why is he spoiled?",
    "Jeremiah 2:15": "The young lions roared upon him, and yelled, and they made his land waste: his cities are burned without inhabitant.",
    "Jeremiah 2:16": "Also the children of Noph and Tahapanes have broken the crown of thy head.",
    "Jeremiah 2:17": "Hast thou not procured this unto thyself, in that thou hast forsaken the LORD thy God, when he led thee by the way?",
    "Jeremiah 2:18": "And now what hast thou to do in the way of Egypt, to drink the waters of Sihor? or what hast thou to do in the way of Assyria, to drink the waters of the river?",
    "Jeremiah 2:19": "Thine own wickedness shall correct thee, and thy backslidings shall reprove thee: know therefore and see that it is an evil thing and bitter, that thou hast forsaken the LORD thy God, and that my fear is not in thee, saith the LORD God of hosts.",
    "Jeremiah 2:20": "For of old time I have broken thy yoke, and burst thy bands; and thou saidst, I will not transgress; when upon every high hill and under every green tree thou wanderest, playing the harlot.",
    "Jeremiah 2:21": "Yet I had planted thee a noble vine, wholly a right seed: how then art thou turned into the degenerate plant of a strange vine unto me?",
    "Jeremiah 2:22": "For though thou wash thee with lye, and take thee much soap, yet thine iniquity is marked before me, saith the LORD God.",
    "Jeremiah 2:23": "How canst thou say, I am not polluted, I have not gone after Baalim? see thy way in the valley, know what thou hast done: thou art a swift dromedary traversing her ways;",
    "Jeremiah 2:24": "A wild ass used to the wilderness, that snuffeth up the wind at her pleasure; in her occasion who can turn her away? all they that seek her will not weary themselves; in her month they shall find her.",
    "Jeremiah 2:25": "Withhold thy foot from being unshod, and thy throat from thirst: but thou saidst, There is no hope: no; for I have loved strangers, and after them will I go.",
    "Jeremiah 2:26": "As the thief is ashamed when he is found, so is the house of Israel ashamed; they, their kings, their princes, and their priests, and their prophets,",
    "Jeremiah 2:27": "Saying to a stock, Thou art my father; and to a stone, Thou hast brought me forth: for they have turned their back unto me, and not their face: but in the time of their trouble they will say, Arise, and save us.",
    "Jeremiah 2:28": "But where are thy gods that thou hast made thee? let them arise, if they can save thee in the time of thy trouble: for according to the number of thy cities are thy gods, O Judah.",
    "Jeremiah 2:29": "Wherefore will ye plead with me? ye all have transgressed against me, saith the LORD.",
    "Jeremiah 2:30": "In vain have I smitten your children; they received no correction: your own sword hath devoured your prophets, like a destroying lion.",
    "Jeremiah 2:31": "O generation, see ye the word of the LORD. Have I been a wilderness unto Israel? a land of darkness? wherefore say my people, We are lords; we will come no more unto thee?",
    "Jeremiah 2:32": "Can a maid forget her ornaments, or a bride her attire? yet my people have forgotten me days without number.",
    "Jeremiah 2:33": "Why trimmest thou thy way to seek love? therefore hast thou also taught the wicked ones thy ways.",
    "Jeremiah 2:34": "Also in thy skirts is found the blood of the souls of the poor innocents: I have not found it by secret search, but upon all these.",
    "Jeremiah 2:35": "Yet thou sayest, Because I am innocent, surely his anger shall turn from me. Behold, I will plead with thee, because thou sayest, I have not sinned.",
    "Jeremiah 2:36": "Why gaddest thou about so much to change thy way? thou also shalt be ashamed of Egypt, as thou wast ashamed of Assyria.",
    "Jeremiah 2:37": "Yea, thou shalt go forth from him, and thine hands upon thine head: for the LORD hath rejected thy confidences, and thou shalt not prosper in them.",
    
    // Jeremiah 3 (King James Version)
    "Jeremiah 3:1": "They say, If a man put away his wife, and she go from him, and become another man's, shall he return unto her again? shall not that land be greatly polluted? but thou hast played the harlot with many lovers; yet return again to me, saith the LORD.",
    "Jeremiah 3:2": "Lift up thine eyes unto the high places, and see where thou hast not been lien with. In the ways hast thou sat for them, as the Arabian in the wilderness; and thou hast polluted the land with thy whoredoms and with thy wickedness.",
    "Jeremiah 3:3": "Therefore the showers have been withholden, and there hath been no latter rain; and thou hadst a whore's forehead, thou refusedst to be ashamed.",
    "Jeremiah 3:4": "Wilt thou not from this time cry unto me, My father, thou art the guide of my youth?",
    "Jeremiah 3:5": "Will he reserve his anger for ever? will he keep it to the end? Behold, thou hast spoken and done evil things as thou couldest.",
    "Jeremiah 3:6": "The LORD said also unto me in the days of Josiah the king, Hast thou seen that which backsliding Israel hath done? she is gone up upon every high mountain and under every green tree, and there hath played the harlot.",
    "Jeremiah 3:7": "And I said after she had done all these things, Turn thou unto me. But she returned not. And her treacherous sister Judah saw it.",
    "Jeremiah 3:8": "And I saw, when for all the causes whereby backsliding Israel committed adultery I had put her away, and given her a bill of divorce; yet her treacherous sister Judah feared not, but went and played the harlot also.",
    "Jeremiah 3:9": "And it came to pass through the lightness of her whoredom, that she defiled the land, and committed adultery with stones and with stocks.",
    "Jeremiah 3:10": "And yet for all this her treacherous sister Judah hath not turned unto me with her whole heart, but feignedly, saith the LORD.",
    "Jeremiah 3:11": "And the LORD said unto me, The backsliding Israel hath justified herself more than treacherous Judah.",
    "Jeremiah 3:12": "Go and proclaim these words toward the north, and say, Return, thou backsliding Israel, saith the LORD; and I will not cause mine anger to fall upon you: for I am merciful, saith the LORD, and I will not keep anger for ever.",
    "Jeremiah 3:13": "Only acknowledge thine iniquity, that thou hast transgressed against the LORD thy God, and hast scattered thy ways to the strangers under every green tree, and ye have not obeyed my voice, saith the LORD.",
    "Jeremiah 3:14": "Turn, O backsliding children, saith the LORD; for I am married unto you: and I will take you one of a city, and two of a family, and I will bring you to Zion:",
    "Jeremiah 3:15": "And I will give you pastors according to mine heart, which shall feed you with knowledge and understanding.",
    "Jeremiah 3:16": "And it shall come to pass, when ye be multiplied and increased in the land, in those days, saith the LORD, they shall say no more, The ark of the covenant of the LORD: neither shall it come to mind: neither shall they remember it; neither shall they visit it; neither shall that be done any more.",
    "Jeremiah 3:17": "At that time they shall call Jerusalem the throne of the LORD; and all the nations shall be gathered unto it, to the name of the LORD, to Jerusalem: neither shall they walk any more after the imagination of their evil heart.",
    "Jeremiah 3:18": "In those days the house of Judah shall walk with the house of Israel, and they shall come together out of the land of the north to the land that I have given for an inheritance unto your fathers.",
    "Jeremiah 3:19": "But I said, How shall I put thee among the children, and give thee a pleasant land, a goodly heritage of the hosts of nations? and I said, Thou shalt call me, My father; and shalt not turn away from me.",
    "Jeremiah 3:20": "Surely as a wife treacherously departeth from her husband, so have ye dealt treacherously with me, O house of Israel, saith the LORD.",
    "Jeremiah 3:21": "A voice was heard upon the high places, weeping and supplications of the children of Israel: for they have perverted their way, and they have forgotten the LORD their God.",
    "Jeremiah 3:22": "Return, ye backsliding children, and I will heal your backslidings. Behold, we come unto thee; for thou art the LORD our God.",
    "Jeremiah 3:23": "Truly in vain is salvation hoped for from the hills, and from the multitude of mountains: truly in the LORD our God is the salvation of Israel.",
    "Jeremiah 3:24": "For shame hath devoured the labour of our fathers from our youth; their flocks and their herds, their sons and their daughters.",
    "Jeremiah 3:25": "We lie down in our shame, and our confusion covereth us: for we have sinned against the LORD our God, we and our fathers, from our youth even unto this day, and have not obeyed the voice of the LORD our God.",
    
    // Jeremiah 4 (King James Version)
    "Jeremiah 4:1": "If thou wilt return, O Israel, saith the LORD, return unto me: and if thou wilt put away thine abominations out of my sight, then shalt thou not remove.",
    "Jeremiah 4:2": "And thou shalt swear, The LORD liveth, in truth, in judgment, and in righteousness; and the nations shall bless themselves in him, and in him shall they glory.",
    "Jeremiah 4:3": "For thus saith the LORD to the men of Judah and Jerusalem, Break up your fallow ground, and sow not among thorns.",
    "Jeremiah 4:4": "Circumcise yourselves to the LORD, and take away the foreskins of your heart, ye men of Judah and inhabitants of Jerusalem: lest my fury come forth like fire, and burn that none can quench it, because of the evil of your doings.",
    "Jeremiah 4:5": "Declare ye in Judah, and publish in Jerusalem; and say, Blow ye the trumpet in the land: cry, gather together, and say, Assemble yourselves, and let us go into the defenced cities.",
    "Jeremiah 4:6": "Set up the standard toward Zion: retire, stay not: for I will bring evil from the north, and a great destruction.",
    "Jeremiah 4:7": "The lion is come up from his thicket, and the destroyer of the Gentiles is on his way; he is gone forth from his place to make thy land desolate; and thy cities shall be laid waste, without an inhabitant.",
    "Jeremiah 4:8": "For this gird you with sackcloth, lament and howl: for the fierce anger of the LORD is not turned back from us.",
    "Jeremiah 4:9": "And it shall come to pass at that day, saith the LORD, that the heart of the king shall perish, and the heart of the princes; and the priests shall be astonished, and the prophets shall wonder.",
    "Jeremiah 4:10": "Then said I, Ah, Lord GOD! surely thou hast greatly deceived this people and Jerusalem, saying, Ye shall have peace; whereas the sword reacheth unto the soul.",
    "Jeremiah 4:11": "At that time shall it be said to this people and to Jerusalem, A dry wind of the high places in the wilderness toward the daughter of my people, not to fan, nor to cleanse,",
    "Jeremiah 4:12": "Even a full wind from those places shall come unto me: now also will I give sentence against them.",
    "Jeremiah 4:13": "Behold, he shall come up as clouds, and his chariots shall be as a whirlwind: his horses are swifter than eagles. Woe unto us! for we are spoiled.",
    "Jeremiah 4:14": "O Jerusalem, wash thine heart from wickedness, that thou mayest be saved. How long shall thy vain thoughts lodge within thee?",
    "Jeremiah 4:15": "For a voice declareth from Dan, and publisheth affliction from mount Ephraim.",
    "Jeremiah 4:16": "Make ye mention to the nations; behold, publish against Jerusalem, that watchers come from a far country, and give out their voice against the cities of Judah.",
    "Jeremiah 4:17": "As keepers of a field, are they against her round about; because she hath been rebellious against me, saith the LORD.",
    "Jeremiah 4:18": "Thy way and thy doings have procured these things unto thee; this is thy wickedness, because it is bitter, because it reacheth unto thine heart.",
    "Jeremiah 4:19": "My bowels, my bowels! I am pained at my very heart; my heart maketh a noise in me; I cannot hold my peace, because thou hast heard, O my soul, the sound of the trumpet, the alarm of war.",
    "Jeremiah 4:20": "Destruction upon destruction is cried; for the whole land is spoiled: suddenly are my tents spoiled, and my curtains in a moment.",
    "Jeremiah 4:21": "How long shall I see the standard, and hear the sound of the trumpet?",
    "Jeremiah 4:22": "For my people is foolish, they have not known me; they are sottish children, and they have none understanding: they are wise to do evil, but to do good they have no knowledge.",
    "Jeremiah 4:23": "I beheld the earth, and, lo, it was without form, and void; and the heavens, and they had no light.",
    "Jeremiah 4:24": "I beheld the mountains, and, lo, they trembled, and all the hills moved lightly.",
    "Jeremiah 4:25": "I beheld, and, lo, there was no man, and all the birds of the heavens were fled.",
    "Jeremiah 4:26": "I beheld, and, lo, the fruitful place was a wilderness, and all the cities thereof were broken down at the presence of the LORD, and by his fierce anger.",
    "Jeremiah 4:27": "For thus hath the LORD said, The whole land shall be desolate; yet will I not make a full end.",
    "Jeremiah 4:28": "For this shall the earth mourn, and the heavens above be black: because I have spoken it, I have purposed it, and will not repent, neither will I turn back from it.",
    "Jeremiah 4:29": "The whole city shall flee for the noise of the horsemen and bowmen; they shall go into thickets, and climb up upon the rocks: every city shall be forsaken, and not a man dwell therein.",
    "Jeremiah 4:30": "And when thou art spoiled, what wilt thou do? Though thou clothest thyself with crimson, though thou deckest thee with ornaments of gold, though thou rentest thy face with painting, in vain shalt thou make thyself fair; thy lovers will despise thee, they will seek thy life.",
    "Jeremiah 4:31": "For I have heard a voice as of a woman in travail, and the anguish as of her that bringeth forth her first child, the voice of the daughter of Zion, that bewaileth herself, that spreadeth her hands, saying, Woe is me now! for my soul is wearied because of murderers.",
    
    // Jeremiah 5 (King James Version)
    "Jeremiah 5:1": "Run ye to and fro through the streets of Jerusalem, and see now, and know, and seek in the broad places thereof, if ye can find a man, if there be any that executeth judgment, that seeketh the truth; and I will pardon it.",
    "Jeremiah 5:2": "And though they say, The LORD liveth; surely they swear falsely.",
    "Jeremiah 5:3": "O LORD, are not thine eyes upon the truth? thou hast stricken them, but they have not grieved; thou hast consumed them, but they have refused to receive correction: they have made their faces harder than a rock; they have refused to return.",
    "Jeremiah 5:4": "Therefore I said, Surely these are poor; they are foolish: for they know not the way of the LORD, nor the judgment of their God.",
    "Jeremiah 5:5": "I will get me unto the great men, and will speak unto them; for they have known the way of the LORD, and the judgment of their God: but these have altogether broken the yoke, and burst the bonds.",
    "Jeremiah 5:6": "Wherefore a lion out of the forest shall slay them, and a wolf of the evenings shall spoil them, a leopard shall watch over their cities: every one that goeth out thence shall be torn in pieces: because their transgressions are many, and their backslidings are increased.",
    "Jeremiah 5:7": "How shall I pardon thee for this? thy children have forsaken me, and sworn by them that are no gods: when I had fed them to the full, they then committed adultery, and assembled themselves by troops in the harlots' houses.",
    "Jeremiah 5:8": "They were as fed horses in the morning: every one neighed after his neighbour's wife.",
    "Jeremiah 5:9": "Shall I not visit for these things? saith the LORD: and shall not my soul be avenged on such a nation as this?",
    "Jeremiah 5:10": "Go ye up upon her walls, and destroy; but make not a full end: take away her battlements; for they are not the LORD's.",
    "Jeremiah 5:11": "For the house of Israel and the house of Judah have dealt very treacherously against me, saith the LORD.",
    "Jeremiah 5:12": "They have belied the LORD, and said, It is not he; neither shall evil come upon us; neither shall we see sword nor famine:",
    "Jeremiah 5:13": "And the prophets shall become wind, and the word is not in them: thus shall it be done unto them.",
    "Jeremiah 5:14": "Wherefore thus saith the LORD God of hosts, Because ye speak this word, behold, I will make my words in thy mouth fire, and this people wood, and it shall devour them.",
    "Jeremiah 5:15": "Lo, I will bring a nation upon you from far, O house of Israel, saith the LORD: it is a mighty nation, it is an ancient nation, a nation whose language thou knowest not, neither understandest what they say.",
    "Jeremiah 5:16": "Their quiver is as an open sepulchre, they are all mighty men.",
    "Jeremiah 5:17": "And they shall eat up thine harvest, and thy bread, which thy sons and thy daughters should eat: they shall eat up thy flocks and thine herds: they shall eat up thy vines and thy fig trees: they shall impoverish thy fenced cities, wherein thou trustedst, with the sword.",
    "Jeremiah 5:18": "Nevertheless in those days, saith the LORD, I will not make a full end with you.",
    "Jeremiah 5:19": "And it shall come to pass, when ye shall say, Wherefore doeth the LORD our God all these things unto us? then shalt thou answer them, Like as ye have forsaken me, and served strange gods in your land, so shall ye serve strangers in a land that is not yours.",
    "Jeremiah 5:20": "Declare this in the house of Jacob, and publish it in Judah, saying,",
    "Jeremiah 5:21": "Hear now this, O foolish people, and without understanding; which have eyes, and see not; which have ears, and hear not:",
    "Jeremiah 5:22": "Fear ye not me? saith the LORD: will ye not tremble at my presence, which have placed the sand for the bound of the sea by a perpetual decree, that it cannot pass it: and though the waves thereof toss themselves, yet can they not prevail; though they roar, yet can they not pass over it?",
    "Jeremiah 5:23": "But this people hath a revolting and a rebellious heart; they are revolted and gone.",
    "Jeremiah 5:24": "Neither say they in their heart, Let us now fear the LORD our God, that giveth rain, both the former and the latter, in his season: he reserveth unto us the appointed weeks of the harvest.",
    "Jeremiah 5:25": "Your iniquities have turned away these things, and your sins have withholden good things from you.",
    "Jeremiah 5:26": "For among my people are found wicked men: they lay wait, as he that setteth snares; they set a trap, they catch men.",
    "Jeremiah 5:27": "As a cage is full of birds, so are their houses full of deceit: therefore they are become great, and waxen rich.",
    "Jeremiah 5:28": "They are waxen fat, they shine: yea, they overpass the deeds of the wicked: they judge not the cause, the cause of the fatherless, yet they prosper; and the right of the needy do they not judge.",
    "Jeremiah 5:29": "Shall I not visit for these things? saith the LORD: shall not my soul be avenged on such a nation as this?",
    "Jeremiah 5:30": "A wonderful and horrible thing is committed in the land;",
    "Jeremiah 5:31": "The prophets prophesy falsely, and the priests bear rule by their means; and my people love to have it so: and what will ye do in the end thereof?",
    
    // Jeremiah 6 (King James Version)
    "Jeremiah 6:1": "O ye children of Benjamin, gather yourselves to flee out of the midst of Jerusalem, and blow the trumpet in Tekoa, and set up a sign of fire in Beth-haccerem: for evil appeareth out of the north, and great destruction.",
    "Jeremiah 6:2": "I have likened the daughter of Zion to a comely and delicate woman.",
    "Jeremiah 6:3": "The shepherds with their flocks shall come unto her; they shall pitch their tents against her round about; they shall feed every one in his place.",
    "Jeremiah 6:4": "Prepare ye war against her; arise, and let us go up at noon. Woe unto us! for the day goeth away, for the shadows of the evening are stretched out.",
    "Jeremiah 6:5": "Arise, and let us go by night, and let us destroy her palaces.",
    "Jeremiah 6:6": "For thus hath the LORD of hosts said, Hew ye down trees, and cast a mount against Jerusalem: this is the city to be visited; she is wholly oppression in the midst of her.",
    "Jeremiah 6:7": "As a fountain casteth out her waters, so she casteth out her wickedness: violence and spoil is heard in her; before me continually is grief and wounds.",
    "Jeremiah 6:8": "Be thou instructed, O Jerusalem, lest my soul depart from thee; lest I make thee desolate, a land not inhabited.",
    "Jeremiah 6:9": "Thus saith the LORD of hosts, They shall throughly glean the remnant of Israel as a vine: turn back thine hand as a grapegatherer into the baskets.",
    "Jeremiah 6:10": "To whom shall I speak, and give warning, that they may hear? behold, their ear is uncircumcised, and they cannot hearken: behold, the word of the LORD is unto them a reproach; they have no delight in it.",
    "Jeremiah 6:11": "Therefore I am full of the fury of the LORD; I am weary with holding in: I will pour it out upon the children abroad, and upon the assembly of young men together: for even the husband with the wife shall be taken, the aged with him that is full of days.",
    "Jeremiah 6:12": "And their houses shall be turned unto others, with their fields and wives together: for I will stretch out my hand upon the inhabitants of the land, saith the LORD.",
    "Jeremiah 6:13": "For from the least of them even unto the greatest of them every one is given to covetousness; and from the prophet even unto the priest every one dealeth falsely.",
    "Jeremiah 6:14": "They have healed also the hurt of the daughter of my people slightly, saying, Peace, peace; when there is no peace.",
    "Jeremiah 6:15": "Were they ashamed when they had committed abomination? nay, they were not at all ashamed, neither could they blush: therefore they shall fall among them that fall: at the time that I visit them they shall be cast down, saith the LORD.",
    "Jeremiah 6:16": "Thus saith the LORD, Stand ye in the ways, and see, and ask for the old paths, where is the good way, and walk therein, and ye shall find rest for your souls. But they said, We will not walk therein.",
    "Jeremiah 6:17": "Also I set watchmen over you, saying, Hearken to the sound of the trumpet. But they said, We will not hearken.",
    "Jeremiah 6:18": "Therefore hear, ye nations, and know, O congregation, what is among them.",
    "Jeremiah 6:19": "Hear, O earth: behold, I will bring evil upon this people, even the fruit of their thoughts, because they have not hearkened unto my words, nor to my law, but rejected it.",
    "Jeremiah 6:20": "To what purpose cometh there to me incense from Sheba, and the sweet cane from a far country? your burnt offerings are not acceptable, nor your sacrifices sweet unto me.",
    "Jeremiah 6:21": "Therefore thus saith the LORD, Behold, I will lay stumblingblocks before this people, and the fathers and the sons together shall fall upon them; the neighbour and his friend shall perish.",
    "Jeremiah 6:22": "Thus saith the LORD, Behold, a people cometh from the north country, and a great nation shall be raised from the sides of the earth.",
    "Jeremiah 6:23": "They shall lay hold on bow and spear; they are cruel, and have no mercy; their voice roareth like the sea; and they ride upon horses, set in array as men for war against thee, O daughter of Zion.",
    "Jeremiah 6:24": "We have heard the fame thereof: our hands wax feeble: anguish hath taken hold of us, and pain, as of a woman in travail.",
    "Jeremiah 6:25": "Go not forth into the field, nor walk by the way; for the sword of the enemy and fear is on every side.",
    "Jeremiah 6:26": "O daughter of my people, gird thee with sackcloth, and wallow thyself in ashes: make thee mourning, as for an only son, most bitter lamentation: for the spoiler shall suddenly come upon us.",
    "Jeremiah 6:27": "I have set thee for a tower and a fortress among my people, that thou mayest know and try their way.",
    "Jeremiah 6:28": "They are all grievous revolters, walking with slanders: they are brass and iron; they are all corrupters.",
    "Jeremiah 6:29": "The bellows are burned, the lead is consumed of the fire; the founder melteth in vain: for the wicked are not plucked away.",
    "Jeremiah 6:30": "Reprobate silver shall men call them, because the LORD hath rejected them.",
    
    // Jeremiah 7 (King James Version)
    "Jeremiah 7:1": "The word that came to Jeremiah from the LORD, saying,",
    "Jeremiah 7:2": "Stand in the gate of the LORD'S house, and proclaim there this word, and say, Hear the word of the LORD, all ye of Judah, that enter in at these gates to worship the LORD.",
    "Jeremiah 7:3": "Thus saith the LORD of hosts, the God of Israel, Amend your ways and your doings, and I will cause you to dwell in this place.",
    "Jeremiah 7:4": "Trust ye not in lying words, saying, The temple of the LORD, The temple of the LORD, The temple of the LORD, are these.",
    "Jeremiah 7:5": "For if ye throughly amend your ways and your doings; if ye throughly execute judgment between a man and his neighbour;",
    "Jeremiah 7:6": "If ye oppress not the stranger, the fatherless, and the widow, and shed not innocent blood in this place, neither walk after other gods to your hurt:",
    "Jeremiah 7:7": "Then will I cause you to dwell in this place, in the land that I gave to your fathers, for ever and ever.",
    "Jeremiah 7:8": "Behold, ye trust in lying words, that cannot profit.",
    "Jeremiah 7:9": "Will ye steal, murder, and commit adultery, and swear falsely, and burn incense unto Baal, and walk after other gods whom ye know not;",
    "Jeremiah 7:10": "And come and stand before me in this house, which is called by my name, and say, We are delivered to do all these abominations?",
    "Jeremiah 7:11": "Is this house, which is called by my name, become a den of robbers in your eyes? Behold, even I have seen it, saith the LORD.",
    "Jeremiah 7:12": "But go ye now unto my place which was in Shiloh, where I set my name at the first, and see what I did to it for the wickedness of my people Israel.",
    "Jeremiah 7:13": "And now, because ye have done all these works, saith the LORD, and I spake unto you, rising up early and speaking, but ye heard not; and I called you, but ye answered not;",
    "Jeremiah 7:14": "Therefore will I do unto this house, which is called by my name, wherein ye trust, and unto the place which I gave to you and to your fathers, as I have done to Shiloh.",
    "Jeremiah 7:15": "And I will cast you out of my sight, as I have cast out all your brethren, even the whole seed of Ephraim.",
    "Jeremiah 7:16": "Therefore pray not thou for this people, neither lift up cry nor prayer for them, neither make intercession to me: for I will not hear thee.",
    "Jeremiah 7:17": "Seest thou not what they do in the cities of Judah and in the streets of Jerusalem?",
    "Jeremiah 7:18": "The children gather wood, and the fathers kindle the fire, and the women knead their dough, to make cakes to the queen of heaven, and to pour out drink offerings unto other gods, that they may provoke me to anger.",
    "Jeremiah 7:19": "Do they provoke me to anger? saith the LORD: do they not provoke themselves to the confusion of their own faces?",
    "Jeremiah 7:20": "Therefore thus saith the Lord GOD; Behold, mine anger and my fury shall be poured out upon this place, upon man, and upon beast, and upon the trees of the field, and upon the fruit of the ground; and it shall burn, and shall not be quenched.",
    "Jeremiah 7:21": "Thus saith the LORD of hosts, the God of Israel; Put your burnt offerings unto your sacrifices, and eat flesh.",
    "Jeremiah 7:22": "For I spake not unto your fathers, nor commanded them in the day that I brought them out of the land of Egypt, concerning burnt offerings or sacrifices:",
    "Jeremiah 7:23": "But this thing commanded I them, saying, Obey my voice, and I will be your God, and ye shall be my people: and walk ye in all the ways that I have commanded you, that it may be well unto you.",
    "Jeremiah 7:24": "But they hearkened not, nor inclined their ear, but walked in the counsels and in the imagination of their evil heart, and went backward, and not forward.",
    "Jeremiah 7:25": "Since the day that your fathers came forth out of the land of Egypt unto this day I have even sent unto you all my servants the prophets, daily rising up early and sending them:",
    "Jeremiah 7:26": "Yet they hearkened not unto me, nor inclined their ear, but hardened their neck: they did worse than their fathers.",
    "Jeremiah 7:27": "Therefore thou shalt speak all these words unto them; but they will not hearken to thee: thou shalt also call unto them; but they will not answer thee.",
    "Jeremiah 7:28": "But thou shalt say unto them, This is a nation that obeyeth not the voice of the LORD their God, nor receiveth correction: truth is perished, and is cut off from their mouth.",
    "Jeremiah 7:29": "Cut off thine hair, O Jerusalem, and cast it away, and take up a lamentation on high places; for the LORD hath rejected and forsaken the generation of his wrath.",
    "Jeremiah 7:30": "For the children of Judah have done evil in my sight, saith the LORD: they have set their abominations in the house which is called by my name, to pollute it.",
    "Jeremiah 7:31": "And they have built the high places of Tophet, which is in the valley of the son of Hinnom, to burn their sons and their daughters in the fire; which I commanded them not, neither came it into my heart.",
    "Jeremiah 7:32": "Therefore, behold, the days come, saith the LORD, that it shall no more be called Tophet, nor the valley of the son of Hinnom, but the valley of slaughter: for they shall bury in Tophet, till there be no place.",
    "Jeremiah 7:33": "And the carcases of this people shall be meat for the fowls of the heaven, and for the beasts of the earth; and none shall fray them away.",
    "Jeremiah 7:34": "Then will I cause to cease from the cities of Judah, and from the streets of Jerusalem, the voice of mirth, and the voice of gladness, the voice of the bridegroom, and the voice of the bride: for the land shall be desolate.",
    
    // Jeremiah 8 (King James Version)
    "Jeremiah 8:1": "At that time, saith the LORD, they shall bring out the bones of the kings of Judah, and the bones of his princes, and the bones of the priests, and the bones of the prophets, and the bones of the inhabitants of Jerusalem, out of their graves:",
    "Jeremiah 8:2": "And they shall spread them before the sun, and the moon, and all the host of heaven, whom they have loved, and whom they have served, and after whom they have walked, and whom they have sought, and whom they have worshipped: they shall not be gathered, nor be buried; they shall be for dung upon the face of the earth.",
    "Jeremiah 8:3": "And death shall be chosen rather than life by all the residue of them that remain of this evil family, which remain in all the places whither I have driven them, saith the LORD of hosts.",
    "Jeremiah 8:4": "Moreover thou shalt say unto them, Thus saith the LORD; Shall they fall, and not arise? shall he turn away, and not return?",
    "Jeremiah 8:5": "Why then is this people of Jerusalem slidden back by a perpetual backsliding? they hold fast deceit, they refuse to return.",
    "Jeremiah 8:6": "I hearkened and heard, but they spake not aright: no man repented him of his wickedness, saying, What have I done? every one turned to his course, as the horse rusheth into the battle.",
    "Jeremiah 8:7": "Yea, the stork in the heaven knoweth her appointed times; and the turtle and the crane and the swallow observe the time of their coming; but my people know not the judgment of the LORD.",
    "Jeremiah 8:8": "How do ye say, We are wise, and the law of the LORD is with us? Lo, certainly in vain made he it; the pen of the scribes is in vain.",
    "Jeremiah 8:9": "The wise men are ashamed, they are dismayed and taken: lo, they have rejected the word of the LORD; and what wisdom is in them?",
    "Jeremiah 8:10": "Therefore will I give their wives unto others, and their fields to them that shall inherit them: for every one from the least even unto the greatest is given to covetousness, from the prophet even unto the priest every one dealeth falsely.",
    "Jeremiah 8:11": "For they have healed the hurt of the daughter of my people slightly, saying, Peace, peace; when there is no peace.",
    "Jeremiah 8:12": "Were they ashamed when they had committed abomination? nay, they were not at all ashamed, neither could they blush: therefore shall they fall among them that fall: in the time of their visitation they shall be cast down, saith the LORD.",
    "Jeremiah 8:13": "I will surely consume them, saith the LORD: there shall be no grapes on the vine, nor figs on the fig tree, and the leaf shall fade; and the things that I have given them shall pass away from them.",
    "Jeremiah 8:14": "Why do we sit still? assemble yourselves, and let us enter into the defenced cities, and let us be silent there: for the LORD our God hath put us to silence, and given us water of gall to drink, because we have sinned against the LORD.",
    "Jeremiah 8:15": "We looked for peace, but no good came; and for a time of health, and behold trouble!",
    "Jeremiah 8:16": "The snorting of his horses was heard from Dan: the whole land trembled at the sound of the neighing of his strong ones; for they are come, and have devoured the land, and all that is in it; the city, and those that dwell therein.",
    "Jeremiah 8:17": "For, behold, I will send serpents, cockatrices, among you, which will not be charmed, and they shall bite you, saith the LORD.",
    "Jeremiah 8:18": "When I would comfort myself against sorrow, my heart is faint in me.",
    "Jeremiah 8:19": "Behold the voice of the cry of the daughter of my people because of them that dwell in a far country: Is not the LORD in Zion? is not her king in her? Why have they provoked me to anger with their graven images, and with strange vanities?",
    "Jeremiah 8:20": "The harvest is past, the summer is ended, and we are not saved.",
    "Jeremiah 8:21": "For the hurt of the daughter of my people am I hurt; I am black; astonishment hath taken hold on me.",
    "Jeremiah 8:22": "Is there no balm in Gilead; is there no physician there? why then is not the health of the daughter of my people recovered?",
    
    // Jeremiah 9 (King James Version)
    "Jeremiah 9:1": "Oh that my head were waters, and mine eyes a fountain of tears, that I might weep day and night for the slain of the daughter of my people!",
    "Jeremiah 9:2": "Oh that I had in the wilderness a lodging place of wayfaring men; that I might leave my people, and go from them! for they be all adulterers, an assembly of treacherous men.",
    "Jeremiah 9:3": "And they bend their tongues like their bow for lies: but they are not valiant for the truth upon the earth; for they proceed from evil to evil, and they know not me, saith the LORD.",
    "Jeremiah 9:4": "Take ye heed every one of his neighbour, and trust ye not in any brother: for every brother will utterly supplant, and every neighbour will walk with slanders.",
    "Jeremiah 9:5": "And they will deceive every one his neighbour, and will not speak the truth: they have taught their tongue to speak lies, and weary themselves to commit iniquity.",
    "Jeremiah 9:6": "Thine habitation is in the midst of deceit; through deceit they refuse to know me, saith the LORD.",
    "Jeremiah 9:7": "Therefore thus saith the LORD of hosts, Behold, I will melt them, and try them; for how shall I do for the daughter of my people?",
    "Jeremiah 9:8": "Their tongue is as an arrow shot out; it speaketh deceit: one speaketh peaceably to his neighbour with his mouth, but in heart he layeth his wait.",
    "Jeremiah 9:9": "Shall I not visit them for these things? saith the LORD: shall not my soul be avenged on such a nation as this?",
    "Jeremiah 9:10": "For the mountains will I take up a weeping and wailing, and for the habitations of the wilderness a lamentation, because they are burned up, so that none can pass through them; neither can men hear the voice of the cattle; both the fowl of the heavens and the beast are fled; they are gone.",
    "Jeremiah 9:11": "And I will make Jerusalem heaps, and a den of dragons; and I will make the cities of Judah desolate, without an inhabitant.",
    "Jeremiah 9:12": "Who is the wise man, that may understand this? and who is he to whom the mouth of the LORD hath spoken, that he may declare it, for what the land perisheth and is burned up like a wilderness, that none passeth through?",
    "Jeremiah 9:13": "And the LORD saith, Because they have forsaken my law which I set before them, and have not obeyed my voice, neither walked therein;",
    "Jeremiah 9:14": "But have walked after the imagination of their own heart, and after Baalim, which their fathers taught them:",
    "Jeremiah 9:15": "Therefore thus saith the LORD of hosts, the God of Israel; Behold, I will feed them, even this people, with wormwood, and give them water of gall to drink.",
    "Jeremiah 9:16": "I will scatter them also among the heathen, whom neither they nor their fathers have known: and I will send a sword after them, till I have consumed them.",
    "Jeremiah 9:17": "Thus saith the LORD of hosts, Consider ye, and call for the mourning women, that they may come; and send for cunning women, that they may come:",
    "Jeremiah 9:18": "And let them make haste, and take up a wailing for us, that our eyes may run down with tears, and our eyelids gush out with waters.",
    "Jeremiah 9:19": "For a voice of wailing is heard out of Zion, How are we spoiled! we are greatly confounded, because we have forsaken the land, because our dwellings have cast us out.",
    "Jeremiah 9:20": "Yet hear the word of the LORD, O ye women, and let your ear receive the word of his mouth, and teach your daughters wailing, and every one her neighbour lamentation.",
    "Jeremiah 9:21": "For death is come up into our windows, and is entered into our palaces, to cut off the children from without, and the young men from the streets.",
    "Jeremiah 9:22": "Speak, Thus saith the LORD, Even the carcases of men shall fall as dung upon the open field, and as the handful after the harvestman, and none shall gather them.",
    "Jeremiah 9:23": "Thus saith the LORD, Let not the wise man glory in his wisdom, neither let the mighty man glory in his might, let not the rich man glory in his riches:",
    "Jeremiah 9:24": "But let him that glorieth glory in this, that he understandeth and knoweth me, that I am the LORD which exercise lovingkindness, judgment, and righteousness, in the earth: for in these things I delight, saith the LORD.",
    "Jeremiah 9:25": "Behold, the days come, saith the LORD, that I will punish all them which are circumcised with the uncircumcised;",
    "Jeremiah 9:26": "Egypt, and Judah, and Edom, and the children of Ammon, and Moab, and all that are in the utmost corners, that dwell in the wilderness: for all these nations are uncircumcised, and all the house of Israel are uncircumcised in the heart.",
    
    // Jeremiah 10 (King James Version)
    "Jeremiah 10:1": "Hear ye the word which the LORD speaketh unto you, O house of Israel:",
    "Jeremiah 10:2": "Thus saith the LORD, Learn not the way of the heathen, and be not dismayed at the signs of heaven; for the heathen are dismayed at them.",
    "Jeremiah 10:3": "For the customs of the people are vain: for one cutteth a tree out of the forest, the work of the hands of the workman, with the axe.",
    "Jeremiah 10:4": "They deck it with silver and with gold; they fasten it with nails and with hammers, that it move not.",
    "Jeremiah 10:5": "They are upright as the palm tree, but speak not: they must needs be borne, because they cannot go. Be not afraid of them; for they cannot do evil, neither also is it in them to do good.",
    "Jeremiah 10:6": "Forasmuch as there is none like unto thee, O LORD; thou art great, and thy name is great in might.",
    "Jeremiah 10:7": "Who would not fear thee, O King of nations? for to thee doth it appertain: forasmuch as among all the wise men of the nations, and in all their kingdoms, there is none like unto thee.",
    "Jeremiah 10:8": "But they are altogether brutish and foolish: the stock is a doctrine of vanities.",
    "Jeremiah 10:9": "Silver spread into plates is brought from Tarshish, and gold from Uphaz, the work of the workman, and of the hands of the founder: blue and purple is their clothing: they are all the work of cunning men.",
    "Jeremiah 10:10": "But the LORD is the true God, he is the living God, and an everlasting king: at his wrath the earth shall tremble, and the nations shall not be able to abide his indignation.",
    "Jeremiah 10:11": "Thus shall ye say unto them, The gods that have not made the heavens and the earth, even they shall perish from the earth, and from under these heavens.",
    "Jeremiah 10:12": "He hath made the earth by his power, he hath established the world by his wisdom, and hath stretched out the heavens by his discretion.",
    "Jeremiah 10:13": "When he uttereth his voice, there is a multitude of waters in the heavens, and he causeth the vapours to ascend from the ends of the earth; he maketh lightnings with rain, and bringeth forth the wind out of his treasures.",
    "Jeremiah 10:14": "Every man is brutish in his knowledge: every founder is confounded by the graven image: for his molten image is falsehood, and there is no breath in them.",
    "Jeremiah 10:15": "They are vanity, and the work of errors: in the time of their visitation they shall perish.",
    "Jeremiah 10:16": "The portion of Jacob is not like them: for he is the former of all things; and Israel is the rod of his inheritance: The LORD of hosts is his name.",
    "Jeremiah 10:17": "Gather up thy wares out of the land, O inhabitant of the fortress.",
    "Jeremiah 10:18": "For thus saith the LORD, Behold, I will sling out the inhabitants of the land at this once, and will distress them, that they may find it so.",
    "Jeremiah 10:19": "Woe is me for my hurt! my wound is grievous: but I said, Truly this is a grief, and I must bear it.",
    "Jeremiah 10:20": "My tabernacle is spoiled, and all my cords are broken: my children are gone forth of me, and they are not: there is none to stretch forth my tent any more, and to set up my curtains.",
    "Jeremiah 10:21": "For the pastors are become brutish, and have not sought the LORD: therefore they shall not prosper, and all their flocks shall be scattered.",
    "Jeremiah 10:22": "Behold, the noise of the bruit is come, and a great commotion out of the north country, to make the cities of Judah desolate, and a den of dragons.",
    "Jeremiah 10:23": "O LORD, I know that the way of man is not in himself: it is not in man that walketh to direct his steps.",
    "Jeremiah 10:24": "O LORD, correct me, but with judgment; not in thine anger, lest thou bring me to nothing.",
    "Jeremiah 10:25": "Pour out thy fury upon the heathen that know thee not, and upon the families that call not on thy name: for they have eaten up Jacob, and devoured him, and consumed him, and have made his habitation desolate.",
    
};