const bibleVerses4 = {
    // Mark 1 (King James Version)
    "Mark 1:1": "The beginning of the gospel of Jesus Christ, the Son of God;",
    "Mark 1:2": "As it is written in the prophets, Behold, I send my messenger before thy face, which shall prepare thy way before thee.",
    "Mark 1:3": "The voice of one crying in the wilderness, Prepare ye the way of the Lord, make his paths straight.",
    "Mark 1:4": "John did baptize in the wilderness, and preach the baptism of repentance for the remission of sins.",
    "Mark 1:5": "And there went out unto him all the land of Judaea, and they of Jerusalem, and were all baptized of him in the river of Jordan, confessing their sins.",
    "Mark 1:6": "And John was clothed with camel's hair, and with a girdle of a skin about his loins; and he did eat locusts and wild honey;",
    "Mark 1:7": "And preached, saying, There cometh one mightier than I after me, the latchet of whose shoes I am not worthy to stoop down and unloose.",
    "Mark 1:8": "I indeed have baptized you with water: but he shall baptize you with the Holy Ghost.",
    "Mark 1:9": "And it came to pass in those days, that Jesus came from Nazareth of Galilee, and was baptized of John in Jordan.",
    "Mark 1:10": "And straightway coming up out of the water, he saw the heavens opened, and the Spirit like a dove descending upon him:",
    "Mark 1:11": "And there came a voice from heaven, saying, Thou art my beloved Son, in whom I am well pleased.",
    "Mark 1:12": "And immediately the Spirit driveth him into the wilderness.",
    "Mark 1:13": "And he was there in the wilderness forty days, tempted of Satan; and was with the wild beasts; and the angels ministered unto him.",
    "Mark 1:14": "Now after that John was put in prison, Jesus came into Galilee, preaching the gospel of the kingdom of God,",
    "Mark 1:15": "And saying, The time is fulfilled, and the kingdom of God is at hand: repent ye, and believe the gospel.",
    "Mark 1:16": "Now as he walked by the sea of Galilee, he saw Simon and Andrew his brother casting a net into the sea: for they were fishers.",
    "Mark 1:17": "And Jesus said unto them, Come ye after me, and I will make you to become fishers of men.",
    "Mark 1:18": "And straightway they forsook their nets, and followed him.",
    "Mark 1:19": "And when he had gone a little farther thence, he saw James the son of Zebedee, and John his brother, who also were in the ship mending their nets.",
    "Mark 1:20": "And straightway he called them: and they left their father Zebedee in the ship with the hired servants, and went after him.",
    "Mark 1:21": "And they went into Capernaum; and straightway on the sabbath day he entered into the synagogue, and taught.",
    "Mark 1:22": "And they were astonished at his doctrine: for he taught them as one that had authority, and not as the scribes.",
    "Mark 1:23": "And there was in their synagogue a man with an unclean spirit; and he cried out,",
    "Mark 1:24": "Saying, Let us alone; what have we to do with thee, thou Jesus of Nazareth? art thou come to destroy us? I know thee who thou art, the Holy One of God.",
    "Mark 1:25": "And Jesus rebuked him, saying, Hold thy peace, and come out of him.",
    "Mark 1:26": "And when the unclean spirit had torn him, and cried with a loud voice, he came out of him.",
    "Mark 1:27": "And they were all amazed, insomuch that they questioned among themselves, saying, What thing is this? what new doctrine is this? for with authority commandeth he even the unclean spirits, and they do obey him.",
    "Mark 1:28": "And immediately his fame spread abroad throughout all the region round about Galilee.",
    "Mark 1:29": "And forthwith, when they were come out of the synagogue, they entered into the house of Simon and Andrew, with James and John.",
    "Mark 1:30": "But Simon's wife's mother lay sick of a fever, and anon they tell him of her.",
    "Mark 1:31": "And he came and took her by the hand, and lifted her up; and immediately the fever left her, and she ministered unto them.",
    "Mark 1:32": "And at even, when the sun did set, they brought unto him all that were diseased, and them that were possessed with devils.",
    "Mark 1:33": "And all the city was gathered together at the door.",
    "Mark 1:34": "And he healed many that were sick of divers diseases, and cast out many devils; and suffered not the devils to speak, because they knew him.",
    "Mark 1:35": "And in the morning, rising up a great while before day, he went out, and departed into a solitary place, and there prayed.",
    "Mark 1:36": "And Simon and they that were with him followed after him.",
    "Mark 1:37": "And when they had found him, they said unto him, All men seek for thee.",
    "Mark 1:38": "And he said unto them, Let us go into the next towns, that I may preach there also: for therefore came I forth.",
    "Mark 1:39": "And he preached in their synagogues throughout all Galilee, and cast out devils.",
    "Mark 1:40": "And there came a leper to him, beseeching him, and kneeling down to him, and saying unto him, If thou wilt, thou canst make me clean.",
    "Mark 1:41": "And Jesus, moved with compassion, put forth his hand, and touched him, and saith unto him, I will; be thou clean.",
    "Mark 1:42": "And as soon as he had spoken, immediately the leprosy departed from him, and he was cleansed.",
    "Mark 1:43": "And he straitly charged him, and forthwith sent him away;",
    "Mark 1:44": "And saith unto him, See thou say nothing to any man: but go thy way, shew thyself to the priest, and offer for thy cleansing those things which Moses commanded, for a testimony unto them.",
    "Mark 1:45": "But he went out, and began to publish it much, and to blaze abroad the matter, insomuch that Jesus could no more openly enter into the city, but was without in desert places: and they came to him from every quarter.",
    
    // Mark 2 (King James Version)
    "Mark 2:1": "And again he entered into Capernaum after some days; and it was noised that he was in the house.",
    "Mark 2:2": "And straightway many were gathered together, insomuch that there was no room to receive them, no, not so much as about the door: and he preached the word unto them.",
    "Mark 2:3": "And they come unto him, bringing one sick of the palsy, which was borne of four.",
    "Mark 2:4": "And when they could not come nigh unto him for the press, they uncovered the roof where he was: and when they had broken it up, they let down the bed wherein the sick of the palsy lay.",
    "Mark 2:5": "When Jesus saw their faith, he said unto the sick of the palsy, Son, thy sins be forgiven thee.",
    "Mark 2:6": "But there were certain of the scribes sitting there, and reasoning in their hearts,",
    "Mark 2:7": "Why doth this man thus speak blasphemies? who can forgive sins but God only?",
    "Mark 2:8": "And immediately when Jesus perceived in his spirit that they so reasoned within themselves, he said unto them, Why reason ye these things in your hearts?",
    "Mark 2:9": "Whether is it easier to say to the sick of the palsy, Thy sins be forgiven thee; or to say, Arise, and take up thy bed, and walk?",
    "Mark 2:10": "But that ye may know that the Son of man hath power on earth to forgive sins, (he saith to the sick of the palsy,)",
    "Mark 2:11": "I say unto thee, Arise, and take up thy bed, and go thy way into thine house.",
    "Mark 2:12": "And immediately he arose, took up the bed, and went forth before them all; insomuch that they were all amazed, and glorified God, saying, We never saw it on this fashion.",
    "Mark 2:13": "And he went forth again by the sea side; and all the multitude resorted unto him, and he taught them.",
    "Mark 2:14": "And as he passed by, he saw Levi the son of Alphaeus sitting at the receipt of custom, and said unto him, Follow me. And he arose and followed him.",
    "Mark 2:15": "And it came to pass, that, as Jesus sat at meat in his house, many publicans and sinners sat also together with Jesus and his disciples: for there were many, and they followed him.",
    "Mark 2:16": "And when the scribes and Pharisees saw him eat with publicans and sinners, they said unto his disciples, How is it that he eateth and drinketh with publicans and sinners?",
    "Mark 2:17": "When Jesus heard it, he saith unto them, They that are whole have no need of the physician, but they that are sick: I came not to call the righteous, but sinners to repentance.",
    "Mark 2:18": "And the disciples of John and of the Pharisees used to fast: and they come and say unto him, Why do the disciples of John and of the Pharisees fast, but thy disciples fast not?",
    "Mark 2:19": "And Jesus said unto them, Can the children of the bridechamber fast, while the bridegroom is with them? as long as they have the bridegroom with them, they cannot fast.",
    "Mark 2:20": "But the days will come, when the bridegroom shall be taken away from them, and then shall they fast in those days.",
    "Mark 2:21": "No man also seweth a piece of new cloth on an old garment: else the new piece that filled it up taketh away from the old, and the rent is made worse.",
    "Mark 2:22": "And no man putteth new wine into old bottles: else the new wine doth burst the bottles, and the wine is spilled, and the bottles will be marred: but new wine must be put into new bottles.",
    "Mark 2:23": "And it came to pass, that he went through the corn fields on the sabbath day; and his disciples began, as they went, to pluck the ears of corn.",
    "Mark 2:24": "And the Pharisees said unto him, Behold, why do they on the sabbath day that which is not lawful?",
    "Mark 2:25": "And he said unto them, Have ye never read what David did, when he had need, and was an hungred, he, and they that were with him?",
    "Mark 2:26": "How he went into the house of God in the days of Abiathar the high priest, and did eat the shewbread, which is not lawful to eat but for the priests, and gave also to them which were with him?",
    "Mark 2:27": "And he said unto them, The sabbath was made for man, and not man for the sabbath:",
    "Mark 2:28": "Therefore the Son of man is Lord also of the sabbath.",
    
    // Mark 3 (King James Version)
    "Mark 3:1": "And he entered again into the synagogue; and there was a man there which had a withered hand.",
    "Mark 3:2": "And they watched him, whether he would heal him on the sabbath day; that they might accuse him.",
    "Mark 3:3": "And he saith unto the man which had the withered hand, Stand forth.",
    "Mark 3:4": "And he saith unto them, Is it lawful to do good on the sabbath days, or to do evil? to save life, or to kill? But they held their peace.",
    "Mark 3:5": "And when he had looked round about on them with anger, being grieved for the hardness of their hearts, he saith unto the man, Stretch forth thine hand. And he stretched it out: and his hand was restored whole as the other.",
    "Mark 3:6": "And the Pharisees went forth, and straightway took counsel with the Herodians against him, how they might destroy him.",
    "Mark 3:7": "But Jesus withdrew himself with his disciples to the sea: and a great multitude from Galilee followed him, and from Judaea,",
    "Mark 3:8": "And from Jerusalem, and from Idumaea, and from beyond Jordan; and they about Tyre and Sidon, a great multitude, when they had heard what great things he did, came unto him.",
    "Mark 3:9": "And he spake to his disciples, that a small ship should wait on him because of the multitude, lest they should throng him.",
    "Mark 3:10": "For he had healed many; insomuch that they pressed upon him for to touch him, as many as had plagues.",
    "Mark 3:11": "And unclean spirits, when they saw him, fell down before him, and cried, saying, Thou art the Son of God.",
    "Mark 3:12": "And he straitly charged them that they should not make him known.",
    "Mark 3:13": "And he goeth up into a mountain, and calleth unto him whom he would: and they came unto him.",
    "Mark 3:14": "And he ordained twelve, that they should be with him, and that he might send them forth to preach,",
    "Mark 3:15": "And to have power to heal sicknesses, and to cast out devils:",
    "Mark 3:16": "And Simon he surnamed Peter;",
    "Mark 3:17": "And James the son of Zebedee, and John the brother of James; and he surnamed them Boanerges, which is, The sons of thunder:",
    "Mark 3:18": "And Andrew, and Philip, and Bartholomew, and Matthew, and Thomas, and James the son of Alphaeus, and Thaddaeus, and Simon the Canaanite,",
    "Mark 3:19": "And Judas Iscariot, which also betrayed him: and they went into an house.",
    "Mark 3:20": "And the multitude cometh together again, so that they could not so much as eat bread.",
    "Mark 3:21": "And when his friends heard of it, they went out to lay hold on him: for they said, He is beside himself.",
    "Mark 3:22": "And the scribes which came down from Jerusalem said, He hath Beelzebub, and by the prince of the devils casteth he out devils.",
    "Mark 3:23": "And he called them unto him, and said unto them in parables, How can Satan cast out Satan?",
    "Mark 3:24": "And if a kingdom be divided against itself, that kingdom cannot stand.",
    "Mark 3:25": "And if a house be divided against itself, that house cannot stand.",
    "Mark 3:26": "And if Satan rise up against himself, and be divided, he cannot stand, but hath an end.",
    "Mark 3:27": "No man can enter into a strong man's house, and spoil his goods, except he will first bind the strong man; and then he will spoil his house.",
    "Mark 3:28": "Verily I say unto you, All sins shall be forgiven unto the sons of men, and blasphemies wherewith soever they shall blaspheme:",
    "Mark 3:29": "But he that shall blaspheme against the Holy Ghost hath never forgiveness, but is in danger of eternal damnation:",
    "Mark 3:30": "Because they said, He hath an unclean spirit.",
    "Mark 3:31": "There came then his brethren and his mother, and, standing without, sent unto him, calling him.",
    "Mark 3:32": "And the multitude sat about him, and they said unto him, Behold, thy mother and thy brethren without seek for thee.",
    "Mark 3:33": "And he answered them, saying, Who is my mother, or my brethren?",
    "Mark 3:34": "And he looked round about on them which sat about him, and said, Behold my mother and my brethren!",
    "Mark 3:35": "For whosoever shall do the will of God, the same is my brother, and my sister, and mother.",
    
    // Mark 4 (King James Version)
    "Mark 4:1": "And he began again to teach by the sea side: and there was gathered unto him a great multitude, so that he entered into a ship, and sat in the sea; and the whole multitude was by the sea on the land.",
    "Mark 4:2": "And he taught them many things by parables, and said unto them in his doctrine,",
    "Mark 4:3": "Hearken; Behold, there went out a sower to sow:",
    "Mark 4:4": "And it came to pass, as he sowed, some fell by the way side, and the fowls of the air came and devoured it up.",
    "Mark 4:5": "And some fell on stony ground, where it had not much earth; and immediately it sprang up, because it had no depth of earth:",
    "Mark 4:6": "But when the sun was up, it was scorched; and because it had no root, it withered away.",
    "Mark 4:7": "And some fell among thorns, and the thorns grew up, and choked it, and it yielded no fruit.",
    "Mark 4:8": "And other fell on good ground, and did yield fruit that sprang up and increased; and brought forth, some thirty, and some sixty, and some an hundred.",
    "Mark 4:9": "And he said unto them, He that hath ears to hear, let him hear.",
    "Mark 4:10": "And when he was alone, they that were about him with the twelve asked of him the parable.",
    "Mark 4:11": "And he said unto them, Unto you it is given to know the mystery of the kingdom of God: but unto them that are without, all these things are done in parables:",
    "Mark 4:12": "That seeing they may see, and not perceive; and hearing they may hear, and not understand; lest at any time they should be converted, and their sins should be forgiven them.",
    "Mark 4:13": "And he said unto them, Know ye not this parable? and how then will ye know all parables?",
    "Mark 4:14": "The sower soweth the word.",
    "Mark 4:15": "And these are they by the way side, where the word is sown; but when they have heard, Satan cometh immediately, and taketh away the word that was sown in their hearts.",
    "Mark 4:16": "And these are they likewise which are sown on stony ground; who, when they have heard the word, immediately receive it with gladness;",
    "Mark 4:17": "And have no root in themselves, and so endure but for a time: afterward, when affliction or persecution ariseth for the word's sake, immediately they are offended.",
    "Mark 4:18": "And these are they which are sown among thorns; such as hear the word,",
    "Mark 4:19": "And the cares of this world, and the deceitfulness of riches, and the lusts of other things entering in, choke the word, and it becometh unfruitful.",
    "Mark 4:20": "And these are they which are sown on good ground; such as hear the word, and receive it, and bring forth fruit, some thirtyfold, some sixty, and some an hundred.",
    "Mark 4:21": "And he said unto them, Is a candle brought to be put under a bushel, or under a bed? and not to be set on a candlestick?",
    "Mark 4:22": "For there is nothing hid, which shall not be manifested; neither was any thing kept secret, but that it should come abroad.",
    "Mark 4:23": "If any man have ears to hear, let him hear.",
    "Mark 4:24": "And he said unto them, Take heed what ye hear: with what measure ye mete, it shall be measured to you: and unto you that hear shall more be given.",
    "Mark 4:25": "For he that hath, to him shall be given: and he that hath not, from him shall be taken even that which he hath.",
    "Mark 4:26": "And he said, So is the kingdom of God, as if a man should cast seed into the ground;",
    "Mark 4:27": "And should sleep, and rise night and day, and the seed should spring and grow up, he knoweth not how.",
    "Mark 4:28": "For the earth bringeth forth fruit of herself; first the blade, then the ear, after that the full corn in the ear.",
    "Mark 4:29": "But when the fruit is brought forth, immediately he putteth in the sickle, because the harvest is come.",
    "Mark 4:30": "And he said, Whereunto shall we liken the kingdom of God? or with what comparison shall we compare it?",
    "Mark 4:31": "It is like a grain of mustard seed, which, when it is sown in the earth, is less than all the seeds that be in the earth:",
    "Mark 4:32": "But when it is sown, it groweth up, and becometh greater than all herbs, and shooteth out great branches; so that the fowls of the air may lodge under the shadow of it.",
    "Mark 4:33": "And with many such parables spake he the word unto them, as they were able to hear it.",
    "Mark 4:34": "But without a parable spake he not unto them: and when they were alone, he expounded all things to his disciples.",
    "Mark 4:35": "And the same day, when the even was come, he saith unto them, Let us pass over unto the other side.",
    "Mark 4:36": "And when they had sent away the multitude, they took him even as he was in the ship. And there were also with him other little ships.",
    "Mark 4:37": "And there arose a great storm of wind, and the waves beat into the ship, so that it was now full.",
    "Mark 4:38": "And he was in the hinder part of the ship, asleep on a pillow: and they awake him, and say unto him, Master, carest thou not that we perish?",
    "Mark 4:39": "And he arose, and rebuked the wind, and said unto the sea, Peace, be still. And the wind ceased, and there was a great calm.",
    "Mark 4:40": "And he said unto them, Why are ye so fearful? how is it that ye have no faith?",
    "Mark 4:41": "And they feared exceedingly, and said one to another, What manner of man is this, that even the wind and the sea obey him?",
    
    // Mark 5 (King James Version)
    "Mark 5:1": "And they came over unto the other side of the sea, into the country of the Gadarenes.",
    "Mark 5:2": "And when he was come out of the ship, immediately there met him out of the tombs a man with an unclean spirit,",
    "Mark 5:3": "Who had his dwelling among the tombs; and no man could bind him, no, not with chains:",
    "Mark 5:4": "Because that he had been often bound with fetters and chains, and the chains had been plucked asunder by him, and the fetters broken in pieces: neither could any man tame him.",
    "Mark 5:5": "And always, night and day, he was in the mountains, and in the tombs, crying, and cutting himself with stones.",
    "Mark 5:6": "But when he saw Jesus afar off, he ran and worshipped him,",
    "Mark 5:7": "And cried with a loud voice, and said, What have I to do with thee, Jesus, thou Son of the most high God? I adjure thee by God, that thou torment me not.",
    "Mark 5:8": "For he said unto him, Come out of the man, thou unclean spirit.",
    "Mark 5:9": "And he asked him, What is thy name? And he answered, saying, My name is Legion: for we are many.",
    "Mark 5:10": "And he besought him much that he would not send them away out of the country.",
    "Mark 5:11": "Now there was there nigh unto the mountains a great herd of swine feeding.",
    "Mark 5:12": "And all the devils besought him, saying, Send us into the swine, that we may enter into them.",
    "Mark 5:13": "And forthwith Jesus gave them leave. And the unclean spirits went out, and entered into the swine: and the herd ran violently down a steep place into the sea, (they were about two thousand;) and were choked in the sea.",
    "Mark 5:14": "And they that fed the swine fled, and told it in the city, and in the country. And they went out to see what it was that was done.",
    "Mark 5:15": "And they come to Jesus, and see him that was possessed with the devil, and had the legion, sitting, and clothed, and in his right mind: and they were afraid.",
    "Mark 5:16": "And they that saw it told them how it befell to him that was possessed with the devil, and also concerning the swine.",
    "Mark 5:17": "And they began to pray him to depart out of their coasts.",
    "Mark 5:18": "And when he was come into the ship, he that had been possessed with the devil prayed him that he might be with him.",
    "Mark 5:19": "Howbeit Jesus suffered him not, but saith unto him, Go home to thy friends, and tell them how great things the Lord hath done for thee, and hath had compassion on thee.",
    "Mark 5:20": "And he departed, and began to publish in Decapolis how great things Jesus had done for him: and all men did marvel.",
    "Mark 5:21": "And when Jesus was passed over again by ship unto the other side, much people gathered unto him: and he was nigh unto the sea.",
    "Mark 5:22": "And, behold, there cometh one of the rulers of the synagogue, Jairus by name; and when he saw him, he fell at his feet,",
    "Mark 5:23": "And besought him greatly, saying, My little daughter lieth at the point of death: I pray thee, come and lay thy hands on her, that she may be healed; and she shall live.",
    "Mark 5:24": "And Jesus went with him; and much people followed him, and thronged him.",
    "Mark 5:25": "And a certain woman, which had an issue of blood twelve years,",
    "Mark 5:26": "And had suffered many things of many physicians, and had spent all that she had, and was nothing bettered, but rather grew worse,",
    "Mark 5:27": "When she had heard of Jesus, came in the press behind, and touched his garment.",
    "Mark 5:28": "For she said, If I may touch but his clothes, I shall be whole.",
    "Mark 5:29": "And straightway the fountain of her blood was dried up; and she felt in her body that she was healed of that plague.",
    "Mark 5:30": "And Jesus, immediately knowing in himself that virtue had gone out of him, turned him about in the press, and said, Who touched my clothes?",
    "Mark 5:31": "And his disciples said unto him, Thou seest the multitude thronging thee, and sayest thou, Who touched me?",
    "Mark 5:32": "And he looked round about to see her that had done this thing.",
    "Mark 5:33": "But the woman fearing and trembling, knowing what was done in her, came and fell down before him, and told him all the truth.",
    "Mark 5:34": "And he said unto her, Daughter, thy faith hath made thee whole; go in peace, and be whole of thy plague.",
    "Mark 5:35": "While he yet spake, there came from the ruler of the synagogue's house certain which said, Thy daughter is dead: why troublest thou the Master any further?",
    "Mark 5:36": "As soon as Jesus heard the word that was spoken, he saith unto the ruler of the synagogue, Be not afraid, only believe.",
    "Mark 5:37": "And he suffered no man to follow him, save Peter, and James, and John the brother of James.",
    "Mark 5:38": "And he cometh to the house of the ruler of the synagogue, and seeth the tumult, and them that wept and wailed greatly.",
    "Mark 5:39": "And when he was come in, he saith unto them, Why make ye this ado, and weep? the damsel is not dead, but sleepeth.",
    "Mark 5:40": "And they laughed him to scorn. But when he had put them all out, he taketh the father and the mother of the damsel, and them that were with him, and entereth in where the damsel was lying.",
    "Mark 5:41": "And he took the damsel by the hand, and said unto her, Talitha cumi; which is, being interpreted, Damsel, I say unto thee, arise.",
    "Mark 5:42": "And straightway the damsel arose, and walked; for she was of the age of twelve years. And they were astonished with a great astonishment.",
    "Mark 5:43": "And he charged them straitly that no man should know it; and commanded that something should be given her to eat.",
    // Mark 6 (King James Version)
    
    // Mark 7 (King James Version)
    
    // Mark 8 (King James Version)
    
    // Mark 9 (King James Version)
    
    // Mark 10 (King James Version)
    
    // Mark 11 (King James Version)
    
    // Mark 12 (King James Version)
    
    // Mark 13 (King James Version)
    
    // Mark 15 (King James Version)
    
    // Mark 15 (King James Version)

    // Mark 16 (King James Version)
    "Mark 16:1": "And when the sabbath was past, Mary Magdalene, and Mary the mother of James, and Salome, had bought sweet spices, that they might come and anoint him.",
    "Mark 16:2": "And very early in the morning the first day of the week, they came unto the sepulchre at the rising of the sun.",
    "Mark 16:3": "And they said among themselves, Who shall roll us away the stone from the door of the sepulchre?",
    "Mark 16:4": "And when they looked, they saw that the stone was rolled away: for it was very great.",
    "Mark 16:5": "And entering into the sepulchre, they saw a young man sitting on the right side, clothed in a long white garment; and they were affrighted.",
    "Mark 16:6": "And he saith unto them, Be not affrighted: Ye seek Jesus of Nazareth, which was crucified: he is risen; he is not here: behold the place where they laid him.",
    "Mark 16:7": "But go your way, tell his disciples and Peter that he goeth before you into Galilee: there shall ye see him, as he said unto you.",
    "Mark 16:8": "And they went out quickly, and fled from the sepulchre; for they trembled and were amazed: neither said they any thing to any man; for they were afraid.",
    "Mark 16:9": "Now when Jesus was risen early the first day of the week, he appeared first to Mary Magdalene, out of whom he had cast seven devils.",
    "Mark 16:10": "And she went and told them that had been with him, as they mourned and wept.",
    "Mark 16:11": "And they, when they had heard that he was alive, and had been seen of her, believed not.",
    "Mark 16:12": "After that he appeared in another form unto two of them, as they walked, and went into the country.",
    "Mark 16:13": "And they went and told it unto the residue: neither believed they them.",
    "Mark 16:14": "Afterward he appeared unto the eleven as they sat at meat, and upbraided them with their unbelief and hardness of heart, because they believed not them which had seen him after he was risen.",
    "Mark 16:15": "And he said unto them, Go ye into all the world, and preach the gospel to every creature.",
    "Mark 16:16": "He that believeth and is baptized shall be saved; but he that believeth not shall be damned.",
    "Mark 16:17": "And these signs shall follow them that believe; In my name shall they cast out devils; they shall speak with new tongues;",
    "Mark 16:18": "They shall take up serpents; and if they drink any deadly thing, it shall not hurt them; they shall lay hands on the sick, and they shall recover.",
    "Mark 16:19": "So then after the Lord had spoken unto them, he was received up into heaven, and sat on the right hand of God.",
    "Mark 16:20": "And they went forth, and preached every where, the Lord working with them, and confirming the word with signs following. Amen."
};