const bibleVerses43 = {
    // John 1 (King James Version)
    "John 1:1": "In the beginning was the Word, and the Word was with God, and the Word was God.",
    "John 1:2": "The same was in the beginning with God.",
    "John 1:3": "All things were made by him; and without him was not any thing made that was made.",
    "John 1:4": "In him was life; and the life was the light of men.",
    "John 1:5": "And the light shineth in darkness; and the darkness comprehended it not.",
    "John 1:6": "There was a man sent from God, whose name was John.",
    "John 1:7": "The same came for a witness, to bear witness of the Light, that all men through him might believe.",
    "John 1:8": "He was not that Light, but was sent to bear witness of that Light.",
    "John 1:9": "That was the true Light, which lighteth every man that cometh into the world.",
    "John 1:10": "He was in the world, and the world was made by him, and the world knew him not.",
    "John 1:11": "He came unto his own, and his own received him not.",
    "John 1:12": "But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name:",
    "John 1:13": "Which were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God.",
    "John 1:14": "And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,) full of grace and truth.",
    "John 1:15": "John bare witness of him, and cried, saying, This was he of whom I spake, He that cometh after me is preferred before me: for he was before me.",
    "John 1:16": "And of his fullness have all we received, and grace for grace.",
    "John 1:17": "For the law was given by Moses, but grace and truth came by Jesus Christ.",
    "John 1:18": "No man hath seen God at any time; the only begotten Son, which is in the bosom of the Father, he hath declared him.",
    "John 1:19": "And this is the record of John, when the Jews sent priests and Levites from Jerusalem to ask him, Who art thou?",
    "John 1:20": "And he confessed, and denied not; but confessed, I am not the Christ.",
    "John 1:21": "And they asked him, What then? Art thou Elias? And he saith, I am not. Art thou that prophet? And he answered, No.",
    "John 1:22": "Then said they unto him, Who art thou? that we may give an answer to them that sent us. What sayest thou of thyself?",
    "John 1:23": "He said, I am the voice of one crying in the wilderness, Make straight the way of the Lord, as said the prophet Esaias.",
    "John 1:24": "And they which were sent were of the Pharisees.",
    "John 1:25": "And they asked him, and said unto him, Why baptizest thou then, if thou be not that Christ, nor Elias, neither that prophet?",
    "John 1:26": "John answered them, saying, I baptize with water: but there standeth one among you, whom ye know not;",
    "John 1:27": "He it is, who coming after me is preferred before me, whose shoe's latchet I am not worthy to unloose.",
    "John 1:28": "These things were done in Bethabara beyond Jordan, where John was baptizing.",
    "John 1:29": "The next day John seeth Jesus coming unto him, and saith, Behold the Lamb of God, which taketh away the sin of the world.",
    "John 1:30": "This is he of whom I said, After me cometh a man which is preferred before me: for he was before me.",
    "John 1:31": "And I knew him not: but that he should be made manifest to Israel, therefore am I come baptizing with water.",
    "John 1:32": "And John bare record, saying, I saw the Spirit descending from heaven like a dove, and it abode upon him.",
    "John 1:33": "And I knew him not: but he that sent me to baptize with water, the same said unto me, Upon whom thou shalt see the Spirit descending, and remaining on him, the same is he which baptizeth with the Holy Ghost.",
    "John 1:34": "And I saw, and bare record that this is the Son of God.",
    "John 1:35": "Again the next day after John stood, and two of his disciples;",
    "John 1:36": "And looking upon Jesus as he walked, he saith, Behold the Lamb of God!",
    "John 1:37": "And the two disciples heard him speak, and they followed Jesus.",
    "John 1:38": "Then Jesus turned, and saw them following, and saith unto them, What seek ye? They said unto him, Rabbi, (which is to say, being interpreted, Master,) where dwellest thou?",
    "John 1:39": "He saith unto them, Come and see. They came and saw where he dwelt, and abode with him that day: for it was about the tenth hour.",
    "John 1:40": "One of the two which heard John speak, and followed him, was Andrew, Simon Peter's brother.",
    "John 1:41": "He first findeth his own brother Simon, and saith unto him, We have found the Messias, which is, being interpreted, the Christ.",
    "John 1:42": "And he brought him to Jesus. And when Jesus beheld him, he said, Thou art Simon the son of Jona: thou shalt be called Cephas, which is by interpretation, A stone.",
    "John 1:43": "The day following Jesus would go forth into Galilee, and findeth Philip, and saith unto him, Follow me.",
    "John 1:44": "Now Philip was of Bethsaida, the city of Andrew and Peter.",
    "John 1:45": "Philip findeth Nathanael, and saith unto him, We have found him, of whom Moses in the law, and the prophets, did write, Jesus of Nazareth, the son of Joseph.",
    "John 1:46": "And Nathanael said unto him, Can there any good thing come out of Nazareth? Philip saith unto him, Come and see.",
    "John 1:47": "Jesus saw Nathanael coming to him, and saith of him, Behold an Israelite indeed, in whom is no guile!",
    "John 1:48": "Nathanael saith unto him, Whence knowest thou me? Jesus answered and said unto him, Before that Philip called thee, when thou wast under the fig tree, I saw thee.",
    "John 1:49": "Nathanael answered and saith unto him, Rabbi, thou art the Son of God; thou art the King of Israel.",
    "John 1:50": "Jesus answered and said unto him, Because I said unto thee, I saw thee under the fig tree, believest thou? thou shalt see greater things than these.",
    "John 1:51": "And he saith unto him, Verily, verily, I say unto you, Hereafter ye shall see heaven open, and the angels of God ascending and descending upon the Son of man.",
    
    // John 2 (King James Version)
    "John 2:1": "And the third day there was a marriage in Cana of Galilee; and the mother of Jesus was there:",
    "John 2:2": "And both Jesus was called, and his disciples, to the marriage.",
    "John 2:3": "And when they wanted wine, the mother of Jesus saith unto him, They have no wine.",
    "John 2:4": "Jesus saith unto her, Woman, what have I to do with thee? mine hour is not yet come.",
    "John 2:5": "His mother saith unto the servants, Whatsoever he saith unto you, do it.",
    "John 2:6": "And there were set there six waterpots of stone, after the manner of the purifying of the Jews, containing two or three firkins apiece.",
    "John 2:7": "Jesus saith unto them, Fill the waterpots with water. And they filled them up to the brim.",
    "John 2:8": "And he saith unto them, Draw out now, and bear unto the governor of the feast. And they bare it.",
    "John 2:9": "When the ruler of the feast had tasted the water that was made wine, and knew not whence it was: (but the servants which drew the water knew;) the governor of the feast called the bridegroom,",
    "John 2:10": "And saith unto him, Every man at the beginning doth set forth good wine; and when men have well drunk, then that which is worse: but thou hast kept the good wine until now.",
    "John 2:11": "This beginning of miracles did Jesus in Cana of Galilee, and manifested forth his glory; and his disciples believed on him.",
    "John 2:12": "After this he went down to Capernaum, he, and his mother, and his brethren, and his disciples: and they continued there not many days.",
    "John 2:13": "And the Jews' passover was at hand, and Jesus went up to Jerusalem,",
    "John 2:14": "And found in the temple those that sold oxen and sheep and doves, and the changers of money sitting.",
    "John 2:15": "And when he had made a scourge of small cords, he drove them all out of the temple, and the sheep, and the oxen; and poured out the changers' money, and overthrew the tables;",
    "John 2:16": "And said unto them that sold doves, Take these things hence; make not my Father's house an house of merchandise.",
    "John 2:17": "And his disciples remembered that it was written, The zeal of thine house hath eaten me up.",
    "John 2:18": "Then answered the Jews and said unto him, What sign shewest thou unto us, seeing that thou doest these things?",
    "John 2:19": "Jesus answered and said unto them, Destroy this temple, and in three days I will raise it up.",
    "John 2:20": "Then said the Jews, Forty and six years was this temple in building, and wilt thou rear it up in three days?",
    "John 2:21": "But he spake of the temple of his body.",
    "John 2:22": "When therefore he was risen from the dead, his disciples remembered that he had said this unto them; and they believed the scripture, and the word which Jesus had said.",
    "John 2:23": "Now when he was in Jerusalem at the passover, in the feast day, many believed in his name, when they saw the miracles which he did.",
    "John 2:24": "But Jesus did not commit himself unto them, because he knew all men,",
    "John 2:25": "And needed not that any should testify of man: for he knew what was in man.",
    
    // John 3 (King James Version)
    "John 3:1": "There was a man of the Pharisees, named Nicodemus, a ruler of the Jews:",
    "John 3:2": "The same came to Jesus by night, and said unto him, Rabbi, we know that thou art a teacher come from God: for no man can do these miracles that thou doest, except God be with him.",
    "John 3:3": "Jesus answered and said unto him, Verily, verily, I say unto thee, Except a man be born again, he cannot see the kingdom of God.",
    "John 3:4": "Nicodemus saith unto him, How can a man be born when he is old? can he enter the second time into his mother's womb, and be born?",
    "John 3:5": "Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God.",
    "John 3:6": "That which is born of the flesh is flesh; and that which is born of the Spirit is spirit.",
    "John 3:7": "Marvel not that I said unto thee, Ye must be born again.",
    "John 3:8": "The wind bloweth where it listeth, and thou hearest the sound thereof, but canst not tell whence it cometh, and whither it goeth: so is every one that is born of the Spirit.",
    "John 3:9": "Nicodemus answered and said unto him, How can these things be?",
    "John 3:10": "Jesus answered and said unto him, Art thou a master of Israel, and knowest not these things?",
    "John 3:11": "Verily, verily, I say unto thee, We speak that we do know, and testify that we have seen; and ye receive not our witness.",
    "John 3:12": "If I have told you earthly things, and ye believe not, how shall ye believe, if I tell you of heavenly things?",
    "John 3:13": "And no man hath ascended up to heaven, but he that came down from heaven, even the Son of man which is in heaven.",
    "John 3:14": "And as Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up:",
    "John 3:15": "That whosoever believeth in him should not perish, but have eternal life.",
    "John 3:16": "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
    "John 3:17": "For God sent not his Son into the world to condemn the world; but that the world through him might be saved.",
    "John 3:18": "He that believeth on him is not condemned: but he that believeth not is condemned already, because he hath not believed in the name of the only begotten Son of God.",
    "John 3:19": "And this is the condemnation, that light is come into the world, and men loved darkness rather than light, because their deeds were evil.",
    "John 3:20": "For every one that doeth evil hateth the light, neither cometh to the light, lest his deeds should be reproved.",
    "John 3:21": "But he that doeth truth cometh to the light, that his deeds may be made manifest, that they are wrought in God.",
    "John 3:22": "After these things came Jesus and his disciples into the land of Judaea; and there he tarried with them, and baptized.",
    "John 3:23": "And John also was baptizing in Aenon near to Salim, because there was much water there: and they came, and were baptized.",
    "John 3:24": "For John was not yet cast into prison.",
    "John 3:25": "Then there arose a question between some of John's disciples and the Jews about purifying.",
    "John 3:26": "And they came unto John, and said unto him, Rabbi, he that was with thee beyond Jordan, to whom thou barest witness, behold, the same baptizeth, and all men come to him.",
    "John 3:27": "John answered and said, A man can receive nothing, except it be given him from heaven.",
    "John 3:28": "Ye yourselves bear me witness, that I said, I am not the Christ, but that I am sent before him.",
    "John 3:29": "He that hath the bride is the bridegroom: but the friend which standeth and heareth him rejoiceth greatly because of the bridegroom's voice: this my joy therefore is fulfilled.",
    "John 3:30": "He must increase, but I must decrease.",
    "John 3:31": "He that cometh from above is above all: he that is of the earth is earthly, and speaketh of the earth: he that cometh from heaven is above all.",
    "John 3:32": "And what he hath seen and heard, that he testifieth; and no man receiveth his testimony.",
    "John 3:33": "He that hath received his testimony hath set to his seal that God is true.",
    "John 3:34": "For he whom God hath sent speaketh the words of God: for God giveth not the Spirit by measure unto him.",
    "John 3:35": "The Father loveth the Son, and hath given all things into his hand.",
    "John 3:36": "He that believeth on the Son hath everlasting life: and he that believeth not the Son shall not see life; but the wrath of God abideth on him.",
    
    // John 4 (King James Version)
    "John 4:1": "When therefore the Lord knew how the Pharisees had heard that Jesus made and baptized more disciples than John,",
    "John 4:2": "(Though Jesus himself baptized not, but his disciples,)",
    "John 4:3": "He left Judaea, and departed again into Galilee.",
    "John 4:4": "And he must needs go through Samaria.",
    "John 4:5": "Then cometh he to a city of Samaria, which is called Sychar, near to the parcel of ground that Jacob gave to his son Joseph.",
    "John 4:6": "Now Jacob's well was there. Jesus therefore, being wearied with his journey, sat thus on the well: and it was about the sixth hour.",
    "John 4:7": "There cometh a woman of Samaria to draw water: Jesus saith unto her, Give me to drink.",
    "John 4:8": "(For his disciples were gone away unto the city to buy meat.)",
    "John 4:9": "Then saith the woman of Samaria unto him, How is it that thou, being a Jew, askest drink of me, which am a woman of Samaria? for the Jews have no dealings with the Samaritans.",
    "John 4:10": "Jesus answered and said unto her, If thou knewest the gift of God, and who it is that saith to thee, Give me to drink; thou wouldest have asked of him, and he would have given thee living water.",
    "John 4:11": "The woman saith unto him, Sir, thou hast nothing to draw with, and the well is deep: from whence then hast thou that living water?",
    "John 4:12": "Art thou greater than our father Jacob, which gave us the well, and drank thereof himself, and his children, and his cattle?",
    "John 4:13": "Jesus answered and said unto her, Whosoever drinketh of this water shall thirst again:",
    "John 4:14": "But whosoever drinketh of the water that I shall give him shall never thirst; but the water that I shall give him shall be in him a well of water springing up into everlasting life.",
    "John 4:15": "The woman saith unto him, Sir, give me this water, that I thirst not, neither come hither to draw.",
    "John 4:16": "Jesus saith unto her, Go, call thy husband, and come hither.",
    "John 4:17": "The woman answered and said, I have no husband. Jesus said unto her, Thou hast well said, I have no husband:",
    "John 4:18": "For thou hast had five husbands; and he whom thou now hast is not thy husband: in that saidst thou truly.",
    "John 4:19": "The woman saith unto him, Sir, I perceive that thou art a prophet.",
    "John 4:20": "Our fathers worshipped in this mountain; and ye say, that in Jerusalem is the place where men ought to worship.",
    "John 4:21": "Jesus saith unto her, Woman, believe me, the hour cometh, when ye shall neither in this mountain, nor yet at Jerusalem, worship the Father.",
    "John 4:22": "Ye worship ye know not what: we know what we worship: for salvation is of the Jews.",
    "John 4:23": "But the hour cometh, and now is, when the true worshippers shall worship the Father in spirit and in truth: for the Father seeketh such to worship him.",
    "John 4:24": "God is a Spirit: and they that worship him must worship him in spirit and in truth.",
    "John 4:25": "The woman saith unto him, I know that Messiah cometh, which is called Christ: when he is come, he will tell us all things.",
    "John 4:26": "Jesus saith unto her, I that speak unto thee am he.",
    "John 4:27": "And upon this came his disciples, and marvelled that he talked with the woman: yet no man said, What seekest thou? or, Why talkest thou with her?",
    "John 4:28": "The woman then left her waterpot, and went her way into the city, and saith to the men,",
    "John 4:29": "Come, see a man, which told me all things that ever I did: is not this the Christ?",
    "John 4:30": "Then they went out of the city, and came unto him.",
    "John 4:31": "In the mean while his disciples prayed him, saying, Master, eat.",
    "John 4:32": "But he said unto them, I have meat to eat that ye know not of.",
    "John 4:33": "Therefore said the disciples one to another, Hath any man brought him ought to eat?",
    "John 4:34": "Jesus saith unto them, My meat is to do the will of him that sent me, and to finish his work.",
    "John 4:35": "Say not ye, There are yet four months, and then cometh harvest? behold, I say unto you, Lift up your eyes, and look on the fields; for they are white already to harvest.",
    "John 4:36": "And he that reapeth receiveth wages, and gathereth fruit unto life eternal: that both he that soweth and he that reapeth may rejoice together.",
    "John 4:37": "And herein is that saying true, One soweth, and another reapeth.",
    "John 4:38": "I sent you to reap that whereon ye bestowed no labour: other men laboured, and ye are entered into their labours.",
    "John 4:39": "And many of the Samaritans of that city believed on him for the saying of the woman, which testified, He told me all that ever I did.",
    "John 4:40": "So when the Samaritans were come unto him, they besought him that he would tarry with them: and he abode there two days.",
    "John 4:41": "And many more believed because of his own word;",
    "John 4:42": "And said unto the woman, Now we believe, not because of thy saying: for we have heard him ourselves, and know that this is indeed the Christ, the Saviour of the world.",
    "John 4:43": "Now after two days he departed thence, and went into Galilee.",
    "John 4:44": "For Jesus himself testified, that a prophet hath no honour in his own country.",
    "John 4:45": "Then when he was come into Galilee, the Galilaeans received him, having seen all the things that he did at Jerusalem at the feast: for they also went unto the feast.",
    "John 4:46": "So Jesus came again into Cana of Galilee, where he made the water wine. And there was a certain nobleman, whose son was sick at Capernaum.",
    "John 4:47": "When he heard that Jesus was come out of Judaea into Galilee, he went unto him, and besought him that he would come down, and heal his son: for he was at the point of death.",
    "John 4:48": "Then said Jesus unto him, Except ye see signs and wonders, ye will not believe.",
    "John 4:49": "The nobleman saith unto him, Sir, come down ere my child die.",
    "John 4:50": "Jesus saith unto him, Go thy way; thy son liveth. And the man believed the word that Jesus had spoken unto him, and he went his way.",
    "John 4:51": "And as he was now going down, his servants met him, and told him, saying, Thy son liveth.",
    "John 4:52": "Then enquired he of them the hour when he began to amend. And they said unto him, Yesterday at the seventh hour the fever left him.",
    "John 4:53": "So the father knew that it was at the same hour, in the which Jesus said unto him, Thy son liveth: and himself believed, and his whole house.",
    "John 4:54": "This is again the second miracle that Jesus did, when he was come out of Judaea into Galilee.",
    
    // John 5 (King James Version)
    "John 5:1": "After this there was a feast of the Jews; and Jesus went up to Jerusalem.",
    "John 5:2": "Now there is at Jerusalem by the sheep market a pool, which is called in the Hebrew tongue Bethesda, having five porches.",
    "John 5:3": "In these lay a great multitude of impotent folk, of blind, halt, withered, waiting for the moving of the water.",
    "John 5:4": "For an angel went down at a certain season into the pool, and troubled the water: whosoever then first after the troubling of the water stepped in was made whole of whatsoever disease he had.",
    "John 5:5": "And a certain man was there, which had an infirmity thirty and eight years.",
    "John 5:6": "When Jesus saw him lie, and knew that he had been now a long time in that case, he saith unto him, Wilt thou be made whole?",
    "John 5:7": "The impotent man answered him, Sir, I have no man, when the water is troubled, to put me into the pool: but while I am coming, another steppeth down before me.",
    "John 5:8": "Jesus saith unto him, Rise, take up thy bed, and walk.",
    "John 5:9": "And immediately the man was made whole, and took up his bed, and walked: and on the same day was the sabbath.",
    "John 5:10": "The Jews therefore said unto him that was cured, It is the sabbath day: it is not lawful for thee to carry thy bed.",
    "John 5:11": "He answered them, He that made me whole, the same said unto me, Take up thy bed, and walk.",
    "John 5:12": "Then asked they him, What man is that which said unto thee, Take up thy bed, and walk?",
    "John 5:13": "And he that was healed wist not who it was: for Jesus had conveyed himself away, a multitude being in that place.",
    "John 5:14": "Afterward Jesus findeth him in the temple, and said unto him, Behold, thou art made whole: sin no more, lest a worse thing come unto thee.",
    "John 5:15": "The man departed, and told the Jews that it was Jesus, which had made him whole.",
    "John 5:16": "And therefore did the Jews persecute Jesus, and sought to slay him, because he had done these things on the sabbath day.",
    "John 5:17": "But Jesus answered them, My Father worketh hitherto, and I work.",
    "John 5:18": "Therefore the Jews sought the more to kill him, because he not only had broken the sabbath, but said also that God was his Father, making himself equal with God.",
    "John 5:19": "Then answered Jesus and said unto them, Verily, verily, I say unto you, The Son can do nothing of himself, but what he seeth the Father do: for what things soever he doeth, these also doeth the Son likewise.",
    "John 5:20": "For the Father loveth the Son, and showeth him all things that himself doeth: and he will show him greater works than these, that ye may marvel.",
    "John 5:21": "For as the Father raiseth up the dead, and quickeneth them; even so the Son quickeneth whom he will.",
    "John 5:22": "For the Father judgeth no man, but hath committed all judgment unto the Son:",
    "John 5:23": "That all men should honour the Son, even as they honour the Father. He that honoureth not the Son honoureth not the Father which hath sent him.",
    "John 5:24": "Verily, verily, I say unto you, He that heareth my word, and believeth on him that sent me, hath everlasting life, and shall not come into condemnation; but is passed from death unto life.",
    "John 5:25": "Verily, verily, I say unto you, The hour is coming, and now is, when the dead shall hear the voice of the Son of God: and they that hear shall live.",
    "John 5:26": "For as the Father hath life in himself; so hath he given to the Son to have life in himself;",
    "John 5:27": "And hath given him authority to execute judgment also, because he is the Son of man.",
    "John 5:28": "Marvel not at this: for the hour is coming, in the which all that are in the graves shall hear his voice,",
    "John 5:29": "And shall come forth; they that have done good, unto the resurrection of life; and they that have done evil, unto the resurrection of damnation.",
    "John 5:30": "I can of mine own self do nothing: as I hear, I judge: and my judgment is just; because I seek not mine own will, but the will of the Father which hath sent me.",
    "John 5:31": "If I bear witness of myself, my witness is not true.",
    "John 5:32": "There is another that beareth witness of me; and I know that the witness which he witnesseth of me is true.",
    "John 5:33": "Ye sent unto John, and he bare witness unto the truth.",
    "John 5:34": "But I receive not testimony from man: but these things I say, that ye might be saved.",
    "John 5:35": "He was a burning and a shining light: and ye were willing for a season to rejoice in his light.",
    "John 5:36": "But I have greater witness than that of John: for the works which the Father hath given me to finish, the same works that I do, bear witness of me, that the Father hath sent me.",
    "John 5:37": "And the Father himself, which hath sent me, hath borne witness of me. Ye have neither heard his voice at any time, nor seen his shape.",
    "John 5:38": "And ye have not his word abiding in you: for whom he hath sent, him ye believe not.",
    "John 5:39": "Search the scriptures; for in them ye think ye have eternal life: and they are they which testify of me.",
    "John 5:40": "And ye will not come to me, that ye might have life.",
    "John 5:41": "I receive not honour from men.",
    "John 5:42": "But I know you, that ye have not the love of God in you.",
    "John 5:43": "I am come in my Father's name, and ye receive me not: if another shall come in his own name, him ye will receive.",
    "John 5:44": "How can ye believe, which receive honour one of another, and seek not the honour that cometh from God only?",
    "John 5:45": "Do not think that I will accuse you to the Father: there is one that accuseth you, even Moses, in whom ye trust.",
    "John 5:46": "For had ye believed Moses, ye would have believed me; for he wrote of me.",
    "John 5:47": "But if ye believe not his writings, how shall ye believe my words?",
    
    // John 6 (King James Version)
    "John 6:1": "After these things Jesus went over the sea of Galilee, which is the sea of Tiberias.",
    "John 6:2": "And a great multitude followed him, because they saw his miracles which he did on them that were diseased.",
    "John 6:3": "And Jesus went up into a mountain, and there he sat with his disciples.",
    "John 6:4": "And the passover, a feast of the Jews, was nigh.",
    "John 6:5": "When Jesus then lifted up his eyes, and saw a great company come unto him, he saith unto Philip, Whence shall we buy bread, that these may eat?",
    "John 6:6": "And this he said to prove him: for he himself knew what he would do.",
    "John 6:7": "Philip answered him, Two hundred pennyworth of bread is not sufficient for them, that every one of them may take a little.",
    "John 6:8": "One of his disciples, Andrew, Simon Peter's brother, saith unto him,",
    "John 6:9": "There is a lad here, which hath five barley loaves, and two small fishes: but what are they among so many?",
    "John 6:10": "And Jesus said, Make the men sit down. Now there was much grass in the place. So the men sat down, in number about five thousand.",
    "John 6:11": "And Jesus took the loaves; and when he had given thanks, he distributed to the disciples, and the disciples to them that were set down; and likewise of the fishes as much as they would.",
    "John 6:12": "When they were filled, he said unto his disciples, Gather up the fragments that remain, that nothing be lost.",
    "John 6:13": "Therefore they gathered them together, and filled twelve baskets with the fragments of the five barley loaves, which remained over and above unto them that had eaten.",
    "John 6:14": "Then those men, when they had seen the miracle that Jesus did, said, This is of a truth that prophet that should come into the world.",
    "John 6:15": "When Jesus therefore perceived that they would come and take him by force, to make him a king, he departed again into a mountain himself alone.",
    "John 6:16": "And when even was now come, his disciples went down unto the sea,",
    "John 6:17": "And entered into a ship, and went over the sea toward Capernaum. And it was now dark, and Jesus was not come to them.",
    "John 6:18": "And the sea arose by reason of a great wind that blew.",
    "John 6:19": "So when they had rowed about five and twenty or thirty furlongs, they see Jesus walking on the sea, and drawing nigh unto the ship: and they were afraid.",
    "John 6:20": "But he saith unto them, It is I; be not afraid.",
    "John 6:21": "Then they willingly received him into the ship: and immediately the ship was at the land whither they went.",
    "John 6:22": "The day following, when the people which stood on the other side of the sea saw that there was none other boat there, save that one whereinto his disciples were entered, and that Jesus went not with his disciples into the boat, but that his disciples were gone away alone;",
    "John 6:23": "Howbeit there came other boats from Tiberias nigh unto the place where they did eat bread, after that the Lord had given thanks:",
    "John 6:24": "When the people therefore saw that Jesus was not there, neither his disciples, they also took shipping, and came to Capernaum, seeking for Jesus.",
    "John 6:25": "And when they had found him on the other side of the sea, they said unto him, Rabbi, when camest thou hither?",
    "John 6:26": "Jesus answered them and said, Verily, verily, I say unto you, Ye seek me, not because ye saw the miracles, but because ye did eat of the loaves, and were filled.",
    "John 6:27": "Labour not for the meat which perisheth, but for that meat which endureth unto everlasting life, which the Son of man shall give unto you: for him hath God the Father sealed.",
    "John 6:28": "Then said they unto him, What shall we do, that we might work the works of God?",
    "John 6:29": "Jesus answered and said unto them, This is the work of God, that ye believe on him whom he hath sent.",
    "John 6:30": "They said therefore unto him, What sign shewest thou then, that we may see, and believe thee? what dost thou work?",
    "John 6:31": "Our fathers did eat manna in the desert; as it is written, He gave them bread from heaven to eat.",
    "John 6:32": "Then Jesus said unto them, Verily, verily, I say unto you, Moses gave you not that bread from heaven; but my Father giveth you the true bread from heaven.",
    "John 6:33": "For the bread of God is he which cometh down from heaven, and giveth life unto the world.",
    "John 6:34": "Then said they unto him, Lord, evermore give us this bread.",
    "John 6:35": "And Jesus said unto them, I am the bread of life: he that cometh to me shall never hunger; and he that believeth on me shall never thirst.",
    "John 6:36": "But I said unto you, That ye also have seen me, and believe not.",
    "John 6:37": "All that the Father giveth me shall come to me; and him that cometh to me I will in no wise cast out.",
    "John 6:38": "For I came down from heaven, not to do mine own will, but the will of him that sent me.",
    "John 6:39": "And this is the Father's will which hath sent me, that of all which he hath given me I should lose nothing, but should raise it up again at the last day.",
    "John 6:40": "And this is the will of him that sent me, that every one which seeth the Son, and believeth on him, may have everlasting life: and I will raise him up at the last day.",
    "John 6:41": "The Jews then murmured at him, because he said, I am the bread which came down from heaven.",
    "John 6:42": "And they said, Is not this Jesus, the son of Joseph, whose father and mother we know? how is it then that he saith, I came down from heaven?",
    "John 6:43": "Jesus therefore answered and said unto them, Murmur not among yourselves.",
    "John 6:44": "No man can come to me, except the Father which hath sent me draw him: and I will raise him up at the last day.",
    "John 6:45": "It is written in the prophets, And they shall be all taught of God. Every man therefore that hath heard, and hath learned of the Father, cometh unto me.",
    "John 6:46": "Not that any man hath seen the Father, save he which is of God, he hath seen the Father.",
    "John 6:47": "Verily, verily, I say unto you, He that believeth on me hath everlasting life.",
    "John 6:48": "I am that bread of life.",
    "John 6:49": "Your fathers did eat manna in the wilderness, and are dead.",
    "John 6:50": "This is the bread which cometh down from heaven, that a man may eat thereof, and not die.",
    "John 6:51": "I am the living bread which came down from heaven: if any man eat of this bread, he shall live for ever: and the bread that I will give is my flesh, which I will give for the life of the world.",
    "John 6:52": "The Jews therefore strove among themselves, saying, How can this man give us his flesh to eat?",
    "John 6:53": "Then Jesus said unto them, Verily, verily, I say unto you, Except ye eat the flesh of the Son of man, and drink his blood, ye have no life in you.",
    "John 6:54": "Whoso eateth my flesh, and drinketh my blood, hath eternal life; and I will raise him up at the last day.",
    "John 6:55": "For my flesh is meat indeed, and my blood is drink indeed.",
    "John 6:56": "He that eateth my flesh, and drinketh my blood, dwelleth in me, and I in him.",
    "John 6:57": "As the living Father hath sent me, and I live by the Father: so he that eateth me, even he shall live by me.",
    "John 6:58": "This is that bread which came down from heaven: not as your fathers did eat manna, and are dead: he that eateth of this bread shall live for ever.",
    "John 6:59": "These things said he in the synagogue, as he taught in Capernaum.",
    "John 6:60": "Many therefore of his disciples, when they had heard this, said, This is a hard saying; who can hear it?",
    "John 6:61": "When Jesus knew in himself that his disciples murmured at it, he said unto them, Doth this offend you?",
    "John 6:62": "What and if ye shall see the Son of man ascend up where he was before?",
    "John 6:63": "It is the spirit that quickeneth; the flesh profiteth nothing: the words that I speak unto you, they are spirit, and they are life.",
    "John 6:64": "But there are some of you that believe not. For Jesus knew from the beginning who they were that believed not, and who should betray him.",
    "John 6:65": "And he said, Therefore said I unto you, that no man can come unto me, except it were given unto him of my Father.",
    "John 6:66": "From that time many of his disciples went back, and walked no more with him.",
    "John 6:67": "Then said Jesus unto the twelve, Will ye also go away?",
    "John 6:68": "Then Simon Peter answered him, Lord, to whom shall we go? thou hast the words of eternal life.",
    "John 6:69": "And we believe and are sure that thou art that Christ, the Son of the living God.",
    "John 6:70": "Jesus answered them, Have not I chosen you twelve, and one of you is a devil?",
    "John 6:71": "He spake of Judas Iscariot the son of Simon: for he it was that should betray him, being one of the twelve.",
    
    // John 7 (King James Version)
    "John 7:1": "After these things Jesus walked in Galilee; for he would not walk in Jewry, because the Jews sought to kill him.",
    "John 7:2": "Now the Jews' feast of tabernacles was at hand.",
    "John 7:3": "His brethren therefore said unto him, Depart hence, and go into Judaea, that thy disciples also may see the works that thou doest.",
    "John 7:4": "For there is no man that doeth any thing in secret, and he himself seeketh to be known openly. If thou do these things, show thyself to the world.",
    "John 7:5": "For neither did his brethren believe in him.",
    "John 7:6": "Then Jesus said unto them, My time is not yet come: but your time is alway ready.",
    "John 7:7": "The world cannot hate you; but me it hateth, because I testify of it, that the works thereof are evil.",
    "John 7:8": "Go ye up unto this feast: I go not up yet unto this feast; for my time is not yet full come.",
    "John 7:9": "When he had said these words unto them, he abode still in Galilee.",
    "John 7:10": "But when his brethren were gone up, then went he also up unto the feast, not openly, but as it were in secret.",
    "John 7:11": "Then the Jews sought him at the feast, and said, Where is he?",
    "John 7:12": "And there was much murmuring among the people concerning him: for some said, He is a good man: others said, Nay; but he deceiveth the people.",
    "John 7:13": "Howbeit no man spake openly of him for fear of the Jews.",
    "John 7:14": "Now about the midst of the feast Jesus went up into the temple, and taught.",
    "John 7:15": "And the Jews marvelled, saying, How knoweth this man letters, having never learned?",
    "John 7:16": "Jesus answered them, and said, My doctrine is not mine, but his that sent me.",
    "John 7:17": "If any man will do his will, he shall know of the doctrine, whether it be of God, or whether I speak of myself.",
    "John 7:18": "He that speaketh of himself seeketh his own glory: but he that seeketh his glory that sent him, the same is true, and no unrighteousness is in him.",
    "John 7:19": "Did not Moses give you the law, and yet none of you keepeth the law? Why go ye about to kill me?",
    "John 7:20": "The people answered and said, Thou hast a devil: who goeth about to kill thee?",
    "John 7:21": "Jesus answered and said unto them, I have done one work, and ye all marvel.",
    "John 7:22": "Moses therefore gave unto you circumcision; (not because it is of Moses, but of the fathers;) and ye on the sabbath day circumcise a man.",
    "John 7:23": "If a man on the sabbath day receive circumcision, that the law of Moses should not be broken; are ye angry at me, because I have made a man every whit whole on the sabbath day?",
    "John 7:24": "Judge not according to the appearance, but judge righteous judgment.",
    "John 7:25": "Then said some of them of Jerusalem, Is not this he, whom they seek to kill?",
    "John 7:26": "But, lo, he speaketh boldly, and they say nothing unto him. Do the rulers know indeed that this is the very Christ?",
    "John 7:27": "Howbeit we know this man whence he is: but when Christ cometh, no man knoweth whence he is.",
    "John 7:28": "Then cried Jesus in the temple as he taught, saying, Ye both know me, and ye know whence I am: and I am not come of myself, but he that sent me is true, whom ye know not.",
    "John 7:29": "But I know him: for I am from him, and he hath sent me.",
    "John 7:30": "Then they sought to take him: but no man laid hands on him, because his hour was not yet come.",
    "John 7:31": "And many of the people believed on him, and said, When Christ cometh, will he do more miracles than these which this man hath done?",
    "John 7:32": "The Pharisees heard that the people murmured such things concerning him; and the Pharisees and the chief priests sent officers to take him.",
    "John 7:33": "Then said Jesus unto them, Yet a little while am I with you, and then I go unto him that sent me.",
    "John 7:34": "Ye shall seek me, and shall not find me: and where I am, thither ye cannot come.",
    "John 7:35": "Then said the Jews among themselves, Whither will he go, that we shall not find him? will he go unto the dispersed among the Gentiles, and teach the Gentiles?",
    "John 7:36": "What manner of saying is this that he said, Ye shall seek me, and shall not find me: and where I am, thither ye cannot come?",
    "John 7:37": "In the last day, that great day of the feast, Jesus stood and cried, saying, If any man thirst, let him come unto me, and drink.",
    "John 7:38": "He that believeth on me, as the scripture hath said, out of his belly shall flow rivers of living water.",
    "John 7:39": "But this spake he of the Spirit, which they that believe on him should receive: for the Holy Ghost was not yet given; because that Jesus was not yet glorified.",
    "John 7:40": "Many of the people therefore, when they heard this saying, said, Of a truth this is the Prophet.",
    "John 7:41": "Others said, This is the Christ. But some said, Shall Christ come out of Galilee?",
    "John 7:42": "Hath not the scripture said, That Christ cometh of the seed of David, and out of the town of Bethlehem, where David was?",
    "John 7:43": "So there was a division among the people because of him.",
    "John 7:44": "And some of them would have taken him; but no man laid hands on him.",
    "John 7:45": "Then came the officers to the chief priests and Pharisees; and they said unto them, Why have ye not brought him?",
    "John 7:46": "The officers answered, Never man spake like this man.",
    "John 7:47": "Then answered them the Pharisees, Are ye also deceived?",
    "John 7:48": "Have any of the rulers or of the Pharisees believed on him?",
    "John 7:49": "But this people who knoweth not the law are cursed.",
    "John 7:50": "Nicodemus saith unto them, (he that came to Jesus by night, being one of them,)",
    "John 7:51": "Doth our law judge any man, before it hear him, and know what he doeth?",
    "John 7:52": "They answered and said unto him, Art thou also of Galilee? Search, and look: for out of Galilee ariseth no prophet.",
    "John 7:53": "And every man went unto his own house.",
    
    // John 8 (King James Version)
    "John 8:1": "Jesus went unto the mount of Olives.",
    "John 8:2": "And early in the morning he came again into the temple, and all the people came unto him; and he sat down, and taught them.",
    "John 8:3": "And the scribes and Pharisees brought unto him a woman taken in adultery; and when they had set her in the midst,",
    "John 8:4": "They say unto him, Master, this woman was taken in adultery, in the very act.",
    "John 8:5": "Now Moses in the law commanded us, that such should be stoned: but what sayest thou?",
    "John 8:6": "This they said, tempting him, that they might have to accuse him. But Jesus stooped down, and with his finger wrote on the ground, as though he heard them not.",
    "John 8:7": "So when they continued asking him, he lifted up himself, and said unto them, He that is without sin among you, let him first cast a stone at her.",
    "John 8:8": "And again he stooped down, and wrote on the ground.",
    "John 8:9": "And they which heard it, being convicted by their own conscience, went out one by one, beginning at the eldest, even unto the last: and Jesus was left alone, and the woman standing in the midst.",
    "John 8:10": "When Jesus had lifted up himself, and saw none but the woman, he said unto her, Woman, where are those thine accusers? hath no man condemned thee?",
    "John 8:11": "She said, No man, Lord. And Jesus said unto her, Neither do I condemn thee: go, and sin no more.",
    "John 8:12": "Then spake Jesus again unto them, saying, I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.",
    "John 8:13": "The Pharisees therefore said unto him, Thou bearest record of thyself; thy record is not true.",
    "John 8:14": "Jesus answered and said unto them, Though I bear record of myself, yet my record is true: for I know whence I came, and whither I go; but ye cannot tell whence I come, and whither I go.",
    "John 8:15": "Ye judge after the flesh; I judge no man.",
    "John 8:16": "And yet if I judge, my judgment is true: for I am not alone, but I and the Father that sent me.",
    "John 8:17": "It is also written in your law, that the testimony of two men is true.",
    "John 8:18": "I am one that bear witness of myself, and the Father that sent me beareth witness of me.",
    "John 8:19": "Then said they unto him, Where is thy Father? Jesus answered, Ye neither know me, nor my Father: if ye had known me, ye should have known my Father also.",
    "John 8:20": "These words spake Jesus in the treasury, as he taught in the temple: and no man laid hands on him; for his hour was not yet come.",
    "John 8:21": "Then said Jesus again unto them, I go my way, and ye shall seek me, and shall die in your sins: whither I go, ye cannot come.",
    "John 8:22": "Then said the Jews, Will he kill himself? because he saith, Whither I go, ye cannot come.",
    "John 8:23": "And he said unto them, Ye are from beneath; I am from above: ye are of this world; I am not of this world.",
    "John 8:24": "I said therefore unto you, that ye shall die in your sins: for if ye believe not that I am he, ye shall die in your sins.",
    "John 8:25": "Then said they unto him, Who art thou? And Jesus saith unto them, Even the same that I said unto you from the beginning.",
    "John 8:26": "I have many things to say and to judge of you: but he that sent me is true; and I speak to the world those things which I have heard of him.",
    "John 8:27": "They understood not that he spake to them of the Father.",
    "John 8:28": "Then said Jesus unto them, When ye have lifted up the Son of man, then shall ye know that I am he, and that I do nothing of myself; but as my Father hath taught me, I speak these things.",
    "John 8:29": "And he that sent me is with me: the Father hath not left me alone; for I do always those things that please him.",
    "John 8:30": "As he spake these words, many believed on him.",
    "John 8:31": "Then said Jesus to those Jews which believed on him, If ye continue in my word, then are ye my disciples indeed;",
    "John 8:32": "And ye shall know the truth, and the truth shall make you free.",
    "John 8:33": "They answered him, We be Abraham's seed, and were never in bondage to any man: how sayest thou, Ye shall be made free?",
    "John 8:34": "Jesus answered them, Verily, verily, I say unto you, Whosoever committeth sin is the servant of sin.",
    "John 8:35": "And the servant abideth not in the house for ever: but the Son abideth ever.",
    "John 8:36": "If the Son therefore shall make you free, ye shall be free indeed.",
    "John 8:37": "I know that ye are Abraham's seed; but ye seek to kill me, because my word hath no place in you.",
    "John 8:38": "I speak that which I have seen with my Father: and ye do that which ye have seen with your father.",
    "John 8:39": "They answered and said unto him, Abraham is our father. Jesus saith unto them, If ye were Abraham's children, ye would do the works of Abraham.",
    "John 8:40": "But now ye seek to kill me, a man that hath told you the truth, which I have heard of God: this did not Abraham.",
    "John 8:41": "Ye do the deeds of your father. Then said they to him, We be not born of fornication; we have one Father, even God.",
    "John 8:42": "Jesus said unto them, If God were your Father, ye would love me: for I proceeded forth and came from God; neither came I of myself, but he sent me.",
    "John 8:43": "Why do ye not understand my speech? even because ye cannot hear my word.",
    "John 8:44": "Ye are of your father the devil, and the lusts of your father ye will do. He was a murderer from the beginning, and abode not in the truth, because there is no truth in him. When he speaketh a lie, he speaketh of his own: for he is a liar, and the father of it.",
    "John 8:45": "And because I tell you the truth, ye believe me not.",
    "John 8:46": "Which of you convinceth me of sin? And if I say the truth, why do ye not believe me?",
    "John 8:47": "He that is of God heareth God's words: ye therefore hear them not, because ye are not of God.",
    "John 8:48": "Then answered the Jews, and said unto him, Say we not well that thou art a Samaritan, and hast a devil?",
    "John 8:49": "Jesus answered, I have not a devil; but I honour my Father, and ye do dishonour me.",
    "John 8:50": "And I seek not mine own glory: there is one that seeketh and judgeth.",
    "John 8:51": "Verily, verily, I say unto you, If a man keep my saying, he shall never see death.",
    "John 8:52": "Then said the Jews unto him, Now we know that thou hast a devil. Abraham is dead, and the prophets; and thou sayest, If a man keep my saying, he shall never taste of death.",
    "John 8:53": "Art thou greater than our father Abraham, which is dead? and the prophets are dead: whom makest thou thyself?",
    "John 8:54": "Jesus answered, If I honour myself, my honour is nothing: it is my Father that honoureth me; of whom ye say, that he is your God:",
    "John 8:55": "Yet ye have not known him; but I know him: and if I should say, I know him not, I shall be a liar like unto you: but I know him, and keep his saying.",
    "John 8:56": "Your father Abraham rejoiced to see my day: and he saw it, and was glad.",
    "John 8:57": "Then said the Jews unto him, Thou art not yet fifty years old, and hast thou seen Abraham?",
    "John 8:58": "Jesus said unto them, Verily, verily, I say unto you, Before Abraham was, I am.",
    "John 8:59": "Then took they up stones to cast at him: but Jesus hid himself, and went out of the temple, going through the midst of them, and so passed by.",
    
    // John 9 (King James Version)
    "John 9:1": "And as Jesus passed by, he saw a man which was blind from his birth.",
    "John 9:2": "And his disciples asked him, saying, Master, who did sin, this man, or his parents, that he was born blind?",
    "John 9:3": "Jesus answered, Neither hath this man sinned, nor his parents: but that the works of God should be made manifest in him.",
    "John 9:4": "I must work the works of him that sent me, while it is day: the night cometh, when no man can work.",
    "John 9:5": "As long as I am in the world, I am the light of the world.",
    "John 9:6": "When he had thus spoken, he spat on the ground, and made clay of the spittle, and he anointed the eyes of the blind man with the clay.",
    "John 9:7": "And said unto him, Go, wash in the pool of Siloam, (which is by interpretation, Sent.) He went his way therefore, and washed, and came seeing.",
    "John 9:8": "The neighbors therefore, and they which before had seen him that he was blind, said, Is not this he that sat and begged?",
    "John 9:9": "Some said, This is he: others said, He is like him: but he said, I am he.",
    "John 9:10": "Therefore said they unto him, How were thine eyes opened?",
    "John 9:11": "He answered and said, A man that is called Jesus made clay, and anointed mine eyes, and said unto me, Go to the pool of Siloam, and wash: and I went and washed, and I received sight.",
    "John 9:12": "Then said they unto him, Where is he? He said, I know not.",
    "John 9:13": "They brought to the Pharisees him that aforetime was blind.",
    "John 9:14": "And it was the sabbath day when Jesus made the clay, and opened his eyes.",
    "John 9:15": "Then again the Pharisees asked him how he had received his sight. He said unto them, He put clay upon mine eyes, and I washed, and do see.",
    "John 9:16": "Therefore said some of the Pharisees, This man is not of God, because he keepeth not the sabbath day. Others said, How can a man that is a sinner do such miracles? And there was a division among them.",
    "John 9:17": "They say unto the blind man again, What sayest thou of him, that he hath opened thine eyes? He said, He is a prophet.",
    "John 9:18": "But the Jews did not believe concerning him, that he had been blind, and received his sight, until they called the parents of him that had received his sight.",
    "John 9:19": "And they asked them, saying, Is this your son, who ye say was born blind? how then doth he now see?",
    "John 9:20": "His parents answered them and said, We know that this is our son, and that he was born blind:",
    "John 9:21": "But by what means he now seeth, we know not; or who hath opened his eyes, we know not: he is of age; ask him: he shall speak for himself.",
    "John 9:22": "These words spake his parents, because they feared the Jews: for the Jews had agreed already, that if any man did confess that he was Christ, he should be put out of the synagogue.",
    "John 9:23": "Therefore said his parents, He is of age; ask him.",
    "John 9:24": "Then again called they the man that was blind, and said unto him, Give God the praise: we know that this man is a sinner.",
    "John 9:25": "He answered and said, Whether he be a sinner or no, I know not: one thing I know, that, whereas I was blind, now I see.",
    "John 9:26": "Then said they to him again, What did he to thee? how opened he thine eyes?",
    "John 9:27": "He answered them, I have told you already, and ye did not hear: wherefore would ye hear it again? will ye also be his disciples?",
    "John 9:28": "Then they reviled him, and said, Thou art his disciple; but we are Moses' disciples.",
    "John 9:29": "We know that God spake unto Moses: as for this fellow, we know not from whence he is.",
    "John 9:30": "The man answered and said unto them, Why herein is a marvelous thing, that ye know not from whence he is, and yet he hath opened mine eyes.",
    "John 9:31": "Now we know that God heareth not sinners: but if any man be a worshipper of God, and doeth his will, him he heareth.",
    "John 9:32": "Since the world began was it not heard that any man opened the eyes of one that was born blind.",
    "John 9:33": "If this man were not of God, he could do nothing.",
    "John 9:34": "They answered and said unto him, Thou wast altogether born in sins, and dost thou teach us? And they cast him out.",
    "John 9:35": "Jesus heard that they had cast him out; and when he had found him, he said unto him, Dost thou believe on the Son of God?",
    "John 9:36": "He answered and said, Who is he, Lord, that I might believe on him?",
    "John 9:37": "And Jesus said unto him, Thou hast both seen him, and it is he that talketh with thee.",
    "John 9:38": "And he said, Lord, I believe. And he worshipped him.",
    "John 9:39": "And Jesus said, For judgment I am come into this world, that they which see not might see; and that they which see might be made blind.",
    "John 9:40": "And some of the Pharisees which were with him heard these words, and said unto him, Are we blind also?",
    "John 9:41": "Jesus said unto them, If ye were blind, ye should have no sin: but now ye say, We see; therefore your sin remaineth.",
    
    // John 10 (King James Version)
    "John 10:1": "Verily, verily, I say unto you, He that entereth not by the door into the sheepfold, but climbeth up some other way, the same is a thief and a robber.",
    "John 10:2": "But he that entereth in by the door is the shepherd of the sheep.",
    "John 10:3": "To him the porter openeth; and the sheep hear his voice: and he calleth his own sheep by name, and leadeth them out.",
    "John 10:4": "And when he putteth forth his own sheep, he goeth before them, and the sheep follow him: for they know his voice.",
    "John 10:5": "And a stranger will they not follow, but will flee from him: for they know not the voice of strangers.",
    "John 10:6": "This parable spake Jesus unto them: but they understood not what things they were which he spake unto them.",
    "John 10:7": "Then said Jesus unto them again, Verily, verily, I say unto you, I am the door of the sheep.",
    "John 10:8": "All that ever came before me are thieves and robbers: but the sheep did not hear them.",
    "John 10:9": "I am the door: by me if any man enter in, he shall be saved, and shall go in and out, and find pasture.",
    "John 10:10": "The thief cometh not, but for to steal, and to kill, and to destroy: I am come that they might have life, and that they might have it more abundantly.",
    "John 10:11": "I am the good shepherd: the good shepherd giveth his life for the sheep.",
    "John 10:12": "But he that is an hireling, and not the shepherd, whose own the sheep are not, seeth the wolf coming, and leaveth the sheep, and fleeth: and the wolf catcheth them, and scattereth the sheep.",
    "John 10:13": "The hireling fleeth, because he is an hireling, and careth not for the sheep.",
    "John 10:14": "I am the good shepherd, and know my sheep, and am known of mine.",
    "John 10:15": "As the Father knoweth me, even so know I the Father: and I lay down my life for the sheep.",
    "John 10:16": "And other sheep I have, which are not of this fold: them also I must bring, and they shall hear my voice; and there shall be one fold, and one shepherd.",
    "John 10:17": "Therefore doth my Father love me, because I lay down my life, that I might take it again.",
    "John 10:18": "No man taketh it from me, but I lay it down of myself. I have power to lay it down, and I have power to take it again. This commandment have I received of my Father.",
    "John 10:19": "There was a division therefore again among the Jews for these sayings.",
    "John 10:20": "And many of them said, He hath a devil, and is mad; why hear ye him?",
    "John 10:21": "Others said, These are not the words of him that hath a devil. Can a devil open the eyes of the blind?",
    "John 10:22": "And it was at Jerusalem the feast of the dedication, and it was winter.",
    "John 10:23": "And Jesus walked in the temple in Solomon's porch.",
    "John 10:24": "Then came the Jews round about him, and said unto him, How long dost thou make us to doubt? If thou be the Christ, tell us plainly.",
    "John 10:25": "Jesus answered them, I told you, and ye believed not: the works that I do in my Father's name, they bear witness of me.",
    "John 10:26": "But ye believe not, because ye are not of my sheep, as I said unto you.",
    "John 10:27": "My sheep hear my voice, and I know them, and they follow me.",
    "John 10:28": "And I give unto them eternal life; and they shall never perish, neither shall any man pluck them out of my hand.",
    "John 10:29": "My Father, which gave them me, is greater than all; and no man is able to pluck them out of my Father's hand.",
    "John 10:30": "I and my Father are one.",
    "John 10:31": "Then the Jews took up stones again to stone him.",
    "John 10:32": "Jesus answered them, Many good works have I showed you from my Father; for which of those works do ye stone me?",
    "John 10:33": "The Jews answered him, saying, For a good work we stone thee not; but for blasphemy; and because that thou, being a man, makest thyself God.",
    "John 10:34": "Jesus answered them, Is it not written in your law, I said, Ye are gods?",
    "John 10:35": "If he called them gods, unto whom the word of God came, and the scripture cannot be broken;",
    "John 10:36": "Say ye of him, whom the Father hath sanctified, and sent into the world, Thou blasphemest; because I said, I am the Son of God?",
    "John 10:37": "If I do not the works of my Father, believe me not.",
    "John 10:38": "But if I do, though ye believe not me, believe the works: that ye may know, and believe, that the Father is in me, and I in him.",
    "John 10:39": "Therefore they sought again to take him: but he escaped out of their hand.",
    "John 10:40": "And went away again beyond Jordan into the place where John at first baptized; and there he abode.",
    "John 10:41": "And many resorted unto him, and said, John did no miracle: but all things that John spake of this man were true.",
    "John 10:42": "And many believed on him there.",
    
    
    
    
    // John 20 (King James Version)
    "John 20:1": "The first day of the week cometh Mary Magdalene early, when it was yet dark, unto the sepulchre, and seeth the stone taken away from the sepulchre.",
    "John 20:2": "Then she runneth, and cometh to Simon Peter, and to the other disciple, whom Jesus loved, and saith unto them, They have taken away the Lord out of the sepulchre, and we know not where they have laid him.",
    "John 20:3": "Peter therefore went forth, and that other disciple, and came to the sepulchre.",
    "John 20:4": "So they ran both together: and the other disciple did outrun Peter, and came first to the sepulchre.",
    "John 20:5": "And he stooping down, and looking in, saw the linen clothes lying; yet went he not in.",
    "John 20:6": "Then cometh Simon Peter following him, and went into the sepulchre, and seeth the linen clothes lie,",
    "John 20:7": "And the napkin, that was about his head, not lying with the linen clothes, but wrapped together in a place by itself.",
    "John 20:8": "Then went in also that other disciple, which came first to the sepulchre, and he saw, and believed.",
    "John 20:9": "For as yet they knew not the scripture, that he must rise again from the dead.",
    "John 20:10": "Then the disciples went away again unto their own home.",
    "John 20:11": "But Mary stood without at the sepulchre weeping: and as she wept, she stooped down, and looked into the sepulchre,",
    "John 20:12": "And seeth two angels in white sitting, the one at the head, and the other at the feet, where the body of Jesus had lain.",
    "John 20:13": "And they say unto her, Woman, why weepest thou? She saith unto them, Because they have taken away my Lord, and I know not where they have laid him.",
    "John 20:14": "And when she had thus said, she turned herself back, and saw Jesus standing, and knew not that it was Jesus.",
    "John 20:15": "Jesus saith unto her, Woman, why weepest thou? whom seekest thou? She, supposing him to be the gardener, saith unto him, Sir, if thou have borne him hence, tell me where thou hast laid him, and I will take him away.",
    "John 20:16": "Jesus saith unto her, Mary. She turned herself, and saith unto him, Rabboni; which is to say, Master.",
    "John 20:17": "Jesus saith unto her, Touch me not; for I am not yet ascended to my Father: but go to my brethren, and say unto them, I ascend unto my Father, and your Father; and to my God, and your God.",
    "John 20:18": "Mary Magdalene came and told the disciples that she had seen the Lord, and that he had spoken these things unto her.",
    "John 20:19": "Then the same day at evening, being the first day of the week, when the doors were shut where the disciples were assembled for fear of the Jews, came Jesus and stood in the midst, and saith unto them, Peace be unto you.",
    "John 20:20": "And when he had so said, he shewed unto them his hands and his side. Then were the disciples glad, when they saw the Lord.",
    "John 20:21": "Then said Jesus to them again, Peace be unto you: as my Father hath sent me, even so send I you.",
    "John 20:22": "And when he had said this, he breathed on them, and saith unto them, Receive ye the Holy Ghost:",
    "John 20:23": "Whosoever sins ye remit, they are remitted unto them; and whosoever sins ye retain, they are retained.",
    "John 20:24": "But Thomas, one of the twelve, called Didymus, was not with them when Jesus came.",
    "John 20:25": "The other disciples therefore said unto him, We have seen the Lord. But he said unto them, Except I shall see in his hands the print of the nails, and put my finger into the print of the nails, and thrust my hand into his side, I will not believe.",
    "John 20:26": "And after eight days again his disciples were within, and Thomas with them: then came Jesus, the doors being shut, and stood in the midst, and said, Peace be unto you.",
    "John 20:27": "Then saith he to Thomas, Reach hither thy finger, and behold my hands; and reach hither thy hand, and thrust it into my side: and be not faithless, but believing.",
    "John 20:28": "And Thomas answered and said unto him, My Lord and my God.",
    "John 20:29": "Jesus saith unto him, Thomas, because thou hast seen me, thou hast believed: blessed are they that have not seen, and yet have believed.",
    "John 20:30": "And many other signs truly did Jesus in the presence of his disciples, which are not written in this book:",
    "John 20:31": "But these are written, that ye might believe that Jesus is the Christ, the Son of God; and that believing ye might have life through his name.",
    
    // John 21 (King James Version)
    "John 21:1": "After these things Jesus shewed himself again to the disciples at the sea of Tiberias; and on this wise shewed he himself.",
    "John 21:2": "There were together Simon Peter, and Thomas called Didymus, and Nathaniel of Cana in Galilee, and the sons of Zebedee, and two other of his disciples.",
    "John 21:3": "Simon Peter saith unto them, I go a fishing. They say unto him, We also go with thee. They went forth, and entered into a ship immediately; and that night they caught nothing.",
    "John 21:4": "But when the morning was now come, Jesus stood on the shore: but the disciples knew not that it was Jesus.",
    "John 21:5": "Then Jesus saith unto them, Children, have ye any meat? They answered him, No.",
    "John 21:6": "And he said unto them, Cast the net on the right side of the ship, and ye shall find. They cast therefore, and now they were not able to draw it for the multitude of fishes.",
    "John 21:7": "Therefore that disciple whom Jesus loved saith unto Peter, It is the Lord. Now when Simon Peter heard that it was the Lord, he girt his fisher's coat unto him, (for he was naked,) and did cast himself into the sea.",
    "John 21:8": "And the other disciples came in a little ship; (for they were not far from land, but as it were two hundred cubits,) dragging the net with fishes.",
    "John 21:9": "As soon then as they were come to land, they saw a fire of coals there, and fish laid thereon, and bread.",
    "John 21:10": "Jesus saith unto them, Bring of the fish which ye have now caught.",
    "John 21:11": "Simon Peter went up, and drew the net to land full of great fishes, an hundred and fifty and three: and for all there were so many, yet was not the net broken.",
    "John 21:12": "Jesus saith unto them, Come and dine. And none of the disciples durst ask him, Who art thou? knowing that it was the Lord.",
    "John 21:13": "Jesus then cometh, and taketh bread, and giveth them, and fish likewise.",
    "John 21:14": "This is now the third time that Jesus shewed himself to his disciples, after that he was risen from the dead.",
    "John 21:15": "So when they had dined, Jesus saith to Simon Peter, Simon, son of Jonas, lovest thou me more than these? He saith unto him, Yea, Lord; thou knowest that I love thee. He saith unto him, Feed my lambs.",
    "John 21:16": "He saith to him again the second time, Simon, son of Jonas, lovest thou me? He saith unto him, Yea, Lord; thou knowest that I love thee. He saith unto him, Feed my sheep.",
    "John 21:17": "He saith unto him the third time, Simon, son of Jonas, lovest thou me? Peter was grieved because he said unto him the third time, Lovest thou me? And he said unto him, Lord, thou knowest all things; thou knowest that I love thee. Jesus saith unto him, Feed my sheep.",
    "John 21:18": "Verily, verily, I say unto thee, When thou wast young, thou girdedst thyself, and walkedst whither thou wouldest: but when thou shalt be old, thou shalt stretch forth thy hands, and another shall gird thee, and carry thee whither thou wouldest not.",
    "John 21:19": "This spake he, signifying by what death he should glorify God. And when he had spoken this, he saith unto him, Follow me.",
    "John 21:20": "Then Peter, turning about, seeth the disciple whom Jesus loved following; which also leaned on his breast at supper, and said, Lord, which is he that betrayeth thee?",
    "John 21:21": "Peter seeing him saith to Jesus, Lord, and what shall this man do?",
    "John 21:22": "Jesus saith unto him, If I will that he tarry till I come, what is that to thee? follow thou me.",
    "John 21:23": "Then went this saying abroad among the brethren, that that disciple should not die: yet Jesus said not unto him, He shall not die; but, If I will that he tarry till I come, what is that to thee?",
    "John 21:24": "This is the disciple which testifieth of these things, and wrote these things: and we know that his testimony is true.",
    "John 21:25": "And there are also many other things which Jesus did, the which, if they should be written every one, I suppose that even the world itself could not contain the books that should be written. Amen."
};