const bibleVerses44 = {
    // Acts 1 (King James Version)
    "Acts 1:1": "The former treatise have I made, O Theophilus, of all that Jesus began both to do and teach,",
    "Acts 1:2": "Until the day in which he was taken up, after that he through the Holy Ghost had given commandments unto the apostles whom he had chosen:",
    "Acts 1:3": "To whom also he shewed himself alive after his passion by many infallible proofs, being seen of them forty days, and speaking of the things pertaining to the kingdom of God:",
    "Acts 1:4": "And, being assembled together with them, commanded them that they should not depart from Jerusalem, but wait for the promise of the Father, which, saith he, ye have heard of me.",
    "Acts 1:5": "For John truly baptized with water; but ye shall be baptized with the Holy Ghost not many days hence.",
    "Acts 1:6": "When they therefore were come together, they asked of him, saying, Lord, wilt thou at this time restore again the kingdom to Israel?",
    "Acts 1:7": "And he said unto them, It is not for you to know the times or the seasons, which the Father hath put in his own power.",
    "Acts 1:8": "But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me both in Jerusalem, and in all Judaea, and in Samaria, and unto the uttermost part of the earth.",
    "Acts 1:9": "And when he had spoken these things, while they beheld, he was taken up; and a cloud received him out of their sight.",
    "Acts 1:10": "And while they looked stedfastly toward heaven as he went up, behold, two men stood by them in white apparel;",
    "Acts 1:11": "Which also said, Ye men of Galilee, why stand ye gazing up into heaven? this same Jesus, which is taken up from you into heaven, shall so come in like manner as ye have seen him go into heaven.",
    "Acts 1:12": "Then returned they unto Jerusalem from the mount called Olivet, which is from Jerusalem a sabbath day's journey.",
    "Acts 1:13": "And when they were come in, they went up into an upper room, where abode both Peter, and James, and John, and Andrew, Philip, and Thomas, Bartholomew, and Matthew, James the son of Alphaeus, and Simon Zelotes, and Judas the brother of James.",
    "Acts 1:14": "These all continued with one accord in prayer and supplication, with the women, and Mary the mother of Jesus, and with his brethren.",
    "Acts 1:15": "And in those days Peter stood up in the midst of the disciples, and said, (the number of names together were about an hundred and twenty,)",
    "Acts 1:16": "Men and brethren, this scripture must needs have been fulfilled, which the Holy Ghost by the mouth of David spake before concerning Judas, which was guide to them that took Jesus.",
    "Acts 1:17": "For he was numbered with us, and had obtained part of this ministry.",
    "Acts 1:18": "Now this man purchased a field with the reward of iniquity; and falling headlong, he burst asunder in the midst, and all his bowels gushed out.",
    "Acts 1:19": "And it was known unto all the dwellers at Jerusalem; insomuch as that field is called in their proper tongue, Aceldama, that is to say, The field of blood.",
    "Acts 1:20": "For it is written in the book of Psalms, Let his habitation be desolate, and let no man dwell therein: and his bishoprick let another take.",
    "Acts 1:21": "Wherefore of these men which have accompanied with us all the time that the Lord Jesus went in and out among us,",
    "Acts 1:22": "Beginning from the baptism of John, unto that same day that he was taken up from us, must one be ordained to be a witness with us of his resurrection.",
    "Acts 1:23": "And they appointed two, Joseph called Barsabas, who was surnamed Justus, and Matthias.",
    "Acts 1:24": "And they prayed, and said, Thou, Lord, which knowest the hearts of all men, shew whether of these two thou hast chosen,",
    "Acts 1:25": "That he may take part of this ministry and apostleship, from which Judas by transgression fell, that he might go to his own place.",
    "Acts 1:26": "And they gave forth their lots; and the lot fell upon Matthias; and he was numbered with the eleven apostles.",
    
    // Acts 2 (King James Version)
    "Acts 2:1": "And when the day of Pentecost was fully come, they were all with one accord in one place.",
    "Acts 2:2": "And suddenly there came a sound from heaven as of a rushing mighty wind, and it filled all the house where they were sitting.",
    "Acts 2:3": "And there appeared unto them cloven tongues like as of fire, and it sat upon each of them.",
    "Acts 2:4": "And they were all filled with the Holy Ghost and began to speak with other tongues, as the Spirit gave them utterance.",
    "Acts 2:5": "And there were dwelling at Jerusalem Jews, devout men, out of every nation under heaven.",
    "Acts 2:6": "Now when this was noised abroad, the multitude came together, and were confounded, because that every man heard them speak in his own language.",
    "Acts 2:7": "And they were all amazed and marvelled, saying one to another, Behold, are not all these which speak Galileans?",
    "Acts 2:8": "And how hear we every man in our own tongue, wherein we were born?",
    "Acts 2:9": "Parthians, and Medes, and Elamites, and the dwellers in Mesopotamia, and in Judaea, and Cappadocia, in Pontus, and Asia,",
    "Acts 2:10": "Phrygia, and Pamphylia, in Egypt, and in the parts of Libya about Cyrene, and strangers of Rome, Jews and proselytes,",
    "Acts 2:11": "Cretes and Arabians, we do hear them speak in our tongues the wonderful works of God.",
    "Acts 2:12": "And they were all amazed, and were in doubt, saying one to another, What meaneth this?",
    "Acts 2:13": "Others mocking said, These men are full of new wine.",
    "Acts 2:14": "But Peter, standing up with the eleven, lifted up his voice, and said unto them, Ye men of Judaea, and all ye that dwell at Jerusalem, be this known unto you, and hearken to my words:",
    "Acts 2:15": "For these are not drunken, as ye suppose, seeing it is but the third hour of the day.",
    "Acts 2:16": "But this is that which was spoken by the prophet Joel;",
    "Acts 2:17": "And it shall come to pass in the last days, saith God, I will pour out of my Spirit upon all flesh: and your sons and your daughters shall prophesy, and your young men shall see visions, and your old men shall dream dreams:",
    "Acts 2:18": "And on my servants and on my handmaidens I will pour out in those days of my Spirit; and they shall prophesy:",
    "Acts 2:19": "And I will shew wonders in heaven above, and signs in the earth beneath; blood, and fire, and vapour of smoke:",
    "Acts 2:20": "The sun shall be turned into darkness, and the moon into blood, before that great and notable day of the Lord come:",
    "Acts 2:21": "And it shall come to pass, that whosoever shall call on the name of the Lord shall be saved.",
    "Acts 2:22": "Ye men of Israel, hear these words; Jesus of Nazareth, a man approved of God among you by miracles and wonders and signs, which God did by him in the midst of you, as ye yourselves also know:",
    "Acts 2:23": "Him, being delivered by the determinate counsel and foreknowledge of God, ye have taken, and by wicked hands have crucified and slain:",
    "Acts 2:24": "Whom God hath raised up, having loosed the pains of death: because it was not possible that he should be holden of it.",
    "Acts 2:25": "For David speaketh concerning him, I foresaw the Lord always before my face, for he is on my right hand, that I should not be moved:",
    "Acts 2:26": "Therefore did my heart rejoice, and my tongue was glad; moreover also my flesh shall rest in hope:",
    "Acts 2:27": "Because thou wilt not leave my soul in hell, neither wilt thou suffer thine Holy One to see corruption.",
    "Acts 2:28": "Thou hast made known to me the ways of life; thou shalt make me full of joy with thy countenance.",
    "Acts 2:29": "Men and brethren, let me freely speak unto you of the patriarch David, that he is both dead and buried, and his sepulchre is with us unto this day.",
    "Acts 2:30": "Therefore being a prophet, and knowing that God had sworn with an oath to him, that of the fruit of his loins, according to the flesh, he would raise up Christ to sit on his throne;",
    "Acts 2:31": "He seeing this before spake of the resurrection of Christ, that his soul was not left in hell, neither his flesh did see corruption.",
    "Acts 2:32": "This Jesus hath God raised up, whereof we all are witnesses.",
    "Acts 2:33": "Therefore being by the right hand of God exalted, and having received of the Father the promise of the Holy Ghost, he hath shed forth this, which ye now see and hear.",
    "Acts 2:34": "For David is not ascended into the heavens: but he saith himself, The Lord said unto my Lord, Sit thou on my right hand,",
    "Acts 2:35": "Until I make thy foes thy footstool.",
    "Acts 2:36": "Therefore let all the house of Israel know assuredly, that God hath made that same Jesus, whom ye have crucified, both Lord and Christ.",
    "Acts 2:37": "Now when they heard this, they were pricked in their heart, and said unto Peter and to the rest of the apostles, Men and brethren, what shall we do?",
    "Acts 2:38": "Then Peter said unto them, Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost.",
    "Acts 2:39": "For the promise is unto you, and to your children, and to all that are afar off, even as many as the Lord our God shall call.",
    "Acts 2:40": "And with many other words did he testify and exhort, saying, Save yourselves from this untoward generation.",
    "Acts 2:41": "Then they that gladly received his word were baptized: and the same day there were added unto them about three thousand souls.",
    "Acts 2:42": "And they continued stedfastly in the apostles' doctrine and fellowship, and in breaking of bread, and in prayers.",
    "Acts 2:43": "And fear came upon every soul: and many wonders and signs were done by the apostles.",
    "Acts 2:44": "And all that believed were together, and had all things common;",
    "Acts 2:45": "And sold their possessions and goods, and parted them to all men, as every man had need.",
    "Acts 2:46": "And they, continuing daily with one accord in the temple, and breaking bread from house to house, did eat their meat with gladness and singleness of heart,",
    "Acts 2:47": "Praising God, and having favour with all the people. And the Lord added to the church daily such as should be saved.",
    
    // Acts 3 (King James Version)
    "Acts 3:1": "Now Peter and John went up together into the temple at the hour of prayer, being the ninth hour.",
    "Acts 3:2": "And a certain man lame from his mother's womb was carried, whom they laid daily at the gate of the temple which is called Beautiful, to ask alms of them that entered into the temple;",
    "Acts 3:3": "Who seeing Peter and John about to go into the temple asked an alms.",
    "Acts 3:4": "And Peter, fastening his eyes upon him with John, said, Look on us.",
    "Acts 3:5": "And he gave heed unto them, expecting to receive something of them.",
    "Acts 3:6": "Then Peter said, Silver and gold have I none; but such as I have give I thee: In the name of Jesus Christ of Nazareth rise up and walk.",
    "Acts 3:7": "And he took him by the right hand, and lifted him up: and immediately his feet and ankle bones received strength.",
    "Acts 3:8": "And he leaping up stood, and walked, and entered with them into the temple, walking, and leaping, and praising God.",
    "Acts 3:9": "And all the people saw him walking and praising God:",
    "Acts 3:10": "And they knew that it was he which sat for alms at the Beautiful gate of the temple: and they were filled with wonder and amazement at that which had happened unto him.",
    "Acts 3:11": "And as the lame man which was healed held Peter and John, all the people ran together unto them in the porch that is called Solomon's, greatly wondering.",
    "Acts 3:12": "And when Peter saw it, he answered unto the people, Ye men of Israel, why marvel ye at this? or why look ye so earnestly on us, as though by our own power or holiness we had made this man to walk?",
    "Acts 3:13": "The God of Abraham, and of Isaac, and of Jacob, the God of our fathers, hath glorified his Son Jesus; whom ye delivered up, and denied him in the presence of Pilate, when he was determined to let him go.",
    "Acts 3:14": "But ye denied the Holy One and the Just, and desired a murderer to be granted unto you;",
    "Acts 3:15": "And killed the Prince of life, whom God hath raised from the dead; whereof we are witnesses.",
    "Acts 3:16": "And his name through faith in his name hath made this man strong, whom ye see and know: yea, the faith which is by him hath given him this perfect soundness in the presence of you all.",
    "Acts 3:17": "And now, brethren, I wot that through ignorance ye did it, as did also your rulers.",
    "Acts 3:18": "But those things, which God before had showed by the mouth of all his prophets, that Christ should suffer, he hath so fulfilled.",
    "Acts 3:19": "Repent ye therefore, and be converted, that your sins may be blotted out, when the times of refreshing shall come from the presence of the Lord;",
    "Acts 3:20": "And he shall send Jesus Christ, which before was preached unto you:",
    "Acts 3:21": "Whom the heaven must receive until the times of restitution of all things, which God hath spoken by the mouth of all his holy prophets since the world began.",
    "Acts 3:22": "For Moses truly said unto the fathers, A prophet shall the Lord your God raise up unto you of your brethren, like unto me; him shall ye hear in all things whatsoever he shall say unto you.",
    "Acts 3:23": "And it shall come to pass, that every soul, which will not hear that prophet, shall be destroyed from among the people.",
    "Acts 3:24": "Yea, and all the prophets from Samuel and those that follow after, as many as have spoken, have likewise foretold of these days.",
    "Acts 3:25": "Ye are the children of the prophets, and of the covenant which God made with our fathers, saying unto Abraham, And in thy seed shall all the kindreds of the earth be blessed.",
    "Acts 3:26": "Unto you first God, having raised up his Son Jesus, sent him to bless you, in turning away every one of you from his iniquities.",
    
    // Acts 4 (King James Version)
    "Acts 4:1": "And as they spake unto the people, the priests, and the captain of the temple, and the Sadducees, came upon them,",
    "Acts 4:2": "Being grieved that they taught the people, and preached through Jesus the resurrection from the dead.",
    "Acts 4:3": "And they laid hands on them, and put them in hold unto the next day: for it was now eventide.",
    "Acts 4:4": "Howbeit many of them which heard the word believed; and the number of the men was about five thousand.",
    "Acts 4:5": "And it came to pass on the morrow, that their rulers, and elders, and scribes,",
    "Acts 4:6": "And Annas the high priest, and Caiaphas, and John, and Alexander, and as many as were of the kindred of the high priest, were gathered together at Jerusalem.",
    "Acts 4:7": "And when they had set them in the midst, they asked, By what power, or by what name, have ye done this?",
    "Acts 4:8": "Then Peter, filled with the Holy Ghost, said unto them, Ye rulers of the people, and elders of Israel,",
    "Acts 4:9": "If we this day be examined of the good deed done to the impotent man, by what means he is made whole;",
    "Acts 4:10": "Be it known unto you all, and to all the people of Israel, that by the name of Jesus Christ of Nazareth, whom ye crucified, whom God raised from the dead, even by him doth this man stand here before you whole.",
    "Acts 4:11": "This is the stone which was set at nought of you builders, which is become the head of the corner.",
    "Acts 4:12": "Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved.",
    "Acts 4:13": "Now when they saw the boldness of Peter and John, and perceived that they were unlearned and ignorant men, they marveled; and they took knowledge of them, that they had been with Jesus.",
    "Acts 4:14": "And beholding the man which was healed standing with them, they could say nothing against it.",
    "Acts 4:15": "But when they had commanded them to go aside out of the council, they conferred among themselves,",
    "Acts 4:16": "Saying, What shall we do to these men? for that indeed a notable miracle hath been done by them is manifest to all them that dwell in Jerusalem; and we cannot deny it.",
    "Acts 4:17": "But that it spread no further among the people, let us straitly threaten them, that they speak henceforth to no man in this name.",
    "Acts 4:18": "And they called them, and commanded them not to speak at all nor teach in the name of Jesus.",
    "Acts 4:19": "But Peter and John answered and said unto them, Whether it be right in the sight of God to hearken unto you more than unto God, judge ye.",
    "Acts 4:20": "For we cannot but speak the things which we have seen and heard.",
    "Acts 4:21": "So when they had further threatened them, they let them go, finding nothing how they might punish them, because of the people: for all men glorified God for that which was done.",
    "Acts 4:22": "For the man was above forty years old, on whom this miracle of healing was shewed.",
    "Acts 4:23": "And being let go, they went to their own company, and reported all that the chief priests and elders had said unto them.",
    "Acts 4:24": "And when they heard that, they lifted up their voice to God with one accord, and said, Lord, thou art God, which hast made heaven, and earth, and the sea, and all that in them is:",
    "Acts 4:25": "Who by the mouth of thy servant David hast said, Why did the heathen rage, and the people imagine vain things?",
    "Acts 4:26": "The kings of the earth stood up, and the rulers were gathered together against the Lord, and against his Christ.",
    "Acts 4:27": "For of a truth against thy holy child Jesus, whom thou hast anointed, both Herod, and Pontius Pilate, with the Gentiles, and the people of Israel, were gathered together,",
    "Acts 4:28": "For to do whatsoever thy hand and thy counsel determined before to be done.",
    "Acts 4:29": "And now, Lord, behold their threatenings: and grant unto thy servants, that with all boldness they may speak thy word,",
    "Acts 4:30": "By stretching forth thine hand to heal; and that signs and wonders may be done by the name of thy holy child Jesus.",
    "Acts 4:31": "And when they had prayed, the place was shaken where they were assembled together; and they were all filled with the Holy Ghost, and they spake the word of God with boldness.",
    "Acts 4:32": "And the multitude of them that believed were of one heart and of one soul: neither said any of them that ought of the things which he possessed was his own; but they had all things common.",
    "Acts 4:33": "And with great power gave the apostles witness of the resurrection of the Lord Jesus: and great grace was upon them all.",
    "Acts 4:34": "Neither was there any among them that lacked: for as many as were possessors of lands or houses sold them, and brought the prices of the things that were sold,",
    "Acts 4:35": "And laid them down at the apostles' feet: and distribution was made unto every man according as he had need.",
    "Acts 4:36": "And Joses, who by the apostles was surnamed Barnabas, (which is, being interpreted, The son of consolation,) a Levite, and of the country of Cyprus,",
    "Acts 4:37": "Having land, sold it, and brought the money, and laid it at the apostles' feet.",
    
    // Acts 5 (King James Version)
    "Acts 5:1": "But a certain man named Ananias, with Sapphira his wife, sold a possession,",
    "Acts 5:2": "And kept back part of the price, his wife also being privy to it, and brought a certain part, and laid it at the apostles' feet.",
    "Acts 5:3": "But Peter said, Ananias, why hath Satan filled thine heart to lie to the Holy Ghost, and to keep back part of the price of the land?",
    "Acts 5:4": "Whiles it remained, was it not thine own? and after it was sold, was it not in thine own power? why hast thou conceived this thing in thine heart? thou hast not lied unto men, but unto God.",
    "Acts 5:5": "And Ananias hearing these words fell down, and gave up the ghost: and great fear came on all them that heard these things.",
    "Acts 5:6": "And the young men arose, wound him up, and carried him out, and buried him.",
    "Acts 5:7": "And it was about the space of three hours after, when his wife, not knowing what was done, came in.",
    "Acts 5:8": "And Peter answered unto her, Tell me whether ye sold the land for so much? And she said, Yea, for so much.",
    "Acts 5:9": "Then Peter said unto her, How is it that ye have agreed together to tempt the Spirit of the Lord? behold, the feet of them which have buried thy husband are at the door, and shall carry thee out.",
    "Acts 5:10": "Then fell she down straightway at his feet, and yielded up the ghost: and the young men came in and found her dead, and, carrying her forth, buried her by her husband.",
    "Acts 5:11": "And great fear came upon all the church, and upon as many as heard these things.",
    "Acts 5:12": "And by the hands of the apostles were many signs and wonders wrought among the people; and they were all with one accord in Solomon's porch.",
    "Acts 5:13": "And of the rest durst no man join himself to them: but the people magnified them.",
    "Acts 5:14": "And believers were the more added to the Lord, multitudes both of men and women.)",
    "Acts 5:15": "Insomuch that they brought forth the sick into the streets, and laid them on beds and couches, that at the least the shadow of Peter passing by might overshadow some of them.",
    "Acts 5:16": "There came also a multitude out of the cities round about unto Jerusalem, bringing sick folks, and them which were vexed with unclean spirits: and they were healed every one.",
    "Acts 5:17": "Then the high priest rose up, and all they that were with him, (which is the sect of the Sadducees,) and were filled with indignation,",
    "Acts 5:18": "And laid their hands on the apostles, and put them in the common prison.",
    "Acts 5:19": "But the angel of the Lord by night opened the prison doors, and brought them forth, and said,",
    "Acts 5:20": "Go, stand and speak in the temple to the people all the words of this life.",
    "Acts 5:21": "And when they heard that, they entered into the temple early in the morning, and taught. But the high priest came, and they that were with him, and called the council together, and all the senate of the children of Israel, and sent to the prison to have them brought.",
    "Acts 5:22": "But when the officers came, and found them not in the prison, they returned, and told,",
    "Acts 5:23": "Saying, The prison truly found we shut with all safety, and the keepers standing without before the doors: but when we had opened, we found no man within.",
    "Acts 5:24": "Now when the high priest and the captain of the temple and the chief priests heard these things, they doubted of them whereunto this would grow.",
    "Acts 5:25": "Then came one and told them, saying, Behold, the men whom ye put in prison are standing in the temple, and teaching the people.",
    "Acts 5:26": "Then went the captain with the officers, and brought them without violence: for they feared the people, lest they should have been stoned.",
    "Acts 5:27": "And when they had brought them, they set them before the council: and the high priest asked them,",
    "Acts 5:28": "Saying, Did not we straitly command you that ye should not teach in this name? and, behold, ye have filled Jerusalem with your doctrine, and intend to bring this man's blood upon us.",
    "Acts 5:29": "Then Peter and the other apostles answered and said, We ought to obey God rather than men.",
    "Acts 5:30": "The God of our fathers raised up Jesus, whom ye slew and hanged on a tree.",
    "Acts 5:31": "Him hath God exalted with his right hand to be a Prince and a Saviour, for to give repentance to Israel, and forgiveness of sins.",
    "Acts 5:32": "And we are his witnesses of these things; and so is also the Holy Ghost, whom God hath given to them that obey him.",
    "Acts 5:33": "When they heard that, they were cut to the heart, and took counsel to slay them.",
    "Acts 5:34": "Then stood there up one in the council, a Pharisee, named Gamaliel, a doctor of the law, had in reputation among all the people, and commanded to put the apostles forth a little space;",
    "Acts 5:35": "And said unto them, Ye men of Israel, take heed to yourselves what ye intend to do as touching these men.",
    "Acts 5:36": "For before these days rose up Theudas, boasting himself to be somebody; to whom a number of men, about four hundred, joined themselves: who was slain; and all, as many as obeyed him, were scattered, and brought to nought.",
    "Acts 5:37": "After this man rose up Judas of Galilee in the days of the taxing, and drew away much people after him: he also perished; and all, even as many as obeyed him, were dispersed.",
    "Acts 5:38": "And now I say unto you, Refrain from these men, and let them alone: for if this counsel or this work be of men, it will come to nought:",
    "Acts 5:39": "But if it be of God, ye cannot overthrow it; lest haply ye be found even to fight against God.",
    "Acts 5:40": "And to him they agreed: and when they had called the apostles, and beaten them, they commanded that they should not speak in the name of Jesus, and let them go.",
    "Acts 5:41": "And they departed from the presence of the council, rejoicing that they were counted worthy to suffer shame for his name.",
    "Acts 5:42": "And daily in the temple, and in every house, they ceased not to teach and preach Jesus Christ.",
    
    // Acts 6 (King James Version)
    "Acts 6:1": "And in those days, when the number of the disciples was multiplied, there arose a murmuring of the Grecians against the Hebrews, because their widows were neglected in the daily ministration.",
    "Acts 6:2": "Then the twelve called the multitude of the disciples unto them, and said, It is not reason that we should leave the word of God, and serve tables.",
    "Acts 6:3": "Wherefore, brethren, look ye out among you seven men of honest report, full of the Holy Ghost and wisdom, whom we may appoint over this business.",
    "Acts 6:4": "But we will give ourselves continually to prayer, and to the ministry of the word.",
    "Acts 6:5": "And the saying pleased the whole multitude: and they chose Stephen, a man full of faith and of the Holy Ghost, and Philip, and Prochorus, and Nicanor, and Timon, and Parmenas, and Nicolas a proselyte of Antioch:",
    "Acts 6:6": "Whom they set before the apostles: and when they had prayed, they laid their hands on them.",
    "Acts 6:7": "And the word of God increased; and the number of the disciples multiplied in Jerusalem greatly; and a great company of the priests were obedient to the faith.",
    "Acts 6:8": "And Stephen, full of faith and power, did great wonders and miracles among the people.",
    "Acts 6:9": "Then there arose certain of the synagogue, which is called the synagogue of the Libertines, and Cyrenians, and Alexandrians, and of them of Cilicia and of Asia, disputing with Stephen.",
    "Acts 6:10": "And they were not able to resist the wisdom and the spirit by which he spake.",
    "Acts 6:11": "Then they suborned men, which said, We have heard him speak blasphemous words against Moses, and against God.",
    "Acts 6:12": "And they stirred up the people, and the elders, and the scribes, and came upon him, and caught him, and brought him to the council,",
    "Acts 6:13": "And set up false witnesses, which said, This man ceaseth not to speak blasphemous words against this holy place, and the law:",
    "Acts 6:14": "For we have heard him say, that this Jesus of Nazareth shall destroy this place, and shall change the customs which Moses delivered us.",
    "Acts 6:15": "And all that sat in the council, looking stedfastly on him, saw his face as it had been the face of an angel.",
    
    // Acts 7 (King James Version)
    "Acts 7:1": "Then said the high priest, Are these things so?",
    "Acts 7:2": "And he said, Men, brethren, and fathers, hearken; The God of glory appeared unto our father Abraham, when he was in Mesopotamia, before he dwelt in Charran,",
    "Acts 7:3": "And said unto him, Get thee out of thy country, and from thy kindred, and come into the land which I shall shew thee.",
    "Acts 7:4": "Then came he out of the land of the Chaldeans, and dwelt in Charran: and from thence, when his father was dead, he removed him into this land, wherein ye now dwell.",
    "Acts 7:5": "And he gave him none inheritance in it, no, not so much as to set his foot on: yet he promised that he would give it to him for a possession, and to his seed after him, when as yet he had no child.",
    "Acts 7:6": "And God spake on this wise, That his seed should sojourn in a strange land; and that they should bring them into bondage, and entreat them evil four hundred years.",
    "Acts 7:7": "And the nation to whom they shall be in bondage will I judge, said God: and after that shall they come forth, and serve me in this place.",
    "Acts 7:8": "And he gave him the covenant of circumcision: and so Abraham begat Isaac, and circumcised him the eighth day; and Isaac begat Jacob; and Jacob begat the twelve patriarchs.",
    "Acts 7:9": "And the patriarchs, moved with envy, sold Joseph into Egypt: but God was with him,",
    "Acts 7:10": "And delivered him out of all his afflictions, and gave him favour and wisdom in the sight of Pharaoh king of Egypt; and he made him governor over Egypt and all his house.",
    "Acts 7:11": "Now there came a dearth over all the land of Egypt and Chanaan, and great affliction: and our fathers found no sustenance.",
    "Acts 7:12": "But when Jacob heard that there was corn in Egypt, he sent out our fathers first.",
    "Acts 7:13": "And at the second time Joseph was made known to his brethren; and Joseph's kindred was made known unto Pharaoh.",
    "Acts 7:14": "Then sent Joseph, and called his father Jacob to him, and all his kindred, threescore and fifteen souls.",
    "Acts 7:15": "So Jacob went down into Egypt, and died, he, and our fathers,",
    "Acts 7:16": "And were carried over into Sychem, and laid in the sepulchre that Abraham bought for a sum of money of the sons of Emmor the father of Sychem.",
    "Acts 7:17": "But when the time of the promise drew nigh, which God had sworn to Abraham, the people grew and multiplied in Egypt,",
    "Acts 7:18": "Till another king arose, which knew not Joseph.",
    "Acts 7:19": "The same dealt subtly with our kindred, and evilly entreated our fathers, so that they cast out their young children, to the end they might not live.",
    "Acts 7:20": "In which time Moses was born, and was exceeding fair, and nourished up in his father's house three months:",
    "Acts 7:21": "And when he was cast out, Pharaoh's daughter took him up, and nourished him for her own son.",
    "Acts 7:22": "And Moses was learned in all the wisdom of the Egyptians, and was mighty in words and in deeds.",
    "Acts 7:23": "And when he was full forty years old, it came into his heart to visit his brethren the children of Israel.",
    "Acts 7:24": "And seeing one of them suffer wrong, he defended him, and avenged him that was oppressed, and smote the Egyptian:",
    "Acts 7:25": "For he supposed his brethren would have understood how that God by his hand would deliver them: but they understood not.",
    "Acts 7:26": "And the next day he shewed himself unto them as they strove, and would have set them at one again, saying, Sirs, ye are brethren; why do ye wrong one to another?",
    "Acts 7:27": "But he that did his neighbour wrong thrust him away, saying, Who made thee a ruler and a judge over us?",
    "Acts 7:28": "Wilt thou kill me, as thou didst the Egyptian yesterday?",
    "Acts 7:29": "Then fled Moses at this saying, and was a stranger in the land of Midian, where he begat two sons.",
    "Acts 7:30": "And when forty years were expired, there appeared to him in the wilderness of mount Sinai an angel of the Lord in a flame of fire in a bush.",
    "Acts 7:31": "When Moses saw it, he wondered at the sight: and as he drew near to behold it, the voice of the Lord came unto him,",
    "Acts 7:32": "Saying, I am the God of thy fathers, the God of Abraham, and the God of Isaac, and the God of Jacob. Then Moses trembled, and durst not behold.",
    "Acts 7:33": "Then said the Lord to him, Put off thy shoes from thy feet: for the place where thou standest is holy ground.",
    "Acts 7:34": "I have seen, I have seen the affliction of my people which is in Egypt, and I have heard their groaning, and am come down to deliver them. And now come, I will send thee into Egypt.",
    "Acts 7:35": "This Moses whom they refused, saying, Who made thee a ruler and a judge? the same did God send to be a ruler and a deliverer by the hand of the angel which appeared to him in the bush.",
    "Acts 7:36": "He brought them out, after that he had shewed wonders and signs in the land of Egypt, and in the Red sea, and in the wilderness forty years.",
    "Acts 7:37": "This is that Moses, which said unto the children of Israel, A prophet shall the Lord your God raise up unto you of your brethren, like unto me; him shall ye hear.",
    "Acts 7:38": "This is he, that was in the church in the wilderness with the angel which spake to him in the mount Sina, and with our fathers: who received the lively oracles to give unto us:",
    "Acts 7:39": "To whom our fathers would not obey, but thrust him from them, and in their hearts turned back again into Egypt,",
    "Acts 7:40": "Saying unto Aaron, Make us gods to go before us: for as for this Moses, which brought us out of the land of Egypt, we wot not what is become of him.",
    "Acts 7:41": "And they made a calf in those days, and offered sacrifice unto the idol, and rejoiced in the works of their own hands.",
    "Acts 7:42": "Then God turned, and gave them up to worship the host of heaven; as it is written in the book of the prophets, O ye house of Israel, have ye offered to me slain beasts and sacrifices by the space of forty years in the wilderness?",
    "Acts 7:43": "Yea, ye took up the tabernacle of Moloch, and the star of your god Remphan, figures which ye made to worship them: and I will carry you away beyond Babylon.",
    "Acts 7:44": "Our fathers had the tabernacle of witness in the wilderness, as he had appointed, speaking unto Moses, that he should make it according to the fashion that he had seen.",
    "Acts 7:45": "Which also our fathers that came after brought in with Jesus into the possession of the Gentiles, whom God drave out before the face of our fathers unto the days of David;",
    "Acts 7:46": "Who found favour before God, and desired to find a tabernacle for the God of Jacob.",
    "Acts 7:47": "But Solomon built him a house.",
    "Acts 7:48": "Howbeit the most High dwelleth not in temples made with hands; as saith the prophet,",
    "Acts 7:49": "Heaven is my throne, and earth is my footstool: what house will ye build me? saith the Lord: or what is the place of my rest?",
    "Acts 7:50": "Hath not my hand made all these things?",
    "Acts 7:51": "Ye stiffnecked and uncircumcised in heart and ears, ye do always resist the Holy Ghost: as your fathers did, so do ye.",
    "Acts 7:52": "Which of the prophets have not your fathers persecuted? and they have slain them which shewed before of the coming of the Just One; of whom ye have been now the betrayers and murderers:",
    "Acts 7:53": "Who have received the law by the disposition of angels, and have not kept it.",
    "Acts 7:54": "When they heard these things, they were cut to the heart, and they gnashed on him with their teeth.",
    "Acts 7:55": "But he, being full of the Holy Ghost, looked up stedfastly into heaven, and saw the glory of God, and Jesus standing on the right hand of God,",
    "Acts 7:56": "And said, Behold, I see the heavens opened, and the Son of man standing on the right hand of God.",
    "Acts 7:57": "Then they cried out with a loud voice, and stopped their ears, and ran upon him with one accord,",
    "Acts 7:58": "And cast him out of the city, and stoned him: and the witnesses laid down their clothes at a young man's feet, whose name was Saul.",
    "Acts 7:59": "And they stoned Stephen, calling upon God, and saying, Lord Jesus, receive my spirit.",
    "Acts 7:60": "And he kneeled down, and cried with a loud voice, Lord, lay not this sin to their charge. And when he had said this, he fell asleep.",
    
    // Acts 8 (King James Version)
    "Acts 8:1": "And Saul was consenting unto his death. And at that time there was a great persecution against the church which was at Jerusalem; and they were all scattered abroad throughout the regions of Judaea and Samaria, except the apostles.",
    "Acts 8:2": "And devout men carried Stephen to his burial, and made great lamentation over him.",
    "Acts 8:3": "As for Saul, he made havock of the church, entering into every house, and hailing men and women committed them to prison.",
    "Acts 8:4": "Therefore they that were scattered abroad went every where preaching the word.",
    "Acts 8:5": "Then Philip went down to the city of Samaria, and preached Christ unto them.",
    "Acts 8:6": "And the people with one accord gave heed unto those things which Philip spake, hearing and seeing the miracles which he did.",
    "Acts 8:7": "For unclean spirits, crying with loud voice, came out of many that were possessed with them: and many taken with palsies, and that were lame, were healed.",
    "Acts 8:8": "And there was great joy in that city.",
    "Acts 8:9": "But there was a certain man, called Simon, which beforetime in the same city used sorcery, and bewitched the people of Samaria, giving out that himself was some great one:",
    "Acts 8:10": "To whom they all gave heed, from the least to the greatest, saying, This man is the great power of God.",
    "Acts 8:11": "And to him they had regard, because that of long time he had bewitched them with sorceries.",
    "Acts 8:12": "But when they believed Philip preaching the things concerning the kingdom of God, and the name of Jesus Christ, they were baptized, both men and women.",
    "Acts 8:13": "Then Simon himself believed also: and when he was baptized, he continued with Philip, and wondered, beholding the miracles and signs which were done.",
    "Acts 8:14": "Now when the apostles which were at Jerusalem heard that Samaria had received the word of God, they sent unto them Peter and John:",
    "Acts 8:15": "Who, when they were come down, prayed for them, that they might receive the Holy Ghost:",
    "Acts 8:16": "(For as yet he was fallen upon none of them: only they were baptized in the name of the Lord Jesus.)",
    "Acts 8:17": "Then laid they their hands on them, and they received the Holy Ghost.",
    "Acts 8:18": "And when Simon saw that through laying on of the apostles' hands the Holy Ghost was given, he offered them money,",
    "Acts 8:19": "Saying, Give me also this power, that on whomsoever I lay hands, he may receive the Holy Ghost.",
    "Acts 8:20": "But Peter said unto him, Thy money perish with thee, because thou hast thought that the gift of God may be purchased with money.",
    "Acts 8:21": "Thou hast neither part nor lot in this matter: for thy heart is not right in the sight of God.",
    "Acts 8:22": "Repent therefore of this thy wickedness, and pray God, if perhaps the thought of thine heart may be forgiven thee.",
    "Acts 8:23": "For I perceive that thou art in the gall of bitterness, and in the bond of iniquity.",
    "Acts 8:24": "Then answered Simon, and said, Pray ye to the Lord for me, that none of these things which ye have spoken come upon me.",
    "Acts 8:25": "And they, when they had testified and preached the word of the Lord, returned to Jerusalem, and preached the gospel in many villages of the Samaritans.",
    "Acts 8:26": "And the angel of the Lord spake unto Philip, saying, Arise, and go toward the south unto the way that goeth down from Jerusalem unto Gaza, which is desert.",
    "Acts 8:27": "And he arose and went: and, behold, a man of Ethiopia, an eunuch of great authority under Candace, queen of the Ethiopians, who had the charge of all her treasure, and had come to Jerusalem for to worship,",
    "Acts 8:28": "Was returning, and sitting in his chariot read Esaias the prophet.",
    "Acts 8:29": "Then the Spirit said unto Philip, Go near, and join thyself to this chariot.",
    "Acts 8:30": "And Philip ran thither to him, and heard him read the prophet Esaias, and said, Understandest thou what thou readest?",
    "Acts 8:31": "And he said, How can I, except some man should guide me? And he desired Philip that he would come up and sit with him.",
    "Acts 8:32": "The place of the scripture which he read was this, He was led as a sheep to the slaughter; and like a lamb dumb before his shearer, so opened he not his mouth:",
    "Acts 8:33": "In his humiliation his judgment was taken away: and who shall declare his generation? for his life is taken from the earth.",
    "Acts 8:34": "And the eunuch answered Philip, and said, I pray thee, of whom speaketh the prophet this? of himself, or of some other man?",
    "Acts 8:35": "Then Philip opened his mouth, and began at the same scripture, and preached unto him Jesus.",
    "Acts 8:36": "And as they went on their way, they came unto a certain water: and the eunuch said, See, here is water; what doth hinder me to be baptized?",
    "Acts 8:37": "And Philip said, If thou believest with all thine heart, thou mayest. And he answered and said, I believe that Jesus Christ is the Son of God.",
    "Acts 8:38": "And he commanded the chariot to stand still: and they went down both into the water, both Philip and the eunuch; and he baptized him.",
    "Acts 8:39": "And when they were come up out of the water, the Spirit of the Lord caught away Philip, that the eunuch saw him no more: and he went on his way rejoicing.",
    "Acts 8:40": "But Philip was found at Azotus: and passing through he preached in all the cities, till he came to Caesarea.",
    
    // Acts 9 (King James Version)
    "Acts 9:1": "And Saul, yet breathing out threatenings and slaughter against the disciples of the Lord, went unto the high priest,",
    "Acts 9:2": "And desired of him letters to Damascus to the synagogues, that if he found any of this way, whether they were men or women, he might bring them bound unto Jerusalem.",
    "Acts 9:3": "And as he journeyed, he came near Damascus: and suddenly there shined round about him a light from heaven:",
    "Acts 9:4": "And he fell to the earth, and heard a voice saying unto him, Saul, Saul, why persecutest thou me?",
    "Acts 9:5": "And he said, Who art thou, Lord? And the Lord said, I am Jesus whom thou persecutest: it is hard for thee to kick against the pricks.",
    "Acts 9:6": "And he trembling and astonished said, Lord, what wilt thou have me to do? And the Lord said unto him, Arise, and go into the city, and it shall be told thee what thou must do.",
    "Acts 9:7": "And the men which journeyed with him stood speechless, hearing a voice, but seeing no man.",
    "Acts 9:8": "And Saul arose from the earth; and when his eyes were opened, he saw no man: but they led him by the hand, and brought him into Damascus.",
    "Acts 9:9": "And he was three days without sight, and neither did eat nor drink.",
    "Acts 9:10": "And there was a certain disciple at Damascus, named Ananias; and to him said the Lord in a vision, Ananias. And he said, Behold, I am here, Lord.",
    "Acts 9:11": "And the Lord said unto him, Arise, and go into the street which is called Straight, and inquire in the house of Judas for one called Saul, of Tarsus: for, behold, he prayeth,",
    "Acts 9:12": "And hath seen in a vision a man named Ananias coming in, and putting his hand on him, that he might receive his sight.",
    "Acts 9:13": "Then Ananias answered, Lord, I have heard by many of this man, how much evil he hath done to thy saints at Jerusalem:",
    "Acts 9:14": "And here he hath authority from the chief priests to bind all that call on thy name.",
    "Acts 9:15": "But the Lord said unto him, Go thy way: for he is a chosen vessel unto me, to bear my name before the Gentiles, and kings, and the children of Israel:",
    "Acts 9:16": "For I will shew him how great things he must suffer for my name's sake.",
    "Acts 9:17": "And Ananias went his way, and entered into the house; and putting his hands on him said, Brother Saul, the Lord, even Jesus, that appeared unto thee in the way as thou camest, hath sent me, that thou mightest receive thy sight, and be filled with the Holy Ghost.",
    "Acts 9:18": "And immediately there fell from his eyes as it had been scales: and he received sight forthwith, and arose, and was baptized.",
    "Acts 9:19": "And when he had received meat, he was strengthened. Then was Saul certain days with the disciples which were at Damascus.",
    "Acts 9:20": "And straightway he preached Christ in the synagogues, that he is the Son of God.",
    "Acts 9:21": "But all that heard him were amazed, and said; Is not this he that destroyed them which called on this name in Jerusalem, and came hither for that intent, that he might bring them bound unto the chief priests?",
    "Acts 9:22": "But Saul increased the more in strength, and confounded the Jews which dwelt at Damascus, proving that this is very Christ.",
    "Acts 9:23": "And after that many days were fulfilled, the Jews took counsel to kill him:",
    "Acts 9:24": "But their laying await was known of Saul. And they watched the gates day and night to kill him.",
    "Acts 9:25": "Then the disciples took him by night, and let him down by the wall in a basket.",
    "Acts 9:26": "And when Saul was come to Jerusalem, he assayed to join himself to the disciples: but they were all afraid of him, and believed not that he was a disciple.",
    "Acts 9:27": "But Barnabas took him, and brought him to the apostles, and declared unto them how he had seen the Lord in the way, and that he had spoken to him, and how he had preached boldly at Damascus in the name of Jesus.",
    "Acts 9:28": "And he was with them coming in and going out at Jerusalem.",
    "Acts 9:29": "And he spake boldly in the name of the Lord Jesus, and disputed against the Grecians: but they went about to slay him.",
    "Acts 9:30": "Which when the brethren knew, they brought him down to Caesarea, and sent him forth to Tarsus.",
    "Acts 9:31": "Then had the churches rest throughout all Judaea and Galilee and Samaria, and were edified; and walking in the fear of the Lord, and in the comfort of the Holy Ghost, were multiplied.",
    "Acts 9:32": "And it came to pass, as Peter passed throughout all quarters, he came down also to the saints which dwelt at Lydda.",
    "Acts 9:33": "And there he found a certain man named Aeneas, which had kept his bed eight years, and was sick of the palsy.",
    "Acts 9:34": "And Peter said unto him, Aeneas, Jesus Christ maketh thee whole: arise, and make thy bed. And he arose immediately.",
    "Acts 9:35": "And all that dwelt at Lydda and Saron saw him, and turned to the Lord.",
    "Acts 9:36": "Now there was at Joppa a certain disciple named Tabitha, which by interpretation is called Dorcas: this woman was full of good works and almsdeeds which she did.",
    "Acts 9:37": "And it came to pass in those days, that she was sick, and died: whom when they had washed, they laid her in an upper chamber.",
    "Acts 9:38": "And forasmuch as Lydda was nigh to Joppa, and the disciples had heard that Peter was there, they sent unto him two men, desiring him that he would not delay to come to them.",
    "Acts 9:39": "Then Peter arose and went with them. When he was come, they brought him into the upper chamber: and all the widows stood by him weeping, and shewing the coats and garments which Dorcas made, while she was with them.",
    "Acts 9:40": "But Peter put them all forth, and kneeled down, and prayed; and turning him to the body said, Tabitha, arise. And she opened her eyes: and when she saw Peter, she sat up.",
    "Acts 9:41": "And he gave her his hand, and lifted her up, and when he had called the saints and widows, presented her alive.",
    "Acts 9:42": "And it was known throughout all Joppa; and many believed in the Lord.",
    "Acts 9:43": "And it came to pass, that he tarried many days in Joppa with one Simon a tanner.",
    
    // Acts 10 (King James Version)
    "Acts 10:1": "There was a certain man in Caesarea called Cornelius, a centurion of the band called the Italian band,",
    "Acts 10:2": "A devout man, and one that feared God with all his house, which gave much alms to the people, and prayed to God alway.",
    "Acts 10:3": "He saw in a vision evidently about the ninth hour of the day an angel of God coming in to him, and saying unto him, Cornelius.",
    "Acts 10:4": "And when he looked on him, he was afraid, and said, What is it, Lord? And he said unto him, Thy prayers and thine alms are come up for a memorial before God.",
    "Acts 10:5": "And now send men to Joppa, and call for one Simon, whose surname is Peter:",
    "Acts 10:6": "He lodgeth with one Simon a tanner, whose house is by the sea side: he shall tell thee what thou oughtest to do.",
    "Acts 10:7": "And when the angel which spake unto Cornelius was departed, he called two of his household servants, and a devout soldier of them that waited on him continually;",
    "Acts 10:8": "And when he had declared all these things unto them, he sent them to Joppa.",
    "Acts 10:9": "On the morrow, as they went on their journey, and drew nigh unto the city, Peter went up upon the housetop to pray about the sixth hour:",
    "Acts 10:10": "And he became very hungry, and would have eaten: but while they made ready, he fell into a trance,",
    "Acts 10:11": "And saw heaven opened, and a certain vessel descending unto him, as it had been a great sheet knit at the four corners, and let down to the earth:",
    "Acts 10:12": "Wherein were all manner of fourfooted beasts of the earth, and wild beasts, and creeping things, and fowls of the air.",
    "Acts 10:13": "And there came a voice to him, Rise, Peter; kill, and eat.",
    "Acts 10:14": "But Peter said, Not so, Lord; for I have never eaten any thing that is common or unclean.",
    "Acts 10:15": "And the voice spake unto him again the second time, What God hath cleansed, that call not thou common.",
    "Acts 10:16": "This was done thrice: and the vessel was received up again into heaven.",
    "Acts 10:17": "Now while Peter doubted in himself what this vision which he had seen should mean, behold, the men which were sent from Cornelius had made inquiry for Simon's house, and stood before the gate,",
    "Acts 10:18": "And called, and asked whether Simon, which was surnamed Peter, were lodged there.",
    "Acts 10:19": "While Peter thought on the vision, the Spirit said unto him, Behold, three men seek thee.",
    "Acts 10:20": "Arise therefore, and get thee down, and go with them, doubting nothing: for I have sent them.",
    "Acts 10:21": "Then Peter went down to the men which were sent unto him from Cornelius; and said, Behold, I am he whom ye seek: what is the cause wherefore ye are come?",
    "Acts 10:22": "And they said, Cornelius the centurion, a just man, and one that feareth God, and of good report among all the nation of the Jews, was warned from God by an holy angel to send for thee into his house, and to hear words of thee.",
    "Acts 10:23": "Then called he them in, and lodged them. And on the morrow Peter went away with them, and certain brethren from Joppa accompanied him.",
    "Acts 10:24": "And the morrow after they entered into Caesarea. And Cornelius waited for them, and had called together his kinsmen and near friends.",
    "Acts 10:25": "And as Peter was coming in, Cornelius met him, and fell down at his feet, and worshipped him.",
    "Acts 10:26": "But Peter took him up, saying, Stand up; I myself also am a man.",
    "Acts 10:27": "And as he talked with him, he went in, and found many that were come together.",
    "Acts 10:28": "And he said unto them, Ye know how that it is an unlawful thing for a man that is a Jew to keep company, or come unto one of another nation; but God hath shewed me that I should not call any man common or unclean.",
    "Acts 10:29": "Therefore came I unto you without gainsaying, as soon as I was sent for: I ask therefore for what intent ye have sent for me?",
    "Acts 10:30": "And Cornelius said, Four days ago I was fasting until this hour; and at the ninth hour I prayed in my house, and, behold, a man stood before me in bright clothing,",
    "Acts 10:31": "And said, Cornelius, thy prayer is heard, and thine alms are had in remembrance in the sight of God.",
    "Acts 10:32": "Send therefore to Joppa, and call hither Simon, whose surname is Peter; he is lodged in the house of one Simon a tanner by the sea side: who, when he cometh, shall speak unto thee.",
    "Acts 10:33": "Immediately therefore I sent to thee; and thou hast well done that thou art come. Now therefore are we all here present before God, to hear all things that are commanded thee of God.",
    "Acts 10:34": "Then Peter opened his mouth, and said, Of a truth I perceive that God is no respecter of persons:",
    "Acts 10:35": "But in every nation he that feareth him, and worketh righteousness, is accepted with him.",
    "Acts 10:36": "The word which God sent unto the children of Israel, preaching peace by Jesus Christ: (he is Lord of all:)",
    "Acts 10:37": "That word, I say, ye know, which was published throughout all Judaea, and began from Galilee, after the baptism which John preached;",
    "Acts 10:38": "How God anointed Jesus of Nazareth with the Holy Ghost and with power: who went about doing good, and healing all that were oppressed of the devil; for God was with him.",
    "Acts 10:39": "And we are witnesses of all things which he did both in the land of the Jews, and in Jerusalem; whom they slew and hanged on a tree:",
    "Acts 10:40": "Him God raised up the third day, and shewed him openly;",
    "Acts 10:41": "Not to all the people, but unto witnesses chosen before of God, even to us, who did eat and drink with him after he rose from the dead.",
    "Acts 10:42": "And he commanded us to preach unto the people, and to testify that it is he which was ordained of God to be the Judge of quick and dead.",
    "Acts 10:43": "To him give all the prophets witness, that through his name whosoever believeth in him shall receive remission of sins.",
    "Acts 10:44": "While Peter yet spake these words, the Holy Ghost fell on all them which heard the word.",
    "Acts 10:45": "And they of the circumcision which believed were astonished, as many as came with Peter, because that on the Gentiles also was poured out the gift of the Holy Ghost.",
    "Acts 10:46": "For they heard them speak with tongues, and magnify God. Then answered Peter,",
    "Acts 10:47": "Can any man forbid water, that these should not be baptized, which have received the Holy Ghost as well as we?",
    "Acts 10:48": "And he commanded them to be baptized in the name of the Lord. Then prayed they him to tarry certain days.",
    
    // Acts 11 (King James Version)
    "Acts 11:1": "And the apostles and brethren that were in Judaea heard that the Gentiles had also received the word of God.",
    "Acts 11:2": "And when Peter was come up to Jerusalem, they that were of the circumcision contended with him,",
    "Acts 11:3": "Saying, Thou wentest in to men uncircumcised, and didst eat with them.",
    "Acts 11:4": "But Peter rehearsed the matter from the beginning, and expounded it by order unto them, saying,",
    "Acts 11:5": "I was in the city of Joppa praying: and in a trance I saw a vision, a certain vessel descend, as it had been a great sheet, let down from heaven by four corners; and it came even to me:",
    "Acts 11:6": "Upon the which when I had fastened mine eyes, I considered, and saw fourfooted beasts of the earth, and wild beasts, and creeping things, and fowls of the air.",
    "Acts 11:7": "And I heard a voice saying unto me, Arise, Peter; slay and eat.",
    "Acts 11:8": "But I said, Not so, Lord: for nothing common or unclean hath at any time entered into my mouth.",
    "Acts 11:9": "But the voice answered me again from heaven, What God hath cleansed, that call not thou common.",
    "Acts 11:10": "And this was done three times: and all were drawn up again into heaven.",
    "Acts 11:11": "And, behold, immediately there were three men already come unto the house where I was, sent from Caesarea unto me.",
    "Acts 11:12": "And the Spirit bade me go with them, nothing doubting. Moreover these six brethren accompanied me, and we entered into the man's house:",
    "Acts 11:13": "And he showed us how he had seen an angel in his house, which stood and said unto him, Send men to Joppa, and call for Simon, whose surname is Peter;",
    "Acts 11:14": "Who shall tell thee words, whereby thou and all thy house shall be saved.",
    "Acts 11:15": "And as I began to speak, the Holy Ghost fell on them, as on us at the beginning.",
    "Acts 11:16": "Then remembered I the word of the Lord, how that he said, John indeed baptized with water; but ye shall be baptized with the Holy Ghost.",
    "Acts 11:17": "Forasmuch then as God gave them the like gift as he did unto us, who believed on the Lord Jesus Christ; what was I, that I could withstand God?",
    "Acts 11:18": "When they heard these things, they held their peace, and glorified God, saying, Then hath God also to the Gentiles granted repentance unto life.",
    "Acts 11:19": "Now they which were scattered abroad upon the persecution that arose about Stephen travelled as far as Phenice, and Cyprus, and Antioch, preaching the word to none but unto the Jews only.",
    "Acts 11:20": "And some of them were men of Cyprus and Cyrene, which, when they were come to Antioch, spake unto the Grecians, preaching the Lord Jesus.",
    "Acts 11:21": "And the hand of the Lord was with them: and a great number believed, and turned unto the Lord.",
    "Acts 11:22": "Then tidings of these things came unto the ears of the church which was in Jerusalem: and they sent forth Barnabas, that he should go as far as Antioch.",
    "Acts 11:23": "Who, when he came, and had seen the grace of God, was glad, and exhorted them all, that with purpose of heart they would cleave unto the Lord.",
    "Acts 11:24": "For he was a good man, and full of the Holy Ghost and of faith: and much people was added unto the Lord.",
    "Acts 11:25": "Then departed Barnabas to Tarsus, for to seek Saul:",
    "Acts 11:26": "And when he had found him, he brought him unto Antioch. And it came to pass, that a whole year they assembled themselves with the church, and taught much people. And the disciples were called Christians first in Antioch.",
    "Acts 11:27": "And in these days came prophets from Jerusalem unto Antioch.",
    "Acts 11:28": "And there stood up one of them named Agabus, and signified by the Spirit that there should be a great dearth throughout all the world: which came to pass in the days of Claudius Caesar.",
    "Acts 11:29": "Then the disciples, every man according to his ability, determined to send relief unto the brethren which dwelt in Judaea:",
    "Acts 11:30": "Which also they did, and sent it to the elders by the hands of Barnabas and Saul.",
    
    // Acts 12 (King James Version)
    "Acts 12:1": "Now about that time Herod the king stretched forth his hands to vex certain of the church.",
    "Acts 12:2": "And he killed James the brother of John with the sword.",
    "Acts 12:3": "And because he saw it pleased the Jews, he proceeded further to take Peter also. (Then were the days of unleavened bread.)",
    "Acts 12:4": "And when he had apprehended him, he put him in prison, and delivered him to four quaternions of soldiers to keep him; intending after Easter to bring him forth to the people.",
    "Acts 12:5": "Peter therefore was kept in prison: but prayer was made without ceasing of the church unto God for him.",
    "Acts 12:6": "And when Herod would have brought him forth, the same night Peter was sleeping between two soldiers, bound with two chains: and the keepers before the door kept the prison.",
    "Acts 12:7": "And, behold, the angel of the Lord came upon him, and a light shined in the prison: and he smote Peter on the side, and raised him up, saying, Arise up quickly. And his chains fell off from his hands.",
    "Acts 12:8": "And the angel said unto him, Gird thyself, and bind on thy sandals. And so he did. And he saith unto him, Cast thy garment about thee, and follow me.",
    "Acts 12:9": "And he went out, and followed him; and wist not that it was true which was done by the angel; but thought he saw a vision.",
    "Acts 12:10": "When they were past the first and the second ward, they came unto the iron gate that leadeth unto the city; which opened to them of his own accord: and they went out, and passed on through one street; and forthwith the angel departed from him.",
    "Acts 12:11": "And when Peter was come to himself, he said, Now I know of a surety, that the Lord hath sent his angel, and hath delivered me out of the hand of Herod, and from all the expectation of the people of the Jews.",
    "Acts 12:12": "And when he had considered the thing, he came to the house of Mary the mother of John, whose surname was Mark; where many were gathered together praying.",
    "Acts 12:13": "And as Peter knocked at the door of the gate, a damsel came to hearken, named Rhoda.",
    "Acts 12:14": "And when she knew Peter's voice, she opened not the gate for gladness, but ran in, and told how Peter stood before the gate.",
    "Acts 12:15": "And they said unto her, Thou art mad. But she constantly affirmed that it was even so. Then said they, It is his angel.",
    "Acts 12:16": "But Peter continued knocking: and when they had opened the door, and saw him, they were astonished.",
    "Acts 12:17": "But he, beckoning unto them with the hand to hold their peace, declared unto them how the Lord had brought him out of the prison. And he said, Go shew these things unto James, and to the brethren. And he departed, and went into another place.",
    "Acts 12:18": "Now as soon as it was day, there was no small stir among the soldiers, what was become of Peter.",
    "Acts 12:19": "And when Herod had sought for him, and found him not, he examined the keepers, and commanded that they should be put to death. And he went down from Judaea to Caesarea, and there abode.",
    "Acts 12:20": "And Herod was highly displeased with them of Tyre and Sidon: but they came with one accord to him, and, having made Blastus the king's chamberlain their friend, desired peace; because their country was nourished by the king's country.",
    "Acts 12:21": "And upon a set day Herod, arrayed in royal apparel, sat upon his throne, and made an oration unto them.",
    "Acts 12:22": "And the people gave a shout, saying, It is the voice of a god, and not of a man.",
    "Acts 12:23": "And immediately the angel of the Lord smote him, because he gave not God the glory: and he was eaten of worms, and gave up the ghost.",
    "Acts 12:24": "But the word of God grew and multiplied.",
    "Acts 12:25": "And Barnabas and Saul returned from Jerusalem, when they had fulfilled their ministry, and took with them John, whose surname was Mark.",
    
    // Acts 13 (King James Version)
    "Acts 13:1": "Now there were in the church that was at Antioch certain prophets and teachers; as Barnabas, and Simeon that was called Niger, and Lucius of Cyrene, and Manaen, which had been brought up with Herod the tetrarch, and Saul.",
    "Acts 13:2": "As they ministered to the Lord, and fasted, the Holy Ghost said, Separate me Barnabas and Saul for the work whereunto I have called them.",
    "Acts 13:3": "And when they had fasted and prayed, and laid their hands on them, they sent them away.",
    "Acts 13:4": "So they, being sent forth by the Holy Ghost, departed unto Seleucia; and from thence they sailed to Cyprus.",
    "Acts 13:5": "And when they were at Salamis, they preached the word of God in the synagogues of the Jews: and they had also John to their minister.",
    "Acts 13:6": "And when they had gone through the isle unto Paphos, they found a certain sorcerer, a false prophet, a Jew, whose name was Barjesus:",
    "Acts 13:7": "Which was with the deputy of the country, Sergius Paulus, a prudent man; who called for Barnabas and Saul, and desired to hear the word of God.",
    "Acts 13:8": "But Elymas the sorcerer (for so is his name by interpretation) withstood them, seeking to turn away the deputy from the faith.",
    "Acts 13:9": "Then Saul, (who also is called Paul,) filled with the Holy Ghost, set his eyes on him,",
    "Acts 13:10": "And said, O full of all subtilty and all mischief, thou child of the devil, thou enemy of all righteousness, wilt thou not cease to pervert the right ways of the Lord?",
    "Acts 13:11": "And now, behold, the hand of the Lord is upon thee, and thou shalt be blind, not seeing the sun for a season. And immediately there fell on him a mist and a darkness; and he went about seeking some to lead him by the hand.",
    "Acts 13:12": "Then the deputy, when he saw what was done, believed, being astonished at the doctrine of the Lord.",
    "Acts 13:13": "Now when Paul and his company loosed from Paphos, they came to Perga in Pamphylia: and John departing from them returned to Jerusalem.",
    "Acts 13:14": "But when they departed from Perga, they came to Antioch in Pisidia, and went into the synagogue on the sabbath day, and sat down.",
    "Acts 13:15": "And after the reading of the law and the prophets the rulers of the synagogue sent unto them, saying, Ye men and brethren, if ye have any word of exhortation for the people, say on.",
    "Acts 13:16": "Then Paul stood up, and beckoning with his hand said, Men of Israel, and ye that fear God, give audience.",
    "Acts 13:17": "The God of this people of Israel chose our fathers, and exalted the people when they dwelt as strangers in the land of Egypt, and with an high arm brought he them out of it.",
    "Acts 13:18": "And about the time of forty years suffered he their manners in the wilderness.",
    "Acts 13:19": "And when he had destroyed seven nations in the land of Canaan, he divided their land to them by lot.",
    "Acts 13:20": "And after that he gave unto them judges about the space of four hundred and fifty years, until Samuel the prophet.",
    "Acts 13:21": "And afterward they desired a king: and God gave unto them Saul the son of Cis, a man of the tribe of Benjamin, by the space of forty years.",
    "Acts 13:22": "And when he had removed him, he raised up unto them David to be their king; to whom also he gave testimony, and said, I have found David the son of Jesse, a man after mine own heart, which shall fulfill all my will.",
    "Acts 13:23": "Of this man's seed hath God according to his promise raised unto Israel a Saviour, Jesus:",
    "Acts 13:24": "When John had first preached before his coming the baptism of repentance to all the people of Israel.",
    "Acts 13:25": "And as John fulfilled his course, he said, Whom think ye that I am? I am not he. But, behold, there cometh one after me, whose shoes of his feet I am not worthy to loose.",
    "Acts 13:26": "Men and brethren, children of the stock of Abraham, and whosoever among you feareth God, to you is the word of this salvation sent.",
    "Acts 13:27": "For they that dwell at Jerusalem, and their rulers, because they knew him not, nor yet the voices of the prophets which are read every sabbath day, they have fulfilled them in condemning him.",
    "Acts 13:28": "And though they found no cause of death in him, yet desired they Pilate that he should be slain.",
    "Acts 13:29": "And when they had fulfilled all that was written of him, they took him down from the tree, and laid him in a sepulchre.",
    "Acts 13:30": "But God raised him from the dead:",
    "Acts 13:31": "And he was seen many days of them which came up with him from Galilee to Jerusalem, who are his witnesses unto the people.",
    "Acts 13:32": "And we declare unto you glad tidings, how that the promise which was made unto the fathers,",
    "Acts 13:33": "God hath fulfilled the same unto us their children, in that he hath raised up Jesus again; as it is also written in the second psalm, Thou art my Son, this day have I begotten thee.",
    "Acts 13:34": "And as concerning that he raised him up from the dead, now no more to return to corruption, he said on this wise, I will give you the sure mercies of David.",
    "Acts 13:35": "Wherefore he saith also in another psalm, Thou shalt not suffer thine Holy One to see corruption.",
    "Acts 13:36": "For David, after he had served his own generation by the will of God, fell on sleep, and was laid unto his fathers, and saw corruption:",
    "Acts 13:37": "But he, whom God raised again, saw no corruption.",
    "Acts 13:38": "Be it known unto you therefore, men and brethren, that through this man is preached unto you the forgiveness of sins:",
    "Acts 13:39": "And by him all that believe are justified from all things, from which ye could not be justified by the law of Moses.",
    "Acts 13:40": "Beware therefore, lest that come upon you, which is spoken of in the prophets;",
    "Acts 13:41": "Behold, ye despisers, and wonder, and perish: for I work a work in your days, a work which ye shall in no wise believe, though a man declare it unto you.",
    "Acts 13:42": "And when the Jews were gone out of the synagogue, the Gentiles besought that these words might be preached to them the next sabbath.",
    "Acts 13:43": "Now when the congregation was broken up, many of the Jews and religious proselytes followed Paul and Barnabas: who, speaking to them, persuaded them to continue in the grace of God.",
    "Acts 13:44": "And the next sabbath day came almost the whole city together to hear the word of God.",
    "Acts 13:45": "But when the Jews saw the multitudes, they were filled with envy, and spake against those things which were spoken by Paul, contradicting and blaspheming.",
    "Acts 13:46": "Then Paul and Barnabas waxed bold, and said, It was necessary that the word of God should first have been spoken to you: but seeing ye put it from you, and judge yourselves unworthy of everlasting life, lo, we turn to the Gentiles.",
    "Acts 13:47": "For so hath the Lord commanded us, saying, I have set thee to be a light of the Gentiles, that thou shouldest be for salvation unto the ends of the earth.",
    "Acts 13:48": "And when the Gentiles heard this, they were glad, and glorified the word of the Lord: and as many as were ordained to eternal life believed.",
    "Acts 13:49": "And the word of the Lord was published throughout all the region.",
    "Acts 13:50": "But the Jews stirred up the devout and honorable women, and the chief men of the city, and raised persecution against Paul and Barnabas, and expelled them out of their coasts.",
    "Acts 13:51": "But they shook off the dust of their feet against them, and came unto Iconium.",
    "Acts 13:52": "And the disciples were filled with joy, and with the Holy Ghost.",
    
};